- Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
- Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
Ports: https://github.com/DeltaV-Station/Delta-v/pull/976
Ports: https://github.com/DeltaV-Station/Delta-v/pull/975
"PrisonJumpsuit" component is removed from jumpskirts, so none of the tags are needed hence PrisonJumpskirt no longer needs to overwrite any tags. WhitelistChameleon, ClothMade and Skirt are added to fix Harpy, Cloth and Chameleon issues.
PrisonUniform no longer used on Jumpskirts
**Changelog**
:cl: DangerRevolution
- fix: Fixed Harpies being unable to wear prison jumpskirts
- fix: Moths can now eat jumpskirts
- fix: Jumpskirts are now a chameleon option.
> [PORT] Harpy & Moth Clothing Fixes

- README.md
It was just recently brought to my attention that we had listed a link on our Readme for the SSMV launcher. I'm not opposed to having it, but it's possible that this might be perceived as a form of bias that we don't have. For the sake of impartiality, I've listed both launchers side by side.
> Remove Launcher Bias

- .github/workflows/update-credits.yml
- Tools/dump_github_contributors.ps1
On a repository (and organization) level, I have enabled Actions to create and approve pull requests.
This PR will have the in-game GitHub contributor credits automatically updated every week.
> Update the Credits Action

- Content.Server/Light/EntitySystems/LightReplacerSystem.cs
https://github.com/space-wizards/space-station-14/pull/26136
Light Replacer no longer sends out the wrong locale string. Read PR above for details ^
Cherrypicked from Wizden in the gap between last merge and right now.
> Light Replacer Fix

- Content.Server/Fluids/EntitySystems/PuddleDebugDebugOverlaySystem.cs
- Content.Server/Fluids/EntitySystems/PuddleSystem.cs
- Content.Server/Fluids/EntitySystems/SmokeSystem.cs
- Content.Server/Spreader/KudzuSystem.cs
- Content.Server/Spreader/SpreadNeighborsEvent.cs
- Content.Server/Spreader/SpreaderSystem.cs
Ports https://github.com/space-wizards/space-station-14/pull/26102.
> Code Cleanup: Puddles and Spreaders

- Resources/Prototypes/DeltaV/Entities/Markers/anti_anomaly_zone.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/52761126?v=4" width="16"/><a href="https://github.com/rosieposieeee"> rosieposieeee</a> at 2024-03-08 19:07:59 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/52761126?v=4" width="16"/><a href="https://github.com/rosieposieeee"> rosieposieeee</a> at 2024-03-17 13:35:52 UTC</aside>
<sup>
`7abdf9a19fe59243201336e6b586ee4780a4722e`
</sup>
---
- Changes: YML
---
> 
> 
> 
> 
> 
> https://github.com/space-wizards/space-station-14/pull/24634
> 
> Upstream added, then removed this, saying "Remove[d] mapping …
> Add Anti Anomaly Zone

- Resources/Prototypes/DeltaV/siliconlaws.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/142105406?v=4" width="16"/><a href="https://github.com/DangerRevolution"> DangerRevolution</a> at 2024-03-14 17:13:03 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/142105406?v=4" width="16"/><a href="https://github.com/DangerRevolution"> DangerRevolution</a> at 2024-03-17 13:47:48 UTC</aside>
<sup>
`155fc7d7515238afde3718c1451b51e1a0870cee`
</sup>
---
- Changes: YML
---
> 
> 
> Removed a rogue 1 from SiliconPolice ID
> 
> 
> 
> No other lawset has a 1
</details>
> Removes a random `1` from SiliconPolice lawset

- Resources/Prototypes/Maps/arena.yml
- Resources/Prototypes/Maps/asterisk.yml
- Resources/Prototypes/Maps/edge.yml
- Resources/Prototypes/Maps/hammurabi.yml
- Resources/Prototypes/Maps/hive.yml
- Resources/Prototypes/Maps/pebble.yml
- Resources/Prototypes/Maps/shoukou.yml
- Resources/Prototypes/Maps/submarine.yml
- Resources/Prototypes/Maps/tortuga.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-19 00:13:41 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-19 02:19:48 UTC</aside>
<sup>
`1f6cb805d63ec66194dbcc04a8cd4cb20b389711`
</sup>
---
- Changes: Map
---
> **About**
> Title(I honestly thought this pulled from a random string until yesterday)
> 
> We'll use DV for our maps from here out. 
</details>
> Change map prefix to DV

- Content.Shared/Access/Components/IdCardConsoleComponent.cs
- Resources/Locale/en-US/deltav/prototypes/access/accesses.ftl
- Resources/Prototypes/Access/misc.yml
- Resources/Prototypes/Access/security.yml
- Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
- Resources/Prototypes/DeltaV/Access/misc.yml
- Resources/Prototypes/DeltaV/Access/security.yml
- Resources/Prototypes/DeltaV/Entities/Structures/Doors/Airlocks/access.yml
- Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
- Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml
- Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/52761126?v=4" width="16"/><a href="https://github.com/rosieposieeee"> rosieposieeee</a> at 2024-02-23 18:21:40 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/52761126?v=4" width="16"/><a href="https://github.com/rosieposieeee"> rosieposieeee</a> at 2024-03-19 12:13:13 UTC</aside>
<sup>
`304fdcd35659c4bdcb17561d093d16b52b172b2e`
</sup>
---
- Changes: YML
- Changes: C#
- Changes: Localization
---
> 
> 
> 
> 
> 
> <img width="524" alt="Content Client_AQ40yzRyFY" …
> Add Corspman Access & Airlocks

- Resources/Locale/en-US/deltav/warp-points/warp-points.ftl
- Resources/Prototypes/DeltaV/Entities/Markers/warp_points.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-21 18:53:11 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-22 01:35:14 UTC</aside>
<sup>
`2ad986dddd855df06eb430b0640340b9f14a79ee`
</sup>
---
- Changes: YML
- Changes: Localization
---
> Title
> Will work together with [this](https://github.com/DeltaV-Station/Delta-v/pull/968) to create a cleaner more straightforward WP/Beacon …
> Adds pre-set warp points

- Content.Server/Ame/AmeNodeGroup.cs
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-23 00:07:05 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-23 00:16:26 UTC</aside>
<sup>
`b4fc2e342be6ef395b1ca21f27787ac08a89df59`
</sup>
---
- Changes: C#
---
> Reverts DeltaV-Station/Delta-v#939
> 
> We might revert this again if everything burns but it's worth a shot. Let's gooo
> 
> 
> :cl: Velcroboy
> - tweak: Reverted AME …
> Revert "Revert "Revert AME buff""

- Content.Server/Whitelist/WhitelistCommands.cs
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/56081759?v=4" width="16"/><a href="https://github.com/NullWanderer"> NullWanderer</a> at 2024-03-21 23:16:47 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/56081759?v=4" width="16"/><a href="https://github.com/NullWanderer"> NullWanderer</a> at 2024-03-27 23:53:10 UTC</aside>
<sup>
`a2a3bcbb869530aa1511af8339d8abc2cc84eba8`
</sup>
---
- Changes: C#
---
> Admins asked for it, and it looks to be a mistake in the code
> 
> :cl:
> DELTAVADMIN:
> - fix: whitelistremove now requires either ban or whitelist, not …
> Whitelistremoves now requires either ban or whitelist, not both

- Resources/Locale/en-US/advertisements/vending/sectech.ftl
Reverts [a WizDen change](https://github.com/space-wizards/space-station-14/pull/24965) to the sectech specifically calling out the Syndicate even though the Syndicate terrorist attacks are supposed to be unexpected and uncommon even if that is not reflected in gameplay.
:cl:
- tweak: Sectech now says "Crack communist skulls!" instead of "Crack syndicate skulls!"
> Revert WizDen "Crack syndicate skulls!" Sectech Message

- Content.Server/Shuttles/Systems/DockingSystem.Shuttle.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/10494922?v=4" width="16"/><a href="https://github.com/ShadowCommander"> ShadowCommander</a> at 2024-03-12 09:44:08 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 12:57:35 UTC
---
- Issue: Bug
- Size: Very Small
---
> 
> 
> 
> 
> 
> 
> Angle tolerance was too tight for the arrivals shuttle to dock on station when it was spinning.
> 
> Changed the tolerance from 0.01 to 0.15.
> 
> Fixes #25901
> 
> 
> 
> 
> 
> ## …
> Mirror: Fix arrivals not docking on spinning stations

- Content.Server/Zombies/PendingZombieComponent.cs
- Content.Shared/Zombies/ZombieComponent.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/104418166?v=4" width="16"/><a href="https://github.com/liltenhead"> liltenhead</a> at 2024-03-10 01:40:46 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 18:44:09 UTC
---
PR changed 2 files with 3 additions and 4 deletions.
---
> 
> 
> 
> This PR changes the damage numbers of the zombie infection. It also increases the chances of getting infected per bite, with and without clothing.
> 
> Most zombies are created through people getting bit to death, or infecting …
> Mirror: Buff Zombie Infection

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Lathes/clothing.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/83733158?v=4" width="16"/><a href="https://github.com/Cojoke-dot"> Cojoke-dot</a> at 2024-02-28 06:09:28 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 08:45:33 UTC
---
PR changed 2 files with 64 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> Added the Senior position drip to the Uniform Printer
> 
> 
> Senior drip was lost when the roles got removed, this will bring them back without the issue of having the position.
> 
> 
> Added all of the Senior position …
> Mirror: Add's Senior role drip to the Uniform Printer.

- Resources/Prototypes/Entities/Objects/Misc/carpets.yml
- Resources/Prototypes/tags.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/62253058?v=4" width="16"/><a href="https://github.com/Gyrandola"> Gyrandola</a> at 2024-03-12 18:19:09 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 02:03:04 UTC
---
PR changed 2 files with 15 additions and 9 deletions.
- No C#
---
> 
> 
> 
> 
> Adding Sky Blue carpets to tables no longer results in red carpet ones.
> 
> 
> Fixes #26040 
> 
> 
> CarpetSBlue tag was missing.
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its …
> Mirror: Fix Sky Blue carpet making red tables

- Resources/Prototypes/Entities/Stations/base.yml
It's been gone for a bit too long.
> Revert Salvage Shittle and Trading Post removal

- Resources/Locale/en-US/deltav/advertisements/vending/courierdrobe.ftl
- Resources/Locale/en-US/deltav/advertisements/vending/pride.ftl
- Resources/Prototypes/DeltaV/Catalog/VendingMachines/Advertisements/courierdrobe.yml
- Resources/Prototypes/DeltaV/Catalog/VendingMachines/Advertisements/pride.yml
This fixes a crash related to the CourierDrobe and PrideVend not having thank you messages. Instead of deleting the ability to say a thank you message, I have elected to add thank you messages to both vendors.
> Fix Pride and Courier Vendors Not Being Able To Say Thank You, and Crashing the Game Out of Protest

- Content.Client/Drugs/DrugOverlaySystem.cs
- Content.Client/Drugs/RainbowOverlay.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/62557990?v=4" width="16"/><a href="https://github.com/PolterTzi"> PolterTzi</a> at 2024-02-27 18:09:49 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-09 19:33:40 UTC
---
PR changed 2 files with 14 additions and 1 deletions.
---
> 
> 
> 
> 
> 
> The space drugs shader effect now gradually loses intensity as it's nearing its end.
> 
> 
> Makes for a smoother transition than going from 100% to 0% instantly.
> 
> ## Media
> 
> 
> https://github.com/space-wizards/space-station-14/assets/62557990 …
> Mirror: Added winddown to space drugs effect

- Content.Client/Shuttles/UI/MapScreen.xaml.cs
- Content.Client/Shuttles/UI/ShuttleMapControl.xaml.cs
- Content.Shared/Shuttles/Systems/SharedShuttleSystem.IFF.cs
- Content.Shared/Shuttles/UI/MapObjects/GridMapObject.cs
- Content.Shared/Shuttles/UI/MapObjects/IMapObject.cs
- Content.Shared/Shuttles/UI/MapObjects/ShuttleBeaconObject.cs
- Content.Shared/Shuttles/UI/MapObjects/ShuttleExclusionObject.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/31366439?v=4" width="16"/><a href="https://github.com/metalgearsloth"> metalgearsloth</a> at 2024-03-07 02:06:24 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 02:11:46 UTC
---
PR changed 7 files with 32 additions and 9 deletions.
- Changes: UI
---
> - HideLabel just means it won't have its name / button drawn whereas Hide will block it completely.
> 
> ![image](https://github.com/space-wizards/space-station-14/assets/31366439/d582dbe2-90a1-43e9-b3bf-ad97807f43f6)
> 
> :cl:
> - tweak: Remove the buttons for generated …
> Mirror: Shuttle map IFF tweaks

- Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
- Resources/Prototypes/Entities/Structures/Windows/mining.yml
- Resources/Prototypes/Entities/Structures/Windows/plasma.yml
- Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
- Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
- Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
- Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
- Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
- Resources/Prototypes/Entities/Structures/Windows/uranium.yml
- Resources/Prototypes/Entities/Structures/Windows/window.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/20659419?v=4" width="16"/><a href="https://github.com/MACMAN2003"> MACMAN2003</a> at 2024-03-08 05:40:47 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-08 07:50:34 UTC
---
PR changed 10 files with 50 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> the corner walls are untouched because they didn't have this issue (they actually held the solution)
> 
> fixes https://github.com/space-wizards/space-station-14/issues/25924
> 
> 
> ## Media
> 
> 
> - [x] I have added …
> Mirror: Fix air not existing in corner window tiles

- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
- Resources/Prototypes/Catalog/uplink_catalog.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/159550239?v=4" width="16"/><a href="https://github.com/AlexUmAndXGabriel08X"> AlexUmAndXGabriel08X</a> at 2024-03-07 21:21:02 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-07 23:55:25 UTC
---
PR changed 3 files with 14 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> In this another uplink related PR we changed that now you will get barber scissors when purchasing chameleon bundle, and you can just purchase barber scissors on their own in pointless tab.
> 
> We want to see them being …
> Mirror: Barber scissors in uplink and chameleon bundle.

- Content.Shared/Doors/Components/AirlockComponent.cs
- Content.Shared/Doors/Systems/SharedAirlockSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-10 18:09:35 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 01:50:09 UTC
---
PR changed 2 files with 2 additions and 1 deletions.
---
> fixes #25800
> fixes #25900
> 
> 
> 
> 
> 
> The client now actually knows when an airlock is in emergency access.
> 
> 
> The EmergencyAccess bool was not getting synced to the client. Made it AutoNetworked. Also dirtied the airlock component on …
> Mirror: Fix misprediction of emergency access

- Content.Server/Kitchen/EntitySystems/SharpSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/62253058?v=4" width="16"/><a href="https://github.com/Gyrandola"> Gyrandola</a> at 2024-03-10 22:13:55 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 01:41:02 UTC
---
PR changed 1 files with 8 additions and 1 deletions.
---
> 
> 
> 
> 
> Adds an admin log for when someone successfully butchers something. The attempt was already logged.
> 
> 
> Fixes #25278 
> 
> 
> Added a couple dependencies and the log at the end of SharpSystem's OnDoAfter.
> 
> ## Media
> 
> 
> …
> Mirror: Add admin logs for butchering

- Resources/Prototypes/Catalog/Fills/Crates/botany.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/39013340?v=4" width="16"/><a href="https://github.com/deltanedas"> deltanedas</a> at 2024-03-06 11:49:30 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 04:52:22 UTC
---
PR changed 1 files with 4 additions and 0 deletions.
- No C#
---
> adds:
> - clippers
> - spade
> - 2 bottles of ez nutrient
> 
> to hydroponics crate order
> 
> right now the crate only has 2 useful things, plant b gone and the hoe. with these you can actually use it to kickstart a farm. the ez nutrient is much more …
> Mirror: buff cargo hydroponics crate

- Content.Client/Audio/ContentAudioSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/82627200?v=4" width="16"/><a href="https://github.com/Kokoc9n"> Kokoc9n</a> at 2024-03-10 16:26:28 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-10 17:08:05 UTC
---
PR changed 1 files with 3 additions and 3 deletions.
---
> 
> 
> 
> 
> Ambient music  volume now set to ambient music volume slider.
> 
> Space ambience tracks being super loud #25874.
> 
> FadeIn and UpdateFades now get correct values instead of blasting music on maximum volume.
> ## Media
> 
> 
> - [X] …
> Mirror: fix: ambient music fade in (#25874)

- Content.Client/Alerts/ClientAlertsSystem.cs
- Content.Client/Clothing/ClientClothingSystem.cs
- Content.Client/IconSmoothing/IconSmoothSystem.cs
- Content.Client/Info/InfoSystem.cs
- Content.Client/Light/RgbLightControllerSystem.cs
- Content.Client/Sprite/RandomSpriteSystem.cs
- Content.Server/Atmos/EntitySystems/AutomaticAtmosSystem.cs
- Content.Server/Atmos/Piping/Trinary/EntitySystems/GasFilterSystem.cs
- Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs
- Content.Server/Explosion/EntitySystems/ExplosionSystem.TileFill.cs
- Content.Server/Explosion/EntitySystems/ExplosionSystem.cs
- Content.Server/Explosion/EntitySystems/SmokeOnTriggerSystem.cs
- Content.Server/Humanoid/Systems/HumanoidAppearanceSystem.cs
- Content.Server/Info/InfoSystem.cs
- Content.Server/ParticleAccelerator/EntitySystems/ParticleAcceleratorSystem.Emitter.cs
- Content.Server/Spawners/EntitySystems/ConditionalSpawnerSystem.cs
- Content.Server/Station/Systems/StationJobsSystem.Roundstart.cs
- Content.Server/Station/Systems/StationSystem.cs
- Content.Server/Store/Systems/StoreSystem.Listings.cs
- Content.Server/Strip/StrippableSystem.cs
- Content.Server/Traits/TraitSystem.cs
- Content.Server/Worldgen/Systems/Biomes/BiomeSelectionSystem.cs
- Content.Server/Worldgen/Systems/WorldgenConfigSystem.cs
- Content.Shared/DoAfter/SharedDoAfterSystem.cs
- Content.Shared/Interaction/SharedInteractionSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/27449516?v=4" width="16"/><a href="https://github.com/LordCarve"> LordCarve</a> at 2024-03-09 12:19:14 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-10 00:15:13 UTC
---
PR changed 25 files with 41 additions and 45 deletions.
---
> 
> 
> 
> 
> Changed almost all[^1] obsolete `Logger` calls in Content's `EntitySystem`s to use `Log` instead. `Log` automatically selects the system-specific `Sawmill`, so this isn't just a refactor - it makes logs slightly more accurate (puts them in …
> Mirror: Obsolete `Logger` cleanup for `EntitySystem`s

- Content.Server/Communications/CommunicationsConsoleSystem.cs
- Content.Server/Materials/MaterialReclaimerSystem.cs
- Content.Shared.Database/LogType.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-11 18:01:29 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 10:57:05 UTC
---
PR changed 3 files with 8 additions and 0 deletions.
---
> fixes #25556 
> fixes #25037 
> 
> 
> 
> 
> 
> This just adds logs for broadcasting and getting gibbed by a recycler.
> 
> 
> Me admin. Me want this logs. Me beat logs with rock if I no know why passenger gibbed or who put the …
> Mirror: Add logs to recycler gibbing and broadcasting.

- Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
PR opened by <img src="https://avatars.githubusercontent.com/u/47093363?v=4" width="16"/><a href="https://github.com/Titian3"> Titian3</a> at 2024-03-13 23:35:30 UTC
---
- No C#
---
> Super small typo in Cryogenics guidebook, feel bad its such small PR let me know if there is a better way.
> 
> It's currently wrong value, got someone killed in game as player followed wrong instructions.
> 
> Guidebook update.
> 
> ## Media
> NA
>  …
> Mirror: Typo in guidebook for cyro pressure

- Resources/Prototypes/Entities/Clothing/Head/hardhats.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/misc.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/skewer.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/124214523?v=4" width="16"/><a href="https://github.com/lzk228"> lzk228</a> at 2024-03-13 18:28:23 UTC
---
PR changed 3 files with 7 additions and 1 deletions.
- No C#
---
> 
> 
> 
> 
> - remove cloth tag from hardhats and cardborg hat
> - add meat tag for lizard-tail kebab
> 
> 
> 
> 
> 
> ## Media
> 
> 
> 
> 
> 
> 
> not a big cl so no cl no fun
> 
> 
</details>
> Mirror: Fix some tags for prototypes

- Content.Shared/Blocking/BlockingSystem.User.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-10 17:36:06 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 01:55:19 UTC
---
PR changed 1 files with 12 additions and 2 deletions.
---
> fixes #25966
> 
> 
> 
> 
> 
> The shield will now only reduce damage itself can absorb.
> 
> 
> A shield should probably not oxygenate your blood supply.
> 
> 
> Instead of just multiplying the damage of the user, we now create …
> Mirror: Fix shield absorbing asphyxiation damage

- Content.Client/MassMedia/Ui/ArticleEditorPanel.xaml.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/103440971?v=4" width="16"/><a href="https://github.com/Brandon-Huu"> Brandon-Huu</a> at 2024-03-09 07:48:04 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-09 08:26:02 UTC
---
PR changed 1 files with 6 additions and 0 deletions.
- Changes: UI
---
> disable buttons when out of bounds
> 
> disable buttons when excedded
> 
> 
> 
> 
> 
> Disable buttons when outside of bounds
> 
> 
> Articles not being published even though users were allowed is VV annoying.
> 
> 
> 
> ## …
> Mirror: Disable the publish and preview buttons on news management console when bounds are exceeded

- Content.Server/Chemistry/EntitySystems/InjectorSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/58439124?v=4" width="16"/><a href="https://github.com/Plykiya"> Plykiya</a> at 2024-03-06 21:57:17 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 09:35:48 UTC
---
PR changed 1 files with 14 additions and 2 deletions.
---
> 
> 
> 
> 
> Altered the **additional doafter time penalty** to be based on what's actually in the syringe rather than what you have the TransferAmount set to for both drawing and injecting.
> 
> 
> It just makes sense.. honestly though, if I could change the total …
> Mirror: Syringe doafter based on Syringe contents

- Resources/Locale/en-US/flavors/flavor-profiles.ftl
- Resources/Locale/en-US/reagents/meta/biological.ftl
- Resources/Locale/en-US/reagents/meta/physical-desc.ftl
- Resources/Prototypes/Body/Organs/diona.yml
- Resources/Prototypes/Body/Organs/human.yml
- Resources/Prototypes/Body/Organs/slime.yml
- Resources/Prototypes/Entities/Structures/Machines/material_reclaimer.yml
- Resources/Prototypes/Flavors/flavors.yml
- Resources/Prototypes/Reagents/biological.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/151778459?v=4" width="16"/><a href="https://github.com/FungiFellow"> FungiFellow</a> at 2024-02-22 08:03:24 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 09:06:03 UTC
---
PR changed 9 files with 55 additions and 6 deletions.
- No C#
---
> 
> 
> 
> 
> I added 5u of Grey Matter into Humanoid Brains, it currently does 20 cellular damage total. Prions are scary
> GREY MATTER CANNOT BE EXTRACTED FROM THE BRAIN IN ANY WAY. (Except Solutions manager)
> Drink:
>       effects:
>       - …
> Mirror: Grey Matter Addition and Slime Organ Tweak

- Content.Server/Fax/FaxSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/69344159?v=4" width="16"/><a href="https://github.com/Deatherd"> Deatherd</a> at 2024-03-07 15:31:19 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 09:03:12 UTC
---
PR changed 1 files with 13 additions and 2 deletions.
---
> 
> 
> 
> Added logging for copying and printing from a file using fax.
> 
> My solution for issue [#25694](https://github.com/space-wizards/space-station-14/issues/25694), that takes into account the logic of fax operation.
> 
> ## Technical …
> Mirror: More fax logging

- Resources/Prototypes/Entities/Objects/Misc/implanters.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/83650252?v=4" width="16"/><a href="https://github.com/SlamBamActionman"> SlamBamActionman</a> at 2024-03-12 17:58:45 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 02:02:36 UTC
---
PR changed 1 files with 2 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> 
> This PR removes the Trash tag for Syndicate implanters, stopping them from being recycled. This means they can no longer be destroyed with the station's Recycler/Material Reclaimer. Non-Syndicate implanters can still be recycled as normal.
> 
> ## …
> Mirror: Remove recycling for Syndicate implanters

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-11 01:33:55 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 18:43:22 UTC
---
- No C#
---
> 
> 
> 
> they now go into crit at 60 hp and die at 125 hp
> 
> kobolds shouldnt be as fragile as a mothroach
> 
> 
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, …
> Mirror: kobolds no longer die at 40 hp

- Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/34938708?v=4" width="16"/><a href="https://github.com/VasilisThePikachu"> VasilisThePikachu</a> at 2024-03-10 14:11:20 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-10 16:30:16 UTC
---
PR changed 1 files with 1 additions and 7 deletions.
---
> 
> 
> 
> 
> Closes #21404
> 
> The server checked this fine and would let you join correctly as the antag. Just the client prevented you.
> 
> ## Media
> 
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not …
> Mirror: Fix game.role_timers not effecting the antag menu

- Content.Client/Movement/Systems/FloorOcclusionSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/68350815?v=4" width="16"/><a href="https://github.com/DoutorWhite"> DoutorWhite</a> at 2024-03-10 08:16:46 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-10 17:07:24 UTC
---
PR changed 1 files with 6 additions and 1 deletions.
---
> 
> This PR adds a condition so that FloorOcclusionSystem does not overwrite existing PostShaders.
> 
> 
> Because if a Mutable PostShader already exists, the FloorOcclusionSystem will simply replace it with its own, which is Immutable, which creates conflict …
> Mirror: Prevents FloorOcclusion from breaking rendering

- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
- Resources/Prototypes/Objectives/objectiveGroups.yml
- Resources/Prototypes/Objectives/stealTargetGroups.yml
- Resources/Prototypes/Objectives/thief.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/96445749?v=4" width="16"/><a href="https://github.com/TheShuEd"> TheShuEd</a> at 2024-03-07 22:07:40 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-07 23:53:36 UTC
---
PR changed 4 files with 0 additions and 66 deletions.
- No C#
---
> title
> 
> stealing ghostrole is asspain 
> 
> :cl:
> - remove: Removed Hamlet, Smile and Pun Pun from Thief objectives
> 
</details>
> Mirror: Remove Hamlet, Smile and Pun Pun from Thief objective

- Resources/Prototypes/Entities/Objects/Weapons/security.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/81056464?v=4" width="16"/><a href="https://github.com/wrexbe"> wrexbe</a> at 2024-03-24 01:19:57 UTC
---
- No C#
---
> I was on ss14, and some kind of truncheon error was spamming in the console, and I am guessing it's this, because it looked sus.
</details>
> Mirror: Maybe fix rsi truncheon error

- Content.Client/UserInterface/Systems/Actions/Controls/ActionButtonContainer.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/81056464?v=4" width="16"/><a href="https://github.com/wrexbe"> wrexbe</a> at 2024-03-23 02:21:12 UTC
---
PR changed 1 files with 5 additions and 4 deletions.
---
> I fixed the game crashing if you don't have hotkeys assigned to the action bar slots when the game loads
</details>
> Mirror: Fix crash on load when no slot key assigned

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
- Resources/Prototypes/Recipes/Crafting/Graphs/improvised/improvised_shotgun_shell.yml
- Resources/Prototypes/Recipes/Crafting/improvised.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/151778459?v=4" width="16"/><a href="https://github.com/FungiFellow"> FungiFellow</a> at 2024-02-25 06:30:06 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 23:52:32 UTC
---
PR changed 4 files with 98 additions and 7 deletions.
- No C#
---
> 
> 
> 
> 
> I added a Recipe for crafting Improvised Shotgun Shells, Recipe is as follows: 1 Steel, 1 Plastic, 4 Glass Shards, and 6 Matches
> 
> It was added because prior there was no way to obtain ammo for your Improvised Shotgun. There was already …
> Mirror: Improvised shell crafting recipe

- Content.Server/Zombies/ZombieSystem.Transform.cs
- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
- Content.Shared/Zombies/ZombieComponent.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-13 00:13:44 UTC
---
PR changed 3 files with 10 additions and 1 deletions.
---
> 
> 
> 
> zombies wideswing, also makes the bite sound into the carp biting sound on zombified (human zombies will bite you, but it sounds like punching?)
> 
> hard to hit moving target as a zombie
> 
> made AltDisarm an AutoNetworkedField in MeleeWeaponComponent
> 
> ## Media
> 
> https://github.com/space-wizards/space-station-14/assets/45323883/8e1a2d17-a0a0-4320-92f2 …
> Mirror: zombie wideswing and misc fix

- Content.Client/Weapons/Ranged/Systems/GunSystem.Magazine.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/33431126?v=4" width="16"/><a href="https://github.com/778b"> 778b</a> at 2024-03-11 18:34:37 UTC
---
PR changed 1 files with 9 additions and 0 deletions.
---
> 
> 
> 
> 
> Fix bug with guns which used MagazineAmmoProviderComponent with Battery magazines like svalinn laser pistol.
> 
> 
> Bugfix, no balance here
> 
> 
> Just added subscribe for AmmoCounterControlEvent which using AmmoCounterComponent because battery magazines must redefine control in this event to display ammo, now its work well. 
> Also checked some other guns which using MagazineAmmoProviderComponent and …
> Mirror: Fixed bug with appearance of ammo battery magazine guns

- Content.Server/Administration/Systems/AdminVerbSystem.cs
- Content.Server/Administration/UI/EditSolutionsEui.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/83650252?v=4" width="16"/><a href="https://github.com/SlamBamActionman"> SlamBamActionman</a> at 2024-03-11 17:16:10 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 12:10:10 UTC
---
PR changed 2 files with 26 additions and 11 deletions.
---
> 
> 
> 
> 
> 
> Makes it so that you can have multiple debug Solution Editor/Add Reagent windows open at once.
> 
> 
> 
> Admin request. Useful if you want to multitask editing multiple solution containers and their contents.
> …
> Mirror: Enable multiple Solution Editor windows

- Content.Server/Nutrition/EntitySystems/DrinkSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/88361930?v=4" width="16"/><a href="https://github.com/maylokana"> maylokana</a> at 2024-03-14 03:59:47 UTC
---
PR changed 1 files with 3 additions and 0 deletions.
---
> 
> 
> 
> 
> All drink containers now check if the container is closed once the do-after is done, and will stop you from trying to drink from it if it is closed
> 
> 
> Bug fix. I think
> 
> 
> In `DrinkSystem.cs`, added an `_openable.IsClosed()` method to `OnDoAfter()`, which returns if true
> 
> ## Media
> 
> 
> https://github.com/space-wizards/space-station-14/assets/88361930/cf983879-5073-407a-98fc-200469 …
> Mirror: Drink from closed container fix

- Content.Server/Kitchen/EntitySystems/SharpSystem.cs
- Content.Server/Nutrition/EntitySystems/UtensilSystem.cs
- Resources/Locale/en-US/clothing/boots.ftl
- Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml
- Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
- Resources/Prototypes/Entities/Objects/Fun/toys.yml
- Resources/Prototypes/Entities/Objects/Misc/utensils.yml
- Resources/Prototypes/tags.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/42424291?v=4" width="16"/><a href="https://github.com/Krunklehorn"> Krunklehorn</a> at 2024-02-28 02:04:52 UTC
---
PR changed 9 files with 75 additions and 30 deletions.
---
> 
> - Fixes improper popups with edible+butcherable items, and sharp+utensil items
> - Clown shoes have item slots
>   - Intended for non-harmful items other than their job specific gun
>   - Currently supports plastic knives, cap gun & fake cap gun
> 
> Minor stuff...
> - Spoons are metal
> - Plastic knives are actually plastic knives
> - Plastic utensils are now zero damage weapons
> - Raw rat meat is sliceable
> 
> 
> …
> Mirror: Fix Butcherable handling, ItemSlots for clown shoes

- Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/91865152?v=4" width="16"/><a href="https://github.com/PursuitInAshes"> PursuitInAshes</a> at 2024-03-10 18:12:13 UTC
---
PR changed 1 files with 12 additions and 0 deletions.
- No C#
---
> Adds a Contraband Storage Crate for the armory. This can be used by mappers to provide better and more suitable storage then an empty rack.
> 
> Dumping items that were confiscated from the syndicate on the ground or in exposed racks felt wrong and unfitting for more stations. This provides an armory locked crate to fill that purpose.
> 
> ## Media
> ![Content …
> Mirror: Contraband Storage Crate

- Content.Server/Audio/ServerGlobalSoundSystem.cs
- Content.Server/Nuke/NukeSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/35878406?v=4" width="16"/><a href="https://github.com/Errant-4"> Errant-4</a> at 2024-03-09 18:24:36 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 18:50:34 UTC
---
PR changed 2 files with 16 additions and 5 deletions.
---
> 
> Nuke Music now begins playing at the appropriate time  to end just-on-target regardless of the duration of the music (as long as it's less than 290 seconds)
> 
> fixes  #25775
> 
> ## Media
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** …
> Mirror: Nuke Music start adjusted for duration

- Resources/Locale/en-US/game-ticking/game-presets/preset-thief.ftl
- Resources/Locale/en-US/reagents/meta/consumable/food/food.ftl
PR opened by <img src="https://avatars.githubusercontent.com/u/30327355?v=4" width="16"/><a href="https://github.com/arimah"> arimah</a> at 2024-03-12 15:52:06 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 15:58:04 UTC
---
PR changed 2 files with 2 additions and 2 deletions.
- No C#
---
> While playing around with the game's data, I discovered 'cocoa powder' got sorted after all the other reagents. I poked around for a minute, and what do you know, that first letter isn't a c, it's actually the [Cyrillic lowercase letter …
> Mirror: Remove random Cyrillic characters from locale files

- Content.Server/Shuttles/Systems/EmergencyShuttleSystem.Console.cs
- Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/31366439?v=4" width="16"/><a href="https://github.com/metalgearsloth"> metalgearsloth</a> at 2024-03-05 07:13:06 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 18:54:28 UTC
---
PR changed 2 files with 10 additions and 2 deletions.
---
> Doesn't fix them restarting in lobby I think but should fix most of it.
</details>
> Mirror: Fix rounds restarting in the next round

- Content.Client/DoAfter/DoAfterOverlay.cs
- Content.Client/Options/UI/Tabs/MiscTab.xaml
- Content.Client/Options/UI/Tabs/MiscTab.xaml.cs
- Content.Client/Overlays/EntityHealthBarOverlay.cs
- Content.Client/UserInterface/Controls/ProgressTextureRect.cs
- Content.Client/UserInterface/Systems/ProgressColorSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
PR opened by <img src="https://avatars.githubusercontent.com/u/98561806?v=4" width="16"/><a href="https://github.com/EmoGarbage404"> EmoGarbage404</a> at 2024-02-16 17:40:39 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-09 11:43:20 UTC
---
PR changed 8 files with 169 additions and 84 deletions.
- Changes: UI
---
> 
> 
> 
> 
> Adds a toggle in the accessibility menu that lets 'progress bars' (doafters, medhud) toggle between a standard rainbow palette and the colorblind-friendly Viridis palette.
> 
> also makes the medhud bar unshaded to match the …
> Mirror: Add a toggle for colorblind friendly progress bar colors

- Content.IntegrationTests/Tests/Buckle/BuckleTest.cs
- Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs
- Content.Shared/Interaction/RotateToFaceSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/4543739?v=4" width="16"/><a href="https://github.com/Nopey"> Nopey</a> at 2024-01-19 22:47:45 UTC
---
PR changed 3 files with 11 additions and 18 deletions.
---
> 
> 
> 
> Bugfix.
> 
> Previously, players could always turn a bar stool (or office chair, etc..) they were buckled into; even while stone cold dead.
> 
> RotateToFaceSystem now only lets players rotate barstools (& similar) when the actionBlockerSystem reports that they CanChangeDirection; this also means players who are frozen by admins (see AdminFrozenSystem) can no longer spin barstools.
> 
> SharedBuckleSystem …
> Mirror: Prevent dead players from turning bar stools

- Content.Server/Database/ServerDbBase.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-18 17:50:15 UTC
---
PR changed 1 files with 2 additions and 0 deletions.
---
> Fixes #20645
> 
> :cl:
> - add: Bans are now shown in the "adminremarks" command.
</details>
> Mirror: Include bans in adminremarks command

- Content.Server/Glue/GlueSystem.cs
- Content.Server/Lube/LubeSystem.cs
- Resources/Locale/en-US/glue/glue.ftl
- Resources/Locale/en-US/lube/lube.ftl
PR opened by <img src="https://avatars.githubusercontent.com/u/83650252?v=4" width="16"/><a href="https://github.com/SlamBamActionman"> SlamBamActionman</a> at 2024-03-11 15:15:49 UTC
---
PR changed 4 files with 67 additions and 25 deletions.
---
> 
> 
> 
> 
> 
> Added right-click Glue/Lube verbs (used by Space glue / lube tubes). This allows them to be used on containers and glasses.
> 
> 
> 
> Attempting to glue/lube a container like a bag makes the insert verb take priority. Same for trying to glue/lube something like a glass, which empties the reagent into the container. That keeps those objects from being glued/lubed, but with a right-click verb it is …
> Mirror: Added verb action to Glue/Lube system

- Content.Server/Zombies/ZombieSystem.cs
- Resources/Prototypes/Reagents/toxins.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-18 03:07:02 UTC
---
PR changed 2 files with 10 additions and 3 deletions.
---
> 
> 
> 
> title
> 
> for zombie nukies it's bad because you have to have someone whose in crit in order to efficiently infect them
> 
> adds a new check if the entity is dead upon ``PendingZombie`` map init, if it is then zombify
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an …
> Mirror: make romerol work on the dead

- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/117393350?v=4" width="16"/><a href="https://github.com/HappyRoach"> HappyRoach</a> at 2024-03-17 14:10:47 UTC
---
- No C#
---
> Fixed filling of WT550 safes 
> 
> 
> The WT550 requires a different type of magazine, which was clearly not noticed when creating safes. Therefore, what is now in safes is simply not suitable for the WT550.
> 
> ## Media
> 
> 
> :cl:
> - fix: The …
> Mirror: Fixed safe filling with WT550

- Content.Server/Medical/SuitSensors/SuitSensorComponent.cs
- Content.Server/Medical/SuitSensors/SuitSensorSystem.cs
- Content.Server/Radio/EntitySystems/JammerSystem.cs
- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Entities/Objects/Tools/jammer.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-12 17:11:18 UTC
---
PR changed 5 files with 36 additions and 5 deletions.
---
> 
> 
> 
> 
> Radio jammers will now additionally block suit sensors.
> 
> When someone with suit sensors is in range of an active radio jammer, their suit sensor output will be jammed. This will lead to them appearing as frozen on any crew monitors for roughly 10 seconds before they completely disappear from it.
> 
> 
> 
> This gives syndies more stealth options when doing their objectives, …
> Mirror: Make radio jammer block suit sensors

- Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
- Content.Shared/VendingMachines/VendingMachineComponent.cs
- Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/732532?v=4" width="16"/><a href="https://github.com/FairlySadPanda"> FairlySadPanda</a> at 2024-03-11 13:50:33 UTC
---
PR changed 3 files with 39 additions and 9 deletions.
---
> 
> 
> 
> Reduces the amount of food in all food and vending machines EXCEPT the Honk meal one by about half.
> 
> Vending machines provide too much food (and drink) at the moment to the crew, robbing the chef/bartender of a reason to exist, and robbing the janitor of a reason to want to refill vending machines early in the round.
> 
> This PR adds a new "initialStockQuality" …
> Mirror: SS14-12462 Nerf food and drink vending machines

- Content.Server/Chemistry/Components/SolutionInjectOnCollideComponent.cs
- Content.Server/Chemistry/EntitySystems/SolutionInjectOnCollideSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-15 13:11:00 UTC
---
PR changed 2 files with 5 additions and 11 deletions.
---
> 
> 
> 
> 
> Tranquilizer rounds no longer inject their target when they are successfully reflected.
> 
> 
> Fixes #26137
> 
> 
> Changed SolutionInjectOnCollideSystem to subscribe to ProjectileHitEvent instead of StartCollideEvent. This also simplifies the logic a little and removes a component field (FixtureId), since SolutionInjectOnCollideSystem no longer has to check for fixture match or fixture hardness …
> Mirror: Fix tranq rounds injecting when reflected

- Resources/Prototypes/Actions/diona.yml
- Resources/Prototypes/Actions/types.yml
- Resources/Prototypes/Entities/Clothing/Neck/misc.yml
- Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/81056464?v=4" width="16"/><a href="https://github.com/wrexbe"> wrexbe</a> at 2024-03-24 22:11:54 UTC
---
PR changed 4 files with 13 additions and 5 deletions.
- No C#
---
> Fixes some .png rsi reference warnings
</details>
> Mirror: Fixed some icon rsi warnings

- Content.Shared/Climbing/Components/BonkableComponent.cs
- Content.Shared/Climbing/Components/ClimbingComponent.cs
- Content.Shared/Climbing/Events/AttemptClimbEvent.cs
- Content.Shared/Climbing/Systems/BonkSystem.cs
- Content.Shared/Climbing/Systems/ClimbSystem.cs
- Resources/Locale/en-US/bonk/components/bonkable-component.ftl
- Resources/Locale/en-US/climbing/climbable-component.ftl
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-02-05 21:32:50 UTC
---
PR changed 7 files with 101 additions and 39 deletions.
---
> 
> 
> 
> 
> Stops clumsy characters being able to climb/vault onto tables and such by using alt-click or the verb menu instead of drag-dropping.
> 
> This also fixes a separate bug where, when a clumsy character managed to pass the bonk check, the action would just cancel and the character didn't actually climb the object. Passing the check will now let the character climb.
> 
> Additionally, this fixes a oddity where the …
> Mirror: Fix bypassing vaulting clumsy check with verb action.

- Content.Server/Atmos/Piping/Unary/EntitySystems/GasThermoMachineSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/7117411?v=4" width="16"/><a href="https://github.com/Menshin"> Menshin</a> at 2024-03-07 20:16:52 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-07 21:05:43 UTC
---
---
> 
> 
> 
> 
> Atmospherics thermomachines now properly invalidate the tile they are exchanging heat with.
> Fixes #25827.
> 
> 
> Atmospherics thermomachines were retrieving the gas mixture from the tile they were on without invalidating the …
> Mirror: Atmospherics thermomachines now properly excite the gas mixture they add heat to

- Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/pizza.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-20 16:41:16 UTC
---
- No C#
---
> 
> 
> 
> 
> Pizza no longer qualifies as fruit.
> 
> 
> Pizza being considered a fruit has been causing integration test failures because the FoodPizzaLarge cargo order contains 16 random pizzas, and a cargo bounty for fruits was recently added (#26160).
> 
> The base pizza has the Fruit tag, so any types of pizza that don't override the Tag component also count as fruit. The ones that do override the …
> Mirror: Pizza is not a fruit

- Content.Server/Remotes/DoorRemoteSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-24 00:28:39 UTC
---
PR changed 1 files with 3 additions and 8 deletions.
---
> 
> 
> 
> 
> This makes it so door remotes can no longer manipulate doors just because their user has access to them. 
> 
> 
> Being able to bolt doors and put them on emergency access from a distance is extremely powerful. You should not be able to do it just because you have the access in your id card, it should be limited to the capabilities of the door remote.
> 
> It also makes no sense.
> 
> ## Technical …
> Mirror: Restrict door remotes to only being able to manipulate doors relevant to their type

- Resources/Prototypes/Entities/Objects/Devices/door_remote.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/152836416?v=4" width="16"/><a href="https://github.com/Baptr0b0t"> Baptr0b0t</a> at 2024-03-24 05:03:38 UTC
---
- No C#
---
> 
> 
> 
> 
> Add access to the command door remote.
> 
> Because of #26371 
> The command remote control becomes useless and cannot access most doors
> 
> 
> YML configuration, change access group of command door remote 
> ## Media
> 
> 
> - [x] this PR does not require an ingame showcase
> 
> 
> 
> 
> 
> 
> :cl: 
> - fix: Fix access of command door remote. …
> Mirror: Give cap door remote his access

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/107586145?v=4" width="16"/><a href="https://github.com/IProduceWidgets"> IProduceWidgets</a> at 2024-03-24 18:29:22 UTC
---
PR changed 1 files with 1 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> fixed #25519  the tagging for the captain's laser glass box.
> 
> 
> 
> 
> 
> ## Media
> 
> 
> 
> 
> 
> 
> 
> 
> :cl:
> - fix: The captain can now return his laser to the glass display box.
</details>
> Mirror: fix: the captain can put his laser gun back in the box.

- Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-16 20:59:22 UTC
---
- No C#
---
> Title
> 
> Frequently requested feature/QoL
> 
> n/a
> 
> ## Media
> n/a
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase
> 
> n/a
> 
> :cl: Velcroboy
> - tweak: Tweaked gas canisters to pass through cargo flaps.
</details>
> Mirror: Change collision mask of canisters to allow passing through cargo flaps

- Content.Server/Objectives/ObjectivesSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/254972?v=4" width="16"/><a href="https://github.com/Crotalus"> Crotalus</a> at 2024-03-12 22:44:16 UTC
---
PR changed 1 files with 34 additions and 16 deletions.
---
> Sort the agents by success rate in the end game summary
> Fame and glory to the robust
> 
> :cl:
> - tweak: Sort agents by success rate in end game summary
> 
> 
</details>
> Mirror: Sort agents by success rate in end game summary

- Resources/Prototypes/Entities/Mobs/Player/human.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-02-20 00:35:08 UTC
---
PR changed 1 files with 15 additions and 4 deletions.
- No C#
---
> 
> 
> 
> traitor syndie reinforcements get the autotraitor component, like traitor syndie monkies
> 
> syndie monkies can see the codewords, so why cant the more expensive human reinforcement see the codewords aswell?
> this also makes it so they are listed as an antag with admin vision
> 
> 
> made syndicate base for human reinforcement
> …
> Mirror: make traitor syndicate reinforcements get the traitor role

- Content.Server/Chemistry/EntitySystems/VaporSystem.cs
- Content.Server/DeviceNetwork/Systems/DeviceListSystem.cs
- Content.Server/Forensics/Systems/ForensicScannerSystem.cs
- Content.Server/Mapping/MappingSystem.cs
- Content.Server/Mech/Systems/MechSystem.cs
- Content.Server/Movement/Systems/LagCompensationSystem.cs
- Content.Server/NPC/Systems/NpcFactionSystem.cs
- Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
- Content.Server/StationEvents/EventManagerSystem.cs
- Content.Server/VendingMachines/VendingMachineSystem.cs
- Content.Shared/Anomaly/SharedAnomalySystem.cs
- Content.Shared/DeviceLinking/SharedDeviceLinkSystem.cs
- Content.Shared/Nutrition/EntitySystems/ThirstSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/27449516?v=4" width="16"/><a href="https://github.com/LordCarve"> LordCarve</a> at 2024-03-17 20:05:08 UTC
---
PR changed 13 files with 43 additions and 82 deletions.
---
> 
> 
> 
> 
> Log things via `Log` with generated sawmill name rather than an explicitly set one for all Content `EntitySystem`s, except the ones with `Rule`s. In all cases the explicit `_sawmill` was redundant.
> 
> 
> - Bringing consistency to logs (all logs originating from `EntitySystem` should be recognizible in the logs `system.something`).
> - Logs' sawmills match system class name to assist with …
> Mirror: Unify `Content`'s `EntitySystem` logging

- Content.Shared/Slippery/SlipperySystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/35878406?v=4" width="16"/><a href="https://github.com/Errant-4"> Errant-4</a> at 2024-01-25 00:04:36 UTC
---
PR changed 1 files with 21 additions and 1 deletions.
- Status: Awaiting Changes
---
> Thrown objects can no longer slip until they have landed. For a succesful slip, the attacker must now calculate how to throw the soap in front of/on the target. If the target is chasing and very close, it might be more effective to drop the soap/banana rather than throw it, but then this choice is another decision that must be quickly made to carry out the slip (also you can mess that up and slip yourself)
> 
> A "MISS" …
> Mirror: Thrown soap/banana/(etc?) will fail to slip until it lands

- Resources/Prototypes/Entities/Mobs/NPCs/space.yml
- Resources/Prototypes/Entities/Objects/Tools/cowtools.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
- Resources/Prototypes/NPCs/Combat/melee.yml
- Resources/Prototypes/NPCs/utility_queries.yml
- Resources/Prototypes/Reagents/botany.yml
- Resources/Prototypes/Reagents/fun.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-20 19:10:30 UTC
---
PR changed 7 files with 8 additions and 8 deletions.
- No C#
---
> 
> 
> 
> 
> Corrected the names of a few damage types in various DamageTypeSpecifiers.
> 
> 
> This might have some balance implications, as a few things will be doing damage they didn't previously.
> 
> - Space bears now do some blunt damage along with the usual slash.
> - The Throngler does massive structural damage.
> - RobustHarvest does a little heat damage to non-plants. 
> - Fresium does a bit of negative heat damage.
> …
> Mirror: Fix some invalid damage types

- Resources/Prototypes/GameRules/events.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/58439124?v=4" width="16"/><a href="https://github.com/Plykiya"> Plykiya</a> at 2024-03-16 01:37:52 UTC
---
PR changed 1 files with 0 additions and 1 deletions.
- No C#
---
> 
> 
> 
> 
> Changed the earliest start for ion storms to be at shift start
> 
> 
> Ion storms rarely happen, and it adds more variety for borgs if it does happen early on, also Discord discussion...
> https://discord.com/channels/310555209753690112/1218041638115348500
> 
> 
> Changed earliestStart from 20 minutes to 0 minutes in the yml
> 
> 
> 
> 
> :cl:
> - tweak: Ion storms now have a …
> Mirror: Round start Ion storms

- Resources/Prototypes/Recipes/Construction/Graphs/food/egg.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/39013340?v=4" width="16"/><a href="https://github.com/deltanedas"> deltanedas</a> at 2024-03-15 15:46:48 UTC
---
PR changed 1 files with 2 additions and 1 deletions.
- No C#
---
> how does this shit not make yaml linter fail so many bugs have been caused by it
> 
> ## Media
> 
> ![15:49:11](https://github.com/space-wizards/space-station-14/assets/39013340/7a642926-4197-435c-a886-871808b59d7a)
> 
</details>
> Mirror: fix eggsplosion

- Content.Server/Disposal/Tube/DisposalTubeSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/9883873?v=4" width="16"/><a href="https://github.com/CrafterKolyan"> CrafterKolyan</a> at 2024-03-15 21:45:04 UTC
---
---
> Super small performance optimization
> 
> Obvious change
</details>
> Mirror: Small performance optimization. Don't do String.Trim() second time

- Content.Server/Store/Systems/StoreSystem.Ui.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/31366439?v=4" width="16"/><a href="https://github.com/metalgearsloth"> metalgearsloth</a> at 2024-03-16 11:25:11 UTC
---
PR changed 1 files with 4 additions and 2 deletions.
---
> Index out of range + error log + cleaning up boughtentities.
> 
> :cl:
> - fix: Fix store refunds.
</details>
> Mirror: Fix store refunds

- Content.Shared/Weather/BlockWeatherComponent.cs
- Content.Shared/Weather/SharedWeatherSystem.cs
- Resources/Prototypes/Entities/Objects/Decoration/flora.yml
- Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
- Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
- Resources/Prototypes/Entities/Structures/Doors/SecretDoor/secret_door.yml
- Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
- Resources/Prototypes/Entities/Structures/Furniture/bookshelf.yml
- Resources/Prototypes/Entities/Structures/Walls/walls.yml
- Resources/Prototypes/Entities/Structures/Windows/window.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/96445749?v=4" width="16"/><a href="https://github.com/TheShuEd"> TheShuEd</a> at 2024-03-15 09:30:10 UTC
---
PR changed 10 files with 12 additions and 11 deletions.
---
> inverting the logic of the component. Now inversely, tagging an entity with this component will cause it to block weather if it is attached to the floor. Previously, this conversely excluded the entity from weather checking, and only applied to trees on planets.
> 
> It now blocks rain on walls, windows, airlocks. 
> 
> 95% of the structures in the game should not block weather. Railings, tables, chairs, fences all logically …
> Mirror: Convert "IgnoreWeatherComponent" into "BlockWeatherComponent"

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-21 01:33:59 UTC
---
- No C#
---
> am in vr. approved by real spaniard.
> 
> 
</details>
> Mirror: fix legally distinct visor man plush name.

- Resources/Prototypes/Entities/Structures/Wallmounts/fireaxe_cabinet.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/62253058?v=4" width="16"/><a href="https://github.com/Gyrandola"> Gyrandola</a> at 2024-03-10 12:10:09 UTC
---
PR changed 1 files with 19 additions and 1 deletions.
- No C#
---
> 
> 
> 
> 
> Makes fireaxe and shotgun cabinets destructible.
> 
> 
> Fixes #25525. 
> 
> 
> Simply added the component to the fireaxe cabinet base entity.
> Glass breaking sounds regardless of state.
> Damage thresholds:
> min: 200
> max: 300 (The axe will be destroyed as well).
> 
> ## Media
> 
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does …
> Mirror: Make fireaxe & shotgun cabinets destructible

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/83650252?v=4" width="16"/><a href="https://github.com/SlamBamActionman"> SlamBamActionman</a> at 2024-03-11 15:42:49 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 23:05:25 UTC
---
PR changed 1 files with 18 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> 
> Eating a Lizard Plushie as a moth now also makes you consume 10u _Juice that makes you Weh_.
> 
> 
> 
> 10u was chosen for 2 reasons:
> 
> - Just finding and eating a plushie shouldn't be as rewarding as having to go through …
> Mirror: Add "Juice that makes you Weh" to moths eating Lizard plushies

- Resources/Prototypes/Reagents/Consumable/Drink/soda.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/128169402?v=4" width="16"/><a href="https://github.com/Nimfar11"> Nimfar11</a> at 2024-03-06 21:30:38 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-07 20:50:10 UTC
---
PR changed 1 files with 4 additions and 0 deletions.
- No C#
---
> 
> Slimes can drink FourteenLoko not 1 time or even 2, but as much as they want. Their stomachs can process this obscure slurry without harming their bodies. 
> 
> 
> Strange finding legal poison, that way they'll have at least one …
> Mirror: Slimes can drink fourteenloko

- Content.Server/Speech/Components/ParrotAccentComponent.cs
- Content.Server/Speech/EntitySystems/ParrotAccentSystem.cs
- Resources/Locale/en-US/accent/parrot.ftl
- Resources/Locale/en-US/chat/managers/chat-manager.ftl
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Voice/speech_emote_sounds.yml
- Resources/Prototypes/Voice/speech_sounds.yml
- Resources/Prototypes/Voice/speech_verbs.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-22 17:22:18 UTC
---
PR changed 8 files with 168 additions and 0 deletions.
---
> 
> 
> 
> 
> In the rare cases that parrot become controlled by players, they now sound a bit more parrot-y.
> 
> - Added the parrot squawk sound as a speech sound, so they no longer speak silently.
> - Gave parrots a speech verb set, so they "squawk", "tweet", and "chirp" their messages, instead of just "say"-ing them.
> - Parrots can "scream" now (which just plays the squawk sound).
> - Parrots have their own accent that gets applied to everything …
> Mirror: Make parrots talk like parrots

- RUN_THIS.py
PR opened by <img src="https://avatars.githubusercontent.com/u/9883873?v=4" width="16"/><a href="https://github.com/CrafterKolyan"> CrafterKolyan</a> at 2024-03-11 22:02:53 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-12 00:02:41 UTC
---
PR changed 1 files with 1 additions and 6 deletions.
- No C#
---
> I'm not sure why it was decided to do this weird setup with `py -3` on Windows cygwin when there's `sys.executable` which contains the full absolute path to the current python3 that executes the current script.
> 
> Everything works correctly:
> …
> Mirror: Fix RUN_THIS.py so it would be cross-platform and it would be possible to use it from cmd on Windows

- Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-18 15:16:25 UTC
---
PR changed 1 files with 4 additions and 2 deletions.
---
> Oops
> 
> In #26217 I re-organized the logic for the calculation. Part of that was moving the logic for GetFeltLowPressure and GetFeltHighPressure to be done before we actually check the hazard thresholds. What I didn't realize is that, with how our pressure protection is set up, these functions can return values so extreme they rebound into the other category.
> 
> For example, according to the math, when you're wearing a hardsuit in a …
> Mirror: Fix barotrauma pressure protection

- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Entities/Structures/Machines/bombs.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/57039557?v=4" width="16"/><a href="https://github.com/Ilya246"> Ilya246</a> at 2024-03-12 10:07:47 UTC
---
PR changed 3 files with 26 additions and 1 deletions.
- No C#
---
> 
> 
> 
> adds a decoy syndicate bomb to uplink for 4 TC
> in all ways similar to a real syndicate bomb, but only explodes as hard as a training bomb
> 
> price has been discussed on discord several times and seems good
> 
> *also fixes syndicate bomb description saying their timer is 120 seconds, when it's actually 180
> 
> a lesser distraction (no huge hole and dead people if it blows) for a lesser price, and allows …
> Mirror: add decoy syndicate bomb to uplink

- Content.Server/Chemistry/TileReactions/SpillTileReaction.cs
- Content.Server/Fluids/EntitySystems/PuddleSystem.cs
- Content.Shared/Movement/Components/SpeedModifiedByContactComponent.cs
- Content.Shared/Movement/Components/SpeedModifierContactsComponent.cs
- Content.Shared/Movement/Systems/FrictionContactsSystem.cs
- Content.Shared/Movement/Systems/SpeedModifierContactsSystem.cs
- Resources/Prototypes/Entities/Objects/Misc/kudzu.yml
- Resources/Prototypes/Entities/Objects/Misc/spider_web.yml
- Resources/Prototypes/Entities/Tiles/water.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/96445749?v=4" width="16"/><a href="https://github.com/TheShuEd"> TheShuEd</a> at 2024-03-14 09:45:33 UTC
---
PR changed 9 files with 42 additions and 34 deletions.
---
> system and components are renamed. It can now be used including to accelerate entities
> 
> more reusability for the system
> 
> Now the system calculates the arithmetic mean of all the entities that affects your speed.
</details>
> Mirror: SlowContactsSystem to SpeedModifierContactsSystem mini rework

- Content.Server/Access/Systems/PresetIdCardSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/31366439?v=4" width="16"/><a href="https://github.com/metalgearsloth"> metalgearsloth</a> at 2024-03-17 00:47:51 UTC
---
PR changed 1 files with 4 additions and 2 deletions.
---
> Resolves https://github.com/space-wizards/space-station-14/issues/25798
> 
> :cl:
> - fix: Fix ID cards sometimes not loading properly.
</details>
> Mirror: Fix presetidcard extended access throwing

- Content.Client/Actions/ActionsSystem.cs
- Content.Server/Bed/Sleep/SleepingSystem.cs
- Content.Shared/ActionBlocker/ActionBlockerSystem.cs
- Content.Shared/Actions/BaseActionComponent.cs
- Content.Shared/Actions/SharedActionsSystem.cs
- Content.Shared/Interaction/Events/InteractionAttemptEvent.cs
- Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
- Resources/Prototypes/Actions/crit.yml
- Resources/Prototypes/Actions/diona.yml
- Resources/Prototypes/Actions/types.yml
- Resources/Prototypes/Entities/Mobs/Player/guardian.yml
- Resources/Prototypes/Entities/Objects/Fun/pai.yml
- Resources/mapping_actions.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-10 19:33:05 UTC
---
PR changed 13 files with 142 additions and 3 deletions.
---
> fixes #25662 
> 
> 
> 
> 
> 
> This pr makes it so you can use the SCRAM implant while cuffed. Also fixes the freedom implant working while you are in crit, or even dead.
> 
> 
> The implant is made so you can escape horrible situations. It should as such work while in crit.
> 
> 
> ActionBlockers now has a specific check to see if someone is conscious. It is also …
> Mirror: Fix SCRAM implant not working while cuffed. Incidentally fix freedom implant working while dead/crit

- Content.Shared/Zombies/ZombieComponent.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/140359015?v=4" width="16"/><a href="https://github.com/shampunj"> shampunj</a> at 2024-03-08 05:06:55 UTC
---
PR changed 1 files with 3 additions and 1 deletions.
---
> 
> 
> 
> 
> Zombies have learned to regenerate burns very slowly
> 
> Make zombies stronger, make it possible to get up from crit when severely burned
> 
> n/a
> ## Media
> 
> 
> 
> 
> 
> 
> :cl:
> - tweak: Zombies …
> Mirror: Zombies can very slowly regen heat and shock damage

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-20 13:38:25 UTC
---
PR changed 1 files with 11 additions and 0 deletions.
- No C#
---
> 
> 
> 
> when they hit things it made the no hit sound, this fixes it
> 
> more realistic
> 
> ## Media
> 
> 
> 
</details>
> Mirror: Monkey and gorilla melee weapon fix

- Content.Client/Chat/UI/SpeechBubble.cs
- Content.Client/Stylesheets/StyleNano.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/88361930?v=4" width="16"/><a href="https://github.com/maylokana"> maylokana</a> at 2024-02-26 14:44:39 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 08:03:32 UTC
---
PR changed 2 files with 10 additions and 1 deletions.
---
> 
> 
> 
> 
> Added a bigger difference between talk bubbles and whisper bubbles
> 
> 
> Because (at least for me) it was a little difficult to see when someone was whispering vs when someone was normally speaking. There is a small change between borders, but it is …
> Mirror: Attempt at a more noticably whispered bubble

- Content.Server/Kitchen/EntitySystems/SharpSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/62253058?v=4" width="16"/><a href="https://github.com/Gyrandola"> Gyrandola</a> at 2024-03-12 19:13:34 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-13 03:52:20 UTC
---
---
> 
> 
> 
> 
> Prevents a useless butchering-related popup when one clicks themselves with a knife.
> 
> 
> Fixes #26025 
> 
> 
> Simple (target != user) check
> 
> ## Media
> 
> - [X] I have added screenshots/videos to this PR showcasing its …
> Mirror: Remove butchering popup when clicking own sprite with a knife

- Content.Client/Disposal/Systems/DisposalUnitSystem.cs
- Resources/Prototypes/Entities/Structures/Piping/Disposal/units.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-24 11:57:45 UTC
---
PR changed 2 files with 14 additions and 3 deletions.
---
> fixes #18275
> 
> 
> 
> 
> This fixes mailing units appearing as disposal units when flushed.
> 
> 
> The states were hardcoded.
> 
> Now they are not.
> 
> Bug seems to have been introduced in #17803 as a part of a larger refactor on disposal units. To my understanding, this was made in error with the logic that no other objects would ever have a different animation when flushing and …
> Mirror: Fix mailing units turning into disposal units while recharging.

- Content.Server/Cargo/Systems/CargoSystem.CVars.cs
- Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
- Resources/Prototypes/Entities/Stations/base.yml
This fixes a bug introduced inadvertently by https://github.com/Simple-Station/Einstein-Engines/pull/344 by adding a CVar that makes it a choice to be made by our downstreams. Also, welcome to our new CVar standard where they should be included in other systems.
> Fix Double Trade Station Bug

- shell.nix
Change just for the nix devenv,
Currently it pulls glibc from 23.11, which breaks the devenv if the rest of your system is on a different version, such as unstable.
> Remove glibc from shell.nix

- .github/workflows/close-master-pr.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-24 22:47:21 UTC
---
- No C#
---
> Fix name of "Close PRs on master" workflow
> 
</details>
> Mirror: Update close-master-pr.yml

- Resources/Prototypes/Entities/Objects/Devices/holoprojectors.yml
- Resources/Prototypes/Recipes/Lathes/janitorial.yml
- Resources/Prototypes/Recipes/Lathes/tools.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/22885888?v=4" width="16"/><a href="https://github.com/Callmore"> Callmore</a> at 2024-03-24 19:11:50 UTC
---
PR changed 3 files with 37 additions and 8 deletions.
- No C#
---
> 
> 
> 
> 
> Adds versions of the holoprojectors (janitoral, fan, and field) that start without a battery and changes the lathe recipe to use these instead. This is consistant with flashlights, which when made do not start with a cell.
> 
> Also it's a bit silly to have cargo printing a bunch of these to sell.
> 
> 
> 
> Cargo can no longer print a bunch of holosign projectors to just sell for... apparently huge profit (i …
> Mirror: Holoprojectors crafted at lathes no longer come with a cell.

- Resources/Prototypes/Entities/Structures/Machines/stasisbed.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/58439124?v=4" width="16"/><a href="https://github.com/Plykiya"> Plykiya</a> at 2024-03-15 05:47:26 UTC
---
PR changed 1 files with 5 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> Made stasis beds heal you at the same rate as normal beds and allows you to sleep on it.
> Edit: I have made the healing 100x worse than normal beds.
> 
> 
> I kinda just wanted to sleep on a stasis bed and was sad I couldn't. I'm open to any arguments for changing the numbers...
> 
> 
> .yml component that adds a sleep action
> 
> ## Media
> 
> 
> - [ X ] I have added screenshots/videos to …
> Mirror: Sleep on Stasis Beds

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
- Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
- Resources/Prototypes/Entities/Mobs/Species/vox.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-16 17:39:26 UTC
---
PR changed 4 files with 7 additions and 6 deletions.
- No C#
---
> 
> 
> 
> - kobolds have the claw arc instead of the punch arc and do 5 slash 4 piercing instead of 9 piercing
> - arachnids make the carp bite sound similar to tarantulas and space spiders
> - lizards now make the slashing sound on hit instead of pierce, since they claw not pierce
> 
> kobolds did the old lizard pierce animation when they clawed, made more sense
> 
> if space bears …
> Mirror: Small species melee weapon change

- Content.Server.Database/SnakeCaseNaming.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-20 11:47:51 UTC
---
---
> 
</details>
> Mirror: Fix EFCore obsoletion warnings in Content.Server.Database

- Content.Client/Humanoid/MarkingPicker.xaml.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/10968691?v=4" width="16"/><a href="https://github.com/DrSmugleaf"> DrSmugleaf</a> at 2024-03-24 03:49:01 UTC
---
PR changed 1 files with 33 additions and 11 deletions.
- Changes: UI
---
> Updates when something about the character is changed.
> This helps not gaslight me about which markings a species has available, and also slime person players are faced with the hard truth that they barely have any.
> 
> ## Media
> https://github.com/space-wizards/space-station-14/assets/10968691/439a4b39-a7c6-4ab1-839f-5436ba54b817
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this …
> Mirror: Hide empty marking categories in the markings picker

- Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
- Resources/keybinds.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/81056464?v=4" width="16"/><a href="https://github.com/wrexbe"> wrexbe</a> at 2024-03-23 02:49:07 UTC
---
PR changed 2 files with 2 additions and 1 deletions.
- Changes: UI
---
> Changed it so the priority isn't lost when you set a binding in the UI.
> Also added a priority to MoveStoredItem so it doesn't conflict with Use.
> Fixes https://github.com/space-wizards/space-station-14/issues/26142
> Does not fix old keybinds files, so they will need to reset it, and rebind it.
> 
> A better solution might be to change it so the keybinds are always in the order they appear in the default keybinds folder, to prevent the ordering from …
> Mirror: Store keybind priority

- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/leaves.yml
- Resources/Prototypes/Objectives/stealTargetGroups.yml
- Resources/Prototypes/Objectives/thief.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/57235581?v=4" width="16"/><a href="https://github.com/ChaseFlorom"> ChaseFlorom</a> at 2024-03-24 21:40:14 UTC
---
PR changed 3 files with 4 additions and 26 deletions.
- No C#
---
> 
> 
> 
> 
> 
> Removed the cannabis objective from the thief objectives. 
> 
> 
> 
> 20-30 cannabis leaves is neither fun for the thief, or for the botanist that they're asking to grow it. It doesn't fit with the heart of the thief objective system, as the only real way to accomplish it is to ask the botanist to grow it for you, or grow it yourself. Neither of which is stealing.
> 
> Resolve …
> Mirror: Removed Cannabis from thief objectives

- Content.Server/Administration/Systems/AdminVerbSystem.Smites.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Chemistry/EntitySystems/VaporSystem.cs
- Content.Server/ImmovableRod/ImmovableRodSystem.cs
- Content.Server/ParticleAccelerator/EntitySystems/ParticleAcceleratorSystem.Emitter.cs
- Content.Server/Physics/Controllers/ChasingWalkSystem.cs
- Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
- Content.Server/Shuttles/Systems/ShuttleSystem.cs
- Content.Server/StationEvents/Events/MeteorSwarmRule.cs
- Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs
- Content.Shared/Movement/Systems/SharedJetpackSystem.cs
- Content.Shared/Throwing/ThrowingSystem.cs
- Content.Shared/Throwing/ThrownItemSystem.cs
- Content.Shared/Weapons/Melee/MeleeThrowOnHitSystem.cs
- Content.Shared/Weapons/Misc/SharedTetherGunSystem.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-20 13:37:25 UTC
---
PR changed 16 files with 43 additions and 43 deletions.
---
> 
> 
> 
> Requires https://github.com/space-wizards/RobustToolbox/pull/4979
> 
> 
> Cleans up some obsolete method calls.
> 
> ## Why / Balance / Technical
> 
> Cleaning up obsolete Dirty calls in RT required changing the signatures of some public methods in SharedPhysicsSystem. This updates the calls to those methods here in Content to use the new signatures passing in UIDs.
> 
> 
</details>
> Mirror: Code cleanup: Purge obsoleted SharedPhysicsSystem methods

- Content.Server/Administration/Managers/AdminManager.Metrics.cs
- Content.Server/Administration/Managers/AdminManager.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/8107459?v=4" width="16"/><a href="https://github.com/PJB3005"> PJB3005</a> at 2024-03-20 10:12:29 UTC
---
PR changed 2 files with 106 additions and 1 deletions.
---
> Fixes #20828
> 
> Reports time series for admin count. Counts are separated by state (active, AFK, or deadminned) and admin rank.
> 
> Requires engine master
</details>
> Mirror: Add Prometheus stats for admin count

- Content.Server/Store/Systems/StoreSystem.Ui.cs
- Content.Shared/Store/ListingPrototype.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/54602815?v=4" width="16"/><a href="https://github.com/keronshb"> keronshb</a> at 2024-03-24 14:16:44 UTC
---
PR changed 2 files with 8 additions and 3 deletions.
---
> 
> 
> 
> 
> 
> When testing around some things with the magic PR I found that the purchase event wasn't being compared correctly. Also I added support to raise the purchase event directed at the buyer instead of just a broadcast event.
> 
> 
> The equals method will now check for purchase event type instead of comparing the references. To make this stronger we should talk about creating a base store …
> Mirror: Fixes store purchase events and adds support to raise a directed event

- Resources/Prototypes/Entities/Mobs/Species/vox.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/35878406?v=4" width="16"/><a href="https://github.com/Errant-4"> Errant-4</a> at 2024-03-11 09:29:16 UTC
---
PR changed 1 files with 2 additions and 0 deletions.
- No C#
---
> Clothing with custom sprites for vox have been displaying the default sprites due to a component accident.
> 
> ## Media
> 
> :cl: Errant
> - fix: Clothes with alternate sprites for vox once again show the alternate sprites, instead of the defaults.
> 
</details>
> Mirror: Fix vox custom sprites

- global.json
This is apparently a more desirable behavior for global.json, as it allows servers running any version of Dotnet 8.0.1xx to automatically switch to a newer version than the base. This update was apparently required for DS14, NS14, and Syndicate Station to work properly, since Linux servers can't actually run 8.0.100, and the earliest they can use is 8.0.105(which is still a viable version).
> Set RollForward Behavior to Patch

- shell.nix
Nixpkgs updated `8.0.x` to `8.0.3xx` but we need `8.0.1xx`
> Update Nix Direnv .NET SDK

- Content.Server/Atmos/Components/AirtightComponent.cs
- Content.Server/Atmos/EntitySystems/AirtightSystem.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.GridAtmosphere.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Utils.cs
- Content.Server/Atmos/GasMixture.cs
- Content.Server/Atmos/TileAtmosphere.cs
- Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
- Resources/Prototypes/Entities/Structures/Doors/Airlocks/highsec.yml
- Resources/Prototypes/Entities/Structures/Doors/Airlocks/shuttle.yml
- Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
- Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
- Resources/Prototypes/Entities/Structures/Doors/SecretDoor/secret_door.yml
- Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
- Resources/Prototypes/Entities/Structures/Doors/Windoors/base_structurewindoors.yml
- Resources/Prototypes/Entities/Structures/plastic_flaps.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/60421075?v=4" width="16"/><a href="https://github.com/ElectroJr"> ElectroJr</a> at 2024-03-26 04:27:08 UTC - merged at 2024-03-26 04:44:56 UTC
---
PR changed 16 files with 43 additions and 25 deletions.
---
> - Fixes a bug I introduced in #22521 that caused the temperature to be set to `NaN`. I don't know for sure, but I assume this is causing the current atmos issues
> - Fixes `FixVacuum` not working after #22521
> - Removes some redundant yaml that was setting FixVacuum to its default value
> 
> :cl:
> - fix: Fixed an atmos bug, which was (probably) causing atmospherics on the station to behave incorrectly. …
> Mirror 26441: Fix atmos NaN error

- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks-cartons.yml
- Resources/Prototypes/Entities/Objects/Consumable/Drinks/trash_drinks.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-25 16:06:33 UTC - merged at 2024-03-26 04:04:42 UTC
---
PR changed 2 files with 49 additions and 33 deletions.
- No C#
---
> - Reduces the item size of drink cartons with `maxVol: 50` to `small`
> - Fixes discrepancies between full alcohol bottles and empty
> - Makes empty cartons consistent with full as well 
> 
> Keeps it consistent with other drink containers. 
> 
> ## Technical details 
> n/a
> 
> ## Media
> Before:
> ![image](https://github.com/space-wizards/space-station-14/assets/107660393/f232 …
> Mirror 26430: Reduces size of smaller cartons and fix size discrepancies with empty containers

- Content.Client/Gameplay/GameplayState.cs
- Content.Client/UserInterface/Screens/OverlayChatGameScreen.xaml
- Content.Client/UserInterface/Screens/OverlayChatGameScreen.xaml.cs
- Content.Client/UserInterface/Screens/ScreenType.cs
- Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
- Content.Client/UserInterface/Systems/Vote/VoteUIController.cs
- Content.Shared/CCVar/CCVars.cs
<sub>~~Change from Nyano~~</sub>
Uses space a lot better. The old layout still exists if people want it for whatever reason.
I also renamed "Default" to "Overlay", which should stay anyway if the default change is denied.
---
<p>
</p>
</details>
---
:cl:
- tweak: UI layout now defaults to separated, the old one is still available in settings
> Default to Separated UI Layout

- Content.Shared/Movement/Components/MovementSpeedModifierComponent.cs
- Content.Shared/Physics/FrictionRemoverSystem.cs
- Content.Shared/SimpleStation14/Physics/FrictionRemoverSystem.cs
- Resources/Prototypes/Entities/Mobs/Species/moth.yml
This ports https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/pull/46.
This PR is something I consider a key feature adjacent to Space Wind Rework and its accompanying updates, and is an essential part of the space station experience.
In practice, this weirdly enough makes being launched into space a bit easier to survive, since instead of needing to throw potentially hundreds of items, you can simply throw enough items to get started flying in the direction of the station and will eventually float back to the station. 
---
<p>
https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/assets/77995199/5570ef35-16e2-493a-ac35-738f27751346
https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/assets/77995199/51fba943-8dce …
> Port Frictionless Space

- Content.Server/Speech/Components/RandomBarkComponent.cs
- Content.Server/Speech/Systems/RandomBarkSystem.cs
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
- Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/pull/11
Later, I would like to have this system not just for animals, but for implementations of humanoid NPCs, since it can just as easily be used for human NPCs.
I could make space bandits that CHEEKI BREEKI at people.
:cl: DEATHB4DEFEAT
- add: Animals will no longer be a silent, soulless shell
> Port Random Bark System

- Content.Server/Implants/ImplanterSystem.cs
- Content.Shared/Implants/Components/ImplanterComponent.cs
- Resources/Locale/en-US/implant/implant.ftl
PR opened by <img src="https://avatars.githubusercontent.com/u/63975668?v=4" width="16"/><a href="https://github.com/Simyon264"> Simyon264</a> at 2024-03-19 00:44:21 UTC - merged at 2024-03-26 00:16:19 UTC
---
PR changed 3 files with 28 additions and 0 deletions.
---
> 
> 
> 
> This PR makes mind shields unable to be implanted more than once.
> 
> PJB complained and people waste implants by injecting already injected people.
> 
> 
> Adds a new datafield to the Implanter component which is checked in implanter system.
> 
> ## Media
> 
> ![image](https://github.com/space-wizards/space-station-14/assets/63975668/4907 …
> Mirror 26250: Make all implants unable to be implanted more than once

- Resources/Prototypes/GameRules/events.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/149967078?v=4" width="16"/><a href="https://github.com/Boaz1111"> Boaz1111</a> at 2024-03-18 20:52:10 UTC
---
- No C#
---
> 
> 
> 
> 
> I bumped LoneOps minimum required players to 20
> 
> It was at 10, and loneops are extremely dangerous especially if there's no sec.
> 
> 
> ## Media
> 
> 
> 
> 
> 
> 
> 
> 
> :cl: Boaz1111
> - tweak: Lone operatives now …
> Mirror: Bumps LoneOps minimum required players to 20

- Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs
- Content.Server/StationEvents/RampingStationEventSchedulerSystem.cs
- Content.Shared/CCVar/CCVars.cs
Ports and improves https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/pull/59
Slows rounds down so the station doesn't always have to evacuate in a blaze and can instead leave complete.
Also makes Survival not stupidly destructive and gives a chance for the shift to last a decent time.
Allows servers to configure the times themselves if they want to, so defaults don't matter too much.
---
:cl:
- tweak: Mid-round events will occur much less often
> Fewer Mid-Round Events

- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
- Resources/Prototypes/Entities/Clothing/base_clothing.yml
- Resources/Prototypes/Nyanotrasen/Entities/Clothing/Head/hats.yml
- Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/shock_collar.yml
For centuries SS14 had equip and unequip delays on the clothing component, and yet that feature remained unused and unheard of, not even nyanotrasen/deltav used it when designing shock collars and headcages, whose descriptions clearly suggested they should take time to take off. For centuries salvage specialists could safely swap suits in space. For centuries you could accidentally unequip your eva suit mid-spacewalk and die. Now the time has come. The time when we change it.
This adds equip and unequip delays to the base clothing item. The currently chosen time is half a second - it's meant to not be too annoying, but at the same time prevent people from being able to instantly swap clothes, headsets, other things with a single click.
EVA suits take 1.5 seconds to equip and 1 second to …
> Add Equip Delays to Clothing

- Content.Server/Strip/StrippableSystem.cs
- Content.Shared/Strip/Components/StrippableComponent.cs
This cherrypicks https://github.com/space-wizards/space-station-14/pull/26166
I accidentally bungled the mirrorbots cherrypick in a way that's hard to undo.
> Cherrypick "Fix StrippableSystem Blunders"

- Resources/Prototypes/DeltaV/Body/Prototypes/harpy.yml
- Resources/Prototypes/DeltaV/Body/Prototypes/vulpkanin.yml
- Resources/Prototypes/Nyanotrasen/Entities/Body/Prototypes/felinid.yml
Cherry-picks https://github.com/DeltaV-Station/Delta-v/pull/1194
This is a minor issue in the yml files of custom species that will become a problem if we ever merge wizden's better hand indicators.
This PR shouldn't require a preview; all credit goes to the original author of the fix.
---
Too minor for a cl. Or as some say, no cl no fun.
> Unflip Hands for Felinid, Vulpkanin, Harpy

- Content.Shared/Clothing/EntitySystems/ClothingSystem.cs
- Content.Shared/Inventory/InventorySystem.Equip.cs
For some reason, ClothingSystem.TryEquip would return false if there's a do-after to equip the clothing. This had caused all quick-equip attempts on SMALL ITEMS to fail and ended up with every SMALL clothing item being equipped into one of the pocket slots (which have no equip delays).
Also fixes quick swap - see the comments below.
:cl:
- fix: Equipping clothing using the Z key works correctly again.
> Fix Clothing Quick-Equip

- Content.Server/Station/Systems/StationDampeningSystem.cs
- Content.Shared/Physics/FrictionRemoverSystem.cs
- Content.Shared/Physics/PassiveDampeningComponent.cs
- Resources/Maps/Shuttles/trading_outpost.yml
Makes it so that the station and the ATS get a very tiny bit of friction to prevent cargo tech pros from sending either of those out of this galaxy cluster (which has actually happened multiple times on two servers and required either admin intervention or early round ending).
Added a PassiveDampeningComponent which defines how much friction an entity receives while in 0g. FrictionRemoverSystem was updated to try to fetch this component from an entity before updating its dampening. A new system was added to automatically add this component (if it's not already defined) to all station grids.
See the #when-you-code-it channel for a preview. It's kinda hard to demonstrate, but after a few minutes, stations and the ATS come to an almost complete stop.
:cl:
- tweak: Space stations now have a …
> Frictionfull Space

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
- Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
- Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
- Resources/Prototypes/Entities/Mobs/NPCs/space.yml
Cherry-picks https://github.com/DeltaV-Station/Delta-v/pull/1145
All credit goes to the original author of the PR.
Original description is: "adds carriable component to a lot of animals that didn't have it"
---
---
<p>
</p>
</details>
---
:cl: Froffy025
- add: You can now carry most of the station pets.
> Cherry-Pick Carrypets From Delta-V

- Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs
Fixes job requirements using wrong locales
Happened because one function had role-timer- as its default locale prefix and the other that called the first had null as the default.
---
</p></details>
---
:cl:
- fix: Job requirements are now displayed correctly.
> Fix Them Pesky Job Requirements

- Content.Shared/CCVar/CCVars.cs
This restores the basic/survival event rates to how they were before before #486 (however, it keeps the CVars created in it).
- 5-25 minutes for basic instead of 15-35
- 4-12 minutes for survival instead of 20-45
---
The PR made it so that survival rounds actually have less events than extended - that is considering that survival rounds are supposed to be troublesome and filled with events while extended ones are supposed to be a chill alternative.
Other forks don't bother with editing CVars every 5 minutes, so this "opportunity to configure their experience" was never addressed. Based on the feedback I've received from other players, the change was rather negative.
From my personal experience, survival rounds became an extended extended, where during a 2-hour shift you can get a grand …
> Restore Old Event Rates

- Resources/Prototypes/DeltaV/Entities/Markers/Spawners/Random/miningrock.yml
- Resources/Prototypes/DeltaV/Entities/Structures/Walls/mountain.yml
- Resources/Prototypes/Procedural/biome_templates.yml
Cherry-picks https://github.com/DeltaV-Station/Delta-v/pull/1079
Credit to IamVelcroboy
:cl: Velcroboy
- tweak: Changed asteroids to have more ore...and some danger
> Cherry-Pick Delta-V Asteroids

- Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-21 15:07:50 UTC
---
PR changed 1 files with 8 additions and 6 deletions.
---
> fixes #26310
> 
> 
> 
> 
> 
> This pr fixes the bug with people being unable to move while in cuffs if they were previously pulled even if they were no longer being pulled.
> 
> 
> A security cadet should not be able to merge my legs with the ground by simply touching me while I'm in cuffs.
> 
> 
> 
> When unpulled, the pullableComp has its puller field set to null after the message signifying …
> Cherry-Pick PR #26312: Fix Puller Being Improperly Unset When Pulling Stops.

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Entities/Structures/Power/substation.yml
- Resources/Prototypes/Recipes/Construction/Graphs/utilities/wallmount_substation.yml
- Resources/Prototypes/Recipes/Lathes/electronics.yml
Cherry-picks https://github.com/space-wizards/space-station-14/pull/27138
:cl: osjarw
- add: Wallmount substation electronics can now be created at an autolathe.
> Cherry-Pick PR "Wallmount Substations Can Once Again Be Created" #27138

- Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
- Content.Server/StationEvents/RampingStationEventSchedulerSystem.cs
- Resources/Locale/en-US/game-ticking/game-presets/preset-survival.ftl
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/game_presets.yml
Adds traitors and hellshift to the list of gamemodes offered by the gamemode vote.
Traitors just make sense.
Hellshift is a new version of survival. It starts out roughly as slow as survival, but it slowly devolves into a torrent of station events as frequent as one every 10-30 seconds. Good for when there's no other ~~self-antaggers~~ players to spice up the shift, or when there's one too many security officers to deal with all the threats this brings.
Had to refactor a lot of RampingStationEventScheduler. Firstly, it was total shitcode, secondly, it had everything hardcoded, thirdly, it had a bug that made it possible for events to appear with little to no delay whatsoever. Now its component features four data fields that can be used to configure the scheduler and its system contains …
> More Gamemodes

- Content.Shared/Chat/V2/Moderation/ChatCensor.cs
- Content.Shared/Chat/V2/Moderation/RegexCensor.cs
- Content.Shared/Chat/V2/Moderation/SimpleCensor.cs
- Content.Tests/Shared/Chat/V2/Moderation/SimpleCensor.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/732532?v=4" width="16"/><a href="https://github.com/FairlySadPanda"> FairlySadPanda</a> at 2024-03-07 12:13:16 UTC - merged at 2024-03-25 23:50:20 UTC
---
PR changed 4 files with 576 additions and 0 deletions.
---
> 
> 
> 
> Adds some systems to manage chat censorship:
> 
> 1. No-op: does nothing
> 2. SimpleCensor: a regex-free censor with a variety of rules to use
> 3. RegexCensor: a censor that uses regex.
> 
> This exposes a singleton backed by a builder pattern (ChatCensor) that is set up, probably during the code init phase, and then globally available for your censorship needs.
> 
> ## …
> Mirror 25908: Chat Censorship Systems

- Content.Server/Research/Systems/ResearchStealerSystem.cs
- Content.Shared/Research/Components/ResearchStealerComponent.cs
- Content.Shared/Research/Systems/SharedResearchSystem.cs
- Resources/Prototypes/Objectives/ninja.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/98561806?v=4" width="16"/><a href="https://github.com/EmoGarbage404"> EmoGarbage404</a> at 2024-03-25 01:44:21 UTC - merged at 2024-03-26 00:52:27 UTC
---
PR changed 4 files with 75 additions and 8 deletions.
---
> 
> 
> 
> 
> Changes ninja gloves to steal a flat rate of techs instead of wiping all of them.
> Additionally adjusts the objective to require 1 to 2 steals to reach the target amount.
> 
> 
> Ninja's stealing research was previously an extremely trivial and annoying objective. For them, you can pretty easily break into the server room and wait out the 20 second …
> Mirror 26421: Nerf Ninja's Research Stealing

- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-25 13:50:34 UTC - merged at 2024-03-26 04:05:35 UTC
---
PR changed 2 files with 13 additions and 0 deletions.
- No C#
---
> 
> 
> 
> title
> 
> useful for syndies to hold their gear, or for loneops incase they wanna buy a reinforcement a chest rig
> 
> ## Media
> ![image](https://github.com/space-wizards/space-station-14/assets/45323883/6ab44250-d92b-4d41-b9de-78e434406e8e)
> 
> - [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an …
> Mirror 26427: Make the Chest Rig Purchasable in Uplink

- Content.Server/Language/TranslatorSystem.cs
- Content.Server/Traits/Assorted/ForeignerTraitComponent.cs
- Content.Server/Traits/Assorted/ForeignerTraitSystem.cs
- Content.Shared/Language/Components/LanguageKnowledgeComponent.cs
- Content.Shared/Language/Systems/SharedTranslatorSystem.cs
- Resources/Locale/en-US/language/translator.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Entities/Objects/Devices/translators.yml
- Resources/Prototypes/Traits/inconveniences.yml
Adds two negative traits, foreigner and its light version. Both of them make you unable to speak galactic common and give you a translator that lets you speak/understand GC, and also requires you to know one of the non-GC languages your entity normally speaks in order to work. The translator starts with a high-capacity power cell to compensate for the usual scarcity of publicly accessible chargers on most stations.
The light version of the trait only makes you unable to speak GC. The heavy version also makes you unable to understand others when they speak it.
This PR also makes you able to wear translator in the neck slot for convenience and transparency, and rewamps the examination menu of translators to provide more useful info.
One little known issue (as seen in the screenshots below) …
> Foreigner Traits

- Content.Server/Traits/Assorted/ForeignerTraitComponent.cs
- Resources/Prototypes/Entities/Objects/Devices/translators.yml
#525 Added foreigner traits, now during testing I revealed a few bugs. This PR fixes them:
- The light version now correctly allows you to understand common (it would not because I forgot to add [DataField])
- The translator now correctly starts with a high-capacity power cell
- Equipping the translator in a pocket slot no longer takes time
</p></details>
:cl:
- fix: Foreigner traits now work correctly.
> Foreigner Minor Fixes

- Content.Server/Nyanotrasen/Item/ShockCollar/ShockCollarComponent.cs
- Content.Server/Nyanotrasen/Item/ShockCollar/ShockCollarSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Shock collars were a useful thing in nyano for a long time, but security could never put them to use because they could be removed instantly, so they were forgotten about.
Now that we have enquip delays, shock collars can be useful for controlling unruly prisoners (or unruly secoffs who like to harm baton passengers). Only two problems is there's no way to manufacture them, and they can be quite deadly when used repeatedly. This PR solves both of these issues, and also fixes a little bug:
- Shock collars can be manufactured at the secfab.
- Shock collars deal 1 shock damage instead of 5.
- The shock ignores insulation.
</p></details>
---
:cl:
- tweak: Shock collars can now be manufactured in the security techfab. They also deal less damage and …
> Shock Collar Tweak

- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Movement/Systems/SharedContentEyeSystem.cs
Adds more zoom levels and CVars to configure them.
The defaults make it so that the new minimum zoom is roughly equal to what ss14 had before (29.6%).
Playing as a tiny character made me love having the screen zoomed in, but having only 3 zoom levels didn't quite allow to set the zoom level to what I wanted. This PR fixes that.
https://github.com/user-attachments/assets/61e56913-1c9d-4590-95ac-686018b5caa9
</p></details>
:cl:
- add: You can now configure your zoom more precisely.
> More Zoom Levels

- .vscode/settings.json
This file has been chilling unused (excluding that one workflow) for so long, and it's so useful.
Forks might want to edit the URL to theirs, but it's unlikely they'll ever want to change it.
> Finally Put the meta.json Shema to Use

- Content.Server/Atmos/Serialization/TileAtmosCollectionSerializer.cs
Cherry-Picks Wizden PR 26540, fixing an issue where our downstreams cannot save maps under certain conditions.
https://github.com/space-wizards/space-station-14/pull/26540
> Cherry-Pick PR26540: "Fix Empty Atmos Deserialization"

- Content.Client/Input/ContentContexts.cs
- Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
- Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs
- Content.Server/Standing/LayingDownComponent.cs
- Content.Server/Standing/LayingDownSystem.cs
- Content.Shared/Input/ContentKeyFunctions.cs
- Content.Shared/Weapons/Ranged/Components/GunComponent.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
- Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
- Resources/Locale/en-US/movement/laying.ftl
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/keybinds.yml
Adds a way to lay down/crawl using a keybind (R by default) similarly to ss13. It has the same effects as falling down after slipping or buckling to a bed, except you don't drop items while doing so and can (very slowly) move around. This opens new gameplay and roleplay possibilities.
You can only toggle standing/laying once in 2.5 seconds (this cooldown is to prevent pro gamers from spamming it). It shows a small popup to everyone. If the attempt fails for whatever reason - being buckled, sleeping, stunned, or anything else - another popup is shown that's only visible to you.
It's been tested and made sure that the system works correctly with buckling, sleeping, being stunned, and shocked.
<p>
18 mb recording won't fit on github: …
> Lay Down via Keybind

- Resources/Prototypes/DeltaV/Entities/Clothing/Uniforms/jumpsuits.yml
- Resources/Prototypes/Entities/Clothing/Uniforms/misc_roles.yml
- Resources/Prototypes/Loadouts/Jobs/engineering.yml
- Resources/Prototypes/Loadouts/Jobs/medical.yml
- Resources/Prototypes/Loadouts/Jobs/science.yml
- Resources/Prototypes/Loadouts/Jobs/security.yml
- Resources/Prototypes/Loadouts/Jobs/service.yml
- Resources/Prototypes/Loadouts/shoes.yml
- Resources/Prototypes/Loadouts/uniform.yml
- Resources/Prototypes/Nyanotrasen/Entities/Clothing/Uniforms/costumes.yml
This is kind of a small PR here, all I'm really doing is adding species(read: Harpy) restrictions to all items that are invalid for a Harpy to wear, and then reparenting items that have a skirt but aren't tagged as such, so that Harpies can wear them. This now makes widespread actual usage of species restrictions in Loadouts. And also this stops people complaining that Harpies can buy items that they cannot wear.
Harpies coincidentally now have a blank Shoes tab.
:cl:
- fix: Harpies can no longer buy Loadout items that are impossible for them to wear due to having digitigrade legs.
> Add Species Restrictions to Loadout Items

- Content.Server/Chat/Systems/ChatSystem.cs
- Content.Shared/Language/LanguagePrototype.cs
- Resources/Locale/en-US/language/languages.ftl
- Resources/Locale/en-US/language/sign-language.ftl
- Resources/Prototypes/DeltaV/Entities/Mobs/Species/vulpkanin.yml
- Resources/Prototypes/Language/languages.yml
Gives a new way to speak, Sign Languages using the Language system by only adding a nullable variable.
Sign Language uses the default Emote system, meaning its will not get picked up by Radio or others devices or get blocked by accents.
When a Sign Language is on, "Say/Whisper" will talk in Sign Language, Emote will still act like normal emotes.
The Glorious Sign Language has arrived... and there can be more then one!
---
<p>
</p>
</details>
---
:cl: FoxxoTrystan
- add: Added the ability to speak with Sign Language.
> Sign Languages!

- Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml
Captain's Carapace inherited HidesHarpyWings because wizden made it parent off Large outerwear for reasons. I've moved HidesHarpyWings to only LargeOuterwear that actually have harpy sprites so that this won't happen again.
> Harpy Hotfix (Cherry-Pick Broke Things)

- Content.Shared/CCVar/CCVars.cs
Height Sliders modifying zoom was always going to be temporary, and long term we had planned on phasing it out in favor of allowing Physics to be the balancing factor against players making their characters small. Now that we have features such as Space Wind, Mass Contests, Frictionless Space, and so on, this has come to fruition, and we no longer necessarily need zoom-adjusting to be a balancing factor. Zoom is cited as one of the most common complaints about our codebase, players absolutely seem to not like this, especially since it's not communicated to them in character creation that their viewmodel is going to be adjusted.
This PR does not permanently remove the Modifies_Zoom feature, merely setting it to false by default. Server hosts are still able to re-enable it in their TOML …
> Disable height.modifies_zoom

- Content.Server/Chat/Systems/ChatSystem.cs
This fixes a bug that has been present in the game for ages, that people can talk to each other in the cold vacuum of space without the aid of a radio. I figured out that this doesn't actually need me to make my "SpaceAudioSystem" just yet, and can be handled with an extremely easy check of the voice source's Transform. Simply put, if they're not touching any grid, their voice can't be heard. Additionally, if a speaker is standing on a different grid from a potential receiver, their voice cannot be heard since the two are on different grids. Effectively, all verbal communication MUST be done through a radio if anyone involved is in space, or on a different grid. Voice can no longer travel between grids. 
Sound should not travel through the vacuum of space. Use a radio to communicate, or …
> People Can't Talk In Space

- Content.Client/Camera/CameraRecoilSystem.cs
I made this entirely on a whim to prove a point in the middle of a conversation. I have not tested this code, but I'm confident that it will work as advertised. 
This refactors the public KickCamera function so that it no longer: Divides by 1, divides by 1 again, multiplies by 1, normalizes a vector(turning its A value to 1), and then divides said vector by 1 again for good measure.
Instead 1 has been replaced by MassContest, wooh! I also got rid of redundant steps. The effect of this is that characters with greater than human-standard mass are slightly more resistant to all sources of camera shake(Explosions, gravity generator turning off, gunfire, being hit by flying objects, etc), while characters with less than standard human mass experience a greater amount of camera shake.
You're …
> Mass Contests Affect Camera Shake

- Resources/Prototypes/Catalog/VendingMachines/Inventories/cart.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
By request from @OldDanceJacket, this PR does two things. First, it gives the HoP access to Cargo, so that in ODJ's own words, "The Hop can be like the Warden to Cargo. They are Brothers In Bureaucracy". The second thing this PR does is add BASIC department PDAs for each department to the PTECH vendor, enabling the HOP to hire people on as the basic roles for every department, with additional PDAs for the teaching roles(Interns). 
By design, all specialized department roles(Such as Chemistry) cannot be granted by the HOP, and must instead be given by their respective heads of staff. 
:cl:
- add: The Head Of Personnel can now hire people onto basic roles for each department by vending PDAs.
> Restore HoP As A Functional Job

- Resources/Prototypes/Tiles/floors.yml
By request from @OldDanceJacket , this restores the ability for pipes and wires to be hidden underneath grass and asphalt. I was originally going to also port digging, but it turns out that SOMEONE already ported digging, but completely forgot to also fix the subfloor nonsense. 
With ShowSubfloor:
Subfloors hidden:
Dig the grass to expose pipes and wires:
:cl:
- fix: Pipes and Wires are now correctly hidden by grass and asphalt once more. Use a shovel to expose pipes hidden by grass.
> Fix Subfloors For Diggable Diles

- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Contests/ContestsSystem.cs
This PR massively expands upon the functionality of the Contests System, fully restoring it not only to the original level of functionality available to the Nyanotrasen Contests, but vastly exceeding its functionality too. Contests now include features like Health Contests, Stamina Contests, but also include hooks for Mind Contests (To allow other systems to implement theoretical effects of MindContest even though I'm not yet finished with the Psionic Refactor). 
Additionally, all Contests now include optional overrides, allowing other functions to modify their own expected outcomes from the ContestsSystem. These two optional overrides are:
- BypassClamp: Bypasses the clamp outright, allowing for Classic Nyanotrasen Contests style of outputs, with theoretically infinite results. If …
> Update Contests System

- Content.Client/Lobby/LobbyUIController.cs
:cl:
- fix: Fixed the character editor dummy always acting like a human
> Fix Editor Dummy Always Being Human

- Resources/Locale/en-US/deltav/station-events/events/xeno-vent.ftl
- Resources/Locale/en-US/station-events/events/vent-critters.ftl
- Resources/Prototypes/DeltaV/GameRules/events.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/Nyanotrasen/GameRules/events.yml
Significant event rebalance based on my own experience and feedback from some players, mostly aimed to improve low-pop experience and prevent multiple instances of same event occurring at once.
Added weaker versions of hostile critter events. Those versions spawn 2-3 times less critters and come with a different announcement: SlimesSpawnWeak, SpidersSpawnWeak, XenoVentsWeak.
Rebalanced the following events:
- AnomalySpawn - reoccurrence delay of 8 minutes to prevent multiple anomalies from spawning with a delay of a few seconds (which has happened many times).
- BluespaceArtifact - same, but 5 minutes.
- BluespaceLocker - 15 minute reoccurrence delay and no more than 4 occurrences per shift because it's really annoying.
- BreakerFlip, BureaucraticError, ClericalError - reoccurrence delay …
> Event Rebalance

- Content.Shared/Clothing/EntitySystems/ClothingSystem.cs
Prevents players from picking up their own equipped clothing (via the "put in hand" verb or otherwise) and thus bypassing the unequip delay completely.
Does so by cancelling the GettingPickedUpAttemptEvent on equipped clothing. This does not prevent unequipping the clothing normally, i.e. by interacting with it in the inventory, or stripping clothing from others.
No cl no fun - most people don't even know this was an option.
> Prevent Instant Unequip of Clothing

- Content.Server/Chat/Systems/ChatSystem.cs
https://github.com/Simple-Station/Einstein-Engines/pull/574 introduced a bug whereby people who are each on separate grids, but the grids were attached, could not talk to each other. I have corrected this by making it so that when the Cross-Grid check is handled, it also checks to see if the two different grids are JOINTed to each other. Therefore allowing sound to travel across the connection. This should also work from Shuttle To Planet, since it's also handled via the same system. This means that docked shuttles allow sound to travel across to the docked station(or other shuttle), as well as shuttles docked to a planet's surface will permit sound to travel to the planet.
:cl:
- fix: Fixed a bug where sound was not traveling over a Shuttle-Docking connection. Attached grids now permit …
> Fix Talking Across Docked Grids

- Content.Shared/Customization/Systems/CharacterRequirements.cs
- Content.Shared/Customization/Systems/CharacterRequirementsSystem.cs
- Resources/Locale/en-US/customization/character-requirements.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/DeltaV/Traits/altvision.yml
- Resources/Prototypes/Loadouts/Jobs/engineering.yml
- Resources/Prototypes/Loadouts/Jobs/medical.yml
- Resources/Prototypes/Loadouts/Jobs/science.yml
- Resources/Prototypes/Loadouts/Jobs/security.yml
- Resources/Prototypes/Loadouts/Jobs/service.yml
- Resources/Prototypes/Loadouts/head.yml
- Resources/Prototypes/Loadouts/items.yml
- Resources/Prototypes/Loadouts/outerClothing.yml
- Resources/Prototypes/Loadouts/shoes.yml
- Resources/Prototypes/Loadouts/species.yml
- Resources/Prototypes/Loadouts/uniform.yml
- Resources/Prototypes/Traits/inconveniences.yml
- Resources/Prototypes/Traits/neutral.yml
- Resources/Prototypes/Traits/skills.yml
Fixed species requirements, they can now be used for ORs.
Improved trait/loadout requirement code, made the colors per-item instead of on the commas too.
Removed group exclusion requirements in favor of the aforementioned.
> Fix Multiple Species Requirements

- README.md
The folder for the linux scripts is wrong. Thought I might as well fix it, while I'm at it.
> Fix Script Folder in Readme for Linux

- Content.Server/Administration/Managers/AdminManager.cs
- Resources/toolshedEngineCommandPerms.yml
For reasons unknown, AdminManager has two command permission managers: _commandPermissions and _toolshedCommandPermissions. It used to load normal command permissions into the former, and toolshed command permissions into the latter. Since _toolshedCommandPermissions is NEVER actually used in checking whether a player can execute a command, all toolshed commands remained unavailable to anyone without +HOST.
This PR provides a bandaid fix for that: it makes it so that the same permissions are loaded into both managers at the same time. It's necessary to load them into _commandPermissions in order to allow regular players to execute them, and it's also necessary to load them into _toolshedCommandPermissions because otherwise the ToolshedManager will complain about those commands lacking …
> Fix 125 Toolshed Commands Being Unusable for Anyone without +HOST

- Content.Shared/DoAfter/SharedDoAfterSystem.cs
I got so pissed off that being near a singularity means you can't crowbar doors, that shortly after dying to a singularity because of said bullshit, I had written this before an emergency shuttle even arrived to pick up the crew. 
:cl:
- fix: Radiation damage no longer interrupts DoAfters.
> Radiation Doesn't Prevent DoAfters

- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/Entities/Objects/base_item.yml
- Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml
Done by request from several people who have some issues with the sound mixing of certain items being very off. I did a little digging, and discovered that the heart of the issue is that id: BaseItem had for whatever utterly strange reason, set the volume for every item not overriding it to be above people's sound settings, resulting in pickup and drop sounds being strangely inconsistent with all other volumes. It got so bad that some people reportedly couldn't play the game.
:cl:
- fix: Fixed Tools, Drink Containers, Lockers, and all base items having inconsistent sound settings.
> Fix Sound Params

- Content.Shared/Weapons/Ranged/Components/GunComponent.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
LASERS HAVE NO RECOIL, THEY SHOULD NOT PUSH YOU AROUND IN SPACE. THE CAPTAIN'S LASER PISTOL IS NOT AN INFINITE USE JET PACK. STUPID BUG. ME FIX. 
There are MANY things I hate about the gun system's code, I am going to revisit this later with a more comprehensive update. There are many hardcoded constants in it related to physics that I thoroughly despise. Guns should just be allowed to declare how much force of recoil they have, rather than it being hardcoded as "CONSTANT 25f". Also, I would like that if the Recoil value is greater than your character's mass, to then knock your character on their ass and/or send them flying. Imagine a Felinid getting thrown back by firing a shotgun. There's my justification for doing so. 
:cl:
- fix: Lasers no longer function as jetpacks in space.
> Lasers Have No Recoil

- Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
<p>
</p>
</details>
---
:cl:
- fix: Fixed the Uncategorized category not being hidden when empty
> Fix the Uncategorized Category Not Being Hidden

- Content.Server/Chat/Systems/ChatSystem.cs
- Content.Server/Language/TranslatorSystem.cs
- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Content.Shared/Language/LanguagePrototype.cs
- Resources/Locale/en-US/language/languages.ftl
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Objects/Devices/translators.yml
- Resources/Prototypes/Entities/Structures/Machines/Computers/base_structurecomputers.yml
- Resources/Prototypes/Language/languages.yml
Fixes:
- Whisper not undergoing readability obfuscation when out of range
- Handheld translators ignoring language knowledge requirements
- Several animals not having defined languages
- Computers not having languages (this primarily affects the RnD console and in the future the cargo request console which send radio messages)
- Some languages lacking brightness and thus being hard to read
Also makes language colors from language markers use alpha blending instead of overriding the original color. The change is subtle, kinda hard to make it noticable without defeating the original purpose...
Example of the new colors
</p></details>
---
:cl:
- fix: Whisper can no longer be heard clearly outside the intended range.
- fix: Translators can no …
> Minor Language Fixes

- Resources/Prototypes/Loadouts/Jobs/Heads/captain.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/chiefEngineer.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/chiefMedicalOfficer.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/command.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/headOfPersonnel.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/headOfSecurity.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/quarterMaster.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/researchDirector.yml
- Resources/Prototypes/Loadouts/Jobs/cargo.yml
- Resources/Prototypes/Loadouts/Jobs/medical.yml
- Resources/Prototypes/Loadouts/Jobs/security.yml
- Resources/Prototypes/Loadouts/Jobs/service.yml
- Resources/Prototypes/Loadouts/categories.yml
- Resources/Prototypes/Loadouts/eyes.yml
- Resources/Prototypes/Loadouts/hands.yml
- Resources/Prototypes/Loadouts/head.yml
- Resources/Prototypes/Loadouts/items.yml
- Resources/Prototypes/Loadouts/mask.yml
- Resources/Prototypes/Loadouts/neck.yml
- Resources/Prototypes/Loadouts/outerClothing.yml
- Resources/Prototypes/Loadouts/shoes.yml
- Resources/Prototypes/Loadouts/uniform.yml
Adds significantly more items to Loadouts. Notably, it adds almost every item from the ClothesMate, a decent amount of clothing from the AutoDrobe, and some missing clothes from the WinterDrobe.
Other changes:
- Restrict Command from wearing uniforms outside of their job
- Limit Security's non-sec uniform/head/mask options to those that maintain the Security aesthetic, such as clothes that are red, black, and some blue/beige, and all MNK gear.
- Restrict all shoes from Dionas and Harpies properly. I have a feeling that there's a better way to get around this issue, perhaps by preventing these species from selecting items that are based on `ClothingShoesBase`.
- Make all colored jumpsuits available to all Civilians, and select jumpsuits for departments such as white/blue for Medical, …
> More Loadout Items: Wave 2

- Content.Server/Remotes/DoorRemoteSystem.cs
Reverts Simple-Station/Einstein-Engines#315
As [I brought up](https://github.com/Simple-Station/Einstein-Engines/pull/315#issuecomment-2105861135) in the original pr, this change was made to counter power gaming, which isn't as much of an issue on EE downstreams, and adversely affects the engineering department, without any major benefits.
> Revert "Mirror: Restrict Door Remotes to only Being Able to Manipulate Doors Relevant to Their Type"

- Resources/Prototypes/Catalog/Fills/Boxes/general.yml
- Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Food/Containers/lunchbox.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
- Resources/Prototypes/Entities/Objects/Tools/toolbox.yml
Subcontainers such as Boxes, Medkits, and Lunchboxes are essentially useless items that players always throw away. The given reason for this is that because the boxes only ever provided the same or less inventory slots than the inventory slots they take away, using boxes only ever penalizes players. Since you can only ever open one container at a time, placing items in boxes means you have to first open your backpack, then open the box, then take the item out.
How it SHOULD work instead, is that boxes contain slightly more inventory slots than what they remove. You would effectively be trading the ability to quickly and efficiently access all your items, for having slightly more inventory capacity. This PR buffs the parent of four different categories of items, such that 3x3 boxes occupy …
> Make Boxes Not Useless

- Resources/Prototypes/DeltaV/Traits/altvision.yml
- Resources/Prototypes/Traits/neutral.yml
This takes Ultravision, Dogvision, and Normalvision, making all 3 traits into our first set of "Neutral" traits. They now cost 0 points, but still occupy one of the 5 trait selections. In the future we should have a decent roster of Positive, Neutral, and Negative traits. If Death ever finishes making Subcategories, we'll probably want to have Positive, Neutral, and Negative be the 3 "Main" categories, and all subcategories sit underneath them.
<p>
Token screenshot for a 3 line PR because my maintainers will get onto me if I don't include some kind of media. :trollface: 
</p>
</details>
:cl:
- tweak: Ultraviolet Vision, Deuteranopia, and Trichromat Modification are all now 0 point Neutral traits. They still occupy one of your trait selections.
> "Buff" Vision Traits

- Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
- Resources/Prototypes/Entities/Clothing/Belt/belts.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Loadouts/Jobs/security.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
- Resources/Prototypes/Recipes/Lathes/security.yml
Added combat knives to the SecTech vendor and added the combat knife to the security techfab for a cost of 2.5 steel and 1 plastic.
With this change, Harpy and Diona Security players can now get a combat knife from the SecTech as they cannot spawn nor wear combat boots, which contains a combat knife.
Prison guards now start with combat boots with a combat knife, and a combat knife has been added to Loadouts for Felinid/Harpy security.
Cherry-picked from Space Wizards (https://github.com/space-wizards/space-station-14/pull/27224).
An equivalent to "Fix no combat knives in sec techfab" (https://github.com/space-wizards/space-station-14/pull/28086) has been added with 7809b504cc1c2f8f4e9db2e820d94f292e787115, which also adds the combat knife to emagged autolathes.
:cl: Skubman, Ghagliiarghii …
> Increase Combat Knife Availability

- Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
- Content.Server/StationEvents/RampingStationEventSchedulerSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Resources/Locale/en-US/game-ticking/game-presets/preset-survival.ftl
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/game_presets.yml
This reverts commit 910b4c3c4e83e07fe2e22687e74c940604e97eb1.
The PR was never tested properly, and after it was merged on deep station, a lot of significant issues have been uncovered, including station events appearing every 6-12 seconds regardless of the gamemode, some RampingStationEventScheduler component fields being unused, some CVars having misleading usages, some CVars being unused, and more.
The PR needs to be re-done and tested thoroughly before it can be merged.
:cl:
- fix: Reverted the station event scheduler rework due to it absolutely breaking the game.
> Revert "Refactor Ramping Event Scheduler (#592)"

- Content.Server/StationEvents/EventManagerSystem.cs
Makes it so that the event scheduler doesn't pick events that were already added (but not yet ended).
In order to fix this:
<details><p>
</p></details>
> Fix Event Manager Allowing to Start Multiple Events of the Same Type in a Short Time Window

- Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
- Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
The original intended purpose of Loadouts as designed by Death was to serve as the ultimate solution to the Clothesmate BLOAT. Ironically, when Wizden made their own Loadouts, they made a version of Loadout that is incapable of this. Now that we've more significantly fleshed out EE Loadouts to fulfill that purpose, I can finally trim down the Clothesmate. I haven't touched any of the other vendors, just the Clothesmate. 
As an aside, the cost of a Clothing restock has gone down from a fucking ridiculous 4500, down to only 1500. Making it something Cargo techs can actually reasonably buy. Clothesmates now only contain the absolute barest minimum clothes for a greytider. This also helpfully serves as a balancing act against Loadouts being able to provide items other than clothes. It is much …
> Remove Clothesmate Bloat

- Resources/Prototypes/Roles/Jobs/Security/detective.yml
Partial fix to #145, as the changes in inventory will need reflected in the Security Loadout system which will be in another PR.
Made so Detective has the same access as Security Officers.
> Fixes Failed to Cherry-Pick PR #25986: Return Detective to Security #145

- Resources/Prototypes/Entities/Markers/Spawners/Random/vending.yml
- Resources/Prototypes/Entities/Markers/Spawners/Random/vendingdrinks.yml
https://github.com/Simple-Station/Einstein-Engines/pull/400 added 4 new vendors that were never implemented in the game's spawners, so they never actually appeared ingame. This PR adds them to random vendor spawners, so that they'll show up on stations.
:cl:
- add: SweatMAX, "hot foods", Mars Mart, and Nippon-tan vendors have all been added to vendor spawners.
> Add 4 Missing Vendors To Vendor Spawners

- Content.Server/GameTicking/Rules/ZombieRuleSystem.cs
Problem: "Players like to stall zombie rounds"
Solution: Fix the Anti-Stall mechanic.
The set of functions for handling the automatic shuttle call now correctly only checks "The" station, rather than any grid containing a StationDataComponent. By using the less permissive _gameTicker.GetSpawnableStations(); function, the zombie gamerule no longer includes stations such as Centcomm, Planet Expeditions, some salvage wrecks, certain space ships, the Syndicate Listening Outpost, and Nukie World. Additionally, the check for "Healthy" humans no longer considers anyone infected with the zombie virus to be a "Healthy" human, ensuring that someone with a 200u jug of Bicaridine can no longer contribute to round stalling. Finally, dead (player)zombies are now by default checked for the purpose of …
> Zombie Improvements Take 2

- Content.Server/Traits/Assorted/LanguageKnowledgeModifierComponent.cs
- Content.Server/Traits/Assorted/LanguageKnowledgeModifierSystem.cs
- Resources/Locale/en-US/language/languages.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/skills.yml
**Sign Language** is a 1-point Visual trait that allows you to use Galactic Sign Language.
:cl: Skubman
- add: Add a new 1-point trait called Sign Language, a trait that allows you to communicate in Galactic Sign Language.
> New Trait: Sign Language

- Resources/Prototypes/DeltaV/Species/vulpkanin.yml
As title, will allow players to put as many overlay markings as required for their vulps.
---
:cl: TJohnson
- tweak: Removed overlay restriction for vulps, you can now have as many overlay markings as you want!
> Remove Overlay Restrict From Vulps

- Content.Server/Nyanotrasen/Abilities/Boxer/BoxingSystem.cs
- Content.Server/Nyanotrasen/Abilities/Oni/OniSystem.cs
- Content.Server/Nyanotrasen/Psionics/PsionicsSystem.cs
- Content.Shared/Damage/Events/TakeStaminaDamageEvent.cs
- Content.Shared/Damage/Systems/StaminaSystem.cs
- Content.Shared/Inventory/InventorySystem.Relay.cs
- Content.Shared/Stunnable/StaminaDamageResistanceComponent.cs
- Content.Shared/Stunnable/StaminaDamageResistanceSystem.cs
- Resources/Locale/en-US/armor/armor-examine.ftl
- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Added stamina damage resistance, acts the same way as armor does.
Call this shock resistance if you wish :trollface:
Just attach StaminaDamageResistance component to an entity with a set multiplier and have fun.
Made all hardsuits 25% stun resistant by default.
With some variety, e.g. nukie, ERT, captain, HoS suits are 50%, DS are 90%, etc. etc.
This will not remove stuneta but it will make it more difficult to stamcrit a traitor or such.
Some armor/batong ratios that you need to hit before the target is stamcritted:
0% - 3 batong hits
25% - 4 batong hits
50% - 6 batong hits
75% - 12 batong hits
90% - 28 batong hits :trollface:
100% - 
:cl:
- add: Added different stamina damage resistance to hardsuits.
> Stamina Damage Resistance Real

- Content.Server/Body/Components/BloodstreamComponent.cs
- Content.Server/Body/Systems/BloodstreamSystem.cs
- Content.Server/Traits/BloodDeficiencyComponent.cs
- Content.Server/Traits/BloodDeficiencySystem.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/disabilities.yml
**Blood Deficiency** is a +2 points negative Physical trait that makes you slowly lose blood over time. When left untreated you will die from blood loss. Inspired by the SS13 trait of the same name.
Slash/Piercing weapons and bleeding are much more lethal against you.
The moment you start taking **any** blood loss damage, you start dying because you can't regenerate blood. Even just two consecutive kitchen knife stabs will make you bleed enough to die slowly unless you immediately apply gauze.
Blood packs, iron pills (or copper for Arachnids), and gauze to stop bleeding will help you survive with this trait.
Here's how the timeline looks for untreated blood deficiency:
- ~0-21 minutes: losing blood slowly
- ~21-31 minutes: blood level below 90%, start taking bloodloss damage
- ~31-33 …
> New Trait: Blood Deficiency

- Content.Server/Body/Components/BloodstreamComponent.cs
- Content.Server/Body/Systems/BloodstreamSystem.cs
Being a little too clever with omitting braces in complicated if statement chains in #686 caused blood regeneration for entities without Blood Deficiency to stop working altogether. I added some braces and now blood regeneration works again.
I also added `DataField` to `HasBloodDeficiency` because I forgot to add that.
:cl: Skubman
- fix: Passive blood regeneration now works again.
> Fix No Blood Regeneration

- Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs
This PR fixes an issue with the BarotraumaSystem which would constantly report high pressure damage, even when no such damage was applied.
---
---
:cl:
- fix: Barotrauma admin log spam
> Fix BarotraumaSystem

- Content.Server/DeltaV/NPC/Roboisseur/RoboisseurSystem.cs
- Resources/Prototypes/DeltaV/NPC/roboisseur.yml
Cherry-picks https://github.com/DeltaV-Station/Delta-v/pull/1100 and https://github.com/DeltaV-Station/Delta-v/pull/1222.
Makes butlertron anchorable, pullable, and destructible, and disables logging of butlertron's messages.
Credit to adeinitas and NullWanderer.
This was cherry-picked without testing, someone needs to test it first.
:cl:
- add: Mr. Butlertron can now suffer for its crimes.
> Butlergone (Cherry-Pick From Delta-V)

- Resources/Prototypes/Entities/Objects/Specific/Research/misc.yml
It says Psionic chat out loud
<p>
</p>
</details>
---
:cl:
- add: Readded Psionic Relay Orb
> Add Le Psionic Orb From Nyanotrasen

- Content.Server/Traits/Assorted/TraitSpeedModifierComponent.cs
- Content.Server/Traits/Assorted/TraitSpeedModifierSystem.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/inconveniences.yml
- Resources/Prototypes/Traits/skills.yml
This PR adds two new negative traits that decrease your movement speed: **Sluggish** and **Snail-Paced**.
- Sluggish (+1 points)
- 15% slower movement speed
- 35% slower climbing speed (for standard tables, from 1.5s to ~2.02 seconds)
- Cooldown on laying down/standing up increased from 2.5 seconds to 3 seconds
- Snail-Paced (+2 points)
- 30% slower movement speed
- 66% slower climbing speed (for standard tables, from 1.5s to ~2.48 seconds)
- Cooldown on laying down/standing up increased from 2.5 seconds to 4 seconds
<details><summary>Expand</summary>
**Trait entry**
</details>
:cl: Skubman
- add: Add two new negative traits: Sluggish (+1) and Snail-Paced (+2) that make you move slower, and climb tables slower.
> New Trait: Sluggish / Snail-Paced

- Content.Server/Body/Components/BloodstreamComponent.cs
- Content.Server/Traits/HemophiliaComponent.cs
- Content.Server/Traits/HemophiliaSystem.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/disabilities.yml
**Hemophilia** is a +1 point negative Physical trait that makes you more susceptible to bleeding. You bleed twice as long, and you take 10% more Blunt damage.
<details><summary>Expand</summary>
</details>
---
:cl: Skubman
- add: Add the Hemophilia trait, a new negative trait for 1 point that makes you bleed twice as long and makes you take 10% more Blunt damage.
> New Trait: Hemophilia

- Resources/Locale/en-US/interaction/interaction-popup-component.ftl
- Resources/Prototypes/DeltaV/Entities/Mobs/Player/vulpkanin.yml
- Resources/Prototypes/Entities/Mobs/Player/arachne.yml
- Resources/Prototypes/Entities/Mobs/Player/harpy.yml
- Resources/Prototypes/Entities/Mobs/Player/skeleton.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Player/Oni.yml
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Player/felinid.yml
Reasoning:
1) Hugging your coworkers isn't necessarily always inappropriate, but it's something that should take a bit more intention than it does now.
2) Event subs in this game right now still have no good method of handling multiple subscriptions to the same event. The hugging event is occupying 2 pieces of prime real estate - the empty hand interaction, which is the most common, and the humanoid interaction, which is the most common and most important. And for what? Spamming popups and chat for something that could just be an emote.
3) Because of the above, it's too easy to accidentally hug people while doing something else - the lack of intersectionality makes people just ignore hugging because they assume it means nothing and was not intentional. This does not lead to good roleplay …
> Remove Hugging Interaction Popup From Humanoids

- Content.Shared/CCVar/CCVars.cs
Given the big influx of new traits, a maximum of 5 traits can feel constricting, as often you'll have unspent points but not enough trait slots to buy more traits. This doubles the default trait limit from 5 to 10 to increase player choice and allow more unique trait setups.
Since the base trait points have not been increased, players will still need to take negative traits if they want to have more positive traits than before.
:cl: Skubman
- tweak: The maximum trait limit has increased from 5 traits to 10 traits.
> Increase Trait Limit From 5 To 10

- Resources/Changelog/Changelog.yml
- Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
- Resources/Prototypes/Loadouts/Jobs/science.yml
- Resources/Prototypes/Loadouts/eyes.yml
- Resources/Prototypes/Loadouts/head.yml
- Resources/Prototypes/Loadouts/items.yml
Various minor yaml and QOL ports from Floofstation.
Changelog entries go in order of author. I'm considering just copying over the changelog at some point.
:cl: AeraAuling, ShatteredSwords and Cynical24
- add: Added the Explorer's Labcoat and a Hairflower into Loadouts.
- fix: Fixed Epistemics being unable to take Survival Boxes
- fix: Fixed the NearSighted trait making you unable to take glasses in your loadout
- add: Added a variety of Cowboy Hats into loadouts.
> Various Floofstation Ports.

- Resources/Changelog/Changelog.yml
- Resources/Locale/en-US/loadouts/eyes.ftl
- Resources/Prototypes/Entities/Clothing/Eyes/misc.yml
- Resources/Prototypes/Loadouts/eyes.yml
:cl: DangerRevolution
- add: Adds a new blindfold variant into loadouts.
> Adds Fake Blindfold

- Content.Server/MassMedia/Systems/NewsSystem.cs
It was never used but caused annoyance all the time: the listening post could never use the news console and ghosts/centcom officials/skeletons could never publish news because of it.
(This was not tested, I recommend either waiting til I test it or making someone else test it before merging)
:cl:
- fix: You no longer need to have a station record to publish news.
> Remove the Stupid Station Records Check From News

- Content.Client/Overlays/DogVisionOverlay.cs
- Content.Client/Overlays/DogVisionSystem.cs
- Content.Client/Overlays/SaturationScaleOverlay.cs
- Content.Client/Overlays/SaturationScaleSystem.cs
- Content.Client/Overlays/UltraVisionOverlay.cs
- Content.Client/Overlays/UltraVisionSystem.cs
- Content.Shared/DeltaV/Abilities/UltraVisionComponent.cs
- Content.Shared/Nyanotrasen/Abilities/DogVisionComponent.cs
- Content.Shared/Traits/Assorted/Components/DogVisionComponent.cs
- Content.Shared/Traits/Assorted/Components/UltraVisionComponent.cs
Overlays have a funny bug where the calls to update them are global. Meaning if any single person gets a bad enough mood to greyscale themselves, everyone globally gets greyscaled. This bug was also present on Dogvision and Ultravision, and had the same cause. Frontier luckily had a fix for those two, and the fix works here as well for the Mood Overlay. 
:cl:
- fix: Fixed an issue where Overlays(Dogvision, Ultravision, Mood) would apply globally to all entities when updating.
> Fix Overlays

- Resources/Locale/en-US/traits/traits.ftl
I accidentally deleted these at some point, so here they are again.
No changelog because I don't want to publicly admit the error. :)
> Missing Psychic Trait Strings

- Content.Client/Actions/ActionsSystem.cs
- Content.Server/Abilities/Psionics/Abilities/DispelPowerSystem.cs
- Content.Server/Abilities/Psionics/Abilities/MindSwapPowerSystem.cs
- Content.Server/Abilities/Psionics/Abilities/NoosphericZapPowerSystem.cs
- Content.Shared/Actions/EntityTargetActionComponent.cs
- Content.Shared/Actions/SharedActionsSystem.cs
- Resources/Prototypes/Actions/psionics.yml
I noticed that EntityTargetAction prototypes have a Whitelist field, but no Blacklist field. This turned out to be trivial to add, and now it's no longer necessary for Psionic powers to hardcode in C# that they can't affect anyone psionically insulated or Mindbroken. In total only 3 powers had this change, but new powers in the future that affect a target can now arbitrarily blacklist any component(Most likely, PsionicInsulation and Mindbroken. :))
All of this, just to remove 9 total lines of C# hardcoding. 
:cl:
- add: Actions no longer need to hardcode in target blacklists, and can now blacklist entities in YML. This is notably useful for Psionic powers, which all share a common feature that they can't target people with Psionic Insulation (Or have been Mindbroken).
> Action Blacklists

- Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.cs
While coding another Psionic Power feature, I discovered that the current implementation of iterating over components does not carry over arguments for the components. So I copied over the method used by Traits exactly-as-is, and just changed the names of the variables to accommodate the PsionicSystem.
:cl:
- add: PsionicPowers that add a Component now also allow for adding a Component with Arguments. This works exactly like the trait system's implementation of components.
> Psionic Powers Add Components With Arguments.

- Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.cs
- Content.Server/Traits/TraitSystem.cs
- Content.Shared/Traits/Prototypes/TraitPrototype.cs
I decided traits weren't flexible enough, so I refactored them to also optionally add Actions(Activatable Abilities), and PsionicPowers(Going through the PsionicAbilitiesSystem). Neither of these have any current implementations, I'll leave that to other people. Trait Components are by extension no longer a hard requirement, although if you add a blank trait that adds nothing, you have only yourself to blame. But doing so won't crash the game or throw an error anyway.
:cl:
- add: Traits can now add Active Abilities to a character.
- add: Traits can now add Psionic Powers to a character.
> Traits Refactor

- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/familiars.yml
Closes #754
Ifrit is a fire spirit, he really shouldn't be taking 1.5x fire damage. This makes sense and should help with players accidentally killing themselves with the fire ball. 
For balance, the cold damage modifier was changed to 0.5x, unsure if it should be lower.
Minor passive regeneration has also been added, since there isn't another way to heal other than the Mystagogue sitting there hitting them with the book of mysteries.
:cl: 
- tweak: Ifrit has received some damage resistance changes
> Minor Ifrit Health Rework

- Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
Admin menu tried to load a sprite that doesn't exist which spammed errors in testing a lot.
> Fix Missing Icon Error in Admin Menu

- Content.Shared/CCVar/CCVars.cs
- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/inconveniences.yml
- Resources/Prototypes/Traits/neutral.yml
- Resources/Prototypes/Traits/physical.yml
- Resources/Prototypes/Traits/skills.yml
- Resources/Prototypes/Traits/species.yml
Since we now have a LOT of Traits, and soon to be another fresh batch of Traits coming in now that they've been refactored to offer even more options, it's come up that Traits are kinda hard to balance with the current combination of point costs and allotted starting points. To help alleviate this problem, I've both doubled the point values of every trait in the game, as well as doubled the default allotted starting points. There is now more room to balance trait costs against each other.
I have not however actually made use of the new range of point costs yet, and would like to consult with other contributors and maintainers on which traits need to be adjusted. 
:cl:
- tweak: Trait points have been made more granular by both doubling the available number of trait points, and increasing …
> Increase Trait Point Granularity

- Resources/Prototypes/Species/moth.yml
Magic single line Yml Fix obtained by digging through DeltaV's Blame 
**GO!**
:cl:
- tweak: Moths can now be colorful again.
> Fix RGB Moths

- Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.cs
- Content.Shared/Psionics/PsionicPowerPrototype.cs
- Resources/Prototypes/Psionics/psionics.yml
This PR implements the previously planned feature whereby obtaining a Psionic Power plays some form of notification to alert the player that they have gained a new ability. Since some Psionics like Xenoglossy are purely passive, it's very important to give an indication to players what's going on. To that end, PsionicPowerPrototype has been expanded to include new datafields related to Initialization Feedback. There are now three kinds of feedback messages: Popup, Feedback, and Metapsionic.
All feedback will only play for powers obtained during the round, rather than for entities that innately start with powers.
- Popups will appear over your character's head as a small, brief message. These should be no more than a sentence at most.
- Feedback will appear in the Chat window as a message …
> Psionic Power Feedback Messages

- Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
- Resources/Prototypes/Entities/Mobs/NPCs/mimic.yml
- Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
- Resources/Prototypes/Entities/Mobs/Player/ipc.yml
Soulless Robots didn't have PsionicInsulation, which meant they were eligible targets for powers such as Mindswap. This is a pretty simple fix. 
:cl:
- fix: Robots and other mechanical creatures are now correctly immune to non-physical psionic powers.
> Add Insulation to Robots

- Content.Shared/Contests/ContestsSystem.cs
Now that the initial Psionic Refactor is out of the way, this is my first new standalone Psionics PR, filling in the MindContest function that was added over a month ago(but was set to always return 1f as a placeholder). 
Mind Contests are unique among the Contests System in that they do not treat the lack of a Psionic Component as a failure condition, and instead as a variable.
No changelog because MindContests are not currently used anywhere, all I'm doing is adding the actual function logic.
> Implement Mind Contests

- Resources/Locale/en-US/supermatter/supermatter.ftl
supermatter .ftl was broken, this fixes it.
Easly fix the supermatter .ftl files that was not set correctly, why? i dunno.
now its works.
---
:cl:
- fix: Supermatter Annoncements
> Fix supermatter.ftl

- Resources/Prototypes/DeltaV/Entities/Structures/Doors/Airlocks/access.yml
- Resources/Prototypes/Entities/Objects/Devices/Electronics/door_access.yml
Somehow all the doors accesses broke. Seems somebody used the AccessReader Component on the door instead of the door electronics. This PR fixes all the doors that I could find that were broken.
:cl:
- fix: Fixed most door accesses including: Lawyer, Mantis, Corpsman, Boxer, Clown, Mime, Musician, Reporter, Library, Zookeeper, Salvage and Psychologist.
> Fix Door Access

- Resources/Prototypes/Entities/Mobs/Player/ipc.yml
IPCs were missing Offer Item, Laying Down, and Carriable.
:cl:
- fix: IPCs can now lay down, offer people items, and be picked up and carried.
> Add IPC's Missing Components

- Content.Server/Carrying/CarryingSystem.cs
- Content.Server/Resist/EscapeInventorySystem.cs
- Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Server/Weapons/Melee/ShovingComponent.cs
- Content.Shared/CombatMode/DisarmedEvent.cs
- Content.Shared/Contests/ContestsSystem.cs
- Content.Shared/Damage/Components/StaminaComponent.cs
- Content.Shared/Damage/Systems/StaminaSystem.Slowdown.cs
- Content.Shared/Damage/Systems/StaminaSystem.cs
- Resources/Prototypes/Entities/Mobs/Species/base.yml
First off, shoving was broken badly. It would roll shoving chance twice, meaning that you had only about 6% chance to actually shove someone, and it would only remove 6% of their stamina. Additionally, stamcrits have always pissed me off by just how stupid they were. Also, some of the code in the stamina system had highly misleading names, which has led vmsolidus to implement mass contests the wrong way there.
This PR introduces changes to fix those issues:
- Shoving only rolls the shove chance once.
- Shoving deals 50 * shove chance stamina damage, as intended, without depending on target's stamcrit threshold. In the future it should depend on the weapon used (claws, fists, etc), but for now it's fine.
- Shoving advantage ranges were re-evaluated. Mass difference now can give 0.5x-2x …
> Make Shoving and Stamina Great Again

- Resources/Prototypes/game_presets.yml
Mirroring a PR from Floof that I was much too lazy to cherry-pick. This just changes gamemodes outside of tator and rev to allow thieves if it makes sense to.
---
:cl:
- tweak: Thieves are now in Survival, Hellshift, and Extended.
> Thieves Outside of Traitor

- Content.Server/Chat/TelepathicChatSystem.cs
- Content.Server/Chat/TelepathicRepeaterComponent.cs
- Content.Server/Traits/TraitSystem.cs
- Content.Shared/Psionics/TelepathyComponent.cs
- Content.Shared/Traits/Prototypes/TraitPrototype.cs
- Resources/Locale/en-US/psionics/psionic-powers.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
- Resources/Prototypes/Nyanotrasen/psionicPowers.yml
- Resources/Prototypes/Psionics/psionics.yml
- Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
- Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Traits/skills.yml
This PR re-introduces a feature that was present in the Psionic Refactor version 1, that of the Natural Telepath trait. Where before Natural Telepath was treated as an "Upgraded" version of Latent Psychic, now it is a standalone trait that makes use of new functionality, where traits can add psionic powers directly, as opposed to relying on just adding components. To accomodate for this, the Telepathy functionality has been modified such that it no longer makes the expectation that PsionicComponent users have the ability to coherently speak telepathically, and instead checks for a specific TelepathyComponent. Since Telepathy is added to a Psion via their ActivePowers list, it is also eliminated when the Psion is mindbroken.
<p>
</p>
</details> …
> Telepathy (Minor)Refactor

- Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
- Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
- Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml
- Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
- Resources/Prototypes/Entities/Structures/Doors/Windoors/base_structurewindoors.yml
- Resources/Prototypes/Entities/Structures/Walls/walls.yml
- Resources/Prototypes/Entities/Structures/Windows/plasma.yml
- Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
- Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
- Resources/Prototypes/Entities/Structures/Windows/uranium.yml
This PR is a MUCH needed QOL update for all of our downstream servers that have started mapping in Supermatter engines. I have gone through every single entry of the RadiationResistance component in the game, and tweaked the values of them so that it is actually reasonably practical to provide some protection to the rest of the station during a Supermatter delamination. This fact is highly relevant since one of the things I am working on is a rebase of the wizden map CORE to EE, which will include a replacement of its Singulo with a Supermatter engine. With the pre-existing radiation shielding values, such an engine will near instantly cleanse the entire station of all life within a matter of seconds should it so much as think about delaminating. However with this PR, it's actually …
> Rebalance Radiation Shielding

- Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.cs
- Resources/Prototypes/Entities/Structures/Specific/oracle.yml
- Resources/Prototypes/Nyanotrasen/Entities/Structures/Research/sophicscribe.yml
InnatePsionicPowers needed to be moved from ComponentStartup to MapInitEvent, which is a deceptively named event that ALSO functions identically in use to ComponentStartup, except that it's safe to use for entities that are mapped in, in addition to joining the round or being spawned in. Whereas ComponentStartup isn't allowed to modify or add components for any entity that is mapped(which includes Spawners apparently).
This change allows for entities like Oracle and Sophia to make use of InnatePsionicPowers, which is done by request from Rane, who for mysterious reasons wishes for the two divine statues to be both Prayable, and have the Noospheric Zap Power. 
I have also verified by ingame testing that this does infact apply to people who join after the map is initialized, as well as …
> Fix InnatePsionicPowers For Mapped Entities

- Content.Shared/Preferences/HumanoidCharacterProfile.cs
The current in game UI can reasonably support names up to 48 characters in length, as well as descriptions up to 1024 characters long. Any longer, and the UI requires a scroll bar. This change is present on Cosmatic Drift, which uses the same character UI we currently have. I've had many people requesting this change, and while I am aware that we wish to at some point update to a new character UI(such as Parkstation's UI), but a stopgap here is still nice, and it's just two Const variables.
:cl:
- tweak: Character names can now be up to 48 characters in length.
- tweak: Character descriptions can now be up to 1024 characters in length. This is the maximum size descriptions can be without the menu having a scroll bar. And while we'd like it to be bigger, we're going to want to get a new UI …
> Maximize Default Description Limits

- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
The default stamina cost for Power Attack was supposed to be 10, so imagine my surprise when I find out it's been 20 this whole time. Which wasn't intended. 
:cl:
- fix: The default stamina cost for Power Attacks for any weapon that doesn't explicitly modify it is now correctly set to 10 stamina(down from 20).
> Reduce Default PowerAttack Stamina Cost

- Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/familiars.yml
- Resources/Prototypes/Entities/Mobs/NPCs/elemental.yml
- Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
- Resources/Prototypes/Entities/Mobs/Player/familiars.yml
- Resources/Prototypes/Entities/Mobs/Player/guardian.yml
- Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomalies.yml
- Resources/Prototypes/Nyanotrasen/Entities/Structures/Research/glimmer_prober.yml
Certain things in the game were intended to be classed as Psionic(And mostly without powers), but were apparently lacking the components. To clarify, ANYTHING that comes from an alternate layer of reality, alternative plane of existence, extra dimensions, other universes, bluespace, etc, is intended to have a PsionicComponent to abstract represent their nature as a magical being of some variety. The importance of this is largely related to the use of Metapsionics to detect them, but also for the valid target lists for Anti-Psychic abilities, such as the bonus damage from the Anti-Psychic Knife.
While here, I've also added the "Loto Oil Slime" from Psionic Refactor Version 1, now that Reagent Slimes(as Extraplanar creatures brought to this world by Liquid Anomalies) have a …
> Psionic Extraplanar Creatures

- Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs
I'm putting this here as an option to deal with our Heisentest problems, by making the tests "Fault-Tolerant" wherever practical, but I don't want this merged without Death and Psprite agreeing to this. For the most part I believe that these tests are failing because they are essentially checking that "Random events are not creating entities", by creating their own enforced Race Conditions. This particular test is repeatedly failing because the Mood System has no way of deducing that it's in a test. Even though the alleged issue is a nothingburger. 
Tests absolutely shouldn't have been designed around race conditions.
No changelog because this isn't playerfacing.
> Delete All Then Ghost Fault Tolerance

- Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
This matters for Birbs. All Colored Jumpskirts were incorrectly parented to Jumpsuit and not Jumpskirt, meaning that Harpies couldn't wear them. This fixes that issue. 
:cl:
- add: Due to NUMEROUS complaints, NanoTrasen has swapped the sticker labels on all colored jumpskirts to correctly state that they are infact, "Skirts", so now they can legally be worn by Harpies, Lamia, and Arachne.
> Fix Colored Jumpskirts Actually Being Skirts

- Resources/Prototypes/CharacterItemGroups/miscItemGroups.yml
- Resources/Prototypes/Loadouts/items.yml
- Resources/Prototypes/Loadouts/species.yml
This is the last of the Loadout Item Group PRs I'm going to do for now. This PR adds several more than the previous ones, primarily to split up the Items tab into several distinct groups so as to push down the costs of many items. In particular, the new groups are:
1. Smokes
2. Lighters
3. Instruments
4. Air tanks
5. Box Kits(Survival Boxes or Medkits)
6. Writables
Survival boxes sharing an Item Group with Medkits is kind of intentional here. Both of them take up a SIGNIFICANT amount of your starting inventory space. Now we can have free survival kits once again, but also have as an option, where you can elect to spend some of your loadout points to take a personal Medkit instead of a survival box. You can think of it as an upgrade over a standard survival kit. :)
:cl:
- tweak: Item …
> Miscellaneous Item Groups

- Content.Server/HeightAdjust/BloodstreamAdjustSystem.cs
- Content.Server/HeightAdjust/BloodstreamAffectedByMassComponent.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/HeightAdjust/HeightAdjustSystem.cs
- Content.Shared/HeightAdjust/HeightAdjustedEvent.cs
- Resources/Prototypes/Entities/Mobs/Species/base.yml
Something that just makes sense, this makes your effect character weight affect your bloodstream volume. As a minimum size felinid you will get 33% of normal blood volume, whereas as something as huge as a lamia you may get up to 3 times the normal blood volume.
The resulting volume of your bloodstream can be calculated as `V = clamp(normal_volume * mass_contest ^ 0.6)` (assuming default parameters), where mass_contest is the result of a mass contest between your entity and the average humanoid. For average species like vulps, this means that their bloodstream can become up to ~40% smaller than normal (at minimum size), or up to 50% larger than normal (at maximum size). For onis the range is shifted towards higher values, a maximum size oni will have twice as much blood as an average …
> Make Height Sliders Affect Your Bloodstream Volume

- Content.Server/InteractionVerbs/Actions/MoodAction.cs
- Content.Shared/InteractionVerbs/Requirements/AssortedRequirements.cs
- Resources/Locale/en-US/interaction/verbs/noop.ftl
- Resources/Locale/en-US/mood/mood.ftl
- Resources/Prototypes/Interactions/mood_interactions.yml
- Resources/Prototypes/Interactions/noop_interactions.yml
- Resources/Prototypes/Mood/genericPositiveEffects.yml
Something that was omitted in #733. Hugging and petting now give positive moodlets.
The petting interaction was split into two: one for animals and one for humanoids. The one for animals improves both your own mood and the mood of the animal, whereas petting a humanoid only improves their own mood. In addition to all that, being hugged and being pet do not stack.
<p>
https://github.com/user-attachments/assets/47e8f722-44ee-4d03-a580-65a2946a1920
</p>
</details>
:cl:
- tweak: Hugging and petting interactions now influence mood, just like the old hugging.
> Make Hugging/Petting Interactions Affect Mood

- Resources/Locale/en-US/chat/managers/chat-manager.ftl
4 FTL lines changed
Finally them native GC speakers will know what language to respond in when speaking to us
<p>
https://github.com/user-attachments/assets/68d1b1b2-373d-4f98-958d-3659b7cff440
</p>
</details>
:cl:
- add: Chat bubbles now use the font & color of the language of the message.
> Display Language Fonts/Colors in Chat Bubbles

- Content.Server/StationEvents/Components/OscillatingStationEventSchedulerComponent.cs
- Content.Server/StationEvents/OscillatingStationEventScheduler.cs
- Content.Shared/CCVar/CCVars.cs
- Resources/Locale/en-US/game-ticking/game-presets/preset-irregular.ftl
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/game_presets.yml
This introduces a new event scheduler type that follows a random curve that slowly changes in time. It's designed to sometimes offer the station some chaos, and sometimes offer it times to breathe.
Also adds two new gamemodes - irregular and irregular extended - which use this scheduler.
Also fixed the issue with other related CVars not being archived.
:cl:
- add: Added two new gamemodes - irregular and irregular extended - which use a new type of event scheduler that offers irregular periods of peace, chaos, and anything in between. The extended version is meant for longer rounds with significantly lower levels of chaos.
> Oscillating Event Scheduler

- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
We had some issues and concerns reported by more than a few server hosts that having the default right click be *both* a power attack and a wide swing was extremely undesireable. Since our original intention was to actually deprecate "Wide Swing" only to a handful of a few weapons designed around it, the behavior of this is now that power attack with no wide swing is the default for all weapons. Power attacks are still easier to aim than left clicks, but can only hit a single target except on certain weapons, deal bonus damage in exchange for stamina, and have a narrow 45 degree cone so as to enforce the need to right click at least relatively near your intended target. 
:cl:
- tweak: Wide Swing is no longer possible as a default on all weapons, the default is now Power Attack (10 stamina …
> Nerf Default Power Attack

- Content.Shared/CCVar/CCVars.cs
Apparently people thought we had removed the Arrivals Terminal from the game. This corrects it so that the default behavior is Arrivals to be enabled. 
:cl:
- fix: Arrivals has been re-enabled. I feel sorry for all the people who thought we had disabled it. This was a legacy toggle that was leftover from when we forked DeltaV
> Re-Enable Arrivals

- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Movement/Systems/SharedJetpackSystem.cs
Jetpacks can now be configured via CCVar in a server's TOML file to allow for certain behaviors that people have repeatedly asked for, and were denied by Wizden on the basis that, "Wizden doesn't want this on their servers". Well the request has reached my lap, and my response to this is, "I have the power to give that choice directly to individual servers."
Here you go. Enjoy.
This PR makes it so that jetpacks can be set in Server Configuration to 
- Be usable in ANY condition, even on grids with gravity
- Be usable in zero gravity, even on grids
- Or set the 2 new CVars to false, and it'll just work like it did before. 
:cl:
- add: Jetpacks now work in zero gravity.
- add: New CCVar "jetpack.enable_anywhere" allows server hosts to optionally make it so that jetpacks can be used …
> Jetpack Server Configuration

- Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
- Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
- Resources/Prototypes/Entities/Objects/Devices/Circuitboards/computer.yml
- Resources/Prototypes/Entities/Objects/Devices/hand_teleporter.yml
- Resources/Prototypes/Entities/Objects/Devices/holoprojectors.yml
- Resources/Prototypes/Entities/Objects/Devices/swapper.yml
- Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
- Resources/Prototypes/Entities/Objects/Tools/handheld_mass_scanner.yml
- Resources/Prototypes/Entities/Objects/Tools/jaws_of_life.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/CircuitBoards/production.yml
- Resources/Prototypes/Nyanotrasen/Recipes/Lathes/electronics.yml
- Resources/Prototypes/Research/experimental.yml
Ports the re update from delta and adds the Rcd and its ammo to the re machine along with jaws of life for more potential usage. Also moves the Re components to the Bottom of each yml item for items with the Re component placed in the middle likely from time and neglect, so it's consistent and less messy and better to understand. Also makes the cost of the naynoboards consistent with the other boards 
Expands the re machines catalog and adds it to alternate research tech as well as making it craft able via plasma glass, makes all Nanyo-boards the same cost as the ones from the hyper lathe updates such 
I think this would help those who wish to work on the re machine helps with future updates I need to flesh out too such as the other syndicate suits and items, adds a little more use and …
> Reverse Engineering Update Pr Port/ Board Cost Balance 

- Content.Server/Body/Components/BloodstreamComponent.cs
- Content.Server/Body/Systems/BloodstreamSystem.cs
- Content.Server/HeightAdjust/BloodstreamAdjustSystem.cs
- Content.Server/Traits/BloodDeficiencyComponent.cs
- Content.Server/Traits/BloodDeficiencySystem.cs
- Resources/Prototypes/Traits/disabilities.yml
With https://github.com/Simple-Station/Einstein-Engines/pull/858 (Make Height Sliders Affect Your Bloodstream Volume) being merged, it introduced variable blood volumes for differing sizes, whereas before everyone had the same blood volume (300u).
Because Blood Deficiency subtracted a flat amount from the bloodstream, it resulted in an unintended consequence where small characters died very quickly due to blood loss, while large characters could live for hours. This makes the blood loss amount of Blood Deficiency a **percentage** of the entity's max blood volume, which means that the time to become low blood is now the same regardless of blood volume.
:cl: Skubman
- fix: Blood Deficiency now makes you lose a consistent percentage of blood regardless of your blood volume, which is dictated …
> Make Blood Deficiency Bloodloss Consistent

- Resources/Prototypes/Wires/layouts.yml
Access wire is cool, this PR adds it back to airlocks
---
<p>
https://github.com/user-attachments/assets/622d01ac-01e5-4290-af26-6175fa3eca6c
</p>
</details>
---
:cl:
- add: Airlocks once again have access wires. Happy hacking!
> Add Access Wire to Airlocks

- Content.Client/RCD/RCDMenu.xaml.cs
- Content.Shared/Chat/SharedChatSystem.cs
Cherry-Picks https://github.com/space-wizards/space-station-14/pull/28077
For our downstreams so that they don't get sandbox violation errors when attempting to compile with the Latest Dotnet 8
>  Cherry-Pick #28077

- Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
- Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Changes the Loadouts to Lawyer's and Atmos very slightly, Lawyer's for the purpose of Simplicity and Atmos for preperation of a Backpack Unbloating.
---
[X] do da thing
---
<p>
</p>
</details>
---
:cl:
- tweak: Stuffed Lawyer's Pockets with Space Law guides!
- remove: Took away Atmos backpacks as Starting equipment.
> Slight Starting Gear Changes.

- Content.Client/ShortConstruction/UI/ShortConstructionMenuBUI.cs
The formula needed pi/2 instead of pi, but it got lost in the process of refactoring.
No cl no fun
> Hotfix Shortconstructionmenu Radius Becoming Infinite

- Resources/Prototypes/Traits/disabilities.yml
Uncloneable has rightfully obtained a reputation as **THE** powergamer trait, given the fact that it will extremely rarely come up in game, meaning that it essentially provides a ton of "Free" trait points. Due to its status as an extremely minor trait that's really just an opt-out of Cloning, it is not something that should give any free points at all.
:cl:
- tweak: The Uncloneable trait no longer provides extra trait points.
> Nerf Uncloneable

- Content.Shared/Movement/Pulling/Components/PullableComponent.cs
- Content.Shared/Movement/Pulling/Components/PullerComponent.cs
- Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
- Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Fixes pulling being obnoxiously unphysical. Entities now exert a specific amount of force defined as the product of their mass and the SpecificForce set in their PullerComponent. Doing a ctrl-right click now sets a target position where your entity begins to continuously push the pulled entity towards, instead of throwing it or pushing it once (however, it should still be possible to drag people and disposals and the like). Additionally, your entity will properly experience recoil from dragging someone around.
<p>
https://github.com/user-attachments/assets/2498ef8c-f743-4702-b73c-b2da0c16e9aa
</p>
</details>
:cl:
- add: Pulling has been reworked. Your character will now try to continuously push the pulled entity when you use the push keybind.
- …
> Physical Pulling

- Resources/Maps/core.yml
By request. A typical engineering team takes as much as 40 minutes to setup a Supermatter engine with no experience. Core is designed to **FORCE** players to setup a Singulo, which takes 15 minutes, therefore Core loses power in 20 minutes with its comically undersized and underpowered AME.
I increased the size of Core's AME so that engineers have more time to setup Supermatter. A lot more time actually. 
:cl:
- tweak: Core now has a 6-Core AME, which is supplied with two jars of fuel. This should give Engineers significantly more than 20 minutes of time to setup the Supermatter engine.
> Core Fullsize (Underfueled) AME

- Resources/Locale/en-US/tools/tool-qualities.ftl
- Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
- Resources/Prototypes/Tiles/plating.yml
- Resources/Prototypes/tool_qualities.yml
- Makes the fireaxe once again able to perform its primary function.
- There is now a way to emergency space a room without using an RCD.
- Viva Atmosia.
---
[x] Return Fireaxe Prying
---
<p>
</p>
</details>
---
- tweak: The fireaxe once again can pry subfloors
> Re-Adds Fireaxe Prying 

- Content.Server/Cloning/CloningSystem.Utility.cs
Clone Pod isn't the one that has the ability to say the message, the cloning console does. This fixes a bug where Uncloneable messages aren't being played.
:cl:
- fix: Cloning Consoles will now correctly state when a body has the Uncloneable trait.
> Fix Uncloneable Feedback Message

- Content.Server/Silicon/IPC/InternalEncryptionKeySpawner.cs
After doing an archaological exploration of the fucking SpawnAndDeleteAllEntities test fail, I eventually tracked down the bug to an issue where InternalEncryptionKeySpawner is randomly being handed a Null EntityUid which was Null Forgiven to make the compiler shut up. The actual EntityUid factually cannot be null during ordinary operation, except for the dumbass race condition provided by TestSpawnAndDeleteAllEntities.
> Fix SpawnAndDeleteAllEntities

- Content.Shared/StepTrigger/Components/StepTriggerComponent.cs
- Content.Shared/StepTrigger/Components/StepTriggerImmuneComponent.cs
- Content.Shared/StepTrigger/Prototypes/StepTriggerGroup.cs
- Content.Shared/StepTrigger/Prototypes/StepTriggerTypePrototype.cs
- Content.Shared/StepTrigger/Systems/StepTriggerSystem.cs
- Resources/Prototypes/Entities/Effects/chemistry_effects.yml
- Resources/Prototypes/Entities/Effects/puddle.yml
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
- Resources/Prototypes/Entities/Mobs/Player/ipc.yml
- Resources/Prototypes/Entities/Mobs/Species/diona.yml
- Resources/Prototypes/Entities/Mobs/Species/harpy.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
- Resources/Prototypes/Entities/Objects/Devices/mousetrap.yml
- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/Entities/Objects/Fun/dice.yml
- Resources/Prototypes/Entities/Objects/Materials/shards.yml
- Resources/Prototypes/Entities/Objects/Misc/land_mine.yml
- Resources/Prototypes/Entities/Objects/Misc/spider_web.yml
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
- Resources/Prototypes/Entities/Tiles/bananium.yml
- Resources/Prototypes/Entities/Tiles/chasm.yml
- Resources/Prototypes/Entities/Tiles/lava.yml
- Resources/Prototypes/Entities/Tiles/liquid_plasma.yml
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
- Resources/Prototypes/StepTrigger/StepTriggerTypes.yml
- Resources/Prototypes/Traits/skills.yml
This is a port of https://github.com/WWhiteDreamProject/wwdpublic/pull/53 from White Dream. This PR improves the StepTriggerImmune component by making it operate on a more granular Blacklist system, such that StepTriggerImmune entities can further clarify via prototypes which kinds of floor traps they are immune to, such as landmines/mousetraps, and not have blanket immunity to everything. Because it turns out things like Lava and Soap also were caught by the immunity, when really we just wanted Harpies & Felinids to not trigger landmines. 
<p>
> # Описание
> Необходимо настроить модификатор урона, чтобы IPC не получали урон от осколков стекла.
> 
> Иммунитет StepTriggerImmuneComponent доработан. Теперь имеются несколько типов (types): Lava - тип …
> [Port] StepTriggerGroup From WhiteDream

- Content.Client/Standing/LayingDownSystem.cs
- Content.Server/Flight/FlightSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Standing/LayingDownComponent.cs
- Content.Shared/Standing/StandingStateSystem.cs
- Resources/Locale/en-US/flight/flight_system.ftl
- Resources/Prototypes/Entities/Structures/Furniture/Tables/base_structuretables.yml
- Resources/Prototypes/Entities/Structures/Furniture/Tables/tables.yml
- Resources/Prototypes/Entities/Structures/plastic_flaps.yml
Adds a CVAR that when enabled, allows entities to crawl under tables/flaps by lowering their DrawDepth, which in turn protects them from being targeted for projectiles while crawling. 
Additionally tables and plastic flaps were given collision properties along with reduced damage thresholds, so guns can target & destroy them easily if your mouse is on top of them. 
---
<h1>Media</h1>
<p>
https://github.com/user-attachments/assets/77a04198-11cb-4895-bf2d-6f82b7f2bb5b
</p>
</details>
---
:cl:
- add: Adds an optional server variable which allows entities to crawl under tables.
- tweak: Tables and plastic flaps are less resistant to damage, and can now be targeted by guns by aiming on top of them.
> Allow Crawling Entities To Go Under Tables

- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
- Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_string.yml
- Resources/Prototypes/Entities/Objects/Fun/toys.yml
- Resources/Prototypes/Entities/Objects/Misc/broken_bottle.yml
- Resources/Prototypes/Entities/Objects/Misc/fire_extinguisher.yml
- Resources/Prototypes/Entities/Objects/Specific/Chapel/bibles.yml
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml
- Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
- Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
- Resources/Prototypes/Entities/Objects/Tools/jaws_of_life.yml
- Resources/Prototypes/Entities/Objects/Tools/toolbox.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/cult.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/home_run_bat.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sledgehammer.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
- Resources/Prototypes/Entities/Objects/Weapons/security.yml
There were some unintended changes bundled with the previous melee changes that didn't flow well together. I'm documenting everything here but would like to preface this by saying that, while a number of folks have had issues with the changes, there's been a surprisingly quiet amount of people who have just come forward and said that they've liked a number of the changes. 
Instead of just being satisfied with this, I would like to appease the folks who have had difficulties adjusting to the melee changes by improving the experience on a number of weapons and strange outlier cases that have cropped up. 
Below is the changelog any item not listed was either only changed by the Default Wide Swing change or had no change at all:
**Default Wide Swing**
Angle 45 -> 60
Stamina Cost 10 -> 2.5 …
> Melee Part 5: Less Exhaustion

- Content.Server/NPC/Components/NPCJukeComponent.cs
- Content.Server/NPC/HTN/PrimitiveTasks/Operators/Combat/JukeOperator.cs
- Content.Server/NPC/Systems/NPCJukeSystem.cs
This PR un-hardcodes the JukeSystem timer, such that individual NPC HTN Blackboards can directly state how often, and how far they wish to juke. The effect of this is that NPCs are no longer completely impossible to hit with left-clicks in melee combat, while also allowing for more "Elite" enemies that juke more aggressively and more often to be created. 
Additionally, by introducing an exit condition based on this new "Juke Cooldown", I have made the Juke Operator run a metric shitload of expensive calculations 5000 times less often. 
<p>
Melee enemy with the new default juke settings, 0.5 second juke duration, with 5 second juke Cooldown. The reagent slime will attempt to close to melee with its enemy, but will now only attempt to evade melee …
> Variable NPC Juke Aggression

- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
- Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/plate.yml
- Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
This PR is a follow up to https://github.com/Simple-Station/Einstein-Engines/pull/939
By increasing the number of items that are struck by bullets, or can be targeted by bullets. To add to the "Cinematic" experience of a gunfight, Bottles, Cups, and Plates of all kinds are automatically struck by bullets when fired over, and *probably* destroyed given that they only have 5 hit points. This also serves to aid in limiting the amount of things that can be hidden underneath when crawling under a table, since the station's bar counter will likely explode into a ton of glass and spilled booze when a gunfight gets near it. 
I also added Chairs to the "RequireProjectileTarget" feature, so that if you click on a chair, you'll shoot the chair and (probably) destroy it.
:cl:
- add: Bottles, Drink …
> More Objects Hit By Projectiles

- Content.Server/Abilities/Psionics/Abilities/HealOtherPowerSystem.cs
- Content.Shared/Actions/Events/PsionicHealOtherPowerActionEvent.cs
- Content.Shared/Psionics/Events.cs
- Resources/Prototypes/Actions/psionics.yml
Playtesting uncovered a few bugs with the HealOtherSystem, these are luckily pretty simple to fix. I also made a few of the functions in this system nullable as a performance optimization.
:cl:
- fix: Fixed a bug where Breath of Life and Healing Word would set living people to crit, which would knock them down.
- fix: Fixed a bug where Breath of Life could revive people who were rotten(It will still heal them and reduce the rot timer as intended, but will not revive unless said rot timer reduction brings them below the 10 minute threshold).
- add: The Do-After bar for Breath of Life and Healing Word is now hidden if glimmer is low enough. The threshold for which scales with your Dampening stat. More Dampening = stealthier casting.
> Fix HealingWord & Revivify Bugs

- Resources/Prototypes/Entities/Mobs/Player/ipc.yml
The people who made IPC apparently never setup a fixture for them, so they were using the BaseMob default fixture, which provides a mass of 5kg. I've swapped it out for a standard human fixture for the time being. 
:cl:
- fix: IPC now weigh 71kg by default instead of 5kg. Seriously who the fuck made the BeepBoops out of feathers!?!
> IPCs Don't Weigh 5kg

- Content.Server/Silicon/DeadStartupButtonSystem/DeadStartupButtonSystem.cs
- Content.Shared/Silicon/DeadStartupButton/SharedDeadStartupButtonSystem.cs
This fixes a bug with IPCs where the button to reboot them wasn't appearing.
<p>
</p>
</details>
:cl:
- fix: Fixed a bug where the button to reboot IPCs wasn't appearing.
> Fix IPC Reboot Button

- Content.Shared/Contests/ContestsSystem.cs
Apparently _mobThreshold.TryGetThresholdForState() fucking crashes if you hand it a mob that doesn't have a MobStateComponent, even though it optionally accepts no MobStateComponent at all as one of its inputs. Easy solution for this is to just pre-emptively TryComp for the MobStateComponent and then pass it in explicitly, but I also hate this because TryGetThresholdForState shouldn't be crashing if you hand it a mob without a MobStateComponent... I hate Resolve() so much for this behavior. 
:cl:
- fix: Fix a crash related to Luminous Entities.
> Fix HealthContest Crash

- Content.Server/Mood/MoodSystem.cs
This fixes a bug whereby smoking a cigarette spams your screen with the funny "I feel as if I have been standing my entire life and I just sat down" message. Now moodlet popups only play once when the moodlet is obtained, rather than being constantly spammed. I have tested this ingame to verify that it works correctly.
:cl:
- fix: Smoking cigarettes or drinking loto oil will no longer spam moodlet popup messages.
> Fix Moodlet Popup Spam

- Resources/Prototypes/Nyanotrasen/GameRules/events.yml
Webedit ops.
The changes to those events were balanced around the fact that all english downstreams had the glimmer changes early-merged, and were not reverted after the said glimmer changes were dropped.
Now:
- PsionicCatGotYourTongue occurs above 400 glimmer
- FreeProber occurs above 300
- GlimmerRevenantSpawn occurs above 450 and burns a substantial amount of glimmer, giving epistemics a chance to recover
- GlimmerMiteSpawn occurs above 250
- GlimmerRandomSentience occurs above 250
Not sure about NoosphericFry. I'm pretty sure probers no longer shoot lightnings, but I'm still opting in to keep it as it is, above 550 glimmer.
:cl:
- tweak: Noospheric events should once again occur on lower glimmer levels.
> Update Noospheric Events' Glimmer Ranges

- Content.Shared/Movement/Pulling/Components/PullerComponent.cs
- Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
- Fixes BeingActivelyPushed not resetting when pulling stops, resulting in entities who broke out of pulling being able to fall into trashcans and whatnot.
- Makes it so that the puller does not receive impulse while pushing under gravity (as it turns out, it is, in fact, annoying when you are small)
- Increases the default continuous push duration to 5 seconds to make pushing heavy objects easier.
<p>
https://github.com/user-attachments/assets/1808fb33-b9af-41b4-bec8-138eab088565
</p>
</details>
:cl:
- tweak: Pushing something no longer causes your character to move, but only if there is gravity holding you down.
- tweak: Pushing an object with Ctrl-RMB now pushes it continuously for up to 5 seconds instead of 2.
> Pulling Minor Fixes

- Resources/Prototypes/DeltaV/Entities/Mobs/Customization/Markings/felinid.yml
- Resources/Prototypes/DeltaV/Entities/Mobs/Customization/Markings/vulpkanin.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/reptilian.yml
- Resources/Prototypes/Species/human.yml
Drunk Solidus.
<p>
</p>
</details>
:cl:
- add: Humans can now have tail and ear markings.
> Kemonomimi Markings For Humans

- Content.Server/Abilities/Psionics/Abilities/HealOtherPowerSystem.cs
This fixes a bug with HealOtherPowerSystem where if the performer was forcibly moved during the cast, they would permanently become unable to cast it. 
:cl:
- fix: Fixed a bug with Healing Word and Breath of Life where if the caster was moved by another person mid-cast, they would permanently become unable to cast it again.
> Heal Other Bugfix 2

- Content.Server/InteractionVerbs/Actions/ChangeStandingStateAction.cs
- Content.Server/InteractionVerbs/InteractionVerbsSystem.cs
- Content.Shared/InteractionVerbs/InteractionVerbPrototype.cs
- Content.Shared/InteractionVerbs/Requirements/AssortedRequirements.cs
- Content.Shared/InteractionVerbs/SharedInteractionVerbsSystem.cs
- Updates the standing state requirement and the change standing state action to use the new laying down system (CurrentState instead of the old boolean Standing).
- Makes it so that you cannot use any interaction verbs on entities you cannot interact with (fixes it being possible to look at entities while being in crit)
- Changes the interaction popup clipping algorithm to include a predicate that ignores any entity that does not occlude light (fixes mobs, welding tanks, and some other non-opaque things preventing you from seeing interaction popups)
- Makes it so that the verb requirements are checked one additional time before the verb is interaction is actually executed. (this e.g. prevents the MakeSleepOther from working if the target stands up during the do-after)
:cl:
- fix: Fixed …
> Interaction Verb Minor Fixes

- Content.Server/Abilities/Psionics/Abilities/HealOtherPowerSystem.cs
- Content.Shared/Actions/Events/PsionicHealOtherPowerActionEvent.cs
- Content.Shared/Psionics/Events.cs
- Content.Shared/Psionics/SharedPsionicAbilitiesSystem.cs
This PR implements an initial first foray into adding MoodSystem interactions with Psionics. To put it simply. High mood raises Amplification and lowers Dampening. Low mood lowers Amplification and raises Dampening. 
Sanguine and Saturnine are basically psionic-related traits now. If you're willing to tolerate Saturnine's other debuffs, it will now by extension start making psionic abilities much safer to cast. 
:cl:
- add: Mood System now has some interactions with Psionics.
> Psionic Mood System Interactions

- Content.Server/Devour/DevourSystem.cs
This PR fixes the issue where any corpses devoured by a space dragon dissapear upon the Dragon being gibbed or butchered. 
Cherry-picked from Wizden #28709
---
n/a
---
<p>
</p>
</details>
---
- fix: Space dragons that get butchered or gibbed will now drop devoured corpses.
> Space Dragon Gib/Butchering Fixes

- Content.Client/Preferences/UI/HumanoidProfileEditor.xaml
This PR adds a vertical scroll bar to the Markings tab, which fixes an issue where markings with > 2 color selections could not be used. 
<p>
</p>
</details>
:cl:
- fix: Fixed the Markings menu by adding a scroll container to it. Markings with greater than 2 color selections can now be used.
> Fix Markings Menu

- Content.Server/ImmovableRod/ImmovableRodComponent.cs
- Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
- Resources/Prototypes/GameRules/events.yml
Part of the important gameplay loop for engineering is that they're supposed to be repairing the station when shit breaks it, so the ImmovableRod event is a key part of the game. However, it was currently commented out because people didn't like it gibbing characters with no reactability? Well news flash for people, there's a datafield for that. I can also directly control how much damage it deals.
So in exchange for uncommenting the Immovable Rod event, I've set the immovable rod spawned to be a little fairer for players, while still being able to cause damage to the station that will require repairs(And also expose players to vacuum. So that it puts them in danger.
:cl:
- add: Immovable Rod Event has returned
- add: Immovable Rod Event has been made more fair. It won't automatically gib …
> Uncomment Immovable Rod

- Resources/Prototypes/Loadouts/Categories/categories.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/captain.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/chiefEngineer.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/chiefMedicalOfficer.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/command.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/headOfPersonnel.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/headOfSecurity.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/quarterMaster.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/researchDirector.yml
Between me and a few other people, we have cumulatively spent numerous man hours combing through Loadouts trying to find why the Command loadouts were being dumped to Uncategorized. Finally I've had enough, so they're getting put back into the JobsCommand category. 
:cl:
- fix: Command Loadouts no longer appear in the Uncategorized tab.
> Fix Command Dumping To Uncategorized

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Lathes/devices.yml
- Resources/Prototypes/Recipes/Lathes/robotics.yml
- Resources/Prototypes/Research/experimental.yml
- Resources/Prototypes/Research/industrial.yml
Pretty easy PR, this just uncomments Grapple & Tether Guns, such that players can once again obtain them from Science.
:cl:
- add: Grapple & Tether Guns have been re-added.
> Uncomment Grapple And Tether Guns

- Content.Shared/Prototypes/LocalizedPrototype.cs
Adds a new Type for Prototypes to inherit instead of IPrototype with standard localization formats and lambda shortcuts to them.
---
> Add LocalizedPrototype Type

- Content.Server/Body/Components/BloodstreamComponent.cs
- Content.Server/Body/Events/NaturalBloodRegenerationAttemptEvent.cs
- Content.Server/Body/Systems/BloodstreamSystem.cs
- Content.Server/Traits/BloodDeficiencyComponent.cs
- Content.Server/Traits/BloodDeficiencySystem.cs
- Resources/Prototypes/Entities/Mobs/Species/arachne.yml
- Resources/Prototypes/Entities/Mobs/Species/diona.yml
- Resources/Prototypes/Entities/Mobs/Species/moth.yml
- Resources/Prototypes/Entities/Mobs/Species/slime.yml
- Resources/Prototypes/Entities/Mobs/base.yml
- Resources/Prototypes/Reagents/biological.yml
Makes natural blood regeneration use up some hunger and thirst, and halt completely when you are starving/dying of thirst.
This is necessary to fix two issues:
1. It being possible to feed off of your own blood, by repeatedly drawing your blood and injecting it back with a syringe. (I actually know a few people on floof who do that on a daily basis)
2. Hunger and thirst having no real impact on gameplay, besides giving you a mildly annoying depression overlay when low.
This PR also slightly refactors the blood deficiency trait so that it's no longer completely hardcoded in the bloodstream system.
<p>
https://github.com/user-attachments/assets/f8634de5-19bd-44a5-ada2-62f4504bf3d4
</p>
</details>
:cl:
- add: Blood regeneration now uses up hunger …
> Blood Regeneration Affects Hunger/Thirst

- Resources/Locale/en-US/language/languages.ftl
- Resources/Locale/en-US/species/species.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/CharacterItemGroups/languageGroups.yml
- Resources/Prototypes/Entities/Objects/Devices/translator_implants.yml
- Resources/Prototypes/Entities/Objects/Devices/translators.yml
- Resources/Prototypes/Entities/Objects/Misc/translator_implanters.yml
- Resources/Prototypes/Language/Species-Specific/reptilian.yml
- Resources/Prototypes/Traits/languages.yml
- Resources/ServerInfo/Guidebook/Mobs/Harpy.xml
- Resources/ServerInfo/Guidebook/Mobs/Reptilian.xml
This PR updates the Localizations relevant to the Reptilian species by significantly expanding upon them as Unathi, which is how they are typically referred to as in both /tg/station and Baystation12 derived codebases in SS13. I have added a new "Rare" language taken from Aurora, called Azaziba, which can only be taken by Unathi as a bonus language trait. 
Translators for this new language Azaziba are intentionally not obtainable ingame except as spawned by Admins. This is a "Rare" language, and shouldn't be accessible to players outside of Unathi obtaining the trait. 
The biggest change in this update however is a massive expansion upon the Unathi Guidebook entry, providing a significant volume of Lore, which is largely taken(with slight modifications) from …
> Unathi Lore Update

- Content.Server/Mood/MoodSystem.cs
- Content.Shared/CCVar/CCVars.cs
This PR adds a CVar that allows server hosts (such as N14 who need it) to optionally disable the Crit Threshold modification part of the MoodSystem. This is useful if a server has some other system that frequently messes with Thresholds, and that a server host wishes their system to not have to fight with Mood for it.
No changelog because this isn't playerfacing.
> MoodSystem Crit Threshold CVar

- Content.Server/GameTicking/GameTicker.Spawning.cs
- Content.Shared/CCVar/CCVars.cs
This PR adds a CVar to the Respawn System that optionally allows players to respawn as the same character.
This isn't player facing, so none.
> Respawn System CVar

- Resources/Locale/en-US/mood/mood.ftl
- Resources/Prototypes/Mood/drugs.yml
- Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
- Resources/Prototypes/Reagents/narcotics.yml
This PR adds two more drug related moodlets, neither of which are addictions. This would be Space Drugs and Ethanol. 
:cl:
- add: Added positive moodlets for drinking Space Drugs and Alcohol.
> More Drug Moodlets

- Resources/Prototypes/Mood/drugs.yml
This PR nerfs the Lotophagoi Oil addiction so that the bonus only lasts 10 minutes, and the withdrawl only 10 minutes as well. 
:cl:
- tweak: Nerfed Lotophagoi Moodlets so that both the positive and negative moodlets only last for 10 minutes. The total mood modification has been left untouched.
> Nerf Lotophagoi Oil Addiction

- Resources/Prototypes/Actions/psionics.yml
This PR removes the Supercrit mechanic from the standard Shadeskip. The Supercrit version will return as a WIZARD POWER. 
:cl:
- add: Shadeskip no longer creates Stationwide Shadow Kudzu when casting at high glimmer.
> Nerf Shadeskip

- Resources/Maps/Shuttles/pathfinder.yml
- Resources/Prototypes/Entities/Stations/base.yml
Part 3 of my evil plan to make salvage not suck: Give them a fancy goody, but with a twist. This PR adds the Pathfinder Expedition Vessel from Frontier, which replaces the Shittle as the default salvage shuttle to spawn on each map. I have my own funky reasoning for this. The primary one being, "The Pathfinder is powered by an AME. This means salvage are REQUIRED to periodically return to the station to get fuel. It is impossible for them to refuel themselves away from the station."
It also, notably, spawns with an Expedition Console. More on that in a follow-up PR where I rework expeditions to work "More like Frontier". 
<p>
</p>
</details>
:cl:
- add: The Salvage Shittle has been replaced with the Pathfinder Expedition Vessel from Frontier.
> Replace Shittle With Pathfinder

- Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
- Resources/Prototypes/Loadouts/Jobs/cargo.yml
I apparently accidentally removed the Crusher weapons from their spawner. This PR corrects that. Additionally in case this ever happens again, I've also decided to add the Crusher Dagger as a loadout option for salvage techs.
:cl:
- add: Salvage techs can now buy a Crusher Dagger in their loadout.
- fix: Re-Added the Crusher weapons to salvage spawners.
> Re-Add Crusher Weapons

- Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
- Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
Small fix for the Curadrobe not being accessible by the Librarian/Cataloguer.
:cl:
- fix: Librarian/Cataloguer now correctly has access to his own clothing vendor.
> Fix Librarian Access

- Resources/Prototypes/Traits/mental.yml
The two Psi-Potential traits are mutually exclusive(Due to adding the same component), but I forgot to add a condition that prevents you from taking both.
:cl:
- fix: Fixed High & Low Psi-Potential traits lacking a requirement that you don't have the opposite trait. The two were mutually exclusive, so taking both caused issues.
> Psionic Potential Trait Fixes

- Resources/Locale/en-US/loadouts/itemgroups.ftl
- Resources/Maps/arena.yml
- Resources/Maps/core.yml
- Resources/Maps/glacier.yml
- Resources/Maps/hive.yml
- Resources/Maps/saltern.yml
- Resources/Maps/shoukou.yml
- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
- Resources/Prototypes/CharacterItemGroups/securityGroups.yml
- Resources/Prototypes/DeltaV/Catalog/Fills/Items/Belts/belts.yml
- Resources/Prototypes/DeltaV/Objectives/stealTargetGroups.yml
- Resources/Prototypes/DeltaV/Objectives/traitor.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
- Resources/Prototypes/Loadouts/Jobs/Heads/headOfSecurity.yml
This PR adds a new "Head of Security's Antique Weapon Collection" item group to loadouts, which fully replaces the weapons that were originally map-specific entries for the Head of Security. Instead of whatever map giving the HoS a unique weapon in his office(And thus, overloading him with entirely too many guns), all of these weapons(And a few new ones) have been placed in their own special loadout category for the HoS. The HoS is entitled to a single free pick from any of these weapons. 
Now here's the fun tradeoff. All of them are steal objectives. Since it turns out the game will never give a steal objective to a traitor for an item that doesn't exist, I can actually make steal objectives for items obtainable only via Loadouts. Thus, all of the special weapons that the HoS can spawn …
> Head of Security Equipment

- Content.Server/Speech/EntitySystems/VocalSystem.cs
So you can actually muzzle a felinid to stop them from meowing. Or a vulp from barking. Or a human from screaming. You get the point.
This muzzle part of this PR is a bit hardcode-y, but it's because the muzzle simply adds a replacement accent to the entity instead of using its own system to block speech.
<p>
https://github.com/user-attachments/assets/0e5e4986-d2a0-471a-a119-579741265178
</p>
</details>
:cl:
- add: Sleeping and muzzled entities can no longer use vocal emotes (scream, meow, etc).
> Feat: Sleeping and Muzzle Block Vocal Emotes

- Content.Server/Shuttles/Systems/ArrivalsSystem.cs
- Content.Shared/CCVar/CCVars.cs
Fixes the arrivals shuttle choosing to correct docking port.
---
---
:cl:
- fix: Fixes the arrivals shuttle choosing to correct docking port.
> Fix Arrivals Shuttle

- Content.Server/Antag/AntagSelectionSystem.API.cs
- Content.Server/Antag/AntagSelectionSystem.cs
meow. 
Project compiles and starts. Is the bug gone? I hope so.
---
:cl:
- fix: Latejoin antag selection should respect player's antag preferences.
> Cherry Pick "Fix Latejoin Antag Preferences Not Being Respected"

- Content.Client/Input/ContentContexts.cs
- Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
- Content.Client/Standing/LayingDownSystem.cs
- Content.Server/Standing/LayingDownSystem.cs
- Content.Server/Traits/Assorted/LayingDownModifierSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Input/ContentKeyFunctions.cs
- Content.Shared/Standing/LayingDownComponent.cs
- Content.Shared/Standing/SharedLayingDownSystem.cs
- Content.Shared/Standing/StandingStateSystem.cs
- Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
- Resources/Locale/en-US/movement/laying.ftl
- Resources/keybinds.yml
This reverts most code changes done by https://github.com/Simple-Station/Einstein-Engines/pull/939 and re-implements them in a better way:
- Players can now toggle under-furniture crawling with a keybind (shift-R by default)
- Crawling that way is 50% slower for obvious balancing reasons
- The respective cvar for it is now true by default and prevents players from beginning the "crawl under furniture" thing
Also cleaned up a few methods I was seriously pissed off by. There is still a lot to clean up and fix, but I will leave it for a dedicated PR in the future.
Let me lie on the bed instead of under it!!!!!!!
<p>
https://github.com/user-attachments/assets/5f04c82a-b88b-4005-8052-a1a6f011bcc9
</p>
</details>
:cl:
- add: You can now toggle crawling …
> Feat: Togglable Under-Table Crawling

- Resources/Prototypes/Body/Organs/diona.yml
- Resources/Prototypes/Body/Organs/human.yml
- Resources/Prototypes/Body/Organs/slime.yml
This is a fucking stupid method of irreversible round removal. Gib someone and then eat their brain instantly. This PR makes brains not food, so that they can't be eaten instantly. 
:cl:
- tweak: Brains now can no longer be eaten.
> Make Brains Not Food

- Content.Server/Nyanotrasen/ReverseEngineering/ReverseEngineeringSystem.cs
Title
Upstream cherry pick fucked it, this fixes it.
---
<p>
</p>
</details>
---
:cl:
- fix: Reverse engineering machine UI works again.
> Fix Reverse Engineering UI

- Content.Client/Arachne/CocoonSystem.cs
- Content.Server/Arachne/ArachneSystem.cs
- Content.Shared/Arachne/CocoonComponent.cs
Cocoon size is now based on the humanoids height/width, or the sprite scale/size.
Also makes it so we aren't calling a command to change the scale.
---
<p>
https://github.com/user-attachments/assets/c26f6b34-39f7-437c-af86-715185855aff
https://github.com/user-attachments/assets/5a82affb-b8b7-4b79-aa39-37f5a7a2e35e
https://github.com/user-attachments/assets/42d7b41e-7333-4052-a1d1-698ce337706e
https://github.com/user-attachments/assets/210eab03-416c-4795-a384-9e502fe794a2
</p>
</details>
---
:cl:
- tweak: Cocoon sizing has been changed to reflect the size of the entity inside better.
> Cocoon Sizing Bettering

- Content.Server/Psionics/PsionicsSystem.cs
Apparently the psionic power rolls were not including a D100 roll in the baseline, so people were getting new psionic powers waaaaaay slower than was intended. Also, makes late-join psions use the glimmer calculation.
:cl:
- tweak: Psionic Rolls should now generate larger, random amounts of Potentia. This should make it a lot easier to obtain powers.
> Fix Psionic Power Rolling

- Content.Server/Forensics/Systems/ForensicsSystem.cs
Fixes cleaning forensics off of an object being impossible unless it has a scent. Explained in the latest (to date) comment to #715.
Also removes some unnecessarily duplicated code and inverts an if condition.
:cl:
- fix: Soap once again can be used to clean evidence off.
> Fix Forensics Cleaning

- Content.Client/UserInterface/Systems/Storage/Controls/StorageContainer.cs
- Content.Client/UserInterface/Systems/Storage/StorageUIController.cs
* fix orphaned storage grid pieces getting stuck to the cursor
* instead of denying it, update it smartly
This cherry-picks https://github.com/space-wizards/space-station-14/pull/27960
Which should fix our storage UI bugs.
> Cherry-Pick Wizden PR #27960

- Resources/Prototypes/Entities/Objects/Fun/pai.yml
This PR adds Languages to Personal Ai devices, allowing them to act as an interpreter for their owner. PAIs carry knowledge of all "Common" languages(Not including anything species specific, or Rare), plus the ability to understand(but not speak) Sign language.
:cl:
- add: Personal Ai devices now come loaded with knowledge of all "Common" languages, including Sign language, allowing them to interpret for their owner.
> Personal Ai Languages

- Content.Shared/Contests/ContestsSystem.Utilities.cs
- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
Default values for melee weapon contests were causing balance issues with Mobs that interacted with it, such as Carps being able to defeat the damage threshold of reinforced walls when the intention is that they shouldn't be able to. Also the logic on ContestDisadvantages was inverted, so this fixes that.
:cl:
- fix: Fixed issues with Contests System that allowed mobs such as Space Carps to smash through barriers that were not intended to be breakable by said mobs.
> Fix Melee Contests

- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/Reagents/medicine.yml
Closes #1080
This PR fixes Cryptobiolin so that it correctly adds a temporary "PsionicsDisabled" and "PsionicallyInsulated" status effect to the consumer. This effect lasts for 15 minutes, and is intended to be a highly effective means of providing protection from psionics, especially in the case of a Code White call.
:cl:
- fix: Fixed Cryptobiolin not providing temporary Psionic Insulation. It now provides protection from psionic abilities and events for 15 minutes.
> Fix Cryptobiolin

- Resources/Prototypes/Mood/drugs.yml
It takes 10 minutes to smoke a cigarette, and by the time the cigarette is done smoking, the nicotine addiction benefit wears off, meaning that the instant you stopped smoking, you would immediately suffer the need to smoke again. A better fix would be a more comprehensive refactor of addictions into its own special system, but we're currently in a state of "Rapid fire fixes" so this will do for now by bumping the benefit time up to 17 minutes. I've also done the same for Loto Enthrallment.
:cl:
- tweak: The mood benefit from Nicotine and Lotophagoi Oil has had its duration increased from 10 minutes to 17 minutes. You should no longer IMMEDIATELY feel a need to smoke as soon as the first cigarette is done.
> Fix Nicotine Addiction

- Resources/Locale/en-US/mood/mood.ftl
- Resources/Prototypes/Mood/genericNeeds.yml
Closes #1075
It was basically impossible to eat or drink without triggering the negative moodlet, and this feels entirely the wrong direction for players to be penalized for these actions. So I've simply inverted the penalty into a bonus. 
:cl:
- tweak: Completely satiating all hunger or thirst now provides a mood bonus instead of a penalty.
> Fix Too Much Food And Drink

- Resources/Prototypes/StatusEffects/security.yml
Need someone to test this change first.
Resolves #863 
Closes #149 
:cl:
- fix: Sechud should no longer stop working when someone in your PVS is set to "wanted".
> Cherry-Pick Space-Wizards/Space-Station-14#26001

- Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
Mechs have a more realistic weight now. :)
Fixes #666
:cl:
- add: Ripley now weighs a few tonnes. Good luck ever pulling it.
> Fix Mech Weight

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
All pistols were lacking the AmmoCounterComponent, needed to display their ammo in the UI like all the rest of the guns.
:cl:
- fix: Handguns(Such as Mk58, Viper, Cobra, etc.) now display their ammo counter in the UI.
> Pistol Ammo Counter

- Content.Shared/Traits/Assorted/Systems/SharedSingerSystem.cs
This fixes a bug reported by @Durk over discord, whereby if a Harpy's player disconnects, their midi player does not correctly close, causing the song to perpetually play.
:cl:
- fix: Fixed Harpies not ceasing with their singing when a player disconnects.
> Stop Harpy Singing On Disconnect

- Resources/Locale/en-US/loadouts/itemgroups.ftl
- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
- Resources/Prototypes/CharacterItemGroups/scienceGroups.yml
- Resources/Prototypes/Loadouts/Jobs/science.yml
- Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
Since you get your Backpack from your Loadout, Chaplain no longer gets his bible from his backpack. Actually NOBODY gets their Filled backpacks anymore. Every job that previously had a Filled backpack needs to have their shit added to Loadouts. This PR adds loadout categories for the Chaplain to get his Bible and Stamp back.
I spent literally 2 fucking hours trying to figure out why I can't add job specific categories to Science, and have nothing to show for it. So Uhh.. Fuck. I don't know why I can add job specific categories for service, but can't for Science. 
:cl:
- add: Chaplain's Bible and Stamp is now found in Loadouts.
> Chaplain Bible Loadouts

- Resources/Prototypes/DeltaV/Roles/Jobs/Fun/misc_startinggear.yml
Spiritual successor to an old unintended interaction in Delta V, where LP ops would spawn with uplinks. Except instead of having objectives its just an uplink with 20TC.
Why? Because it turns LP Ops from a simple nuisance into a potential threat that can send support on station for you, and makes taking a trip to the outpost to cash in some TC a very viable strategy. Salvage might be more inclined to raid them too, so thats gonna be fun.
:cl: Mocho
- add: Added an uplink with 20TC for all Listening Post Operatives
> Adds TC To Listening Post Operatives

- Content.Server/Execution/ExecutionSystem.cs
- Content.Shared/Hands/Components/HandHelpers.cs
- Content.Shared/Hands/EntitySystems/SharedHandsSystem.cs
- Content.Shared/Inventory/VirtualItem/SharedVirtualItemSystem.cs
- Content.Shared/Weapons/Ranged/Components/GunRequiresWieldComponent.cs
- Content.Shared/Weapons/Ranged/Events/ShotAttemptedEvent.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
- Content.Shared/Wieldable/WieldableSystem.cs
- Resources/Locale/en-US/virtual/virtual-item.ftl
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_wieldable.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Unhand me, fiend
Literally all of Wizden's "Wielding Quality Of Life" improvements.
Fixes #1074
Fixes #1073
Cherry-picks the following PRs: 
https://github.com/space-wizards/space-station-14/pull/26970
https://github.com/space-wizards/space-station-14/pull/27973
https://github.com/space-wizards/space-station-14/pull/27975
https://github.com/space-wizards/space-station-14/pull/28438
https://github.com/space-wizards/space-station-14/pull/27975
https://github.com/space-wizards/space-station-14/pull/28002
https://github.com/space-wizards/space-station-14/pull/28161
:cl:
- fix: Ported literally all of Wizden's Wielding Quality Of Life improvements.
> Various Wielding Fixes

- Content.Server/Chat/Systems/ChatSystem.cs
Fixes #1085 by making it so that being in a MapAtmosphere outright bypasses the check for "No talking in space!"
Don't merge this without testing it, and I haven't tested it yet.
:cl:
- add: Being in an Atmosphere(such as Planets like Glacier & Nukieworld) bypasses the limitation of "NO TALKING IN SPACE"
> Allow Talking Across Atmosphere

- Resources/Locale/en-US/psionics/psionic-powers.ftl
Fixes #1107
A pretty simple single-line fix that makes Breath of Life have its correct text popup.
:cl:
- fix: Breath of Life now correctly displays its esoteric text popup if the right conditions are met.
> Fix Breath Of Life Locale

- Resources/Maps/Shuttles/pathfinder.yml
Fixes #1099
:cl:
- fix: Removed latejoin spawners from the Salvage Pathfinder.
> Remove Pathfinder Latejoin Spawns

- Content.Server/Chat/Systems/ChatSystem.cs
This reverts commit 9ddd9679eccce166e8fe99fab01377c1bf950d58.
Introduced a game crashing bug.
> Revert "Allow Talking Across Atmosphere (#1089)"

- Resources/Maps/gaxstation.yml
Gax was missing a single LV cable, making it so that the Captain's office could be crowbarred into.
:cl:
- fix: Fixed the Captain's Office on Gax Station missing an LV cable that would power its doors.
> Fix Gax Missing LV Cable

- Content.Server/Shuttles/Systems/ArrivalsSystem.cs
I HAVE VERIFIED WITH INGAME TESTING THAT THIS WORKS.
Fixes #684 
:cl:
- fix: Fixed prisoner not spawning in the Prison if the Arrivals station is enabled.
> Fix Arrivals Not Respecting Force Spawn

- Resources/Maps/asterisk.yml
- Resources/Prototypes/Maps/asterisk.yml
This fixes Asterisk so that it works like the new Glacier, with a pseudoplanet instead of the currently non-functional planet biome. We can return to proper planet biomes whenever they're better supported. 
:cl:
- fix: Asterisk Station no longer spawns entombed in snow, and is now on top of an ice sheet.
> Fix Asterisk

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Custom specie name wouldn't properly update when a different race was selected, or when you changed profiles.
This fixes that.
Also makes it so the text field is automatically filled with the default name instead of an empty space.
(and makes the species check less bad 😺 )
Solves #1101
---
<p>
https://gyazo.com/63ba2d8a3456c19c70f25164ae42078d
</p>
</details>
---
:cl:
- fix: Custom specie name doesn't disappear in the editor anymore.
> Fix Custom Specie Name

- Resources/Locale/en-US/traits/misc.ftl
Fixes issue [reported in the discord.](https://discord.com/channels/1218698320155906090/1218698321053356060/1298139147428696095)
---
---
:cl:
- fix: Cybereyes examine message no longer reveals person's identity.
> [Fix] Cybereyes No Longer Reveal Identity.

- Resources/Prototypes/Traits/mental.yml
Resolves #1132.
:cl:
- fix: Fixed the "high amplification" trait lowering your amplification instead of increasing it.
> Fix High Amplification Trait Being the Wildest Scam in Human History

- Content.Client/CartridgeLoader/Cartridges/NewsReaderUiFragment.xaml.cs
- Content.Client/MassMedia/Ui/ArticleEditorPanel.xaml.cs
- Content.Client/Message/RichTextLabelExt.cs
- Content.Client/Tips/TippyUIController.cs
* Fix (hopefully)
* Fixed Spelling Mistake and minor Code Cleanup
* Revert "Fixed Spelling Mistake and minor Code Cleanup" due to Pull Request Guidelines
This reverts commit cee3e0226b349187bd8fd8b639e161fb877e8bdb.
Fixes https://github.com/SS14-Classic/deep-station-14/issues/87
> Fix Markup Tags in Station News (#30169)

- Resources/Maps/Shuttles/pirateradio.yml
The listening post being able to recall the shuttle was a little too much for people, but luckily it and a few other things are datafields. This PR removes the "Shuttle Recall" functionality for the communications console on the Listening Post, while also giving a custom broadcast announcement to the comms console so that it isn't just using the Nuclear Operative Announcement. This way the listening post isn't forcing people to call red alert by faking a nukie threat every round.
<p>
</p>
</details>
:cl:
- tweak: The Syndicate Listening Post now has a custom communications console, which no longer can recall Nanotrasen shuttles, and doesn't sign its messages as Nuclear Operatives.
> Remove LPO Shuttle Recalling

- Content.Client/RadialSelector/RadialSelectorMenuBUI.cs
Some of the icons consist of multiple layers so they were incorrectly displayed in radial selector menus. Now this system uses the same method PrototypeSelectorMenu uses.
---
:cl:
- fix: Layered icons are now properly displayed in radial menus.
> [Fix] Fixed Icons In Radial Menus

- Content.Server/Alert/Click/CheckHealth.cs
- Content.Shared/HealthExaminable/HealthExaminableSystem.cs
- Resources/Locale/en-US/health-examinable/health-examinable-comp.ftl
- Resources/Locale/en-US/health-examinable/health-examinable-silicon.ftl
- Resources/Prototypes/Alerts/alerts.yml
I don't understand why it hasn't been done before tbf.
https://github.com/user-attachments/assets/6ea2a3eb-80ce-4905-b546-7b8902308533
---
:cl:
- add: Clicking on health alert now will print message in chat, displaying your health state.
> [Feature] Clicking on Health Alerty Now Displays Health State

- Resources/Prototypes/Entities/Mobs/Player/familiars.yml
Default following distance for Psi Familiars was apparently >10 meters, making them have an extremely hard time following their Master in actual live servers. This PR tweaks them to have a maximum 3 meter following distance, the same as Rat Servants actually, so that they can more consistently follow their Master.
:cl:
- tweak: Changed the default "Following distance" of Psionic Familiars from 10 meters to 3 meters, so that they don't have an ungodly hard time keeping up with their Master.
> Tweak Familiars

- Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
- Resources/Prototypes/Catalog/Fills/Crates/materials.yml
This is but a small update in the campaign to, "Make people hate Salvage less". This time, by adding Gold, Silver, and Uranium to the list of raw materials that can be ordered by Logi. This serves as an extremely useful failsafe for in the event that Salvage is Unwilling/Dead/Incompetent/Shitters and failing to provide these raw materials to the station. Now Logi can throw away station money at getting these valuable materials.
This is also extremely useful, since by ordering Uranium, it's possible for Logi to provide spare fuel for Engineering on the newly updated Saltern map. https://github.com/Simple-Station/Einstein-Engines/pull/1170
Which no longer has an AME, and instead contains a dedicated Generator Room to serve as backup power. One crate of Uranium can provide Saltern with power …
> Add Uranium, Gold, And Silver To Cargo Menu

- Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
This broadly fixes a big with Familiars such that, since they inherit a player's factions, they will attack whoever you are factionally opposed to. Which means if you were a Syndicate Chaplain, you could just summon your bat for free damage. This PR flips this on its head by making it so that Syndicate Agents don't have the Syndicate faction, unless they buy a Syndicate ID. This also means that Traitors cannot enter the Listening Outpost, or Nukie Shuttle, without being fired upon by the turrets, unless they are WEARING an Agent ID. 
However this also adds a cool new interaction for CREW. If you are an NT Crewman, and you get your hands on either an Agent ID or a Syndicate PDA, now you can enter a Listening Post or Nukie Shuttle without being fired upon by the turrets.
:cl:
- add: …
> Syndicate Faction Comes From IFF Tags

- Content.Server/Communications/CommunicationsConsoleSystem.cs
CommunicationConsoleComponent.CanShuttle claims its supposed to prevent a given console from Calling OR Recalling the shuttle, but instead it only prevents CALLING the shuttle, but not RECALLING it. This fixes that.
:cl:
- fix: Communications Consoles that are marked as "Can't Recall The Shuttle" now can't recall the shuttle. Previously they were still able to recall it.
> Fix CanShuttle Not Preventing Recalls

- Resources/Prototypes/Entities/Mobs/Player/familiars.yml
Familiars were hilariously overpowered.
:cl:
- fix: Familiars can now be Dispelled.
- tweak: Nerfed Remilia to have 30 HP.
- tweak: Nerfed Base Familiar to have 50 HP.
> Nerf The Shit Out Of Familiars

- Content.Server/Power/EntitySystems/PowerNetSystem.cs
- Content.Server/Power/Pow3r/BatteryRampPegSolver.cs
- Content.Shared/CCVar/CCVars.cs
> Cherry Pick WizDen PR #28488

- Content.Server/Traits/TraitSystem.Functions.cs
Maintainer suggested changes broke the AddTrait and ReplaceTrait functionality of the Version 2 Trait Functions. This restores their functionality.
:cl:
- fix: Fixed AddTrait and ReplaceTrait functions giving players an unmodified, completely default component.
> Fix AddTrait And ReplaceTrait Functions

- shell.nix
Added missing environment variable for nix-shell. I don't like everytime write `export DOTNET_ROOT="/path/to/folder"`, so it should be done by post script in `shell.nix`
> Add Missing `DOTNET_ROOT` Environment Variable For Nix Devs

- Content.Server/Chat/Systems/ChatSystem.cs
- Content.Server/Polymorph/Systems/PolymorphSystem.cs
- Content.Shared/Polymorph/PolymorphPrototype.cs
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/glimmer_creatures.yml
- Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/Entities/Objects/Specific/Robotics/mmi.yml
- Resources/Prototypes/Language/animal.yml
- Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Mail/base_mail.yml
1. Adds languages to... penguins, cockroaches, snakes, mmis, pdas, mail packages. Positronic brains now only speak/understand the borg language.
2. Adds an explicitly defined universal language to revenants and wisps
3. Makes polymorphs copy over a list of components defined in the polymorph proto, thus copying languages and grammar of the original entity to its polymorphed version.
<p>
</p>
</details>
:cl:
- tweak: Added languages to certain entities that lacked them, including MMIs and positronic brains.
- add: Polymorphing into another entity now preserves your languages and grammar.
> Some Language Fixes

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
This PR is intended to fix the issue of pengiuns dying to cold damage on planetary maps like Glacier. It adds a atmosTemperatureTransferEfficiency modifier to the pengiun mod YAML.
Reported on Grimbly, fix from [Floof](https://github.com/Fansana/floofstation1/pull/302/files)
---
n/a
---
<p>
n/a
</p>
</details>
---
- fix: Fixed pengiun cold resistance
> Give Penguins Cold Resistance

- Content.Server/StationEvents/Events/PirateRadioSpawnRule.cs
I hate that I have to check if the map even exists at all. How the hell is there a station even existing in the first place if the default loaded map is NULLSPACE?! GetSpawnableStations should have returned a list containing zero stations if that was the case, which would then exit out.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
I hate these stupid tests.
No CL because this isn't player facing.
> Pirate Radio Heisentest Fix

- Content.Shared/Damage/Systems/StaminaSystem.cs
Goal of this PR is to fix the stamina system, as was caused by #1220.
---
:cl:
- fix: Fixed stamina system
> Hotfix Stamina System

- Content.Server/TimeCycle/TimeCycleSystem.cs
- Content.Server/Toolshed/Commands/VisualizeCommand.cs
- Content.Shared/TimeCycle/TimeCycleComponent.cs
- Content.Shared/TimeCycle/TimeCyclePalettePrototype.cs
- Resources/Prototypes/time_cycle_palletes.yml
Add real world Day/Night cycle changing, with Ambient color interpolation and some configurable features for mappers. 
High inspired by [Nuclear-14](https://github.com/Vault-Overseers/nuclear-14.git) and [Crystall Punk 14](https://github.com/crystallpunk-14/)
TimeCycle use 24h day calculation, instead coefficient, like in N14. 
---
[ ] - Add more examples/prepared map palettes for Day/Night ambient.
[ ] - (Optional) Move all palette description into List of variables, instead calling `IPrototypeManager` every minute passing.
---
https://github.com/user-attachments/assets/cc5d1b8c-bd25-4042-8cee-e2edfa0d9acc
---
:cl:
- add: Added Day/Night time cycle for admins and mapers.
> Day/Night Time Cycle For Maps

- Content.Shared/Traits/Assorted/Components/SelfAwareComponent.cs
Quick fix to prevent the Self-Aware trait from crashing the client of a player when examining their character's health.
[`HealthExaminableSystem.CreateMarkupSelfAware`](https://github.com/Simple-Station/Einstein-Engines/blob/6945e3027bc14eac1de0099d30f8f35b19a3034e/Content.Shared/HealthExaminable/HealthExaminableSystem.cs#L119) attempts to access the `AnalyzableTypes` and `DetectableGroups` data fields from [`SelfAwareComponent`](https://github.com/Simple-Station/Einstein-Engines/blob/6945e3027bc14eac1de0099d30f8f35b19a3034e/Content.Shared/Traits/Assorted/Components/SelfAwareComponent.cs), but since they are only initialized in the server and `null` in the client, the client crashes. I believe this could be related to the recent trait overhauls, but not sure. I just fixed it by adding …
> Fix Self-Aware Crashing Client

- Content.Shared/Medical/Surgery/SharedSurgerySystem.Steps.cs
- Resources/Locale/en-US/surgery/surgery-popup.ftl
Adds popups for surgery steps in Shitmed that every player within PVS range can see. This allows other players to see if the correct procedure is being performed. This PR also includes locale text for the new procedures and steps in #1240.
**Remove Brain / Insert Brain**
https://github.com/user-attachments/assets/ac20afa1-df74-48ab-b1d5-2e9a273dfba2
<details><summary>See more</summary>
**Amputate Right Arm**
https://github.com/user-attachments/assets/17f78683-6d3b-44ee-aea3-bb6987844fdc
**Attach Right Arm**
https://github.com/user-attachments/assets/584d4da2-d8b0-4c82-a323-26636e7fa4b8
</details>
:cl: Skubman
- add: Surgery step descriptions (like making an incision, removing/attaching limbs and organs) are now shown as popups to everyone in range upon the start of the step. This makes it …
> Shitmed Surgery Popups

- Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
- Resources/Locale/en-US/damage/damage-examine.ftl
- Resources/Locale/en-US/weapons/melee/melee.ftl
QoL updates to improve the stamina management experience with power attacks:
- The stamina cost of an object's power attack can be revealed by examining its damage values. 
- Power attacks can't be done if your stamina is too low, so you can't accidentally stamcrit yourself with power attacks anymore.
- **Nerf:** Power attacks now cost stamina even without hitting anything.
- Prevent power attacks from showing a blue visual effect on the character who attacked due to stamina damage.
**Gameplay**
https://github.com/user-attachments/assets/f5031ce3-8303-475a-9c37-d8004ed55dbc
**Damage Examine**
:cl: Skubman
- add: The stamina cost of an object's power attack can now be revealed by examining its damage values. 
- tweak: Power attacks can't be done if your stamina is too low, so you can't …
> Power Attack Stamina Update

- Content.Server/LifeDrainer/LifeDrainerSystem.cs
Small oversight that Glimmer Wisps are generally described as drinking their victim's soul and obliterating their entire personhood. Which is fundamentally just mindbreaking said person. So this PR makes it so that Glimmer Wisps killing a psion also inflicts the Mindbroken condition on them. 
:cl:
- add: Glimmer Wisps now completely obliterate their victim's Personhood, inflicting the Mindbroken condition on them.
> Glimmer Wisps Mindbreak Their Victims

- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
This fixes some stupid math. Power attacks are now correctly slower than left clicks. Previously they were faster.
:cl:
- fix: Power Attacks now correctly apply a penalty on swing speed, and are no longer faster than left clicking.
> Fix Power Attacks Being Faster Than Left Clicks

- Content.Server/Anomaly/AnomalySystem.Scanner.cs
- Resources/Locale/en-US/anomaly/anomaly.ftl
Makes it so that using one anomaly scanner on another transfers the anomaly data onto the used scanner.
<p>
</p>
</details>
:cl:
- add: You can now touch one anomaly scanner with another to copy the anomaly scan data from it.
> Feat: Anomaly Scanner Data Copying

- Content.Shared/Body/Systems/SharedBodySystem.Targeting.cs
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
Oops. Some files refer to the non-existent **Pierce** damage type when the proper name is **Piercing**.
:cl: Skubman
- fix: Piercing damage can now dismember body parts, just like Blunt and Slash damage.
> Rename "Pierce" Typo to "Piercing"

- Content.Server/Nyanotrasen/Abilities/Oni/OniSystem.cs
Examining an item's damage values as an Oni now calculates your bonus damage, and it also works with all of the Oni combat traits.
`OniSystem`, instead of adding melee damage through `MeleeHitEvent`, now adds damage through `GetMeleeDamageEvent`, the same event that examining melee weapon damage raises through `GetDamage`. 
**Normal damage values**
**Oni damage values**
:cl: Skubman
- tweak: As an Oni, examining the damage values of weapons now takes into account the melee damage bonus from your species or trait.
> [QoL] Show Oni Damage Bonus In Damage Examine

- Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
There's a small error on the admin verb for blood cultists which made the verb only work on self. This fixes it.
> Fixes Make Cultist Admin Verb to Act on Target Not Self

- Content.Client/Storage/StorageBoundUserInterface.cs
Fixes the bug with opening storage containers while there's already one opened.
---
:cl:
- fix: Fixed the bug with opening storage containers while there's already one open.
> Fix Bug with Opening Storage Containers

- Resources/Prototypes/Stacks/medical_stacks.yml
- Fixed a bug where applicable medication stacks would revert back to 10 after 1 use.
- Did you know maxstacks were stored in a separate YML? Me neither, until now.
**Changelog**
:cl:
- fix: Fixed a bug where applicable medication stacks would revert back to 10 after 1 use from full.
> Fix Applicable Medication Stack Bug

- Content.Server/Chat/Systems/ChatSystem.cs
- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Resources/Locale/en-US/chat/managers/chat-manager.ftl
- Resources/Locale/en-US/headset/headset-component.ftl
Re-enables language font and colors showing up in chat messages. The language font/colors were bugged after adding language names in chat (https://github.com/Simple-Station/Einstein-Engines/pull/1165)
I also overhauled the format for chat messages to be more aesthetically pleasing, and made sure chat bubbles use the language color/font.
**Nekomimetic**
**Bubblish**
**Tau-Ceti Basic (Default Language)**
**Rootspeak**
:cl: Skubman
- fix: Language colors and fonts will show up in text messages again, both on in-person messages and on the radio.
- tweak: The text on chat bubbles now uses the color and font of the language being spoken.
- tweak: The language prefix before the name on chat messages now uses the language's color.
> Re-Enable Language Color and Font

- Content.Client/Atmos/Consoles/AtmosAlertsComputerWindow.xaml.cs
- Content.Client/Pinpointer/NavMapSystem.Regions.cs
- Content.Client/Pinpointer/NavMapSystem.cs
- Content.Client/Pinpointer/UI/NavMapControl.cs
- Content.Server/Atmos/Consoles/AtmosAlertsComputerSystem.cs
- Content.Shared/Pinpointer/NavMapComponent.cs
- Content.Shared/Pinpointer/SharedNavMapSystem.cs
- Resources/Locale/en-US/atmos/atmos-alerts-console.ftl
- Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Nyanotrasen/Entities/Markers/Spawners/Random/devices.yml
- Resources/Prototypes/Recipes/Lathes/electronics.yml
- Resources/Prototypes/Research/industrial.yml
This PR upgrades the capabilities of the Atmospheric Alerts Computer by displaying colored zones on the station map corresponding to air alarm status. 
Additionally, it makes the Atmospheric Alerts Computer board obtainable in a Circuit Imprinter once Epi has researched "Atmospheric Technologies".
This is a port of [Wizden #31910](https://github.com/space-wizards/space-station-14/pull/31910) by @chromiumboy 
---
n/a
---
<p>
</p>
</details>
---
- tweak: Atmospheric Alerts Computer now displays colored zones corresponding to air alarm status on the station map
- fix: Atmospheric Alerts Computer board is printable in a circuit imprinter
> Atmospheric Alerts Computer Upgrades

- Content.Shared/Materials/SharedMaterialStorageSystem.cs
This change was actually suggested by April, I'm not the author.
It fixes Pacman generators and god knows what else.
Prior to the change you could insert steel in it, or just the wrong kind of fuel.
Since you could only load the wrong kind of fuel the generators were not working at all.
Description.
---
---
<p>
Ejecting steel from a pacman gen
Them working after the fix.
</p>
</details>
---
> Inverts the Check for Material Whitelist in CanChangeMaterialAmount

- Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
- Resources/Prototypes/Catalog/Fills/Crates/engines.yml
- Resources/Prototypes/Entities/Objects/Devices/flatpack.yml
This PR adds the option of constructing a Thermoelectric Generator (TEG) from scratch, by adding flatpacks for the TEG Center and TEG Circulator, as well as a crate that can be ordered from logistics that contains the flatpacks. 
The aim is to give engineering crews the ability to add a TEG to stations that might lack one, as a "fun" engineering project that can be pursued on shift. This capability already exists for the Singularity Engine and Tesla Engines.
The cost of the TEG Construction Kit is set at 8000 spesos, but this can be changed for balance reasons.
Note: Kit may contain small parts not suitable for children under 3 years old. Some assembly required.
---
n/a
---
<p>
</p>
</details>
---
- add: TEG components now be …
> Build Your Own TEG!

- Resources/Prototypes/Objectives/objectiveGroups.yml
- Resources/Prototypes/Objectives/traitor.yml
Title
---
:cl:
- add: Reintroduced 3 traitors objectives: steal Ian's meat, Die Glorious Death and Hijack Evacuation Shuttle
> [Feat] Bring Back Die Glorious Death, Hijack And Ian's Meat Traitor Objectives

- Content.Server/Antag/AntagSelectionSystem.cs
Cherry picks "Fix station events schedulers, antag selection and possibly other systems acting weird in a rare scenario."
This is being PRed mostly as a fix to an issue which caused the round to fail to start due to an error in antag selection, which did happen in Thief antags and may also happen with Bloodcult gamemode.
Double posting from discord:
> It fixed issues caused with antag selection at roundstart which affected roundstart Thief selection.
> 
> Since cultists are also selected exactly at roundstart - unlike traitors for instance, I think this might help with cultists too.
> 
> I tried to force start bloodcult gamemode in the past and it failed to start but I since I had tracebacks disabled trying to improve performance I'm not sure this was the cause.
> 
Credits to April for …
> Replace Direct Uses of GameTicker Dictionary with `TryGetValue` (#33222)

- Resources/Textures/Shaders/flashed_effect.swsl
Original commit changeset: c3dcc7a12464
Dark flash is cowardly. Billions must be flashbanged irl
:cl:
- tweak: Flashes are bright again!
> Back Out "Flash Now Flashes Black Instead of White. (#14642)"

- .envrc
- flake.lock
- flake.nix
- shell.nix
Just some nix dev env maintenance don't mind me
> Nix Housekeeping

- Resources/Prototypes/Entities/Mobs/base.yml
Finally fixed it.
Interact verbs weren't appearing because this is required in BaseMob.
> Fix Interact Verb

- Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
Fix a bug in `MechGrabberSystem` causing the hydraulic clamps in Ripley to drop items far away.
---
<p>
https://github.com/user-attachments/assets/d2c8e951-e391-42d7-b45d-78a275dc8bf2
</p>
</details>
---
:cl:
- fix: Hydraulic clamps now drop entities correctly
> Fix Ripley Hydraulic Clamp

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/mental.yml
This PR adds a few of the "Mentalic" category of psionic abilities to the Traits System, allowing them to be purchased by any character that is also a Latent Psychic. These powers are:
- Dispel
- Metapsionic Pulse
- Xenoglossy (Also requires Natural Telepath)
- Psychognomy (Also requires Natural Telepath)
These are all quite expensive, so to help address the "Expensive trait proliferation", I've increased the points granted by the Blindness trait to 10. Have fun being a blind wizard. From this point on, we're going to need to start adding more "High point value" negative traits.
:cl:
- add: Dispel, Metapsionic Pulse, Xenoglossy, and Psychognomy can all be purchased during character creation using trait points.
- tweak: Blindness now grants 10 trait points instead of 6.
> Trait Purchasable Mentalic Powers

- Resources/Prototypes/Entities/Mobs/Customization/Markings/pointy_ears.yml
- Resources/Prototypes/Species/arachne.yml
- Resources/Prototypes/Species/harpy.yml
Like half the art references I have for Harpies have them with elf-like pointed ears, another half have them with their feather tufts. We have pointy ears markings, so this PR makes it so that Harpies can have them. Actually it also gives them to Arachne, for similar reasons(It's an oddly common thing on Arachne/Lamia art depictions). 
:cl:
- add: Added a variety of Pointy Ears markings for Harpy and Arachne characters.
> Pointy Ears For Harpies And Arachne

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/physical.yml
This PR adds two additional "High Value" physical negative traits, to help address a growing need for more high point value negatives, since there is also a very large number of high point positive traits. These two traits are fairly simple, the first is Redshirt, which decreases your Dead threshold by 100, and Brittle Bone Disease , which reduces your Crit threshold by 50. Taking both on an ordinary human would give +18 trait points to work with, but would in turn give a healthbar of only 50/100, compared with the standard healthbar of 100/200. 
:cl:
- add: Added Redshirt and Brittle Bone Disease traits. These give extremely large negative modifiers to your healthbar, but also grant a large amount of trait points to work with.
> Redshirt And Brittle Bone Traits

- Resources/ConfigPresets/EinsteinEngines/default.toml
this PR extends the list of default advertiser hubs to include every existing hub except for SSMV(Which is mutually exclusive with the others). If there are more hubs I have missed, please let me know. This will allow our servers to appear on as many hubs as possible.
> Example Hub Ad List

- Content.Server/Traits/TraitSystem.cs
- Content.Shared/CCVar/CCVars.cs
It turns out that there was no system in place for serverside fact checking of whether or not people have a legal traits list. Last night a bug was reported whereby a player used Cheat Engine to give himself every trait in the game, bypassing the points system entirely. It's not actually possible to reduce a trait selection down to a legal list without creating interesting race conditions, which limits my options on how to deal with it.
So I made it a vote on the Einstein Engines discord, and the vote was unanimous. PUNISH THE CHEATERS. 
<p>
https://www.youtube.com/watch?v=X2QMN0a_TrA
</p>
</details>
:cl:
- add: Implemented Anti-cheat for Traits. Attempting to join a round with an illegal traits list will result in hilarious consequences.
> Traits System Anticheat

- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
Prisoner is consistently the most problematic role in this entire game, being seen as "The Self Antagging Role", which produces endless amounts of administrative burden. This is especially a problem with lowpop servers, or servers that are understaffed with admins. Players just join as Prisoner, *immediately* break out of the permabrig, and then go on a self antagging spree. The solution to this was staring us in the face the whole time. Just give them the same Pacified component that the Thief antag has. Now it's impossible for them to smash the permabrig windows, someone has to intentionally let them out, and even if they do, they will be hard pressed to selfantag when they can't turn on harm intent.
:cl:
- add: Prisoners now spawn with a Pacifier Implant.
> Make Prisoner Not Shitter Role

- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
- Content.Shared/Movement/Systems/SharedMoverController.Input.cs
- Content.Shared/Movement/Systems/SharedMoverController.cs
This PR adds a simple server configuration option for enabling basic "Soft-Crit", and not much else because oh my god this system is horribly complicated. When enabled, characters can crawl around very slowly while in crit, and really not much else. This more or less mirrors how crit affects character movement in SS13, where you can at least crawl to relative safety while bleeding to death. 
:cl:
- add: Added server config options for basic "Soft-Crit". When enabled, characters who are critically injured can still slowly crawl, but are otherwise still helpless and dying.
> Basic Soft-Crit Implementation

- Resources/Prototypes/Maps/Pools/default.yml
There are a _lot_ of issues surrounding Europa, which include, but the big two are:
- How many complaints I'm receiving about it in general.
- Engineering issues, including a lack of an alternative beyond an SM (supposedly)
- Lacking a cryosleep area.
- Distro air and waste are connected together.
- More here https://github.com/Simple-Station/Einstein-Engines/issues/1379#issuecomment-2564303908
Is there a way we can add people to review maps specifically? I'm not a mapper, but the last few maps that have gotten through have been _bad_ at the start.
---
:cl:
- remove: *Temporarily* removed Europa from map pool, pending some refurbishing.
> Remove Europa From Map Pool

- Resources/Maps/Misc/terminal.yml
Arrivals spawns have been limited to only the massive cryogenics bay, and impassable barriers have been added that block access to the deeper parts of Terminal. I've also modified the admeme items that were in displays so that they are now fake items that can't actually be used by players even if they SOMEHOW smash their way in and defeat the turrets. I have photo evidence of people doing this. 
Just in case, I also made arrivals a ProtectedGrid.
:cl:
- tweak: Tweaked arrivals to reduce the playable area, and some concessions have been made to prevent access to admeme items that were on display. These changes are pending a later update where we port Arrivals Job Spawns.
> Arrivals Tweaks

- Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/special.yml
- Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Guns/Projectiles/shotgun.yml
Fixes #1374
I'm not sure exactly when this changed, but you now have to specify which solution you want to inject.
Also inject on hit defaults to ignoring clothing, so I removed the redundant set.
---
:cl:
- fix: Fixed mindbreaker and soulbreaker cartridges not injecting their solutions.
> Fix Mindbreaker and Soulbreaker Rounds Not Injecting Their Solutions.

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
The slider would jump around to fix the constraints because a division symbol was mistakenly replaced with a multiplication symbol, this fixes that.
---
<p>
</p>
</details>
---
:cl:
- fix: The width slider in the profile editor view now moves correctly regarding the height slider.
> Fix the Width Slider Not Translating Smoothly

- Content.Client/UserInterface/Controls/RadialContainer.cs
Cherry picks https://github.com/space-wizards/space-station-14/pull/29678
Needed for emotes to not be packed tightly together, 
also need this for a future PR where I will be fixing emotes in general ◕‿◕)
---
<p>
</p>
</details>
---
:cl:
- fix: Fixed radial menus overlapping where there's many icons.
> Cherry Pick "Dynamic Radial Menus (#29678)"

- Content.Server/Psionics/PsionicsCommands.cs
- Resources/Locale/en-US/psionics/psionic-commands.ftl
This PR adds three new admin commands that make use of the new functionality available to Psionics V3. These commands are:
- addrandompsionicpower
This takes a Uid and throws it at the random psi power generation code. Which gives it a random psi power that is available in its list of rollable powers.
- removepsionicpower
This takes a Uid and a PsionicPower prototype ID, and attempts to remove that power from said entity. It does nothing if the entity doesn't have that power.
- removeallpsionicpowers
As above, but instead of needing to declare a power prototype, it just removes ALL powers that the entity has, if any.
:cl:
- add: Added new admin commands AddRandomPsionicPower, RemovePsionicPower, and RemoveAllPsionicPowers.
> More Psionic Admin Commands

- Content.Server/Cocoon/CocoonerSystem.cs
I watched someone cocoon themselves while trying to cocoon a mouse on Goob MRP. It was pretty funny but you have to wait for someone to realize why you are making muffled sounds on the radio, then for them to come find you, and if you're not in your department it can take a while, its nearly round removal on low pop as well.
---
:cl:
- tweak: You can no longer cocoon yourself as a spider.
> No Cocooning Yourself!

- Resources/Locale/en-US/guidebook/guides.ftl
Does what it says on the tin
Solves #664 
---
<p>
</p>
</details>
---
:cl:
- fix: Supermatter's guide has a name now
> Add Missing Localization for Supermatter Guide Entry

- Resources/Prototypes/Loadouts/Generic/items.yml
Adds the white cane to loadouts, not restricted to people with the blind trait
Solves #1367
---
<p>
</p>
</details>
---
:cl:
- add: White cane added to loadout options
> Add White Cane to Loadouts

- Resources/Locale/en-US/traits/traits.ftl
A misspelled localization string caused this, someone should probably make an integration test to ensure all traits have names and descriptions
---
<p>
</p>
</details>
---
:cl:
- fix: The 'kα Deficiency' trait has a description now
> Fix Kα Deficiency Not Having a Description

- Content.Client/Clothing/ClientClothingSystem.cs
- Content.Server/Clothing/ClothingSystem.cs
- Content.Server/Traits/TraitSystem.Functions.cs
- Content.Shared/Clothing/Components/ClothingComponent.cs
- Content.Shared/Clothing/EntitySystems/ClothingSystem.cs
This PR was originally going to be called "Psionic Refactor V3 Part 2, Items Of Power", but I began getting shakes and started vomiting when I saw the list of Components that make items do things when equipped, and I had a conniption about how much code there is constantly being repeated. So instead of this PR adding Items Of Power, I added a universal modular generic system for making clothing items do things when equipped and unequipped. Which hooks into the library of TraitFunctions that we've previously created. I also added a few "Inverse" versions of trait functions that can be used by these new clothing functions.
> Generic Clothing Equip Functions

- Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Title!!!
Solves https://github.com/SS14-Classic/deep-station-14/issues/91
---
:cl:
- fix: Fix Shiva's name and description displaying improperly in ghost roles
> Fix Shiva Ghost Role Missing Localization

- Content.Server/Traits/TraitSystem.Functions.cs
- Content.Shared/Mobs/Components/MobStateComponent.cs
- Content.Shared/Mobs/Components/MobThresholdsComponent.cs
- Content.Shared/Mobs/MobState.cs
- Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
- Content.Shared/Mobs/Systems/MobStateSystem.cs
This PR does *some* refactoring of MobState in preparation for adding a more in-depth SoftCritical system, mostly adding code support for the new threshold existing in the first place. Additionally, the MobStateComponent now also includes several DataFields that allow more precise fine tuning of what all mobs are allowed to do in each state, as opposed to hardcoding a majority of these interactions.
The actual SoftCritical state isn't currently used by anything, and so is a largely vestigial feature. It would have to be added individually to mobs, such as the BaseMobSpeciesOrganic when the time comes to actually add this feature.
:cl:
- add: Lots of refactoring of the Mob State Systerm in preparation for implementing a much more detailed Soft Critical state.
> Some MobState Refactoring

- Content.Client/Options/UI/Tabs/MiscTab.xaml
- Content.Client/Options/UI/Tabs/MiscTab.xaml.cs
- Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
- Content.Server/Chat/Managers/ChatManager.cs
- Content.Server/Chat/Managers/IChatManager.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Chat/MsgChatMessage.cs
- Resources/Locale/en-US/chat/chatstack.ftl
- Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
Chatstack.
Can be changed/disabled in settings, and the chat automatically updates to reflect the change.
Does not interfere with filters, etc.
Also updated ChatMessage class and serverside IChatManager with a new IgnoreChatStack bool option, default false.
Currently is limited to looking up to 3 messages behind, only because I feel off adding a textbox to the options.
---
---
<p>
[ee.webm](https://github.com/user-attachments/assets/bf1c92f0-b52a-47a0-b142-70b1ee5003cc)
</p>
</details>
---
:cl:
- add: Chatstack. Look for it in Options under "General - Accessibility".
> Add Chatstack

- Content.Client/Guidebook/Richtext/Box.cs
- Content.Client/Guidebook/Richtext/ColorBox.cs
- Content.Client/Guidebook/Richtext/Table.cs
- Content.Client/UserInterface/Controls/TableContainer.cs
This ports the Guidebook Tables to allow \<Table\> and \<ColorBox\> embeds in the Guidebook.
This just adds extra XML tags to use in rich-text.
---
---
<details><summary><h3>Guidebook Screenshot</h3></summary>
<p>
</p>
</details>
NOTE: This screenshot was taken in the dev-environment. I just copy-pasted my SOP for Alert Levels to check it, since it uses both the \<Table\> and \<ColorBox\> identifiers.
---
:cl:
- add: Added <Table> and <ColorBox> identifiers. Go wild in SOP!
> [Port] Port Guidebook Tables From Wizden PR #28484

- .vscode/launch.json
- .vscode/tasks.json
This adds several different launch types to the VSCode. This allows you to launch Client in Compatibility Mode for the Tools/Release versions as well as launch the Server/Client at the same time in Tools/Release modes and use the VSCode Terminal.
---
---
> Add Different Launch Types to VSCode

- Resources/Locale/en-US/markings/lamia.ftl
- Resources/Prototypes/DeltaV/Entities/Mobs/Species/lamia.yml
- Resources/Prototypes/DeltaV/Species/lamia.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/earrings.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/face.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/gauze.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/human_noses.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/makeup.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/pointy_ears.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/reptilian.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/tattoos.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/wrist.yml
- Resources/Prototypes/Entities/Mobs/Customization/cyberlimbs/bishop.yml
- Resources/Prototypes/Entities/Mobs/Customization/cyberlimbs/hesphiastos.yml
Adds male Lamia with facial hair. Also makes dozens of markings available to Lamiae, including reptilian markings and pointy ears.
Also adds locale strings for the Lamia tail marking.
**Mermaid**
**Face:** Lips, Blush
**Head:** Left Eye
**Head (Top):** Lizard Horns (Ayrshire)
**Head (Side):** Thin Ears, Drop Earrings (Left/Right)
**Chest:** Lizard Chest (Tiger)
**Right Arm:** Right Arm Bracelet
**Right Hand:** Right Bracelet, Right Nail Polish
**Left Hand:** Left Bracelet, Left Nail Polish
**Male**
**Face:** Eyelash (Left/Right), Eye Corner (Left/Right)
**Head (Top):** Lizard Horns (Angler)
**Head (Side):** Lizard Frills (Short)
**Chest:** Lizard Chest (Tiger)
**Right Arm:** Lizard Right Arm (Tiger)
**Right Hand:** Right Watch (Colorable)
**Left Arm:** Lizard Right Arm (Tiger) …
> 💅🏻 Lamia Markings + ♂️ Male Lamia

- Content.Server/Fluids/EntitySystems/AbsorbentSystem.Footprints.cs
- Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
- Content.Server/FootPrint/FootPrintsSystem.cs
- Content.Server/FootPrint/PuddleFootPrintsSystem.cs
- Content.Shared/Fluids/AbsorbentComponent.cs
- Content.Shared/Footprint/FootPrintsComponent.cs
- Content.Shared/Footprint/PuddleFootPrintsComponent.cs
- Resources/Prototypes/Entities/Effects/puddle.yml
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
This is a port of https://github.com/Fansana/floofstation1/pull/445
Except I despise that this wasn't upstreamed so much that I didn't even cherrypick it. 
:cl:
- add: Footprints are now cleaned in a small radius around the mouse cursor when mopping them.
> Footprints Performance Updates

- Resources/Prototypes/DeltaV/Species/vulpkanin.yml
- Resources/Prototypes/Entities/Mobs/Customization/Markings/makeup.yml
- Resources/Prototypes/Nyanotrasen/Species/Oni.yml
- Resources/Prototypes/Nyanotrasen/Species/felinid.yml
- Resources/Prototypes/Species/arachne.yml
- Resources/Prototypes/Species/harpy.yml
- Resources/Prototypes/Species/human.yml
- Resources/Prototypes/Species/moth.yml
- Resources/Prototypes/Species/reptilian.yml
- Resources/Prototypes/Species/slime.yml
Removes the marking limits for the Face category (was limited to 1 marking) for all non-IPC species, now having unlimited markings as designed.
Moth makeup (Moth Blush / Moth Lipstick) is now usable again in the Face category.
**Markings without limits**
**Lizard with frills and earrings**
**Moth Makeup**
:cl: Skubman
- fix: The Face marking category now has unlimited markings for all species apart from IPCs.
- fix: Moth People can now apply Moth makeup markings again in the Face category.
- tweak: Unathi now have 3 'Head (Side)' marking points available, so they can use frills and both left and right-side earrings.
> Unlimited Face Markings

- Resources/Prototypes/DeltaV/Entities/Mobs/Species/lamia.yml
Lamia don't have feet, so they instead make huge drag marks when moving through puddles. :)
:cl:
- fix: Lamia now make drag marks when moving through puddles instead of regular footprints.
> Fix Lamia Footprints

- Resources/Prototypes/_Shitmed/Species/monkey.yml
Apparently this bug was introduced by Shitmed. Pun Pun (And monkeys) were appearing with completely black sprites. This led to numerous situations where characters would ask, "WHY IS PUN PUN WEARING BLACKFACE?"
<p>
</p>
</details>
:cl:
- fix: Confiscated Pun Pun's blackface.
> Fixed Monkey Skin Color

- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/inconveniences.yml
- Resources/Prototypes/Traits/languages.yml
Fixes some various issues with language related traits, such as Mimes being able to take the Mute trait for "Free points", Foreigner being able to be combined with Mute for "Free Points", etc. Foreigner being able to be taken by Mimes for "Free Points". Also stuff like the "Rare" languages giving you points instead of costing points, Sign Language being the "Best Language" because its mechanically better and free, so now it costs points, etc. 
:cl:
- tweak: Mimes can no longer take the Muted or Foreigner traits. 
- tweak: "Rare" languages like Sinta'Azaziba, Valyrian Standard, now cost points instead of giving points.
- tweak: Sign Language now costs points.
> Fix Various Language Trait Issues

- Content.Server/StationEvents/Events/PirateRadioSpawnRule.cs
My last change to Pirate Radio made it so that it doesn't spawn at all. So this PR updates it to instead use a more accurate "Use the spawnable station" check. By picking a random valid spawnable station(in case there's more than one).
:cl:
- fix: Fixed the Syndicate Listening Post not correctly spawning.
> Fix Pirate Radio Rule

- Resources/Prototypes/Catalog/uplink_catalog.yml
merge asap to fix powergaming reel
---
---
:cl:
- fix: Fixed Syndicate Elite hardsuit being one singular Telecrystal. Cybersun will never recover from this financial blunder.
> Fix Elite Suit Being ONE FUCKING TC

- Content.Shared/CCVar/CCVars.cs
When https://github.com/Simple-Station/Einstein-Engines/pull/720 (PR to raise trait limit from 5 to 10) was merged, we only had **53** traits. Now, we have a total of **109** traits. I was conservative with the trait limit back then because we didn't have as much traits, but now that we have so many we should raise the default trait limit from **10** to **14**. I believe 14 should be as high as it gets from now on.
For reference, the quirk limit in /tg/ station is just a maximum of 6 positive quirks. So a typical build that reaches the 14 trait limit would be something like 6 positive traits, 6 negative traits to afford all of those positive traits, 1 language trait and 1 accent trait. 
:cl: Skubman
- tweak: The maximum trait limit has increased from 10 traits to 14 traits.
> Increase Trait Limit From 10 To 14

- Content.Shared/Humanoid/HumanoidCharacterAppearance.cs
- Content.Shared/Preferences/HumanoidCharacterProfile.cs
- Resources/Prototypes/DeltaV/Species/lamia.yml
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
- Resources/Prototypes/Nyanotrasen/Species/Oni.yml
- Resources/Prototypes/Nyanotrasen/Species/felinid.yml
- Resources/Prototypes/Species/arachne.yml
- Resources/Prototypes/Species/dwarf.yml
- Resources/Prototypes/Species/harpy.yml
- Resources/Prototypes/Species/human.yml
- Resources/Prototypes/Species/ipc.yml
Port from [WWDP](https://github.com/WWhiteDreamProject/wwdpublic/pull/212)
---
<p>
How it was before:
How is it now:
</p>
</details>
---
:cl: Spatison
- fix: Humanoid color in the spawn panel is now correct.
- fix: IPCs can no longer spawn invisible.
> Fix Humanoid Color

- Content.Client/MassMedia/Ui/NewsArticleCard.xaml.cs
- Content.Client/MassMedia/Ui/NewsWriterMenu.xaml
- Content.Shared/MassMedia/Systems/SharedNewsSystem.cs
Increases the text limit for news reports:
- Title character limit: 25 -> 50
- Content character limit: 2048 -> 2560
Mostly a personal change for me because I often run into the title character limits when I was playing Reporter. 
:cl: Skubman
- tweak: The news article title character limit has been increased from 25 to 50 characters, and news content from 2048 to 2560 characters.
> Increase Title/Content Text Limits For News Articles

- Content.Server/WhiteDream/BloodCult/Items/ShadowShacklesAura/ShadowShacklesAuraSystem.cs
Fixed Shadow Shackles not activating when you melee hit the target.
The Problem: The code checked if the target wasn't stunned when you hit someone, therefore not activating unless the target was already stunned. I fixed it by removing the ! operator on `HasComp<StunnedComponent>(target)` check.
---
<p>
https://github.com/user-attachments/assets/5ac1a5dd-5d62-4400-be64-56500c87ed5e
</p>
</details>
---
:cl:
- fix: Fixed Shadow Shackles spell not activating.
> Fixed Shadow Shackles Not Activating for Blood Cultists

- Resources/Prototypes/Catalog/Fills/Boxes/security.yml
- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Adds a prisoner headset box for warden's locker
Reason: There's too much chaos in security and making radio headsets with pure encryption keys takes time and tools. More so cause by the time someone gets a perma punishment, its gonna be most likely late in the round and sec department will be dealing with a lot of things at the same time. 
---
<p>
</p>
</details>
---
:cl:
- add: Added prisoner headset box to warden's locker.
> Prisoner Headset Box in Warden's Locker

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Lathes/security.yml
- Resources/Prototypes/Research/arsenal.yml
N1984 exists, but you can't print more ammo reliably. You can refill them, sure, but the moment you lose a magazine, it's gone forever.
This adds the magazines and adds the unique mags to the research.
Edit: Turns out there's like a lot missing in the lathe, so I decided to just add the missing ones I found.
---
<p>
Nothing here
</p>
</details>
---
:cl:
- add: Added missing lathe recipes
> Adds Missing Lathe Recipes

- Content.Shared/Body/Systems/SharedBodySystem.cs
- Content.Shared/_Shitmed/Surgery/Conditions/SurgeryOrganConditionComponent.cs
- Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.cs
- Resources/Prototypes/Body/Organs/diona.yml
- Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgeries.yml
When attempting to insert an organ, a check is now performed to ensure a container exists for it. Skeletons can now lie down, and nymphs can now be subject to surgery.
---
:cl: Spatison
- tweak: Nymphs are now operable.
- fix: Skeletons can now lie down.
- fix: It is no longer possible to insert an organ into a body if the required space is unavailable.
> Some Surgery Fixs

- Content.Client/Administration/UI/BanPanel/BanPanel.xaml.cs
- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Server/Store/Conditions/BuyerDepartmentCondition.cs
- Content.Shared/Roles/DepartmentPrototype.cs
(cherry picked from commit 07dfefc4a29927aa74cfd5c7e75c6cb344d713f6)
Allows hiding of departments by a bool. Tested on Nuclear14 as working. Pertinent code is around line 710 of humanoidprofileeditor.xaml.cs. This was the only file to conflict and the conflicts were overwritten with our code.
---
---
<p>
</p>
</details>
---
> Hiding and Clearing Department Prototype Code (#28114)

- Resources/Maps/gaxstation.yml
- Resources/Prototypes/Maps/gaxstation.yml
Gax Station already had a fully functional AI Satellite ready to go for us, all it needed was to have the spawner added (And two spare EMPTY Ai cores that it has room for), as well as a job slot!
<p>
</p>
</details>
:cl:
- add: Added Station AI to GaxStation
> Add Station AI To Gax

- Resources/Prototypes/Traits/skills.yml
Senior Physician wasn't included in the list of jobs that can't take CPR Training, but they already have CPR training, thus allowing players who don't know this to waste 4 points on a trait they get for free.
> Senior Physician CPR

- Content.Server/Fluids/EntitySystems/AbsorbentSystem.Footprints.cs
- Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
- Resources/Prototypes/Entities/Mobs/Species/shadowkin.yml
classic
this also adds a respiratorcomponent to shadowkin
> Fix AbsorbentTest & Shadowkin Test Fail

- Resources/Maps/radstation.yml
- Resources/Prototypes/Maps/radstation.yml
This PR adds a Station AI to Radstation! Also cleans up some of the camera coverage. Since it's a mid to highpop map, this core is a bit better protected with the addition of blast doors to the windows that the AI can shut with a button. Also two cyborg spawners in the AI room, because I know for a fact we'll want them for any future malf/traitor AI implementation. :)
<p>
</p>
</details>
:cl:
- add: Station AI has been added to Radstation
> Radstation AI

- Content.Client/Shuttles/UI/NavScreen.xaml
- Content.Client/_NF/Shuttles/BUI/ShuttleConsoleBoundUserInterface.cs
- Content.Client/_NF/Shuttles/UI/NavScreen.xaml.cs
- Content.Client/_NF/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
- Content.Client/_NF/Shuttles/UI/ShuttleNavControl.xaml.cs
- Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
- Content.Server/Station/Systems/StationDampeningSystem.cs
- Content.Server/_NF/Shuttles/Systems/ShuttleSystem.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Physics/FrictionRemoverSystem.cs
- Content.Shared/Shuttles/BUIStates/NavInterfaceState.cs
- Content.Shared/_NF/Shuttles/Events/SetInertiaDampeningRequest.cs
- Resources/Locale/en-US/_NF/shuttles/console.ftl
- Resources/Maps/Shuttles/trading_outpost.yml
porting over my cruise control code from frontier with some minor bug fixes.  also had to fuck with the passive dampening system because the notsorobust toolbox has hurt its self in confusion
Description.
redid the port from frontier removing unnecessary complicated and confusing content.
replaced hard coded values with cvars
patched issues with the passive dampener system causing dampener states to reset
added regions to cvar file to make it easier to look threw
reverted text so that its more ship based, your not driving a car
this is my original work so re-licensed my work under my name rather than frontier blanket who is licensed to use edit agpl3
:cl:
- tweak: tweaked friction remover system
- fix: fixed inertia dampening system resetting or effecting the wrong grid
- remove: Removed …
> Porting over My Cruise Control Code From Frontier

- Content.Server/StationEvents/Events/RandomSentienceRule.cs
:cl:
- fix: Fixed announcement spam caused by my silly blunder.
> Fix Announcement Spam

- Content.Client/Weather/WeatherSystem.cs
Pretty simple fix, just tell the weather system "If there's already a weather sound playing, stop.". I have infact tested this, and verified that this fix does work.
Fixes https://github.com/Simple-Station/Einstein-Engines/issues/1285
:cl:
- fix: Fixed a crash caused by Weather System creating millions of sounds.
> Fixes Weather Soundspam(And Crash)

- Content.Server/Administration/Commands/PlayTimeUnlockCommands.cs
- Resources/Locale/en-US/players/play-time/play-time-commands.ftl
Adds a command that adds the playtime requirements of a job.
---
:cl:
ADMIN:
- add: Added a command to easily allow for adding a jobs playtime requirements. (playtime_unlock)
> PlayTime Unlock Command

- Resources/Prototypes/Species/shadowkin.yml
They're kind of awful, and still not meeting my quality expectations. They simply have entirely too many "Buts". Too complicated, not good enough writing quality, what content they have is written like a joke or is very childish. And they're still written out of too many game systems.
:cl:
- tweak: Disabled Shadowkin as a default roundstart-available species.
> Disable Shadowkin (Again)

- Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
Energy swords were missing a component. Also E-Daggers were causing a debug assert so I've fixed that too.
<p>
</p>
</details>
:cl:
- fix: Fixed Energy Swords not displaying their blade when ignited.
> Fix Energy Swords

- Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
- Resources/Prototypes/InventoryTemplates/aghost_inventory_template.yml
Adds 4 pockets to the Admin Ghosts and the ability to Tail-Drag (no hands needed).
---
https://github.com/user-attachments/assets/701b66bd-c42c-429f-a33a-f8e465ef068d
---
:cl:
ADMIN:
- add: Added pockets to Admin Ghosts.
- add: Added tail-drag (no-hands) to Admin Ghosts.
> Add Pockets and Tail-Drag to Admin Ghosts

- Content.Shared/CCVar/CCVars.cs
The Traitsystem anticheat is apparently really good at yeeting players who join as a different job than the one they selected for their traits menu. A better solution would be to rework the latejoin system so that it simply prevents you from joining as any job that would have an invalid trait total(Trait points after all *valid* traits are applied being a negative number is the key here). However since doing that would require me spend 10 hours thoroughly reading a >1000 line function which has so many indentations that parts of it don't even fit on my 17" monitor, I'm electing to disable the system pending a rework.
No changelog because we shouldn't be openly telling the players they can just cheat the traits menu lmao.
> Default Disable Traits Anticheat 

- Resources/Locale/en-US/weapons/extenddescriptions/descriptions.ftl
- Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
- Resources/Prototypes/DeltaV/Catalog/VendingMachines/Inventories/salvage_points.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
- Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
- Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
I may have been a little *too* generous with Salvage players. This update fixes the salvage guns spawning with a magazine or lethal ammo. There was also an issue that they were perhaps "Too easy to obtain". In actual practice, it turns out that a single "Mining Expedition" earns salvage enough mining points to buy like 4 rifles. Which led to situations where Salvage functionally became station security after they then broke into the armory to print ammo. 
Another issue I discovered is that Salvage can also use their breaching charges to blow open security crates(And also blow open the armory......). So now they don't spawn with bombs in their lockers, and need to pay for them with said mining points. 
<p>
</p>
</details>
:cl:
- add: Added a …
> Nerf Salvage

- Content.Shared/Preferences/HumanoidCharacterProfile.cs
I'm trying to fix a crash caused by character profiles saving the same antag preference twice. I have no clue why or how it's happening, but this should probably prevent it from happening by making the profile sanitizer remove duplicate keys before saving them to the database.
The relevant crash log: 
[goobcrash.txt](https://github.com/user-attachments/files/18391763/goobcrash.txt)
:cl:
- fix: Attempted to fix a crash related to antag preferences saving multiple times.
> Maybe Fix Antag Related Crash

- Content.Server/Jobs/AddTraitSpecial.cs
Adds a way to specify traits in the jobs special area.
Hashset so you can specify multiple traits. Tested on Nuclear14 to give the tribals a specific language in a friendly way.
```
special:
- !type:AddTraitSpecial
traits: [ LanguageTribal, LanguageChinese ]
```
> AddTraitSpecial

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.CVars.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
- Content.Shared/CCVar/CCVars.cs
- Content.Shared/Damage/Systems/SharedDamageOtherOnHitSystem.cs
- Resources/Prototypes/Entities/Objects/Misc/tiles.yml
- Resources/Prototypes/Tiles/floors.yml
I promised I would return to this code when I had gotten down the basics of Calculus, and so I have. This PR reworks Space Wind to be even more efficient, while also making it run significantly smoother. Previously, my last optimization to this system involved replacing the need to take the square root of a large float a few thousand times per tick by adding an early exit, cleverly rearranging the math so that it multiplies a few times instead of square rooting, and changing it to use the throwing system. 
That is no longer necessary, it now operates on the Derivative of said function with respect to time. It's no longer necessary to square anything. This new space wind is significantly smoother than before.
<p>
Final refinements of V3 courtesy …
> Space Wind Version 3

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
I realized only afterwards that there was another place I could have optimized this, by normalizing the throw vector before we iterate over every entity on the tile. Which significantly cuts down on what might otherwise be an internally very complicated step.
No changelog, this isn't player facing, just an optimizing hotfix.
> Small Space Wind Optimization Hotfix

- Content.Server/Abilities/Psionics/Abilities/AssayPowerSystem.cs
Assay featured the return of a bug that was present with the "Heal Other Powers", which made it so that failing to cast the Assay power (due to attempting to use it while moving for instance), caused the player to permanently lose the ability to cast any psi powers. The reason for this and the fix for it are pretty much exactly the same as it was for HealOtherPowerSystem.
Goddamn I **desperately** need to generalize these powers so I never have to go through this again.
:cl:
- fix: Fixed a bug where failing to cast the Assay power meant one lost the ability to ever use psionic powers again.
> Assay Power Hotfix

- Content.Server/Shuttles/Systems/ArrivalsSystem.cs
- Content.Server/Silicons/StationAi/StationAiSystem.cs
- Content.Shared/Bed/Cryostorage/CanEnterCryostorageComponent.cs
- Content.Shared/Bed/Cryostorage/SharedCryostorageSystem.cs
- Content.Shared/Intellicard/Components/IntellicardComponent.cs
- Content.Shared/InteractionVerbs/SharedInteractionVerbsSystem.cs
- Content.Shared/Silicons/StationAi/SharedStationAiSystem.Airlock.cs
- Content.Shared/Silicons/StationAi/SharedStationAiSystem.Held.cs
- Content.Shared/Silicons/StationAi/SharedStationAiSystem.cs
- Resources/Locale/en-US/game-ticking/game-ticker.ftl
- Resources/Locale/en-US/intellicard/intellicard.ftl
- Resources/Locale/en-US/silicons/station-ai.ftl
- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
Resolves #1529
:cl:
- fix: Fixed interactions not respecting identity.
- fix: Potentially fixed spawning issues.
- fix: Fixed borgs, animals and aghosts being able to enter cryosleep.
> Fix Even More Issues

- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Bro, it is absolutely wild that they don't have a requirement. This must've been looked over or something, so I added a Security Officer playtime requirement to the already-existing department requirement that was missing an actual minute listing.
---
:cl:
- fix: Fixed the missing playtime requirement on Security Officer. It is now set to 10 hours of Security Department.
> Add Security Officer Playtime Requirement

- Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Fixed big security glasses not having flash protection and security HUD by inheriting from `ClothingEyesGlassesSecurity` instead of `ClothingEyesGlassesCheapSunglasses`.
:cl: Skubman
- fix: Big security glasses now provide flash immunity and a security HUD.
> Fix Big Security Glasses Not Having HUD

- Resources/Prototypes/Entities/Mobs/Species/arachne.yml
- Resources/Prototypes/Nyanotrasen/Entities/Body/Parts/spider.yml
- Resources/Prototypes/Nyanotrasen/Entities/Body/Prototypes/arachne.yml
Arachne can now stand up after lying down again.
Arachne with 8 registered legs lying down and standing up
https://github.com/user-attachments/assets/b7b5c83b-b741-4d4f-88b6-1133834104de
I don't even really understand what I'm about to say, just trying to explain the issue for documentation purposes. 
`LayingDownSystem.TryStandUp` checks if the entity's `BodyComponent.LegEntities` element count is less than `BodyComponent.RequiredLegs`, which for Arachne is 8.
https://github.com/Simple-Station/Einstein-Engines/blob/78347d76fb50908888c77df5e3b935b773297620/Content.Shared/Standing/SharedLayingDownSystem.cs#L141-L151
However, due to some issues with the part slot naming, `BodyComponent.LegEntities` for Arachne has no elements, because of Shitmed being hardcoded and being built with the …
> Arachne Standing Up Fix

- Content.Client/Jittering/JitteringSystem.cs
- Content.Client/Light/Components/LightBehaviourComponent.cs
- Content.Client/Light/EntitySystems/ExpendableLightSystem.cs
- Content.Client/Light/EntitySystems/LightBehaviorSystem.cs
- Content.Client/Light/EntitySystems/RotatingLightSystem.cs
- Content.Client/Light/HandheldLightSystem.cs
- Content.Client/WhiteDream/BloodCult/Items/VoidTorch/VoidTorchSystem.cs
Ports over these commits from Wizden:
https://github.com/space-wizards/space-station-14/commit/32e315c68f2c293b021048c4f77896a27cd512fc
https://github.com/space-wizards/space-station-14/commit/8d015f5c9ff60107dccdf35fa48e1558728ff269
Namely the first is a general refactor to LightBehaviorSystem and the second is a bugfix that fixes some looping behaviors like the low battery effect on a flashlight never stopping. If it's not atomic enough, let me know and I can separate them into two.
:cl:
- fix: Fixed some errors with looping behaviors like jitter.
> Ports Fixes to some Looping Systems, LightBehaviorSystem Refactor From Wizden

- Content.Server/Nutrition/Components/FoodComponent.cs
- Content.Server/Nutrition/EntitySystems/FoodSystem.cs
- Resources/Locale/en-US/_Shitmed/nutrition/components/food-component.ftl
- Resources/Prototypes/Body/Organs/diona.yml
- Resources/Prototypes/Body/Organs/human.yml
- Resources/Prototypes/_Shitmed/Body/Organs/Animal/animal.yml
Increases the delay when eating brains from 1 second to 5 seconds, and when someone starts or finishes eating a brain it shows a red popup to everyone in range.
Eating a character's brain round-removes them. However, it's easy to do with a 1-second timer and very easy to accidentally RR someone through eating their brain by fat-fingering the "Activate item in hand" keybind. (Disclaimer: I did exactly this LOL). This PR will make accidental brain eating very unlikely.
A red popup on eating is also important so everyone in range will be aware if someone might get RR'd through brain eating and be able to try to intervene.
This also fixes a _very hilarious_ bug where the target of a force-feed wouldn't get the popup showing the flavors of the food after the force feed was complete. 
**Popup …
> [Shitmed] Increase Brain Eating Time & Show Brain Eating Popup

- Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Server/Nyanotrasen/Abilities/Boxer/Boxer/BoxerComponent.cs
- Content.Server/Nyanotrasen/Abilities/Boxer/BoxingSystem.cs
- Content.Server/Traits/TraitSystem.Functions.cs
- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Entities/Mobs/Player/silicon_base.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
- Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
- Resources/Prototypes/Traits/physical.yml
Reworks the Martial Artist trait, making it a more impactful and visually distinct trait.
- Left-clicks are now single-target power attacks, requiring less aim than before.
- **50%** damage bonus reduced to **20%** damage bonus (same overall DPS with next change).
- Gain **25%** attack rate bonus.
- The attack rate bonus helps make the trait feel and look distinct from non-Martial Artist melee attacks.
- **50%** range bonus reduced to **10%** range bonus.
- The damage bonus is now also applied to Asphyxiation and Poison damage, which Lamia unarmed attacks deal.
- Trait cost increased from **-3** points to **-5** points.
- Striking Calluses (which requires Martial Artist) cost reduced from **-4** points to **-3** points to prevent the Martial Artist/Striking Calluses combo from being too …
> Martial Artist Rework + Fix MeleeWeapon Wizmerge Bugs

- Content.Shared/Customization/Systems/CharacterRequirements.Profile.cs
- Resources/Prototypes/Loadouts/Jobs/Command/captain.yml
- Resources/Prototypes/Loadouts/Jobs/Security/headOfSecurity.yml
- Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml
- Resources/Prototypes/Loadouts/Jobs/Service/bartender.yml
Just because I can. I've added requirements to every firearm available in Loadouts, and added a minimum character age requirement to them in order to make them consistent with Space Law(Biesel Republic Law). 
:cl:
- add: In order to comply with Biesel Republic laws governing firearm ownership, all firearms now require that a person be 21 years of age or older to purchase.
> Make Loadout Firearms Comply With Space Law

- Content.Server/Damage/Systems/DamageOtherOnHitSystem.cs
- Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
- Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
Fixes the attack values of mining weapons which were messed up in the Wizmerge.
For the pickaxe, I reverted all damage values to be the same as before. For the mining drill however, I opted to keep the rapid fire rate because it was an interesting effect and just added the extra range from pre-wizmerge and the throwing damage back. I also **greatly reduced the mining drill's stamina cost** because it was a common complaint among players.
Before the wizmerge, the mining weapons (pickaxe and drill) were in `Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml`  but they got moved to `Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml` and thus the EE-specific changes got wiped.
Also fixes a subtle bug in `SharedMeleeWeaponSystem.OnMeleeSelected`, responsible for …
> Fix Mining Drills & Reduce Stamina Cost

- Content.Server/Nyanotrasen/Research/SophicScribe/SophicScribeSystem.cs
- Content.Shared/Psionics/Glimmer/GlimmerSystem.cs
:cl:
- fix: Fixed full glimmer float being displayed to chat by Sophia.
> Fix Sophia Sending a Massive Float to Chat

- Content.Client/Chemistry/UI/ChemMasterWindow.xaml
Fixed not having enough space for longer chemicals on the ChemMaster UI.
---
:cl:
- fix: Fixed not having enough space for longer chemicals on the ChemMaster UI.
> Make Room for Longer Chem Names.

- Content.Client/Physics/Controllers/MoverController.cs
- Content.Server/Physics/Controllers/MoverController.cs
- Resources/Locale/en-US/station-laws/laws.ftl
- Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/Entities/Stations/base.yml
- Resources/Prototypes/Entities/Stations/nanotrasen.yml
- Resources/Prototypes/silicon-laws.yml
This PR adds in the classic Asimov's Three Laws of Robotics as a standard lawset for Synthetics. The laws are given thus.
Law 1: A robot may not injure a human being or, through inaction, allow a human being to come to harm.
Law 2: A robot must obey the orders given it by human beings except where such orders would conflict with the First Law.
Law 3:  A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.
The localizations for them are intentionally left exactly-as-is from the original 3 laws written by Isaac Asimov. Yes this is totally different from "Crewsimov", yes this does actually mean an Asimov AI isn't required to obey orders given to it by a Moth. Yes this does actually mean that the AI isn't allowed to "Harm" nukies so …
> Add Classic Asimov Laws

- Content.Server/Speech/EntitySystems/VocalSystem.cs
- Content.Server/Speech/Muting/MutingSystem.cs
- Content.Shared/CCVar/CCVars.Misc.cs
This PR adds a new server configuration that disables the special Scream Action that all players spawn with. It's stupid, it's NRP. And you can still scream with the emote or emote wheel. If the config is set to false at roundstart, the Scream action simply won't spawn. 
:cl:
- tweak: The "Scream Action" no longer appears by default. It may be set in your server's configuration to spawn or not.
> Remove Default Scream Action

- Content.Server/DeviceNetwork/Systems/NetworkConfiguratorSystem.cs
- Content.Shared/Access/Systems/AccessReaderSystem.cs
Fixes the infamous "local entity uid 0" error (hopefully forever)
Also fixes the infamous Access denied with network configs in mapping mode.
---
:cl:
- fix: Fixed the infamous "Access denied" when using a network config in mapping mode.
> Network Configurator Fixes

- Resources/Prototypes/Traits/disabilities.yml
It turns out that when you have a species that has 20x the blood volume of a human, letting them take a trait that makes them constantly bleed some percentage of their blood volume causes a lot of problems. Usually by FLOODING the station with blood. This PR just makes Lamia ineligible for the two blood traits, it unfortunately doesn't fix the issue of them excessively bleeding when you attack them(I actually don't fully consider it to be an issue. I have issues instead with system instances of hardcoded blood amounts). 
:cl:
- remove: Lamia can no longer take blood related traits, such as Blood Deficiency.
> Disable Blood Traits For Lamia

- Content.Client/Verbs/UI/VerbMenuUIController.cs
Hotfix for an issue with the recent update. Verbs weren't working. Here's proof they work now:
> Hotfix Verbs

- Resources/Prototypes/Recipes/Reactions/medicine.yml
Making chems use Unobtainium Reagents doesn't make chemistry interesting, it makes medical gameplay boring. This PR replaces the unobtainium recipes with suitably expensive and/or complicated recipes. Have fun memorizing how to make Acetone, Ammonia and Impedrezine. 
:cl:
- remove: 1984'd most instances of "Unobtainium" chemistry. Chems like Necrosol that previously required normally unobtainable reagents such as Cognizine or Vestine now instead have long production chains of chems that are obtainable, but complicated to produce. Check the chemistry menu for more information.
> 1984 "Unobtainium Chemistry"

- Resources/Locale/en-US/lathe/lathe-categories.ftl
- Resources/Locale/en-US/prototypes/entities/clothing/outerClothing/hardsuits.ftl
- Resources/Locale/en-US/research/technologies.ftl
- Resources/Prototypes/Entities/Objects/Materials/materials.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Lathes/categories.yml
- Resources/Prototypes/Recipes/Lathes/hardsuits.yml
- Resources/Prototypes/Research/arsenal.yml
This PR fills in the basics for the previously commented placeholders for "Advanced Tacsuits" and "Prototype Tacsuits", both new Arsenal researches. These both unlock recipes for manufacturing tacsuits at a Security Techfab, and are an alternative method to making them outside of buying them through Cargo. Here's a genuine reason for Epistemics to consider doing Arsenal T3. 
<p>
</p>
</details>
:cl:
- add: Added Advanced Tacsuits, and Prototype Tacsuits to Arsenal research. Along with them comes Security Techfab recipes for said tacsuits.
> Arsenal Tacsuit Research

- Content.Server/Clothing/Systems/LoadoutSystem.cs
Servers are occasionally experiencing roundstart crashes, and the logs I received concerning this crash imply that LoadoutSystem is SOMEHOW being handed a player character that doesn't actually exist. Well an easy solution I guess is to just make LoadoutSystem check if the entity *factually* exists, before attempting to apply a loadout to it.
:cl:
- fix: Possibly fixed a crash related to Loadouts being applied to entities that don't exist.
> Fix Possible Loadout Related Crash

- Resources/Locale/en-US/station-laws/laws.ftl
- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/Entities/Stations/base.yml
- Resources/Prototypes/silicon-laws.yml
New lawset, see media.
---
:cl: Rane
- add: Added Augustine lawset as a middle ground between Asimov and Crewsimov.
> Augustine Lawset

- Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs
(fix medbays making people go up/down if they speak)
:cl:
- fix: The medbay fent zombie epidemic is now fixed.
> Fix Fent Zombies in Medbay

- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
This gives the Blueshield Officer a Central Command Headset and gives them MedTek as well (by giving ERT Leader MedTek).
The Blueshield Officer should have access to a Central Command Headset to communicate with the other Dignitaries (NTR and MAG) and to communicate with Central Command if they are the only acting Dignitary as well.
The Blueshield Officer should have access to MedTek since they already have access to their sunglasses so that they can check the injuries of an injured command without needing a health analyzer.
---
:cl:
- add: Added MedTek to Blushield Officer PDA.
- tweak: Blueshield Officer now has a Central Command Headset instead of an All-Access Command Headset.
> BSO Changes - Headset and MedTek

- Content.Server/Singularity/Components/GravityWellComponent.cs
- Content.Server/Singularity/EntitySystems/EventHorizonSystem.cs
- Content.Server/Singularity/EntitySystems/GravityWellSystem.cs
- Content.Shared/Singularity/Components/EventHorizonComponent.cs
- Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/singularity.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/energyball.yml
By request from the very same person who assisted with https://github.com/Simple-Station/Einstein-Engines/pull/1618
This PR ports(and fixes) https://github.com/space-wizards/space-station-14/pull/23372 such that it works on modern Robust Toolbox. 
This PR essentially makes it so that the Singularity (And Tesla by extension) inherit some of the momentum of objects thrown into them. Im practice it means that they now work more like they do in SS13, whereby if a traitor does not actively intervene in a Singuloose(such as by using a Singularity Beacon), the singularity will usually be "Blown back into space" by space wind throwing objects at it in retaliation to it eating engineering. 
<p>
https://github.com/user-attachments/assets/04e9e5b9-d873-4425- …
> Newtonian Singularity

- Content.Server/Singularity/EntitySystems/EventHorizonSystem.cs
- Content.Server/Singularity/EntitySystems/GravityWellSystem.cs
- Content.Shared/Physics/CollisionGroup.cs
- Resources/Prototypes/Entities/Mobs/Player/narsie.yml
- Resources/Prototypes/Entities/Mobs/Player/observer.yml
- Resources/Prototypes/Entities/Mobs/Player/ratvar.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/singularity.yml
> Hotfix AI Being Eaten by Singulo

- Resources/Prototypes/DeltaV/Entities/Mobs/Species/lamia.yml
The asphyxiation damage was extremely temporary and it took less than a cycle to get it healed up. In the current stage where you can't strangle someone, this kind of damage is irrelevant.
Thus I have moved the 2 points of asphyx equaly to piercing and poison instead, making the lamia melee feel a bit stronger.
---
:cl:
- tweak: Tweaked lamia bite
> Removes Asphyxiation From Lamia in Favor of Pierce/Poison

- .github/CODEOWNERS
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
- Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Mech/Weapons/Melee/combat.yml
Melee Weapons were accidentally given the wrong attack speed formula again. It took me awhile of reviewing the entire history, but eventually I found the line where the wizmerge introduced a new check that used the old formula.
Also to help prevent this from happening again, I've put in a request to be set as codeowner for the relevant systems I have significantly modified.
:cl:
- fix: Fixed melee weapons having the wrong attack speed calculations(again)
> Fix Melee Attack Speed Again

- Content.Server/Administration/Systems/AdminSystem.cs
This system was just blindly assuming a session couldn't be null without proving it wasn't, and two different functions both incorrectly made this assumption. I have no idea how the hell they managed to sneak it past the compiler's null reference test.
> Don't Assume Sessions Are Real

- Content.Shared/_Arcadis/Computer/DiskBurnerSystem.cs
Had an aneurysm seeing this live on arcadis and webedited a fix. Fixes an issue on examining a disk burner without a board.
---
no
> Hotfix for Disk Burner Examine

- Content.Server/DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs
Thanks to Router for pointing out we can actually reuse code that is apparently just always running exclusively on player characters. So it turns out that this game actually has a system for tracking who the killer is. We can skip enumeration outright if the killer was the one who downed the player. There's still BETTER ways to do this, like subscribing to KillReportedEvent instead of MobStateChanged, but I'm a bit too zonked out to pursue that right now.
> Better Teach Lesson Code

- Resources/Prototypes/_EE/Entities/Mobs/Species/tajaran.yml
- Resources/ServerInfo/Guidebook/Mobs/Tajaran.xml
Updated guidebook text, and fixed enviro damage values (for humans it's 0.1 and 1.5, so for tajara it's 0.065 and 2). Also removed temperature protection cuz it does like, literally nothing.
---
<p>
</p>
</details>
---
:cl:
- fix: Fixed typos in guidebook entry for tajara
- fix: Temperature related fixes for tajara
> Micro Tajara Guidebook Text Fixes/ Bugfixes

- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
I Hate Pacifist Mantises
This PR literally just removes the ability of the Mantis to be a pacifist. He's given a gun and a knife for a reason, his job is a violent one, makes no sense that he should be able to be a pacifist. 
---
---
:cl: ShirouAjisai
- tweak: Mantis can no longer be a pacifist
> Mantis Violence Update

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Blueshield gets the same CPR trait that doctors and the Corpsman get. SOP says he's responsible for first aid on command so this reflects that. Plus, wouldn't it make sense for a highly-trained bodyguard to know basic CPR???
---
:cl: ShirouAjisai
- add: Blueshield Officer now has CPR as a roundstart trait.
> Blueshield CPR Update

- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
- Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
:cl:
- fix: Other species can pick Cataloguer, Psionic Mantis, and Mystagogue again.
> Fix Jobs only Allowing Shadowkin by Accident

- Resources/Prototypes/Catalog/Fills/Items/gas_tanks.yml
- Resources/Prototypes/CharacterItemGroups/Generic/languageGroups.yml
- Resources/Prototypes/GameRules/midround.yml
- Resources/Prototypes/Objectives/objectiveGroups.yml
- Resources/Prototypes/Roles/Jobs/Fun/plasmaman_startinggear.yml
- Resources/Prototypes/Traits/physical.yml
- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
- Added the `SkeletonAccent` trait to the `TraitsAccents` item group prototype (was mistakenly not included)
- Set all plasma tank's output pressure to 5.325 (was 21.3), same as the smaller plasma internals tank
- Apparently the Output Pressure is not really meaningful for engineering on plasma tanks so this is just a QoL feature for plasmamen
- Prevent plasmamen from taking the Temperature Tolerance trait that is useless due to their cold immunity.
- Fix price of uplink mechs due to lack of https://github.com/Goob-Station/Goob-Station/pull/332
- We absolutely want to bring the Telecrystal Rework here, but for now reduce the price Pending Rework™.
- https://github.com/space-wizards/space-station-14/pull/30393 (cherry-picked from Wizden)
- Disable the Raise Glimmer objective due to the …
> Plasmaman Hotfix + Other Fixes

- Resources/Prototypes/Entities/Mobs/Species/plasmaman.yml
Fixed plasmamen being permanently slowed after their temperature changes significantly. And slightly lowered their heat damage threshold by -5 C because why not.
Bug reported after several Plasmamen entered the same room with a different temperature and all came out with permanent movement slows.
The default `TemperatureSpeed` component has the following thresholds:
https://github.com/Simple-Station/Einstein-Engines/blob/aaadc3b7d9bf93200e03a596ce5fef159206ab88/Resources/Prototypes/Entities/Mobs/Species/base.yml#L316-L320
At 293 Kelvin it causes a 20% slow, at 280K it causes a 40% slow. Since Plasmamen have a different normal temperature of 270.15 K instead of 310.15 K, whenever their temperature changes above or below the defined thresholds they will start to be slowed permanently. …
> Fix Plasmaman Temperature Perma-Slow

- .github/workflows/rsi-diff.yml
Ever had the rsi diff bot run and tell you there's spaces in file names in totally unrelated files? Well this should fix that.
> Fix Rsi Diff Bot Detecting Spaces in File Names

- Resources/Prototypes/Voice/speech_emotes.yml
HELP, MY BIRBS CAN'T CHIRP. FIX THIS IMMEDIATELY.
> MISSING HARPY EMOTES

- Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs
- Content.Shared/Damage/Systems/DamageableSystem.cs
Yes this is a spite PR. I found out Barotrauma gibs you pretty much INSTANTLY. So this removes the ability for Barotrauma to damage body parts. 
:cl:
- fix: Space no longer gibs you instantly.
> Remove Barotrauma Gibbing You Instantly.

- Content.Server/Cloning/CloningSystem.Utility.cs
I only just now found out that the stock cloner doesn't transfer your character's appearance. And neither does the Metem machine if you win the roll. This fixes that.
:cl:
- fix: Both standard Cloner, and Metem Machines(when you win the psychic willpower roll) now correctly transfer over your old character appearance.
> Fix Standard Cloners Not Transferring Appearance

- Resources/Prototypes/Guidebook/science.yml
- Resources/ServerInfo/Guidebook/Science/MantisGuide.xml
Adds a Mantis guidebook entry, it's part of the overhaul of science and can directly effect other players negatively severely (such as round removal) if new players have no clue what they're doing. 
🆑 
- add: Psionic Mantis Guidebook
> Psionic Mantis Guidebook Entry

- Content.Server/Chat/TelepathicChatSystem.cs
This removes the ability to use telepathy while unconscious.
:cl:
- remove: Removed the ability to use Telepathy while unconscious. It is now safe to sleepy-pen people who have psi powers.
> No More Telepathy While Unconscious

- Resources/Prototypes/CharacterItemGroups/Jobs/Security/uncategorized.yml
- Resources/Prototypes/Loadouts/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml
- Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
Congratulations, BSO can now take better guns if they wish. Or a sword. I don't care.
:cl:
- add: BSO now selects their weapon from the same list as Security Officers. So you can trade your energy revolver for a Python if desired.
> Make BSO Able To Take Secoff Guns

- Content.Shared/Customization/Systems/CharacterRequirements.Profile.cs
- Resources/Locale/en-US/customization/character-requirements.ftl
I did separate locales because it'd be messy otherwise.
:cl:
- fix: Loadouts will no longer show the integer limit.
> Fix AgeRequirement Showing Int32 Maximum

- Content.Client/Effects/ColorFlashEffectSystem.cs
If a damageable entity gets hit three times in a quick succession, it will get stuck slightly red. This effect is clientside-only, but will be present on all clients that had this happen in their PVS range. Presumably this was happening because TryComp returns the requested component even if it's shut down and is about to be removed.
---
---
<p>
<details><summary>Before</summary>
<p>
https://github.com/user-attachments/assets/5f9a8510-8faa-49df-9cac-b9312e330f53
</p>
</details>
<details><summary>After</summary>
<p>
https://github.com/user-attachments/assets/f1d88ebb-3e6c-460d-b4cc-9e93918f1015
</p>
</details>
</p>
</details>
---
:cl:
- fix: Fixed damageable entities being stuck red after being damaged several times in a quick succession.
> Fix Sprites Getting Stuck Red when Quickly Damaged

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Fixes inheritance on the industrial ore processor so that it correctly inherits its recipes from the regular ore processor. Now you can make Tungsten on your fancier ore processor with a material multiplier. 
:cl:
- fix: Fixed industrial ore processor not inheriting its recipes from the standard one. You are now able to make Tungsten Carbide on your upgraded ore processor.
> Fix Industrial Ore Processor Inheritance

- Content.Client/Traits/SingerSystem.cs
- Content.Server/Traits/Assorted/SingerSystem.cs
- Content.Shared/Instruments/SharedInstrumentComponent.cs
- Content.Shared/Traits/Assorted/Prototypes/SingerInstrumentPrototype.cs
- Content.Shared/Traits/Assorted/Systems/SharedSingerSystem.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/Misc/singer_types.yml
- Resources/Prototypes/Traits/skills.yml
A long time ago someone told me "NO IT'S TOO OP, DON'T GIVE HARPIES A DAW". So now I'm letting Harpies blow 10 trait points on having a DAW. You're welcome. Yes I have actually tested this ingame, and it works.
<p>
</p>
</details>
:cl:
- add: Added "Lyre Bird" as a new trait exclusively available to Harpies. It massively expands their ability to play Midis.
> Lyre Birb Trait

- Resources/Prototypes/Entities/Structures/Power/smes.yml
Seriously the power goes out within 2 minute of roundstart on most stations. This is ridiculous. Imagine having battery backups on your station, and they literally cannot provide a power buffer. This increases the power storage of SMES by 15x, going from 8MW of power, to 120MW, which is significantly more in line with reality, and their values in SS13.
:cl:
- tweak: Stations SMES now store 120MW of power, up from 8MW. They should actually do what they are intended to do now.
> Make SMES Not SUCK

- Content.Shared/Damage/Systems/SharedDamageOtherOnHitSystem.cs
- Content.Shared/Projectiles/SharedProjectileSystem.cs
Stops this from happening:
:cl:
- fix: Thrown objects will no longer collide with entities that are laying down(voluntarily or otherwise). This includes objects thrown by space wind, which will now fly over you once you've been critted by floor tiles.
> Flying Objects Ignore Laying Down

- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
- Resources/Prototypes/Entities/Objects/Devices/Circuitboards/computer.yml
- Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
- Resources/Prototypes/Entities/Structures/Piping/Atmospherics/trinary.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/PA/control_box.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml
Needed for antagonistic AI gameplay. Currently any variant of "Antagonistic AI" is extremely limited in their options for harming crew. Traditionally SS13 AIs would have had a larger variety of options for Harming Crew, the most iconic of which was by Plasmaflooding. With this change, AI can "Assist" in setting up Atmos by turning on pumps and configuring gas mixers to provide the station with breathable air. Or a more murderous AI can "Assist" by configuring the air supply to include plasma. 
Also whitelists the Emitters and Singularity Controller for the same purpose. 
The Research Director now starts with a spare AI Upload circuitboard, as well as 4 basic AI law boards in his locker.
I suggest writing it in your server rules whether or not plasmaflooding is acceptable for MALF AI. …
> More AI QOL Stuff

- Resources/Prototypes/Loadouts/Jobs/Command/blueshield_officer.yml
Removes the LoadoutSecurityWeapons tag from the chester, allowing you to pick it alongside a sidearm again (they are limited to picking between a pistol OR the chester right now, which makes no sense)
---
<p>
</p>
</details>
---
:cl:
- tweak: removed LoadoutSecurityWeapons tag from the chester
> BSO Chester Loadout Change.yml

- Resources/Prototypes/ore.yml
This tweaks the ore rates a little for Lava planets, so that they aren't actually completely useless for getting things other than "Shitton of iron". In practice the previous ore rates would get you like, "Two sheets of glass, maybe a sheet of uranium if you were lucky" when two people were mining fulltime. They're still scarce, just not quite that ridiculously scarce.
:cl:
- tweak: Tweaked ore rates for lava planets so that they give more than "Two sheets of silver per 2000 sheets of iron". Ores other than Iron, Gold, and Tungsten are still scarce, just not quite that scarce.
> Tweak Lava Ore Rates

- Resources/Maps/saltern.yml
Saltern's "Generator Room" had an empty Uranium crate, instead of a filled one. This tiny one-line fix replaces the spawn for it with a filled uranium crate. You now have enough materials roundstart to give the station 1 hour and 30 minutes of battery+generator power, which is a completely absurd amount of time available for someone to setup solars(you literally don't even need to setup the supermatter. Saltern is unique among other stations in that it can run on solars alone). 
:cl:
- tweak: Saltern's generator room now correctly spawns with a crate containing uranium fuel. As a reminder, Saltern is unique among all other maps in that it is the only map which can be run on its solars alone. The generators and generous battery backups are there to provide more than adequate time to setup …
> Tiny Saltern Fix

- Content.Server/Shuttles/Components/ShuttleComponent.cs
- Content.Server/Shuttles/Components/ShuttleConsoleComponent.cs
- Content.Server/Shuttles/Systems/ShuttleConsoleSystem.FTL.cs
- Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
- Content.Server/Station/Components/StationBiomeComponent.cs
- Content.Server/Station/Systems/StationBiomeSystem.cs
- Content.Shared/Parallax/Biomes/BiomeComponent.cs
- Content.Shared/Shuttles/Systems/SharedShuttleSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Goddamn do I love Adderall.
This PR lays the entire groundwork needed for the "Glacier Rework", and it does so by fixing every problem I could think of between FTL and StationBiome that was preventing it from being a reality. Essentially, I'm hitting several birds with one stone by refactoring both systems to be a LOT more flexible. You can technically say that this basically is also partly enabling Lavaland maps, since I conveniently included options in the StationBiomeComponent to generate dungeons. Technically a planet map should probably also have a RestrictedRangeComponent added to it so that players can't wander so far from the station that they generate a truly excessive number of entities. 
Yes, this does infact mean you can now run Nukie gamemodes on planet maps. …
> Planet Maps Prep For Glacier Rework

- Resources/Locale/en-US/research/technologies.ftl
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Research/arsenal.yml
This was actually suggested by Goob MRP, and a lot of my maintainers liked the idea. This PR removes the Nonlethal Ammunition research, and makes all non-lethal ammunition into roundstart static recipes for the Secfab. It turns out part of the reason why Secoffs were always so keen on using lethals was because they simply had no way of getting nonlethal ammo from the warden at roundstart. The other "Nonlethal Weapons" that previously shared the research with rubber boolits were instead moved to their respective weapon researches.
:cl:
- tweak: Nonlethal Ammunition research has been removed. Instead Security Techfabs can manufacture rubber bullets at roundstart.
> Remove Nonlethal Ammo Research

- Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/DeltaV/Catalog/uplink_catalog.yml
- Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
- Resources/Prototypes/Nyanotrasen/Catalog/uplink_catalog.yml
- Resources/Prototypes/Roles/Antags/nukeops.yml
- Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
- Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
This brings over the "Telecrystal Rebalance". To make the TC costs more granular, nearly all values for TC costs have been multiplied by 5x, including the starting TC amounts for each type of uplink. Additionally, Nukies no longer spawn with any of their tacsuits, and have had the cost of said tacsuits refunded as 50 additional TC. Finally, since the Commander and Medic no longer spawn with their respective tacsuits, they've been put into the uplink as new bundles(which traitors can buy as well).
I figure its about time the nukies get some love seeing as on MRP they're facing against Security who can buy an N1984 in their loadouts. Next PR I'm probably going to even further mess with the cost of guns by separating out the guns from their magazines, and adding options for buying more …
> Telecrystal Rebalance

- Content.Server/WhiteDream/BloodCult/Runes/Revive/CultRuneReviveComponent.cs
Rune of rejuvenation was trying to heal the group damage type and not the specific damage types resulting in no healing for any brutes, cold, or shock. Changed to the specific types of damage to actually heal. The healing is probably a bit low especially if you get mag dumped or laser'd but it works and can actually revive people now.
---
:cl:
- fixed: Rune of Rejuvenation to actually heal brutes, cold, and shock
> Fixes Rejuvenation Rune to Heal Specific Damage Types Instead of Groups

- Resources/Prototypes/Loadouts/Generic/species.yml
Gives IPCs access to a high capacity power cell on spawn
Allows IPCs to choose a high capacity power cell as a loadout item.
---
---
<p>
</p>
</details>
---
:cl:
- add: High Cap Battery as a loadout item for IPCs
> IPCs Can Take High Capacity Batteries with Loadout

- Resources/Prototypes/Loadouts/Jobs/Command/blueshield_officer.yml
BSO as of now is treated as a purely combatant role, and while it is for the most part, I see it being closer to Corpsman. This PR adds new medical options to the BSOs loadout so that they can keep their charges in good health. It can be debated that this is overturned/power creep, and you're right to an extent. BSO is currently in a weird spot, as a lot of people disagree on how it should function, however, I believe that giving them access to medical items will lock in their position as the guardian/caretaker of command, and will overall be good for their kit and performing their jobs duties. 
BSO is the Corpsman of command, and them having access to high-tier equipment to match that makes sense. The crew monitor is a very good item, yes, but due to the fact that BSO will ONLY be using …
> BSO Paramed Gaming

- Content.Client/DeltaV/CartridgeLoader/Cartridges/NanoChatUiFragment.xaml.cs
- Content.IntegrationTests/Tests/PostMapInitTest.cs
Previously, NanoChat set you to the "center" of your chat box scroll with selecting a new chat. This fixes that.
:cl:
- tweak: NanoChat will now scroll to the bottom of your chat history when selecting a new chat.
> Scroll to Bottom when Selecting a New Chat

- Resources/Prototypes/Catalog/Fills/Crates/syndicate.yml
This updates Surplus bundles to actually contain the correct number of TC to match the TC Rebalance. For instance, 200tc for the standard surplus crate, which contains 250tc worth of stuff.
:cl:
- tweak: Syndicate Surplus Crates are now included in the TC Rework.
> Fix Surplus Bundles

- Resources/Prototypes/Loadouts/Jobs/Security/corpsman.yml
Gives Corpsman the portable crew monitor. It's a criminally underutilized item that more jobs should have access to.
---
:cl:
- add: Corpsman can take portable crew mon
> Corpsman Crew Monitor

- Content.Server/Singularity/EntitySystems/EventHorizonSystem.cs
Makes the singulo stop quantum tunneling through its containment. If this doesn't work and I'm still on vacation beating up nerds in the woods, you need to revert this pr right here: https://github.com/Simple-Station/Einstein-Engines/pull/1619
:cl:
- fix: Singularity shouldn't escape its containment anymore. If it's still escaping containment, do me a favor and revert PR 1619 (Newtonian Singularity)
> Fix Singulo

- Resources/Locale/en-US/loadouts/itemgroups.ftl
- Resources/Prototypes/CharacterItemGroups/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/Loadouts/Jobs/Command/blueshield_officer.yml
Adds a new "Primary Weapon" category for Blueshield Officer, which the Chester rifle is the origin point for. Per discord discussions, this list includes an option to replace the Chester with an energy shield(It's way more fitting for a bodyguard to have an energy shield oddly enough), or to pay extra points to swap it for the new BRDI-R25 rifle. 
<p>
</p>
</details>
:cl:
- add: Added "Blueshield primary weapon" loadout group. His primary selection currently consists of the classic Chester rifle, an energy shield, and an R25.
> Some More BSO Options

- Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
- Resources/Prototypes/Catalog/Fills/Crates/armory.yml
- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Procedural/salvage_rewards.yml
- Resources/Prototypes/Recipes/Lathes/security.yml
- Resources/Prototypes/Research/arsenal.yml
I said I was going to do this previously, so here I am. this adds a few more "Common Handgun" recipes to the Arsenal research, to be manufactured at a security techfab. Currently the list just includes Mk58(available at Tier 1), and N1984, Viper, and Cobra at Tier 2. Most common firearms are manufactured primarily using Aluminium as their main body material, which is (currently) only obtainable by Salvage.
Also adds an option to order the new BRDI-R25 from Cargo. They are somewhat expensive, although not quite to the extreme extent something imported from Sol' would be. Instead they're a highly sought after gun from a manufacturer local to the same region NT operates in and is friendly towards. So more the "Normal" kind of scarcity.
:cl:
- add: Added handgun manufacturing to Arsenal …
> More Gunsmithing

- Resources/Prototypes/Entities/Objects/Tools/welders.yml
Changes the experimental welder a decent amount. Rather than being practically a normal welder with nigh unlimited fuel, it is now a super fast welder with slower self-fueling, and a much lower fuel capacity. Changes advanced industrial welder to make it still a worthwhile item.
:cl:
- tweak: Advanced Industrial welder from 250 capacity to 500
- tweak: Advanced Industrial welder from 1.3x speed to 1.5x speed
- tweak: Experimental welder from 1000 capacity to 200
- tweak: Experimental welder from 1u of welder fuel generated to 0.5u
- tweak: Experimental welder from 1x speed to 2x speed
> Experimental Welder Rework

- Content.Server/NPC/HTN/PrimitiveTasks/Operators/Specific/PickNearbyWeldableOperator.cs
- Content.Server/NPC/HTN/PrimitiveTasks/Operators/Specific/WeldbotWeldOperator.cs
- Content.Shared/Damage/Systems/DamageableSystem.cs
- Resources/Prototypes/DeltaV/Entities/Structures/Windows/tinted_windows.yml
- Resources/Prototypes/Entities/Structures/Doors/Windoors/base_structurewindoors.yml
- Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/coil.yml
- Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
- Resources/Prototypes/Entities/Structures/Windows/window.yml
- Resources/Prototypes/_Nuclear14/Entities/Structures/Windows/windows.yml
- Resources/Prototypes/tags.yml
As requested in Goobstation MRP;
This update allows the weldbot to, _very slowly_, fix specific structures.
To allow a structure to be repaired by a weldbot, apply the "WeldbotFixableStructure" tag to it.
So far, this has been applied to:
- Windows
- Directional Windows
- Grounding Rods
- Tesla Coils
The robot will repair 5 damage per step to structures. In addition, repair speeds of silicon mobs, borgs and IPC's has been lowered a bit.
---
:cl:
- tweak: Weldbots can now fix specific structures, like windows and grounding rods.
> Allow Weldbot to Fix Specific Structures

- Resources/Prototypes/Reagents/medicine.yml
As requested in Goob: https://discord.com/channels/1323488536501944350/1323488538750353442/1343047906114011167
this allows Tricordrazine to heal _very minor_ amounts of radiation poisoning. The use case: I walked past a Borg with a micro-RTG and the medibot won't stop bugging me because it doesn't know it can't help. 
With this change it _can_ help, but it's really only viable for small amounts.
Ordinarily, in these small amounts of damage (10-12 tops), it was a hassle to make appropriate radiation medicine for; a lot of effort for only a tiny problem. This apparently caused annoyance, and this change will both make Tricordrazine a tiny bit more useful and lessen the aforementioned problem.
---
:cl:
- tweak: Tweaked Tricordrazine to heal MINOR amounts of radiation damage. This includes …
> Allow Tricordrazine to Heal Minor Accidental Exposures

- Resources/Prototypes/Entities/Mobs/Player/guardian.yml
Buffs holoparasite and brings it more in line with its inspiration. Currently, holoparasite attacks very slowly but does high damage per hit, regardless they're very weak and tend to die before they can actually take anybody down. With my buff, it makes them do less damage per hit, but WAY faster, dramatically decreasing their TTK. This buff brings them more in line with the fast-hitting barrages of stands (their inspiration), and also makes them actually viable, and worth their price again.
Also for reference, they cost 10tc more then a damn singularity beacon, and currently kill someone slower then a random guy with a crowbar would.
<p>
</p>
This is a holoparasite CURRENTLY
https://github.com/user-attachments/assets/64f724e8-7d02-4047-bd8b-78d05 …
> Holoparasite Buff

- Resources/Prototypes/Entities/Structures/Doors/airlock_groups.yml
Description.
A fix for [this issue](https://github.com/Simple-Station/Einstein-Engines/issues/1872)
Fixed bug of the painted roboticist airlock displaying the windowed counterpart instead of the standard one.
---
https://github.com/user-attachments/assets/fbe4c85f-c876-4e29-9c8d-cf95314e737f
</details>
---
:cl:
- fix: Fixed bug of the painted roboticist airlock displaying the windowed counterpart instead of the standard one.
> Bug Fix: Fix Roboticist Airlock Sprite Error

- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/physical.yml
Makes a lot of disabilities give more points (based off community and personal opinions), and makes some very strong traits cost more points.
:cl:
- tweak: Narcolepsy gives 6 points instead of 2
- tweak: Pacifist gives 8 points instead of 6
- tweak: Muted gives 6 points instead of 4
- tweak: Sluggish gives 5 points instead of 3
- tweak: Snail Paced gives 8 points instead of 5
- tweak: Blood Deficiency gives 6 points instead of 5
- tweak: Hemophilia gives 4 points instead of 2
- tweak: Clumsy gives 4 points instead of 1
- tweak: Bad knees gives 5 points instead of 3
- tweak: Will to live costs 3 points instead of 1
- tweak: Tenacity costs 4 points instead of 3
- tweak: Steadfast costs 6 points instead of 4
- tweak: Bionic Arm costs 10 points instead of 8
- tweak: Bionic leg costs 8 points …
> Trait Cost Balancing

- Content.Client/Administration/UI/Bwoink/BwoinkControl.xaml.cs
- Content.Client/Flight/FlyingVisualizerSystem.cs
- Content.Client/Weather/WeatherSystem.cs
- Content.Server/Body/Systems/BodySystem.cs
- Content.Server/Doors/Systems/AirlockSystem.cs
- Content.Server/Ghost/GhostReturnToRoundSystem.cs
- Content.Server/Ghost/GhostSystem.cs
- Content.Shared/Cuffs/SharedCuffableSystem.cs
- Resources/Locale/en-US/ghost/ghost-respawn.ftl
- Resources/Locale/ru-RU/ghost/ghost-respawn.ftl
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
- Resources/Prototypes/Entities/Structures/Walls/grille.yml
- Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
- Resources/Prototypes/Recipes/Lathes/mech_parts.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
Ports the following PRs:
https://github.com/WWhiteDreamProject/wwdpublic/pull/271
https://github.com/WWhiteDreamProject/wwdpublic/pull/282
https://github.com/WWhiteDreamProject/wwdpublic/pull/255
https://github.com/WWhiteDreamProject/wwdpublic/pull/254
https://github.com/WWhiteDreamProject/wwdpublic/pull/246
https://github.com/WWhiteDreamProject/wwdpublic/pull/223
https://github.com/WWhiteDreamProject/wwdpublic/pull/220
https://github.com/WWhiteDreamProject/wwdpublic/pull/219
https://github.com/WWhiteDreamProject/wwdpublic/pull/213
This is a rather huge variety of fixes to be honest.
:cl: White Dream
- fix: Fixed airlock opening and closing visuals
- fix: Fixed Weather spamming infinite sounds.
- fix: Cockroaches no longer spam organs when stepped on.
- fix: Fixed the timer on the Return …
> Miscellaneous Fixes From White Dream

- Resources/Prototypes/Entities/Objects/Misc/carpets.yml
- Resources/Prototypes/Recipes/Construction/Graphs/furniture/curtains.yml
- Resources/Prototypes/Recipes/Construction/Graphs/furniture/tables.yml
- Resources/Prototypes/Stacks/floor_tile_stacks.yml
Stolen from https://github.com/Fansana/floofstation1/pull/152, courtesy of cynical24. When you craft a curtain or make a table into a _fancy_ table, it doesn't take the entire stack of carpet. This should hopefully stop me from having to return to the HoP to ask for another 10 carpet.
---
---
<p>
</p>
</details>
---
:cl:
- tweak: you don't use the entire stack of carpet now when crafting colored curtains or fancy tables.
> Crafting Curtains and Tables No Longer Consumes Entire Stack

- Resources/Prototypes/Entities/Structures/Storage/ore_box.yml
- Resources/Prototypes/_Lavaland/Entities/Objects/Materials/ore.yml
- Resources/Prototypes/_Lavaland/Stacks/Materials/materials.yml
Apparently the lavaland ore crates are supposed to have an ore magnet, but this didn't work because they're missing something from the ore bags. So this fixes that. Also I made sure the lavaland's ores actually have the same naming conventions as our regular ores.
:cl:
- tweak: Ores mined from lavaland now have names matching their real-world counterparts.
- fix: Fixed the lavaland ore crates not having working ore magnets.
> More Lavaland Fixes

- Content.Server/Destructible/DestructibleSystem.cs
- Content.Shared/Projectiles/SharedProjectileSystem.cs
- Resources/Locale/en-US/weapons/throwing/throwing.ftl
- Resources/Locale/ru-RU/weapons/throwing/throwing.ftl
* embed children
* locale
* fix
* Update Resources/Locale/ru-RU/weapons/throwing/throwing.ftl
* // WWDP MY BELOVED
This is a port (and general cleanup of) https://github.com/WWhiteDreamProject/wwdpublic/pull/278
Plus clearing a bunch of compiler warning causing things, and also a fix for one of our Heisentests. This PR mainly fixes issues with embeddable projectiles being potentially unintentionally destroyed when the thing they are embedded in gets destroyed. Which can be disastrous for example if my energy sword embeds into a wall, and also destroys that wall, which destroys my precious energy sword...
:cl: Spatison
- fix: Embeddeable projectiles are no longer always destroyed when the thing they are embedded in gets destroyed. Energy Sword throwing enthusiasts may rejoice now that …
> Embeddable Projectile Fixes (Courtesy Of White Dream)

- Resources/Prototypes/Entities/Objects/Specific/revolutionary.yml
Add a two second cooldown on the Revolutionary Manifesto's secondary use (the purely cosmetic one) to not make it cause chat spam.
I made this change from web and have NOT tested it yet (unless I checked the checkbox below in the TODO section!
---
---
:cl:
- tweak: Tweaked rev manifesto to not spam chat anymore
> Rev Manifesto Inhand Use Cooldown

- Content.Shared/CCVar/CCVars.Announcer.cs
- Content.Shared/CCVar/CCVars.Atmos.cs
- Content.Shared/CCVar/CCVars.Customize.cs
- Content.Shared/CCVar/CCVars.Events.cs
- Content.Shared/CCVar/CCVars.Jetpack.cs
- Content.Shared/CCVar/CCVars.Shuttle.cs
- Content.Shared/CCVar/CCVars.StationGoals.cs
I can't believe we never cleaned these up. Yea so our codebase made an astoundingly fucking poor first impression on BPL during their huge playtest, and most of these CVars were to blame. In particular is the godawful Ramping Event Scheduler having "Murder the station with ventcritters every 10 seconds at the 30 minute mark" as its settings. 
:cl:
- tweak: Disabled Monstermos Tile Ripping by default.
- tweak: Default settings for Ramping Event Scheduler no longer throws "Ventcritters every 10 seconds, 30 minutes into the round".
> More Tolerable Default CVars

- Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
- Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
- Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
- Resources/Prototypes/Entities/Objects/Specific/Research/disk.yml
- Resources/Prototypes/Entities/Structures/Specific/oracle.yml
- Resources/Prototypes/Procedural/salvage_loot.yml
Buffs to Salvage Loot
Minor Buff to Oracle loot
Added Radiation Medkits to Radiation Lockers
Why? 
Well Salvage doesn't really make any real money and the station suffers if there's no cargo techs. And I hate receiving a single 1000 research disk from salvage like it's worth something. 
Oracle buffed (not really shit should be rare af) because at the point where you're doing multiple Tier 3s the cost get real silly high.
Radiation Lockers should always have had Rad Medkits.
:cl:
- add: Higher amount variants of Research Disk and Spesos
- add: Increased the amount of Research and Spesos Salvage can randomly find
- add: Added 20000 Disk to Oracle's Loot Table (Super Rare)
- add: Added Radiation Medkits to Radiation Lockers
> Salvage Wreck Loot Buff + a Little Extra

- Resources/Prototypes/Entities/Mobs/NPCs/miscellaneous.yml
Allows Laser Raptors to be Butchered from the Menu, QoL for Logistics so they can get Laser Eyes faster.
I filled the indents this time 100%
:cl:
- add: Butchering to Laser Raptors
> Butcherable Laser Raptor

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
- Content.Shared/Maps/ContentTileDefinition.cs
- Content.Shared/Storage/Components/SharedEntityStorageComponent.cs
This fixes a few issues with SWV5, albeit what I can fix for now until I have completed work on the Matrix Airflow System.
:cl:
- fix: Fixed some bugs with Space Wind related to lockers causing massive air flow spikes,
- fix: Fixed space wind not being calculated correctly for stations which get gravity from their planet, such as Glacier.
- fix: Fixed an issue where Space Wind wasn't respecting the cosmic speed limit of 30 meters per second.
> Small Atmos Fixes

- Resources/Prototypes/Actions/psionics.yml
- Resources/Prototypes/Entities/Objects/Misc/kudzu.yml
Changes Shadeskip fog to only last 30 seconds, and increases its area of effect to 2.5 tiles.still occasionally spawns Trees, Crystals and Portals (the only thing that needs flashes for removal now).
---
---
Single use of Shadeskip with new area centered on Aghost Andy
</p>
</details>
---
:cl:
- tweak: Shadeskip fog now lasts 30 seconds, and has an increased area of effect.
> Shadeskip Changes

- Resources/Maps/saltern.yml
My mappers somehow all at once decided that removing all shuttles was a good idea. This caused problems because the mining shuttle sometimes doesn't dock to the station correctly, and when it happens a shuttle is needed to go retrieve it. Making it so that cargo doesn't have either cargo shuttle or pathfinder makes this impossible. @Ichaie 
@Mike32oz @OldDanceJacket make sure that in future map updates, that your maps have at least one pilotable shuttle, either the cargo shuttle or the Pathfinder. Ideally, you should be using the new Shuttle Spawning Airlocks, such as AirlockExternalGlassShuttlePathfinderFilled
These airlocks spawn a ship already docked to the station, similar to how the escape pods work. 
Also make sure that the doors to Supermatter cores are using High Security …
> Saltern Fixes

- Resources/Prototypes/_EE/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Some more tweaks to the R25 stats after getting more feedback about it. (Shoutout to all the forks that decided to comment it out instead of actually giving feedback to their upstream?...)
:cl:
- tweak: Tweaked the R25's stats, it now has a 3 round burst instead of a 5 round burst.
- fix: Fixed an issue where the R25 was inaudible unless you were the one firing it.
> Tweak R25 Again

- Resources/Prototypes/Loadouts/Jobs/Command/blueshield_officer.yml
This PR makes the following changes:
- Reduce the cost of the Handheld Crew Monitor in the BSO's Loadout from 6 to 2.
- Add the BSO CQC Manual, which was previously unobtainable, to the BSO's loadout at a cost of 8, it currently does not occupy a weapon category.
The monitor I believe has always been overpriced. Your main job as a BSO is to keep command safe, so it should not be this expensive to be able to easily check on their status and location if they do not forget to turn on their suit sensors, and there is plenty of counterplay to it via emps, jammers, or sabotaging the crew monitoring server or its power supply. I am doing this in the same PR as the manual because the price change is also relevant to that. And yes, I know this means you can get a crewmon + BRDI now, but you still …
> Add the BSO CQC Manual to Their Loadout and Make the Crew Monitor Cheaper.

- Resources/Prototypes/WhiteDream/Entities/Objects/Structures/Cult/airlock.yml
Cult doors would launch people at FTL speed, they exerted 13,000 Newtons of force on non-cultists who touched them. Which while sometimes hilarious, is enough to send people through walls. This PR sets it to a more reasonable number of 300 Newtons, which is enough to throw a standard human about 2 tiles from the door.
:cl:
- tweak: Tweaked cult doors so that they don't launch people at luminal speeds.
> Fix Cult Doors

- Resources/Prototypes/_Goobstation/Entities/Clothing/Eyes/glasses.yml
The medsecglasses have been renamed to blueshield glasses, with an updated description.
They also now act as a diagnostic hud, so the status of borgs and IPCs can be monitored.
Firstly, the name looks quite odd next to for example the corpsman glasses, especially if you want to try to fit the word diagnostic in there too, and as these glasses are only used by the BSO, and have the sprite to match, naming them as such seems better.
As for why the diagnostic ability is being added at all, the blueshield is supposed to protect command from threats, and both command AND threats could be IPCs, and borgs can also be threats if their laws are compromised. Being able to identify their integrity at a glance  to decide your priorities, both for who to heal/shield and who to shoot, should be a nice …
> Rename the Medsecglasses to Blueshield Glasses and Add a Diagnostic Hud to Them.

- Content.Server/PowerCell/PowerCellSystem.Draw.cs
- Resources/Prototypes/_EE/Entities/Clothing/SolAlliance/SAN/Modsuits/CSA-85x.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/Back/modsuit.yml
Power cell draw wasn't tick invariant, so batteries on this codebase were being drained anywhere from 30 to 60x faster than people expect, depending on server performance. This was notably something that severely effected MODSuits, which can now enjoy a battery lifespan of around 30 minutes. But it's also a big deal for IPCs.
Closes https://github.com/Simple-Station/Einstein-Engines/issues/1956
:cl:
- fix: Batteries no longer drain power 30 to 60 times faster than physics states. This is particularly a large buff to IPCs and MODSuits, who both no longer have to deal with batteries lasting an absurdly short amount of time. 
- tweak: Solarian Modsuit now provides protection from cold.
> Power Cell Draw Fixes

- Content.Server/Weapons/Ranged/Systems/GunSystem.cs
- Content.Shared/Weapons/Ranged/Components/GunComponent.cs
- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
This Un-hardcodes casing ejections, making it so that on a per-gun basis, guns can change how much force they throw spent casings with.
:cl:
- tweak: Guns can now individually change how much force they eject spent casings with.
> Un-Hardcode Casing Ejections

- Resources/Prototypes/DeltaV/Catalog/VendingMachines/Inventories/salvage_points.yml
Salvage specialist felt a bit too tiring for me, felt like I just kept working and working without reason, so I decided to improve it, now salv can buy their own food, with their own microwave that they can build, along with buying a ore bag of holding for 6k points.
We offer no refunds if the microwave blows up.
---
---
<p>
</p>
</details>
---
:cl: Diggy
- add: Salvage can now buy food, medkits, advanced medkits, a ore bag of holding for 6k and the most important part, you can now build a microwave.
> Salvage Vendor Improvements

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/Oni.yml
- Resources/Prototypes/Traits/species.yml
Oni's melee buff description was wrong in the guidebook, so it's been re-adjusted (to fit the guidebook).
Adjusted Oni's unique traits so it's balanced properly.
Buffed, made Oni's unique traits cheaper because they're niche changes that simply changed their brute values around.
:cl:
- tweak: Tweaked values on Oni melee bonus to correctly reflect the guidebook
- tweak: Tweaked Blademaster and Spearmaster to mirror Default
- tweak: Buffed Oni's unique traits to be cheaper
- tweak: Buffed Weapon Generalist to 30% so it's not just a nerf
> Oni Correction

- Content.Server/Atmos/EntitySystems/FlammableSystem.cs
- Content.Server/EntityEffects/Effects/FlammableReaction.cs
- Content.Server/IgnitionSource/IgnitionSourceSystem.cs
BEFORE:
AFTER:
THIS WAS 2U OF PHLOG IN BOTH.
> Fix Tiny Fires Ashing People

- Content.Shared/Access/Components/AccessReaderComponent.cs
- Content.Shared/Access/Systems/AccessReaderSystem.cs
- Resources/Prototypes/Entities/Mobs/Player/ipc.yml
IPC panels now work simularly to borg panels, as follows:
You can unlock/lock them instantly if you have the requires access.
Unlike borgs, IPCs start unlockable by anyone, but this can be changed with an access config.
IPCs can ALWAYS unlock/lock their own panel, regardless of the access requirement.
After it is unlocked, you can then use a screwdriver to ACTUALLY open/close the panel.
---
<p>
[Link to a video in contribution-general (file too big to attach)](https://discord.com/channels/1218698320155906090/1218698321053356060/1351936832434077787)
</p>
</details>
---
- add: You can now add an access requirement to an IPC's maintenance panel using an access configurator, though an IPC can always unlock their own panel.
- tweak: …
> Rework the IPC Maintenance Panel.

- Content.Client/Verbs/VerbSystem.cs
- Resources/Prototypes/Entities/Effects/puddle.yml
- Resources/Prototypes/Entities/Structures/Wallmounts/surveillance_camera.yml
Rather than doing goofy hacks we just use what sprites are near the mouse.
https://github.com/space-wizards/space-station-14/pull/31792
<p>
</p>
</details>
---
:cl:
- tweak: Make context menu uses spritetree
> Make Context Menu Uses Spritetree 

- Content.Server/Hands/Systems/HandsSystem.cs
- Content.Shared/Hands/HandEvents.cs
- Content.Shared/Movement/Pulling/Components/PullerComponent.cs
- Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
- Resources/Locale/en-US/_white/grab/grab.ftl
This PR nerfs the ability to stun somebody by throwing them after hard-grabbing them, it does this in 2 ways:
1. Stamina damage goes from 120 to 100, Which I am told by eagle will knockdown as opposed to paralyzing.
2. The big one, after you INITIATE your grab on somebody, a 6 second cooldown starts before you can throw them. This cooldown does not reset if you upgrade your grab, and starts as soon as you soft-grab somebody (or instantly hard-grab, for martial artists.)
This is done because right now melee fights involving martial artists are quite bland and simple: Whoever can get the opponent in a hard grab and throw them first, wins, because this instantly stamina crits them, allowing you to cuff them. This completely negates the unique combos/differences between the fighting styles, …
> Throwing Nerfs: Less Stamina Damage, Cooldown After Grabbing Before You Can Throw.

- Resources/Prototypes/Traits/physical.yml
Moves steadfast back to a 4 point cost, disables bionic leg until cybernetics are properly handled as bodyparts
:cl:
- tweak: steadfast is now 4 points
- tweak: Bionic leg is disabled for now
> Steadfast/Bionic Leg

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Entities/Mobs/Species/harpy.yml
- Resources/Prototypes/Entities/Mobs/Species/moth.yml
- Resources/Prototypes/Traits/species.yml
Makes some changes to moths to hopefully make them a bit more mechanically interesting. Changes moths' cold slowdowns from the default 80/60/40% speed to 85/70/55% (on top of their lower thresholds) and gives them inherent 50% temperature protection (equivalent to beanies). Also adds True Flight, a 5-point trait exclusive to small moths that grants access to harpy-style flight.
---
:cl:
- add: Added True Flight, a moth-exclusive trait that grants temporary flight
- tweak: Gave moths 50% temperature protection
- tweak: Reduced severity of slowdown due to cold on moths
> Moff Buffs

- Content.Server/Silicons/Laws/SiliconLawSystem.cs
- Resources/Locale/en-US/station-laws/laws.ftl
- Resources/Prototypes/DeltaV/siliconlaws.yml
- Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/silicon-laws.yml
Adds the "borgs must obey AI" law 0 so that a rogue AI is far more dangerous. Also changes the default lawset for AI to Augustine, and slightly increases the chances of an ion storm.
---
:cl:
- add: Borgs now have a law 0 dictating they must follow the Station AIs commands
- tweak: Station AI now spawns with NT Default rather than Asimov
- tweak: Slightly increases the chances of ion storm
> AI Absolute Control

- Content.Server/Traits/TraitSystem.Functions.cs
- Resources/Prototypes/Traits/physical.yml
This PR marks the return of "Speed Legs Trait" by adding a new class of trait function for replacing bionic limbs. To be honest this actually needs to be done via Loadouts but whatever. I also made Bionic Arm replace your arm with an actual JOL-Arm. Which means that players can now use surgery to remove the bionics you obtained in character creation.
<p>
</p>
</details>
---
:cl:
- add: Added back Bionic Legs. The trait has been reworked so that it makes you start with one of your legs replaced with an actual speed legs cyberware. 
- add: Bionic Arm now gives you an actual bionic arm. Have fun mugging people for their cyberware so you can have a collection of fancy bionic limbs.
> Return Of Bionic Leg

- Resources/Prototypes/_Nuclear14/Entities/Structures/Misc/floradesert.yml
Adds proper PhysShapeAabb boundaries and offsets for N14 trees: N14 Cactus, N14 Yucca Tree, N14 Bald Tree, and all childs.
Need this for decorating up Setrina.
Images under media.
Closes #2025
---
---
<p>
</p>
</details>
What you will see in the post is that some have moved a few tiles over. That is because of the offset being re-set. So any maps that used them will have to be remapped. When asked ODJ about if any are mapped on EE. They said they aren't so I guess we be fine.
---
:cl:
- tweak: Proper offsets & BB for N14 Trees. Remap if they already were mapped.
> Fix Improper Offset & BB for N14 Trees

- Content.Shared/Gibbing/Systems/GibbingSystem.cs
Fixed Pull Request.
The previous pull request only contained conversion of basecontainer to list in on of the switch cases. Changed to both to keept it consistant.
This relates to closed PR #2040 
as well as Gibbing Skeleton Crash Bug #1987 
BaseContainer content could be changed mid loop by events.
---
---
:cl:
- add: BaseContainer ToList for both Switch cases using it.
> Skelly Gib Crash #1987 Pr Fix for Pr #2040

- Resources/Prototypes/Actions/psionics.yml
As it turns out, Healing Word can actually revive people. If we're giving it roundstart as a trait, that should probably be removed.
---
:cl:
- tweak: Made Healing Word no longer revive
> Disable Healing Word Revive

- Resources/Prototypes/Entities/Structures/Furniture/Tables/operating_table.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Recipes/Construction/Graphs/furniture/bed.yml
- Resources/Prototypes/Recipes/Construction/furniture.yml
- Resources/Prototypes/_Shitmed/Entities/Objects/Devices/Circuitboards/Machine/production.yml
- Resources/Prototypes/_Shitmed/Recipes/Lathes/electronics.yml
The operating table is currently a machine that requires a frame and a board to craft.
This is a table. Why does it need this? Why does it have the same cost as an autodoc?
It now instead is buildable from the G menu, for the cost of 5 steel and 2 plastic.
Maints surgeons rejoice!
---
<p>
</p>
</details>
---
:cl:
- tweak: operating tables can now be assembled from the G menu for the cost of 5 steel and 2 plastic
> Makes Operating Table Buildable From G Menu Instead of Being a Machine

- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
The EG-4 Energy revolver has been buffed in several ways:
Firerate 1.5 > 2.5
Projectile Speed 25 > 37.50
Available Shots 8/18 > 10/20
Recharge rate 22 > 50
Recharge pause 0 > 5 [Nerf] (Means after you stop shooting for 5 seconds, it takes 20 seconds to recharge) 
This is done because as a very expensive loadout exclusive weapon, it should not be outclassed by cheaper and printable (arsenal t1) weapons like the PDW-9, which has a superior fire-rate AND damage, even if that weapon does not self recharge.
---
- tweak: The EG-4 Energy Revolver's fire-rate, projectile speed, power use, and recharge rate have been buffed, however a 5 second delay after shooting the weapon has been added before the weapon actually begins to self recharge.
> Buff the EG-4 Energy Revolver

- Content.Shared/Blocking/BlockingSystem.cs
When trying to raise your shield, it is only prevented if the mob you share a tile with actually can be collided with physics wise.
This makes it so that an IPC trying to raise their shield is not prevented from doing so by their own brain.
Also made it so only the server sends the tile is blocked popup, to prevent it being spammed several times.
---
- fix: IPCs are no longer prevented from raising their shield due to the tile being blocked by their own brain.
- fix: If you attempt to raise your shield but get blocked by another mob, you will now only get one popup indicating this.
> Shield Blocking/Raising Fixes

- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/Loadouts/Generic/items.yml
- Resources/Prototypes/game_presets.yml
Decreases weights on various animal spawn events so that interesting stuff actually happens again, removes pAI from loadout so having one is actually cool and there aren't 5 zillion ghost roles, makes greenshift vote only so it can be used for events but doesn't make rounds boring by getting a greenshift with no admins on, makes hellshift more violent (hopefully), and adds a roundstart event for changelings so they can actually spawn.
---
:cl:
- add: Changelings can now spawn as a game mode. don't know why they couldn't before.
- remove: Greenshift can no longer randomly happen; it has to be voted for.
- remove: No more loadout pAIs
- tweak: Animal spawn events are rarer
- tweak: Random Sentience event is rarer
- tweak: Hellshift should be more hellish
> Misc Changes

- Content.Server/Flight/FlightSystem.cs
- Content.Shared/Flight/FlightComponent.cs
- Content.Shared/Flight/SharedFlightSystem.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Body/Parts/harpy.yml
- Resources/Prototypes/Entities/Mobs/Species/harpy.yml
- Resources/Prototypes/Entities/Mobs/Species/moth.yml
- Resources/Prototypes/Traits/species.yml
Rebalances flight for both harpies and moths to make more sense and be more distinct between them. Even when not flying, both harpies and moths now move slightly faster while weightless than while walking under gravity. Both can also now move during the doafter to take off. Moths additionally gain weightless friction which improves their turning ability while weightless. Moth flight was tweaked to no longer block your hands but give a significantly smaller speed boost to compensate (20% as compared to 40% for harpies). (This was sort of the original idea since moths aren't realistically using their arms to fly.) The requirements for the True Flight trait have also been changed to be based on weight instead of size, allowing for a bit more freedom in body type and opening up potential …
> Moff Buffs 2 & Harpies

- Content.Server/Clothing/Systems/LoadoutSystem.cs
- Content.Shared/Clothing/Loadouts/Systems/SharedLoadoutSystem.cs
- Content.Shared/_EE/Contractors/Systems/SharedPassportSystem.cs
Fix the passport not spawning when your loadout replaces your bag by waiting for loadouts to be applied first
---
:cl:
- fix: fix passports not spawning when your loadout replaces your bag
> Delay Passport Spawn so It Isn't Placed in a Deleted Bag

- Resources/Prototypes/Entities/Mobs/Player/silicon_base.yml
Title:
Heat damage multiplier: 2 > 1
Shock damage Multiplier: 2.5 > 2
While I get that in terms of UTILITY, IPCs are in a powerfull state, they suck at combat. EMPs, double heat, 2.5x shock, and now a dedicated ion damage type is being added to further nerf IPCs in combat, so this is going to become neccesary.
The new modifier set is still a net negative, but nowhere near as severe as it was before.
---
- tweak: Tweaked IPC's damage resistances to no longer take double heat damage, and slightly reduce their shock weakness.
> Tweak IPC's Damage Resistances to Reduce Their Extreme Weaknesses

- Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/dogs.yml
I thought it was weird that foxes and dogs can't track scents like Vulpines, so I fixed it. That's all there is really. I'm just surprised this wasn't done when Vulpines initially got the ability, it just makes sense.
This makes it so every dog and fox have the ability to track scents when controlled by a player. This includes Laika, Ians, Renault, Siobhan, Waltuh, and Cerberus (since it extends MobCorgi), as well as all foxes and dogs purchased from cargo.
:cl: PsychoLogik (musicman928)
- tweak: Dogs and Foxes can now track scents (Cerberus included)
> Let Foxes and Dogs Track Scents

- Resources/Prototypes/Body/Prototypes/ipc.yml
- Resources/Prototypes/Entities/Objects/Specific/Robotics/mmi.yml
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgeries.yml
Fixes IPCs having their brains 'wiped' upon being gibbed and allows IPC brains to be surgically removed and inserted.
(I think what was happening was that you were never considered to be controlling the posibrain since it wasn't tagged as a brain?) This incidentally happened as part of me trying to allow you to put MMIs in IPCs, so look forward to that.
---
<p>
https://github.com/user-attachments/assets/8e237104-9f2d-402a-a65b-e1052ce6bae1
You can see the lights on the freshly liberated posibrain indicating that it's active.
</p>
</details>
---
:cl:
- fix: Fixed IPCs losing control of their brain when gibbed
- fix: Fixed IPC brains being unable to be surgically inserted/removed
> IPC Brain Fixes

- Resources/Prototypes/Traits/species.yml
This PR changes the speed modifier for Moth Flight from 1.09 to 1.2 (adding up to an effective ~30% increase over walking with the base moth weightless modifier, over the 20% from before) 
Moths have a trait called true flight which costs 5 points
to take it in the first place you need to be at most 60kg
It essentially gives you harpy flight (moth version)
A PR was made some time ago that changed both the moth flight and harpy flight
What you need to know is that harpies get an effective ~60% speed boost while flying, and handslots taken
Moths however, can use their handslots and also get some friction for sharper turns BUT their effective movement speed increase is only ~20% (By effective increase I mean combining weightless speed buff, flying speed buff, and in the case of harpies, …
> Buff Moth Flight Speed

- Resources/Prototypes/CharacterItemGroups/Generic/languageGroups.yml
- Resources/Prototypes/Traits/languages.yml
This PR removes the limit to how many basic language traits you can take, reduces the cost of sign language from -2 to -1 and ensures that you cannot take more than 1 accent from the accent traits. (Previosly, when new accents got added, the bunch with german, french, spanish, italian and russian, they weren't added to the character item group that makes it so you can only take 1, so I added them)
---
:cl:
- tweak: Reduced sign language cost from -2 to -1
- tweak: Removed the limit on how many language traits you can take
- fix: Made sure that you cannot take more than 1 accent trait
> Tweak Language Stuff

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Server/_EE/Contractors/Systems/EmployerSystem.cs
- Content.Server/_EE/Contractors/Systems/LifepathSystem.cs
- Content.Server/_EE/Contractors/Systems/NationalitySystem.cs
- Content.Shared/Roles/JobPrototype.cs
- Content.Shared/_EE/Contractors/CCVars/CCVars.Contractors.cs
- Content.Shared/_EE/Contractors/Systems/CharacterRequirements.Profile.cs
- Content.Shared/_EE/Contractors/Systems/SharedPassportSystem.cs
- Resources/Prototypes/Loadouts/Generic/outerClothing.yml
- Resources/Prototypes/Loadouts/Jobs/Medical/uncategorized.yml
- Resources/Prototypes/Roles/Jobs/Science/borg.yml
Some coats and scrubs in loadout are branded with specific corporation logo's.
This PR restricts specifically those items to the employers that they are from.
Note that we have coats from other companies currently not listed as available employers too. Perhaps we should consider adding them?
This PR now also includes CCVars that can disable a part, or the entirety, of Contractors for downstreams that prefer free-form RP over gameplay.
While I was at it, I made it so that AI and Borgs don't get Passports.
---
:cl:
- tweak: Restricted some corporate jackets and scrubs to that specific corporation.
- tweak: Downstreams can now disable Contractors entirely or partially if they prefer freeform-rp over gameplay facilitating RP
- tweak: Station AI and Borg are no longer people and don't get …
> Coat and Scrubs Restricted to Respective Employers

- Content.Client/Light/RgbLightControllerSystem.cs
- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Client/Lobby/UI/LoadoutPreferenceSelector.xaml.cs
- Content.Server/Traits/TraitSystem.cs
- Content.Shared/Traits/Prototypes/TraitPrototype.cs
Mfw a downstream fixes things only for themselves, leaving me to hear hundreds of complaints constantly about bugs that I don't have the time or manpower to fix upstream. 
:cl:
- fix: Fixed an issue that prevented players from saving item customizations if they didn't have enough loadout points to buy the item a second time. 
- add: Traits can now define the order in which they are applied. 
- fix: Fixed RGBee pushie not working.
> Various Bugfixes (Mostly Traits System)

- Resources/Prototypes/Loadouts/Generic/outerClothing.yml
Just a small fix, one of the jackets had the wrong item ID.
> Small TCFL Loadout Fix

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Shared/Clothing/Loadouts/Prototypes/LoadoutPrototype.cs
- Content.Shared/Customization/Systems/CharacterRequirements.Profile.cs
- Content.Shared/Prototypes/CharacterItemGroupPrototype.cs
- Content.Shared/Traits/Prototypes/TraitPrototype.cs
- Resources/Prototypes/DeltaV/Traits/neutral.yml
- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/inconveniences.yml
- Resources/Prototypes/Traits/neutral.yml
This PR gently reworks the traits and loadouts system to where both systems have a new Datafield for "Slots", which declares how many selections the trait/loadout occupies. The actual implementation of these differs between the two, since Traits has an actual selection limit, while Loadouts do not(but instead respect CharacterItemGroups). In both cases, Slots are defaulted to 1, and can be omitted in most cases.
Where this shines particularly is in Traits, where it serves as a new second line for trait balancing. Traits such as Accents, which are completely worthless, otherwise would never be taken at all since they compete with other traits for Opportunity Cost. Conversely, there's only so many points we can increase a powerful trait to, (literally, they cannot cost more than the current …
> Loadout And Trait Slot Cost

- Resources/Prototypes/CharacterItemGroups/Generic/languageGroups.yml
- Resources/Prototypes/Traits/languages.yml
- Resources/Prototypes/_EE/Traits/languages.yml
This PR Redefines the max items from the basic language item group (1) BUT makes it so that EVERY SINGLE LANGUAGE TRAIT takes up 0 slots in that item group, letting you effectively take all the languages if you have enough space.
---
:cl:
- tweak: Made every single language trait take up no slots in their defined max items limit, effectively letting you take unlimited languages,  so you can become the man himself, John Language. (FOR REAL THIS TIME.)
> The Creation Of John Language (Removal of Language Limit)

- Content.Server/Psionics/PsionicsSystem.cs
- Content.Shared/Psionics/Glimmer/GlimmerSystem.cs
Fixes two bugs with Psionics, namely that the "Roller Exempt" psionic variants were infact still able to roll new powers. Now the Roller Exemption cuts them off completely from generating Potentia. I'll probably revisit this exit at a later date if I come up with some alternative uses for Potentia.
I also fixed a bug where probers would lock glimmer into one place, rather than cause glimmer to steadily increase towards a given equilibrium point(vs. the current linear decay rate).
:cl:
- fix: Fixed a bug where Probers were locking glimmer at a set number.
- fix: Fixed a bug where Elementalists could still roll for new powers.
> Fix Minor Psionics Bugs

- Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
Fix the office chair sprite overlapping the character when facing south.
---
<p>
</p>
</details>
---
:cl:
- fix: Fix the office chair sprite overlapping the character when facing south
> Fix Office Chairs

- Resources/Maps/hive.yml
There was some invalid configurators left behind in the YML and I was only made aware of them shortly beforehand. They crash the server pretty hard. God, I love mapping issues.
> Hive Bugfix

- Content.Client/Entry/EntryPoint.cs
- Content.Client/Lobby/LobbyUIController.cs
- Content.Client/Nyanotrasen/Mail/MailSystem.cs
Removed RA0032 warnings, 
They triggered when a dependency already exist with a different name in a parent class.
---
:cl:
- add: removed references where a reference already existed
- tweak: Tweaked the names of old refences to match the existing reference.
> RA0032 Warning Fix. Reference to Type Already Exist.

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Lever/lever.yml
NERF MOSIN BUFF CHESTER
https://discord.com/channels/1218698320155906090/1218698321053356060/1360055663426015233 message link for media
:cl:
- tweak: Mosin damage buff nerfed to 1.5x, and melee damage buffed slightly too (it has a bayonet)
- tweak: Chester now does 1.65x damage
> Mosin Nerf & Chester Buff

- Content.Client/Lobby/UI/LoadoutPreferenceSelector.xaml.cs
- Content.Client/Lobby/UI/TraitPreferenceSelector.xaml.cs
- Content.Shared/Customization/Systems/CharacterRequirements.Logic.cs
- Resources/Locale/en-US/customization/character-requirements.ftl
I like doing stupid stuff with UI
---
<p>
I can't take a picture of tooltip, so I got this through a video
</p>
</details>
---
:cl:
- tweak: Loadouts' and traits' tooltips are much easier to read and look better (and cooler of course)
> Cooler More Readable Loadout Tooltips

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Server/Traits/TraitSystem.cs
- Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
- Resources/Prototypes/Species/human.yml
Adds a datafield for Species to define having bonus trait points or penalty trait points. Currently only used by Human because they have literally nothing. But you could for example make a particularly "powerful' species such as Oni have negative bonus trait points.
<p>
Felinid(Default 10 points):
Human: (+2 trait points)
</p>
</details>
:cl:
- add: Humans now have +2 bonus trait points. It's also possible now for "overpowered" species to have fewer trait points, although this is not currently used.
> Bonus Traits

- Resources/Locale/en-US/_Impstation/markings/tattoos.ftl
- Resources/Prototypes/Entities/Mobs/Customization/Markings/wrist.yml
- Resources/Prototypes/_Impstation/Entities/Mobs/Customization/Markings/misc2.yml
- Resources/Prototypes/_Impstation/Entities/Mobs/Customization/Markings/scars.yml
- Resources/Prototypes/_Impstation/Entities/Mobs/Customization/Markings/tattoos.yml
Because people were making invisible ones
Good soldiers follow orders and I won't allow IPCs to explot invisibility lol.
---
---
:cl: Diggy
- add: People were using IPC markings to become invisible, now they can only take doll joints markings in the overlay section.
> The Great IPC Marking Gutting

- Content.Server/Atmos/EntitySystems/FlammableSystem.cs
- Content.Server/EntityEffects/Effects/FlammableReaction.cs
Exactly what the description says. There was some silly little jank in the code that caused [this issue](https://github.com/Simple-Station/Einstein-Engines/issues/2188), and I decided to fix it. People should get lit on fire, it shouldn't do stupid amounts of damage unless you *really* get lit on fire, all appears to be well in the world. The attached media is the approximate damage of 5u of splashed phlogiston.
---
---
<p>
</p>
</details>
---
:cl:
- add: fire has been re-added to the game for more than about a half a second
- tweak: fire shouldn't ash people at tiny amounts
> Fire Actually Works but Shouldn't Ash People Instantly

- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/magistrate.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Command staff are the backbone of communication aboard the station. Whether issuing orders during a crisis, coordinating departments, or resolving station-wide issues, their ability to clearly and quickly speak is not optional — it is essential.
A Command officer who cannot speak, even by choice, undermines the very purpose of the role. Silence in an emergency is a liability. Muted Captains or Heads of Staff cannot effectively lead, respond to crew inquiries, or de-escalate tense situations. The trait is flavourful, yes — but flavour cannot come at the cost of function.
Some players argue that disallowing the Muted trait in Command roles limits their character expression or agency. But Command is not a solo storytelling position — it is a public-facing, high-responsibility job that …
> Requires that a Character Not Be Mute to Be in Command

- Resources/Locale/en-US/_EE/contractors/commands.ftl
- Resources/Locale/en-US/_Impstation/markings/thaven.ftl
Adding missing loc files in ftl causing test errors.
text for stamps provided by Alia Ash, thaven chest scales followed the pattern of other thaven scale parts.
:cl:
- add: spawncorporatestamp, spawnspecificcorporatestamp and marking-ThavenChestScales
> Missing Ftl Entries

- Resources/Prototypes/_EE/Entities/Objects/Specific/Medical/syringecase.yml
Reduced the material composition of the syringe case to be the same as the of the lowest material use of the upgraded lathe, to avoid possibility to generate plastic by repeated crafting / dismantling.
:cl:
- tweak: resource composition
> Material Arbitrage Test Error Fix.

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/skills.yml
This PR adds 2 new surgery related traits to the game (surgery training which boosts your surgery speed to 1.6, only available for non-medical jobs, as well as experienced surgeon, which boosts your surgery speed to 2.5, available only to medical jobs + corpsman, without intern. They both cost 3 points.) while also tweaking and fixing the CPR training one. (reduces cost from 4 to 3 and adds BSO to the blacklist as BSO already has CPR training innately) 
---
<p>
</p>
</details>
---
:cl:
- add: Traits that increase your surgery speed, Surgery Training (1.6, between intern and standard doc) for non-medical, and Experienced Surgeon (2.5, same as CMO) for medical w/o intern and with corpsman
- tweak: CPR Training cost 4 -> 3
- fix: BSO can no longer …
> Surgery Experience Traits + CPR Trait Tweak

- Content.Server/Atmos/Components/GasTankComponent.cs
- Content.Server/Atmos/EntitySystems/GasTankSystem.cs
- Content.Server/Body/Systems/InternalsSystem.cs
- Content.Shared/Clothing/EntitySystems/ToggleableClothingSystem.cs
- Resources/Prototypes/DeltaV/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
This PR adds a mechanic to various hardsuits and tacsuits, which can now include optional features such as Integrated Thrusters, or Integrated Magboots. All the syndicate tacsuits and "Advanced" crew tacsuits have both. Hardsuits typically have one or the other, rarely both. Vacsuits never have either, get a jetpack nerd. 
While I was at it, I fixed various bugs making these features obnoxious to interact with, such as hardsuits helmet toggles not showing the helmet, or turning on your integrated magboots also causing you to start sucking the air out of your integrated thrusters. 
Finally to address players incessantly complaining that "waaah space wind is too unfair it keeps me in the air too long", I lowered the maximum time player characters can go without being updated by space wind …
> Stop Ectoplasms Complaining

- Resources/Locale/en-US/traits/misc.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/physical.yml
- Resources/Prototypes/_Shitmed/Body/Parts/cybernetic.yml
This PR tries to better balance bionic arms and comments out speed legs FOR NOW. 
For Bionic arms, it restricts them to only be accessible to security, command, dignitaries and paramedics, while also knocking down the cost back to 8, as it used to be. (this is because it is now only available to a select few and not everyone)
On top of that, I added a new trait, Prybar Prosthetics, which are cybernetic arms that can pry open UNPOWERED doors (so it's a crowbar). This one is much cheaper than bionic arm (3 points) and is available to everyone besides prisoners. (Yes it replaces your limbs with a new cybernetic arm with this function, the DX-1 Pryarms)
For speed legs, like previously stated, they're getting commented out. This is only temporary, until someone can figure out a way to …
> Woe, Cybernetic Appendage Trait Balancing Be upon Ye.

- Resources/Prototypes/_EE/Contractors/passports.yml
This PR should fix passports being closed while appearing open, and vice-versa
---
<p>
</p>
</details>
---
:cl:
- fix: Fixed passport sometimes being closed while appearing open, and vice-versa
> Fix Passport Visuals Not Matching Actual Opened Status

- Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
- Resources/Prototypes/_EE/Catalog/Fills/Boxes/general.yml
Make survival box smaller. Currently, survival box are large—they occupy a 3x3 slot in the backpack and have a 4x4 storage space. This PR changes them to occupy a 2x2 slot in the backpack and have a 3x3 storage space. The main reason I’m making this PR is that whenever I spawn, an item drops to the ground. I often don’t notice the dropped item and end up losing it (Looking at the player spawn areas, there are often items on the ground most of the time. It doesn’t seem to be just my case.).
---
<p>
</p>
</details>
---
:cl:
- tweak: Make survival box smaller
> Smaller Survival Box

- Content.Server/Construction/Completions/EmptyAllContainers.cs
- Content.Server/Destructible/Thresholds/Behaviors/EmptyAllContainersBehaviour.cs
- Content.Server/Singularity/EntitySystems/EventHorizonSystem.cs
Removed references to obsolete function in the Container manager, replaced them with the recommended ContainerSystem function calls.
Might have unified/verbosed a few variable names while at it.
:cl:
- remove: ContainerManager references
- add: ContainerSystem references
- tweak: some variable naming
> Container Manager Changed to Container System [Obsolete Fix]

- Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
- Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
- Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Fix mining voucher not allowing the selection of the initial kit and not appearing when selecting a backpack other than Salvage in the loadout.
---
<p>
</p>
</details>
---
:cl:
- fix: Fix mining voucher not allowing the selection of the initial kit
- fix: Fix mining voucher not appearing when selecting a backpack other than Salvage in the loadout
> Fix Mining Voucher

- Resources/ServerInfo/Guidebook/Mobs/IPCs.xml
This fixes the header in the IPC guidebook entry by adding a single line. DeltaV fixed this.
---
> Adds a Newline to the IPC Guidebook Entry

- Content.Shared/Clothing/ClothingSpeedModifierComponent.cs
- Content.Shared/Clothing/ClothingSpeedModifierSystem.cs
- Content.Shared/Clothing/MagbootsComponent.cs
- Content.Shared/Clothing/MagbootsSystem.cs
- Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
- Resources/Prototypes/_EE/Entities/Clothing/BieselRepublic/Modsuits/legionnaire.yml
- Resources/Prototypes/_EE/Entities/Clothing/SolAlliance/SAN/Modsuits/CSA-85x.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/apocryphal.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/corporate.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/engineering-responsory.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/inquisitory.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/janitorial-responsory.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/leader-responsory.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/medical-responsory.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/praetorian.yml
- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/security-responsory.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/Shoes/modsuit.yml
- Resources/Prototypes/_TG/Entities/Clothing/Modsuits/SyndicateModsuits.yml
Yea so it turns out that magboots were previously extremely dependent on having other components work with them to do the "Magboot" ability. This doesn't at all comply with ECS standards, since the expectation I have is that the MagbootComponent ALONE should be sufficient to make an item into "Magboots". This PR addresses this issue by refactoring Magboots(and also ClothingSpeedModifier) to no longer depend on each other for this behavior. MagbootsComponent is now responsible for handling its own NoSlip, Gravity Immunity, and Movement Speed. This behavior will also be extremly useful for supporting things such as Modsuits and Hardsuit/Tacsuit upgrades, as well as Clothing Attachments in general(which is another thing I'm working on).
I have attached a video demonstrating that I have …
> Magboots Refactor

- Resources/Prototypes/DeltaV/Traits/neutral.yml
- Resources/Prototypes/Traits/disabilities.yml
- Resources/Prototypes/Traits/inconveniences.yml
Yeah so last time I did an accent/language fix (https://github.com/Simple-Station/Einstein-Engines/pull/2212) I kinda forgot about the scottish, frontal lisp and stutter ones
so this PR does exactly the same thing as the PR linked, just for the missing accents. (Commenting out the lines that were supposed to let us make accents fully free as they don't work for now, which were the ones that specify how many trait slots and slots in the character item group the trait takes up)
---
<p>
https://github.com/user-attachments/assets/bd8a7e15-7f83-4330-b1d7-d3edd203b291
</p>
</details>
---
:cl:
- fix: Fixed the scottish, stutter and frontal lisp accents not working.
> Uncripple the Wall of Green (Accent Fixes)

- Content.Server/Shadowkin/EtherealSystem.cs
- Content.Shared/Shadowkin/EtherealComponent.cs
Darkswap no longer makes you noninteractive with a ton of different things, like *breathing*, or *gravity*, or *space*. It also now has an enforced time limit via continuous stamina damage. Additionally it has now picked up a notable weakness/counterplay in the form of a unique flash vulnerability. When exposed to a flash effect, you immediately take a ton of stamina damage and are dropped out of the dark realm
<p>
https://github.com/user-attachments/assets/e9c061a4-d310-4ff0-8917-86ddc492fa0b
</p>
</details>
:cl:
- add: Added a "Flash" weakness to DarkSwap. Being hit by any flash, even if you have flash protection, causes you to instantly drop out of the dark realm and take a massive amount of stamina damage.
- add: DarkSwap users now take …
> Nerf The Shit Out Of Darkswap

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
Pretty much exactly as the title says. I had to follow a very long and undocumented codepath to find out what Refresh: True does in this context to verify that it's, "SET The stun cooldown to 2s rather than add +2s"
:cl:
- fix: Space wind no longer causes its victims to accumulate infinite stun time.
> Space Wind No Longer Accumulates Infinite Stun

- Content.Server/Destructible/Thresholds/Behaviors/EmptyAllContainersBehaviour.cs
During a previous "Routine Cleanup", this system lost its ability to tell the difference between a Powered Light and an AlwaysPoweredLight, due to no longer checking if the entity has a ContainerManagerComponent. This was essential for the function it passes the "Forced" keyword into. The fix for this is pretty simple, just check for the component and exit if it's not there.
Fixes this:
no CL this isn't player facing.
> Fix EmptyAllContainersBehaviour Test Fail

- Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
During the Abductor port this section of code was removed for a reason I don't know. But it caused people's height to be ignored, and several giant Shadowkin could be seen.
---
---
:cl:
- fix: Fixes character height.
> Fix the Height of Characters that Were Giant.

- Content.Server/Radio/EntitySystems/RadioDeviceSystem.cs
Description.
---
Intercomms were turbo broken because the frequency didn't change from the default "common" frequency causing it to be only useful for common. Now they work for any channel as they were supposed to.
<p>
https://github.com/user-attachments/assets/3abb1e17-9f1b-4ba4-b165-ba94de82501f
</p>
</details>
:cl:
- fix: Intercomms are functional for every channel again.
> Intercomms Fix

- Content.Shared/_Lavaland/CCVar/CCVars.Lavaland.cs
This ONLY prevents the tests from inappropriately generating lavaland constantly, which lags them the hell out and kills them constantly. Consider it the same reason why Worldgen is also disabled on Debug. This notably also doesn't prevent the Lavaland test from running, nor does it prevent the tests from verifying that the lavaland related grids don't have issues. It just prevents the stupid lavaland map itself from generating in completely unrelated tests. If you don't believe me, go watch the test timer and enjoy it not taking 45 minutes anymore.
No CL this isn't player facing.
> Disable Lavaland Worldgen In Debug

- Resources/Maps/anchor.yml
- Resources/Maps/asterisk.yml
- Resources/Maps/core.yml
- Resources/Maps/hive.yml
- Resources/Maps/pebble.yml
Description.
---
This doesn't address the root issue which is that this doesn't happen automatically, but this will make it so that players don't have to fix the crew monitor themselves round start.
<p>
</p>
</details>
---
:cl:
- fix: The Crew Monitor server now works on Anchor, Asterisk, Core, Hive, Lambda, and Pebble roundstart.
> Crew Monitor Map Fixes

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Corporate Liaison is no longer antag-eligible
---
:cl:
- remove: Removed antag eligibility for Corporate Liaison
> Make the Corporate Liaison Not Able to Be an Antagonist

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.cs
- Content.Server/Body/Systems/MetabolizerSystem.cs
- Content.Server/CartridgeLoader/Cartridges/GlimmerMonitorCartridgeSystem.cs
- Content.Server/Chemistry/EntitySystems/SolutionRegenerationSystem.cs
- Content.Server/Medical/SuitSensors/SuitSensorSystem.cs
- Content.Server/NPC/HTN/HTNSystem.cs
- Content.Server/Station/Systems/StationSystem.cs
- Content.Server/Temperature/Systems/TemperatureSystem.cs
- Content.Shared/Clothing/EntitySystems/EmitsSoundOnMoveSystem.cs
- Content.Shared/Inventory/InventorySystem.Relay.cs
- Content.Shared/Movement/Events/GetFootstepSoundEvent.cs
- Content.Shared/Movement/Systems/SharedMoverController.cs
- Content.Shared/Projectiles/EmbedEvent.cs
- Content.Shared/Projectiles/EmbedPassiveDamageSystem.cs
I got baited by Ectoplasm, so I then spent 3 hours shaving off a sizeable chunk of this game's performance cost, including by taking 3 of the "Top 10 frametime consumers", and reducing their performance costs by 99% each. Along with various examples of slimming down some of the worst EQE's. 
Oh, and I fixed EmitSoundOnMove being desynced with actual movement. As part of making EmitSoundOnMove use 99% less CPU time, it was also synchronized with the MoverController. 
:cl:
- fix: Fixed items such as tactical webbing, bell collars, and hardsuits being desynced with character movement. 
- tweak: Made various large performance improvements.
> TCJ Makes A Rage Performance PR

- Resources/Prototypes/Body/Parts/harpy.yml
- Resources/Prototypes/Traits/species.yml
Discussed with some harpy players and agreed upon on call where we talked about trait balance (for the cost reduction for the trait).
This PR makes true flight (the trait for moffs that you can take when under 60kg, gives you a modified version of harpy flight) cost 2 (from 5) and reduces the speed modifier for flying from 1.2 to 1.19. (effective 32% increase to 30.9%)
Also adjusts the speed modifier for harpy flight to 1.3. (from an effective speed increase of 54% to 60.16%)
---
:cl:
- tweak: Adjusted moth and harpy flight to be more balanced. (Moth flight, ~30% speed increase, Harpy flight ~60% over sprinting, accounts for all modifiers, including harpies 10% sprint speed increase) Makes True Flight trait cost -2 instead of -5.
> Flight Speed, Moff Trait Small Rebalance

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/languages.yml
- Resources/Prototypes/_EE/Traits/languages.yml
This PR adds 2 language traits: One for Moffic, one for Chittin. Both can be taken by IPC and Harpy, and Moths can take Chittin, Chitinids can take Moffic. These three are the only ones that can take those traits, which cost 1 point. 
Additionally, it prevents Harpies from taking the Valyrian language trait, as they already start with that language so no need for them to waste a point.
---
<p>
</p>
</details>
---
:cl:
- add: Added Moffic (moff lang) and Chittin (chitinid lang) as languages traits. Available for IPCs and Harpies for 1 point, as well as Moths for Chittin and Chitinids for Moffic.
- fix: Harpies can no longer waste a point on the Valyrian standard language trait, which they already start with.
> Bug Languages Accesibility + a Smol Fix

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/skills.yml
IPCs have vocoder/voicechips to talk, they can resonable be extended altered used to produce a larger range of sound.
<details><summary><h1>The trait avalible on a IPC in character create</h1></summary>
<p>
:cl:
- add: Added IPC to permitted for Lyre Bird.
- altered: description to make it more neutral and less harpy specific.
> Request by ODJ to Add IPC to to the Permited List of the Trait Lyre Bird

- Resources/Locale/en-US/_EE/markings/harpy.ftl
- Resources/Locale/en-US/_EE/markings/xelthia.ftl
APPARENTLY the marking names for coloring don't throw an error when not localized properly. Applied proper names to these. That's the entire PR.
---
<p>
</p>
</details>
:cl: Zeta_Null
- add: Fixed marking localization issues
> Quick FTL Updates for Xelthia Markings and New Harpy Wings

- Resources/Locale/en-US/weapons/extenddescriptions/descriptions.ftl
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLRestrictedWeapons.xml
There were previously some inconsistencies in lawbook and restricted weapons about salvage. Now they are limited to using weapons only in salvage areas as originally meant to. Barkeep as well is unable to use his gun outside of bar anymore as well. 
Security will now no longer run into OOC complainhell when they grab a salvager with the entirey armory on him running around the station carefree.
---
<p>
Simple text-change, it looks as it reads.
</p>
</details>
---
:cl:
- tweak: Tweaked Spacelaw gun restrictions
> Clarifies Salvage Law

- Content.Shared/CCVar/CCVars.Admin.cs
- Content.Shared/CCVar/CCVars.GhostRespawn.cs
The engine [does not technically support](https://github.com/user-attachments/assets/9cb5645b-b767-4f1e-aa43-6fae3ee4e9c8) the `double` type, but it seems some system was converting the interpreted string into a double so CVars worked fine when defined by a config file or when using defaults, but the `cvar` *command* doesn't work with it. I'd add support for it, but we haven't switched engines yet.
---
<p>
Before
After
</p>
</details>
> Fix some Cvars Using Double as Their Type

- Content.Shared/Eye/VisibilityFlags.cs
- Resources/Prototypes/_Shitmed/Entities/Markers/Spawners/Random/dubious.yml
- Resources/Prototypes/_Shitmed/Entities/Structures/Computers/computers.yml
Abductor Eye was visible to people other than the Abductor. That was obviously bad. Alongside that, the invisibility organ had issues revolving deleting items from the inventory. Also obviously bad.
---
<p>
</p>
</details>
---
:cl:
- fix: Abductor Eye is now no longer visible for the inferior organisms.
- remove: Invisibility Organs were removed for being turbo-borked.
> Abductor Eye Visibility Flag Change and Invisble Organ Removal

- Resources/Prototypes/Roles/MindRoles/mind_roles.yml
In the F7 Admin Overlay - The Changeling mindrole did not have a roleType assigned causing it default to non-antagonist.
Added roleType: SoloAntagonist to mind_roles.yml (It was really this simple)
<h1>Media</h1>
---
:cl:
- fix: Changelings are now correctly identified as Solo Antagonists in the admin overlay!
> Fix Changeling Identification in Admin Overlay

- Resources/Maps/Shuttles/ShuttleEvent/SANDropship.yml
- Resources/Prototypes/_EE/Gamerules/SANDeserters.yml
Deserters have actual equipment. Now featuring their own Modsuits.
They also don't speak Tau-Ceti Basic, because why would they have any interest in talking with aliens? 
<p>
</p>
</details>
:cl:
- tweak: SAN Deserters now have actual equipment. Their dropship is also now airtight. 
- tweak: SAN Deserters no longer speak Tau-Ceti Basic. They can only speak Sol Common.
> Smol Deserters Update

- Resources/Prototypes/_Shitmed/Body/Parts/generic.yml
- Resources/Prototypes/_Shitmed/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/_Shitmed/Recipes/Lathes/rehydrateable.yml
This PR adds the bio-synthetic torso, head to the normal medical biofabricator recipes (they cost more and take more time to print out) and the space animal lungs, heart, dragon lungs, laser eyes and cobra gland to the emagged medical biofabricator recipes. The emagged recipes all cost and take double the amount of time to print compared to normal organs. The torso takes 60 biomass and takes 4 times as much time to print (due to the fact it's loaded with 5 organs in it, so that's 10 for the torso and 50 for organs) and the head takes 30 biomass and double the time to print (it has 2 organs inside of it, 10 + 20)
---
<p>
</p>
</details>
---
:cl:
- add: Added a printable torso and head to the medical biofabricator, as well as some space organs for …
> Medical Biofab Additions 

- Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
- Content.Shared/Wieldable/WieldableSystem.cs
There was this really annoying bug that made energy weapons switch their fire mode if you wielded them, this ports a change from wizden/starlight that fixes it. I will link the wizden PR that gives all proper credit/attributions to starlight.
https://github.com/space-wizards/space-station-14/pull/37085
<p>
https://github.com/user-attachments/assets/1a98e393-8096-4406-83b3-a2863ef9cce5
</p>
</details>
---
:cl:
- fix: Energy guns wont cycle on wield anymore
> Fix Energy Weapons Cycling on Wield

- Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
- Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
Chef and Bartender have clothing that is specified for Orion Express and Idris, however, they don't have those companies as potential employers. This PR fixes that.
No media since it's purely just like three lines of added text
:cl:
- tweak: Bartenders and Chefs can now be employed by Orion Express and Idris Incorporated
> Chef and Bartender Employment Fixes

- Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
Fixes an issue where the deathsquad ghostrole was missing 'GhostTakeoverAvailable', and removes the familiar mindrole from it.
---
---
<p>
</p>
</details>
---
:cl:
- fix: Fixed deathsquad ghostrole
> Fix the Deathsquad Ghostrole

- Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.Functions.cs
A single missing exclamation mark was breaking this.
<p>
</p>
</details>
:cl:
- fix: Fixed rolling psionic powers not generating their unique messages in chat.
> Fix Psi Power Rolling Messages

- Resources/Prototypes/_EE/Entities/Mobs/Player/xelthia.yml
- Resources/Prototypes/_EE/Entities/Mobs/Species/xelthia.yml
It was rendering as red. Added a thing to make it render as green.
---
<p>
</p>
</details>
> Fix the Color of Xelthia Blood as Rendered when Damaged

- Content.Server/Traits/TraitSystem.cs
This PR introduces a new "Soft" Anti-Cheat that will outright prevent invalid trait selections from being applied to a character, while also informing admins directly of the potential cheater. 
:cl:
- add: Attempting to spawn in with an invalid trait list will now simply prevent you from spawning with any traits at all. It will also inform any admins who may be online of the attempt.
> Softer Traits Anticheat

- Resources/Prototypes/CharacterItemGroups/Generic/headGroup.yml
- Resources/Prototypes/CharacterItemGroups/Generic/itemGroups.yml
- Resources/Prototypes/Loadouts/Generic/belt.yml
- Resources/Prototypes/Loadouts/Generic/eyes.yml
- Resources/Prototypes/Loadouts/Generic/hands.yml
- Resources/Prototypes/Loadouts/Generic/head.yml
- Resources/Prototypes/Loadouts/Generic/mask.yml
- Resources/Prototypes/Loadouts/Generic/neck.yml
- Resources/Prototypes/Loadouts/Generic/outerClothing.yml
- Resources/Prototypes/Loadouts/Generic/satchels.yml
- Resources/Prototypes/Loadouts/Generic/shoes.yml
- Resources/Prototypes/Loadouts/Generic/uniform.yml
This PR addresses a common complaint about our loadouts by making all generic non-job cosmetic clothing items covered by ItemGroups completely free. You can only take one of them anyway.
Also by popular request, I'm adding several of the enlisted-men uniforms from the Solarian assets to loadouts, with a Solarian+WarVeteran combination required to take them. None of the officers or admiralty, these are purely cosmetic.
<p>
All the cosmetics are free
</p>
</details>
:cl:
- add: Added Solarian army/navy outfits to loadouts for characters with Solarian+WarVeteran.
- tweak: All cosmetic loadout items are now free.
> Free Cosmetic Loadouts

- Content.Server/_EE/Supermatter/Systems/SupermatterSystem.Processing.cs
- Content.Server/_EE/Supermatter/Systems/SupermatterSystem.cs
- Content.Shared/_EE/Supermatter/Components/SupermatterComponent.cs
- Resources/Prototypes/Entities/Markers/atmos_blocker.yml
_config.GetCVar() is generally to be deprecated and replaced with the significantly better performant Subs.CVar(), since it doesn't need to fetch the CVar each time its used and instead keeps it cached. This is particularly important for systems that operate on every frame. Technically Supermatter wasn't on my list of systems to optimize, but it's a good look since it's a system we're uniquely responsible for.
No actual functionality for the Supermatter has been changed, this is just a code cleanup and performance pass.
No CL since this isn't player facing.
> Supermatter Tweaks

- Content.Server/Telephone/TelephoneSystem.cs
- Content.Shared/Telephone/TelephoneComponent.cs
- Resources/Prototypes/DeltaV/Entities/Objects/Devices/aac_tablet.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/defib.yml
- Resources/Prototypes/Entities/Structures/Machines/base_structuremachines.yml
- Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
- Resources/Prototypes/_EE/Entities/Structures/Power/Generation/Supermatter/supermatter.yml
This PR fixes a bug whereby the Holopads weren't respecting languages, and actually basically every machine in the entire game wasn't. There's an in-general broader issue that I would reaaaaaally like if UI elements in general could be differentiated by language, but that's a lot harder to do than this fix. This was shockingly easy to fix actually.
:cl:
- fix: Holopads now correctly respect the speaker's language, and transmit said language to the receiver. They are no longer Universal translators. Have fun yelling at people over the holopad in whatever obscure language your character knows.
- fix: Nearly every machine that can speak, now correctly respects that languages exist. For example, mice can now no longer understand what vending machines are saying.
> Machine Languages

- Content.Server/NPC/Components/NPCRangedCombatComponent.cs
- Content.Server/NPC/HTN/PrimitiveTasks/Operators/Combat/Ranged/GunOperator.cs
- Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs
- Content.Shared/Weapons/Ranged/Components/GunComponent.cs
This fixes an issue whereby turrets were not capable of hitting players who lay down on the floor. Now turrets have a 50% chance to hit them anways, meaning that laying down offers some, but not perfect protection from turrets.
<p>
https://github.com/user-attachments/assets/599583be-d298-452c-8b1b-f32d8d545131
</p>
</details>
:cl:
- fix: Turrets and NPCs can now hit players who are laying down on the floor. They (by default) have a 50% chance to miss players who are laying down, meaning it still offers some protection, but not perfect protection from turrets.
> Turrets Shoot Laying Down People

- Content.Client/Body/Systems/BodySystem.cs
- Content.Client/Humanoid/HumanoidAppearanceSystem.cs
- Content.Shared/Humanoid/Markings/MarkingPrototype.cs
- Resources/Locale/en-US/markings/face.ftl
- Resources/Prototypes/Entities/Mobs/Customization/Markings/harpy.yml
- Resources/Prototypes/Entities/Mobs/Customization/cyberlimbs/eyes.yml
- Resources/Prototypes/Entities/Mobs/Customization/screens.yml
- Resources/Prototypes/Species/human.yml
This PR adds shader support to markings, which can define specific layers that have a shader, and which shader is desired. I wanted to have glowing eyes like my character in Aurora does, but was frustrated that I couldn't. So here's that tiny feature now.
<p>
</p>
</details>
:cl:
- add: Markings can now use shaders. Including things like glowing light effects. You can now also have glowing cybernetic eyes. IPC head screens now glow.
> Marking Shaders

- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
This PR fixes some of the underlying code for melee damage modifiers on the component that were previously not properly used. So now admins can properly edit the multiplier for melee weapon damage.
No CL this isn't player facing.
> VVEdit Melee Damage Modifiers

- Content.Server/Worldgen/Prototypes/BiomePrototype.cs
- Content.Server/Worldgen/Systems/Biomes/BiomeSelectionSystem.cs
- Content.Server/Worldgen/Systems/Debris/DebrisFeaturePlacerSystem.cs
Done by request from Aisha at Hullrot, this PR adds support for defining specific world chunks that will always generate a specific biome prototype. I've slightly adapted the old hullrot code to support the prototypes, while also making sure that it's an optional functionality. Simply don't define the specific locations if you want a prototype to potentially generate anywhere.
No CL this isn't player facing.
> Support Generating In Specific Chunks

- Content.Client/Weapons/Melee/MeleeArcOverlay.cs
- Content.Client/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Server/NPC/Systems/NPCCombatSystem.Melee.cs
- Content.Server/NPC/Systems/NPCJukeSystem.cs
- Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
- Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml
- Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
- Resources/Prototypes/Entities/Objects/Tools/toolbox.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/white_cane.yml
- Resources/Prototypes/_EE/Entities/Objects/Specific/Hydroponics/tools.yml
- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_hammer.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/cane.yml
My previous code for melee weapon range modifiers was missing, this PR restores and adds actual functionality for weapon range modifiers in all instances of weapon range, as well as adds specific range modifiers for light attack and disarm attack.
:cl:
- fix: Fixed melee weapons "Bonus range for heavy attacks" not functioning correctly. 
- add: Added support for melee weapons having bonus range on disarms or light attacks.
> Weapon Range Fixes

- Content.Server/DeltaV/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs
- Content.Server/Disposal/Unit/EntitySystems/DisposalUnitSystem.cs
- Content.Server/Fluids/EntitySystems/DrainSystem.cs
- Content.Server/Light/EntitySystems/ExpendableLightSystem.cs
- Content.Server/Morgue/MorgueSystem.cs
- Content.Server/Power/EntitySystems/ApcSystem.cs
- Content.Shared/Light/Components/ActiveExpendableLightComponent.cs
- Content.Shared/Nutrition/Components/HungerComponent.cs
- Content.Shared/Nutrition/EntitySystems/HungerSystem.cs
- Content.Shared/Projectiles/ActiveEmbeddableProjectileComponent.cs
- Content.Shared/Projectiles/SharedProjectileSystem.cs
These are all essentially just random systems that scaled directly with player count (or were on my list of the top 50 anyways). So just a couple systems that had very inefficient enumerators being swapped out with significantly more efficient ones, plus a few swaps from O(n) to O(m) m << n. A big one was DrainSystem, which was querrying all possible entities, rather than doing so from the "set of all static objects", which is significantly smaller. Puddles are always static objects, so it doesn't make sense to have the drains check for anything other than static. 
We can also use DirtyField to save on performance costs of Dirty(uid, component) in cases where the Dirty is only networking a single component field. 
no CL this isn't player facing.
> More Random Code Optimizations

- Content.Server/Traits/TraitSystem.Functions.cs
- Content.Shared/Actions/SharedActionsSystem.cs
- Content.Shared/Body/Organ/OrganComponent.cs
- Content.Shared/Body/Systems/SharedBodySystem.Organs.cs
Another request by Aisha for Hullrot. This adds the necessary code for supporting completely yml serialized cybernetics, via use of the all powerful TraitFunctions library. A new TraitFunction exists for removing actions from an entity, and in order to make it less terrible to use, I added a new public function to the SharedActionsSystem to allow removing an Action from an entity via Action Prototype rather than EntityUid. 
:cl:
- add: Added support for Organs(such as Cybernetics) to utilize the same massive library of functions used by Traits.
> Cyberware Code Support

- Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
This pr fixes the issue where, when picking up an item with an action, the item's action would become duplicated or flicker briefly on the action bar.
---
<p>
https://github.com/user-attachments/assets/4ef3e05c-8614-44ee-a75f-e34cec6431e1
</p>
</details>
---
:cl: 
- fix: Now the action bar doesn’t turn into a party when it picks up an item with an action.
> Fix Action Bar

- Content.Server/Atmos/EntitySystems/FlammableSystem.cs
- Content.Shared/Atmos/Components/OnFireComponent.cs
I'm yeeting the server costs for the flammable system. This system will no longer querry every entity that might be on fire to check if they're on fire, and is instead querrying only entities that have a new OnFireComponent, which is used to tell them that they're on fire. 99% cost reductions are fun.
I have verified in testing that this works. 
:cl:
- fix: Dramatically improved performance of the flammable system.
> Flammable Performance Improvements

- Resources/Prototypes/_EE/Entities/Clothing/BieselRepublic/outerwear.yml
This was supposed to be equivalent to heavy security vests, and essentially be a reskin of the heavy armor. I guess I never pushed the nerf somehow.
:cl:
- tweak: Nerfed the TCAF Heavy Armor to be equivalent to Heavy Security Armor.
> Nerf TCAF Heavy Armor

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Gases.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.GridAtmosphere.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.LINDA.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.MAS.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Monstermos.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Superconductivity.cs
- Content.Server/Atmos/TileAtmosphere.cs
- Content.Shared/Projectiles/SharedProjectileSystem.cs
This PR ports some fixes to the order of operations for air pressure processing, which will help fix issues with temperature not correctly diffusing, as well as errors in the order of operations processing that made it so that Space Wind was receiving wildly incorrect pressure values. 
Additionally, this fixes a math error that made it so that the diagonal airflows were contributing 41% more to airflows, making diagonal motion unusually harsh. There's still two more bugs I need to fix though.
> Pretty Big Atmos Fixes PR

- Content.Server/Holopad/HolopadSystem.cs
Holopad System had a vestigial set of logic for preventing it from running an expensive AABB check on every frame. I say vestigial because it was actually nonfunctional, and would run on every frame after a single second had passed since roundstart. This PR fixes the logic so that it correctly only checks once per second. Ideally I'd revisit this later and make it only run on ActiveHolopads in the first place, but this was simple enough of a fix.
:cl:
- fix: Made some performance improvements to the Holopad system.
> Holopad System Performance Tweaks

- Content.Server/Fluids/EntitySystems/DrainSystem.cs
- Content.Shared/Fluids/Components/DrainComponent.cs
Actually the bulk of this system's cost was in having these expensive entity querries running on every frame, so instead of interrupting the drain logic on a per drain basis, we interrupt the entire system of querries itself globally, and cut off the main expense of the system at its root source.
:cl:
- tweak: Made some significant performance improvements to Drains.
> More Drain System Perf Tweaks

- Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
Comes from: space-wizards/space-station-14#32480
Upstream/downstream cherry-pick that fixes item saving. Sometimes bound to Ctrl+I, pressing it over an item in an inventory saves that location for when the item is placed into the bag by clicking on it or quick equipped (Shift+E), but it was broken for a while.
:cl:
- fix: Saving item locations are working again
> Fix Saving Prefered Quick Store Item Locations (space-wizards/space-station-14#32480)

- Content.Client/Humanoid/HumanoidAppearanceSystem.cs
- Content.Client/Lobby/LobbyUIController.cs
- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Server/Cloning/CloningSystem.Utility.cs
- Content.Server/Clothing/Systems/LoadoutSystem.cs
- Content.Server/DeltaV/ParadoxAnomaly/Systems/ParadoxAnomalySystem.cs
- Content.Server/GameTicking/Rules/AntagLoadProfileRuleSystem.cs
- Content.Server/GameTicking/Rules/Components/AntagLoadProfileRuleCOmponent.cs
- Content.Server/Implants/SubdermalImplantSystem.cs
- Content.Server/Station/Systems/StationSpawningSystem.cs
- Content.Server/Traits/TraitSystem.Functions.cs
- Content.Server/Traits/TraitSystem.cs
- Content.Server/_EE/Contractors/Systems/EmployerSystem.cs
- Content.Server/_EE/Contractors/Systems/LifepathSystem.cs
- Content.Server/_EE/Contractors/Systems/NationalitySystem.cs
- Content.Server/_Shitmed/StatusEffects/ScrambleDnaEffectSystem.cs
- Content.Shared/Humanoid/LoadProfileExtensionsEvent.cs
- Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/_Shitmed/GameRules/events.yml
This PR gently refactors character profile loading such that it now optionally supports directly loading all of the EE specific extensions for character profiles, such as Traits and Loadouts. This generally means that Antags now actually support antag-specific traits and loadouts. It's currently only used by Nukies, who now spawn with your Traits and Loadout selections. 
Notably, there was already a pre-existing CharacterAntagonistRequirement, but it wasn't previously useful for the loadouts menu, and now it is. We can now fully support character menu options that apply if and only if a specific antagonist is generated. There's still some underlying unwieldiness to it, since antag loadouts will always be hidden due to your character doll never being an antag. 
:cl:
- add: Added code …
> Profile Loading Extensions

- Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
- Resources/Prototypes/Entities/Objects/Tools/jetpacks.yml
Makes the combat first aid kit easier to find in sandbox and makes all jetpacks go on suit storage
:cl: Ghost581
- tweak: Jetpacks can go on suit storage slot
> Make All Jetpacks Go on Suit Storage + Combat First Aid Kit Easier to Find

- Content.Server/Traits/TraitSystem.Functions.cs
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/physical.yml
This PR implements a long since highly demanded and stupidly complicated to implement trait function, which enables me to trivially do something I have been wanting to do for awhile, make a subspecies swapper. This new function is called TraitModifyComponent, and it allows one to directly write to any field of any trait, overwriting said field with a specific value. To make use of this, I created the Species Swap: Shell trait to demonstrate its awesome power.
This trait turns a human into an IPC, while retaining their entire system of humanoid appearance, effectively turning them into a Shell. https://wiki.aurorastation.org/index.php/IPC#Shell_Model_IPCs
You can now play a Hazel. 
<p>
</p>
</details>
I have actually tested this PR and verified …
> Species Swap: Shell

- Content.Server/Speech/EntitySystems/VocalSystem.cs
- Content.Shared/Speech/Components/VocalComponent.cs
- Resources/Prototypes/Traits/physical.yml
- Resources/Prototypes/Traits/species.yml
Vocal emotes were broken for Shells, and there were a few leftover components that they shouldn't have still had which were obtained from other entries in the parent hierarchy. 
:cl:
- tweak: Most traits that were previously IPC exclusive can now also be taken by Shells. 
- fix: Fixed Shells not having any emote sounds.
> Fixes For Shell Species Swap

- Content.Server/Ghost/GhostReturnToRoundSystem.cs
- Resources/Locale/en-US/ghost/ghost-respawn.ftl
The system that is responsible for letting ghosts rejoin the round does not validate the client's request properly.
The outcome is both hilarious and horrifying.
The bug can be triggered either by a modified client straight up sending the `GhostReturnToRoundRequest` message whenever, or by a client with high ping sending it after it has switched bodies (e.g. took a ghost role), but before it has received the update from the server.
---
<p>
[juggernaut.zip.webm](https://github.com/user-attachments/assets/13090f95-283b-4841-9fa3-da723642c3a3)
</p>
it does this now instead
</details>
---
nocl
> Tweak: Nerfed Juggernaut Ult
