Simple-Station/Einstein-Engines

- Resources/Prototypes/DeltaV/Entities/Clothing/Neck/medals.yml
- Resources/Prototypes/Entities/Clothing/Neck/medals.yml
Title
Moffs can't eat them
**Changelog**
:cl: DangerRevolution
- fix: Moths can no longer eat medals
> Make Moths Unable to Eat Medals

- .github/labeler.yml
I added a few more labels to the repository, this'll make the bot use them.
> Add More Labels to the Labeler Action

- Content.Shared/Frontier/Storage/Components/MaterialReclaimerMagnetPickupComponent.cs
- Content.Shared/Frontier/Storage/Components/MaterialStorageMagnetPickupComponent.cs
- Content.Shared/Frontier/Storage/EntitySystems/MaterialReclaimerMagnetPickupSystem.cs
- Content.Shared/Frontier/Storage/EntitySystems/MaterialStorageMagnetPickupSystem.cs
- Resources/Locale/en-US/frontier/storage/components/magnet-pickup-components.ftl
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Entities/Structures/Machines/material_reclaimer.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-10 20:17:18 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-17 13:38:11 UTC</aside>
<sup>
`5acb90a4eb6b8e8436d06cffe92169d07e38d140`
</sup>
---
- Changes: YML
- Changes: C#
- Changes: Localization
---
> - Title: Machines will automatically pull in tagged items for processing, allowing to set them up on …
> Add magnet pickup system from Frontier

- Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/familiars.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/144424013?v=4" width="16"/><a href="https://github.com/Adrian16199"> Adrian16199</a> at 2024-03-17 14:00:00 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/144424013?v=4" width="16"/><a href="https://github.com/Adrian16199"> Adrian16199</a> at 2024-03-17 14:09:23 UTC</aside>
<sup>
`cfe2e712d6fdaef50a3c77635d201d28fe8a16d5`
</sup>
---
- Changes: YML
---
> Basicly adds playtime requirement to ifriit (so that they cant go shitter mode and to have somesort of knowledge of what they should do) and makes them unable to die …
> A small change to ifriit.

- Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/142105406?v=4" width="16"/><a href="https://github.com/DangerRevolution"> DangerRevolution</a> at 2024-03-17 17:28:00 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/142105406?v=4" width="16"/><a href="https://github.com/DangerRevolution"> DangerRevolution</a> at 2024-03-17 17:45:11 UTC</aside>
<sup>
`0271f2ac35a433d06f761936e0d644c8a41f4548`
</sup>
---
- Changes: YML
---
> 
> 
> Moths can now eat jumpskirts by adding - clothmade tag
> 
> 
> 
> moths hungry
> 
> 
> ## Media
> 
> - …
> Fix Moth not eating Jumpskirts

- Resources/Prototypes/Maps/Pools/default.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-20 22:39:09 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/107660393?v=4" width="16"/><a href="https://github.com/IamVelcroboy"> IamVelcroboy</a> at 2024-03-20 22:49:59 UTC</aside>
<sup>
`a14b7c5e23f5126ba0e11ea4c321052b2d9d27d1`
</sup>
---
- Changes: Map
---
> Title
> 
> :cl: Rose
> - add: Added Submarine Station back to the map pool (for real this time)
</details>
> Add Submarine to map pool :)

- Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
- Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
- Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
- Resources/Prototypes/Catalog/Fills/Lockers/science.yml
- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
- Resources/Prototypes/Catalog/Fills/Lockers/service.yml
<aside>PR opened by <img src="https://avatars.githubusercontent.com/u/142105406?v=4" width="16"/><a href="https://github.com/DangerRevolution"> DangerRevolution</a> at 2024-03-21 17:52:42 UTC</aside>
<aside>PR merged by <img src="https://avatars.githubusercontent.com/u/142105406?v=4" width="16"/><a href="https://github.com/DangerRevolution"> DangerRevolution</a> at 2024-03-21 18:46:44 UTC</aside>
<sup>
`d07fa88e1dfba6107602c9cf0d58733ed6074274`
</sup>
---
- Changes: YML
---
> 
> Title.
> 
> :cl: DangerRevolution
> - add: Added lunchboxes to various staff lockers
> 
</details>
> Adds Lunchboxes to Lockers

- Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml
- Resources/Prototypes/DeltaV/Voice/speech_emotes.yml
- Resources/Prototypes/Voice/speech_emotes.yml
A few of the Harpy emotes were previously broken during an upstream merge for DeltaV, roughly a month before this fork was created. Now that I'm finally free for a bit, I'm doing my maintainer duty by fixing Harpy Mimicry.
> Fixing the birb emotes

- Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/47712032?v=4" width="16"/><a href="https://github.com/Killerqu00"> Killerqu00</a> at 2024-03-23 10:36:39 UTC
---
PR changed 1 files with 2 additions and 1 deletions.
- No C#
---
> 
> 
> 
> 
> 1x2 cable coils
> 
> 
> 1x2 cable coils
> 
> 
> 
> ## Media
> 
> ![image](https://github.com/space-wizards/space-station-14/assets/47712032/1158b22c-eb2a-4d5d-8b69-d3d3173175b5)
> 
> 
> 
> 
> 
> …
> Mirror: 1x2 cable coils

- Resources/Prototypes/Catalog/uplink_catalog.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/68826635?v=4" width="16"/><a href="https://github.com/Ghagliiarghii"> Ghagliiarghii</a> at 2024-03-13 18:08:33 UTC
---
PR changed 1 files with 0 additions and 5 deletions.
- No C#
---
> Previously the C-20r magazines were only available for nukies to purchase, but regular syndicate agents could purchase the actual C-20r bundle to get the gun and some magazines. This strikes me an inconsistent. 
> 
> This would be a very minor / QoL buff to normal syndicate agents, as before they could purchase three instances of the .35 auto pistol magazines (for the Viper) and manually load all that ammo into an empty C-20r magazine. This is less …
> Mirror: Democratize C-20r SMG Magazines

- Content.Server/Spreader/SpreaderSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-22 20:20:50 UTC
---
---
> 
> 
> 
> 
> Kudzu should no longer be able to infinitely spread into itself when traversing across grids.
> 
> 
> Bug fix.
> 
> 
> Passed the wrong grid UIDs with part of the cleanup of spreader behavior. Now the right grid UIDs should be used.
> 
> ## Media
> 
> 
> 
> ## Breaking …
> Mirror: Fix cross-grid spreader behavior

- Content.Server/Medical/BiomassReclaimer/BiomassReclaimerComponent.cs
- Content.Server/Medical/BiomassReclaimer/BiomassReclaimerSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/57039557?v=4" width="16"/><a href="https://github.com/Ilya246"> Ilya246</a> at 2024-01-08 09:45:55 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-11 21:59:21 UTC
---
PR changed 2 files with 45 additions and 11 deletions.
---
> 
> 
> 
> title: allows biomass reclaimer to reclaim plants at 0.5 biomass per plant
> also makes insertion doafter time scale with mass of inserted entity
> also fixes click insertion (as opposed to drag insertion) not working
> 
> provides a …
> Mirror: allow biomass reclaimer to reclaim plants

- Resources/Prototypes/Entities/Clothing/Belt/belts.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml
- Resources/Prototypes/Entities/Objects/Tools/lantern.yml
- Resources/Prototypes/tags.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/124214523?v=4" width="16"/><a href="https://github.com/lzk228"> lzk228</a> at 2024-03-13 17:54:03 UTC
---
PR changed 4 files with 13 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> - Allow surgery tools in medbelt (Fixes #26010)
> - Allow hand labeler in utility and botanical belt
> - Allow lantern in utility belt
> 
> 
> 
> 
> 
> ## Media
> 
> 
> 
> 
> 
> 
> 
> :cl:
> - tweak: Surgery tools can be …
> Mirror: Some more whitelists for belts

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/93311212?v=4" width="16"/><a href="https://github.com/icekot8"> icekot8</a> at 2024-03-11 10:27:27 UTC
---
PR changed 1 files with 16 additions and 1 deletions.
- No C#
---
> 
> 
> 
> 
> This PR adds 8 piercing damage to foxes and makes them neutral rather than peaceful.
> 
> 
> this seems logical. At this point, the fox is not neutral, although it is originally a predatory animal.
> 
> I think 8 piercing for their bite is fair damage considering their origin.
> `attackMemoryLength` = 10, because that's the average value for this metric.
> 
> I don't think we should discount animals from their …
> Mirror: foxes are now neutral🦊 

- Content.Server/GameTicking/GameTicker.Spawning.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/32041239?v=4" width="16"/><a href="https://github.com/nikthechampiongr"> nikthechampiongr</a> at 2024-03-13 19:26:04 UTC
---
PR changed 1 files with 1 additions and 0 deletions.
---
> closes #26089 
> 
> 
> 
> 
> This PR adds logs for joining the round as an observer.
> 
> 
> The admin cabal has contracted me to do this. Please I want  to see my family again.
> 
> ## Media
> 
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> 
> 
> 
> 
> 
> 
> :cl: …
> Mirror: Add log when a player starts observing.

- Content.Server/Store/Systems/StoreSystem.Ui.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/54602815?v=4" width="16"/><a href="https://github.com/keronshb"> keronshb</a> at 2024-03-19 02:36:50 UTC
---
PR changed 1 files with 0 additions and 2 deletions.
---
> 
> 
> 
> 
> 
> There was a bug that enabled refunds on all stores.
> 
> Fixes #26202
> 
> 
> 
> Bugfix.
> 
> 
> 
> Removes else that accidentally enables refunds
> 
> ## Media
> 
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> 
> 
> 
> 
> 
> :cl:
> - fix: Fixed a bug where stores …
> Mirror: Store Refund Fix

- Resources/ServerInfo/Guidebook/Science/ArtifactReports.xml
PR opened by <img src="https://avatars.githubusercontent.com/u/32827189?v=4" width="16"/><a href="https://github.com/Vermidia"> Vermidia</a> at 2024-03-19 03:57:37 UTC
---
- No C#
---
> 
> 
> 
> 
> Forgot about this when making the last PR and didn't get to change it to what it's supposed to be.
> 
> 
> Consistency with the reports.
> 
> 
> 
> ## Media
> 
> 
> 
> 
> 
> 
> 
> 
</details>
> Mirror: Changed current value to unextracted value in artifact report guidebook

- Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/103440971?v=4" width="16"/><a href="https://github.com/Brandon-Huu"> Brandon-Huu</a> at 2024-03-11 10:32:34 UTC
---
- No C#
---
> 
> 
> 
> 
> agent id's default to passenger icon
> 
> 
> Lessen meta gaming
> 
> 
> 
> ## Media
> 
> 
> - [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> 
> 
> 
> 
> 
> 
</details>
> Mirror: Agent IDs default to passenger icon

- Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
- Content.Server/Nyanotrasen/Mail/MailCommands.cs
- Content.Server/Nyanotrasen/Mail/MailSystem.cs
This updates us to the current version of Robust Toolbox, while also fixing everyone's favorite maintainer burden system, the deep fryer. Which to absolutely nobody's surprise got broken by an engine update again. One of these days I should take a metaphorical hacksaw to the deep fryer code.
> Engine update 215.2.0

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/107586145?v=4" width="16"/><a href="https://github.com/IProduceWidgets"> IProduceWidgets</a> at 2024-03-24 21:49:41 UTC
---
PR changed 1 files with 2 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> Fixed #26307 by letting ammo techfab accept ingots and cloth. I don't think it makes anything with cloth, but a quick vibe check in contrib chat thought it was fine since they can be ejected.
> 
> 
> It has recipes that call for ingots
> 
> 
> I could use composition to not need to add the tags since they're in the BaseLathe, but I think they're explicitly included in case …
> Mirror: Fix: let ammofab accept the common material types

- Content.Server/Power/EntitySystems/ChargerSystem.cs
PR opened by <img src="https://avatars.githubusercontent.com/u/85356?v=4" width="16"/><a href="https://github.com/Tayrtahn"> Tayrtahn</a> at 2024-03-18 12:52:09 UTC
---
PR changed 1 files with 7 additions and 7 deletions.
---
> 
> 
> 
> 
> Borg chargers can now charge borgs again.
> 
> 
> Bug fix.
> 
> 
> An oversight in #25871 caused ChargerSystem to call BatterySystem's SetCharge with the wrong EntityUid.
> 
> SearchForBattery has been given another out argument which gives the found battery's uid so it can be passed to SetCharge.
> 
> To the author of #25871: get better at testing your code!
> 
> ## Media
> 
> 
> - [X] I have added …
> Mirror: Fix borg charger error

- Resources/Prototypes/Entities/Mobs/base.yml
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
- Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
- Resources/Prototypes/Entities/Objects/Tools/flashlights.yml
- Resources/Prototypes/Entities/Objects/Tools/jaws_of_life.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/Entities/Objects/Tools/welders.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/cult.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sledgehammer.yml
- Resources/Prototypes/Entities/Objects/Weapons/security.yml
- Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/45323883?v=4" width="16"/><a href="https://github.com/Dutch-VanDerLinde"> Dutch-VanDerLinde</a> at 2024-03-20 13:23:56 UTC
---
PR changed 14 files with 36 additions and 0 deletions.
- No C#
---
> 
> 
> 
> most blunt weapons sounded like you're not doing any damage
> 
> quietly gibbing people is bad
> 
> also helps #25929 partially
> 
> ## Media
> 
> 
> 
> no
</details>
> Mirror: Fix blunt melee weapon hitsound

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/144424013?v=4" width="16"/><a href="https://github.com/Adrian16199"> Adrian16199</a> at 2024-03-15 18:05:23 UTC
---
PR changed 1 files with 3 additions and 0 deletions.
- No C#
---
> 
> 
> 
> 
> Gives the tag of glue to crazy glue.
> 
> -Glue but clown advertised.
> -Cant be used to craft stuff like stunprod or someother stuff even tho its same thing as space glue.
> -Suffer.
> 
> 
> ## Media
> 
> 
> 
> 
> 
> …
> Mirror: Gives glue tag to crazy glue

- Resources/Prototypes/Entities/Structures/Walls/asteroid.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/107586145?v=4" width="16"/><a href="https://github.com/IProduceWidgets"> IProduceWidgets</a> at 2024-03-19 16:44:28 UTC
---
- No C#
---
> 
> 
> 
> 
> 
> That's a crab.
> 
> 
> When youre placing a crab, its good to know its a crab.
> 
> 
> 
> ## Media
> 
> 
> 
> 
> 
> 
> 
> 
> no changelog only crab.
</details>
> Mirror: spawn panel rock crab suffix

- Resources/Locale/en-US/salvage/salvage-magnet.ftl
- Resources/Maps/Salvage/vegan-meatball.yml
- Resources/Prototypes/Maps/salvage.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/140123969?v=4" width="16"/><a href="https://github.com/Blackern5000"> Blackern5000</a> at 2024-01-28 04:07:26 UTC
PR merged by <img src="https://avatars.githubusercontent.com/u/19864447?v=4" width="16"/><a href="https://github.com/web-flow"> web-flow</a> at 2024-03-07 19:37:57 UTC
---
PR changed 3 files with 1699 additions and 0 deletions.
- No C#
- Changes: Map
---
> Adds a new salvage called "Vegan Meatball"
> I was sorta going for a "mystical plant orb" feel
> 
> Just one anomaly salvage wasn't enough
> 
> ## Media
> …
> Mirror: Vegan Meatball

- .github/labeler.yml
Realized while going through issues that we don't have a label for audio file changes, I've added one.
> Add an Audio Automatic Label

- .github/workflows/close-master-pr.yml
Didn't intend for this branch to be made on this repo.
Improves the "close PRs from master" workflow's denial message.
> Update close-master-pr Workflow's Denial Message

- .github/workflows/build-map-renderer.yml
- .github/workflows/build-test-debug.yml
- .github/workflows/publish.yml
- .github/workflows/test-packaging.yml
- .github/workflows/yaml-linter.yml
Ports https://github.com/DeltaV-Station/Delta-v/commit/7e3ba621d325db4d838c4d0fb675b5173f3111df until we get the real fix.
Should allow tests to run, though it still fails most of the time according to Null.
> Temporary CI/CD Fix

- Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/164462467?v=4" width="16"/><a href="https://github.com/SoulFN"> SoulFN</a> at 2024-03-22 09:48:46 UTC
---
- No C#
---
> 
> 
> 
> Changes basic welder in borg tool module to industrial welder
> 
> 
> Basic welder sucks
> 
> 
> No
> 
> 
> ## Media
> 
> 
> - This PR does not require an ingame showcase
> 
> No
> 
> 
> :cl:
> - tweak: The borg tool module now has an industrial welding tool.
> 
> 
> 
> 
</details>
> Mirror: Gives borg industrial welder

- Resources/Locale/en-US/speech/speech-chatsan.ftl
- Resources/Prototypes/Accents/word_replacements.yml
PR opened by <img src="https://avatars.githubusercontent.com/u/77215380?v=4" width="16"/><a href="https://github.com/Doctor-Cpu"> Doctor-Cpu</a> at 2024-03-22 05:20:30 UTC
---
PR changed 2 files with 7 additions and 3 deletions.
- No C#
---
> 
> 
> 
> 
> "ig" gets replaced with "i guess"
> 
> 
> Common slang online which I've seen being attempted to be used before.
> 
> 
> N/A
> 
> ## Media
> 
> 
> 
> 
> N/A
> 
> 
> 
> 
> Don't feel like one is needed.
</details>
> Mirror: Sanitize "ig"

- flake.lock
- flake.nix
Nix devShell user only change, this doesn't affect normal building.
> Update to nixpkgs 24.05

- Content.Server/Administration/Managers/AdminManager.cs
There's probably an upcoming mirror for this, but whatever.
> Fix Null Being Taken Literally, Crashing Debug on Login

- Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
Self explanatory
P.S. i genuinely dont know what the fuck i did, who wrote this?
https://youtu.be/hbJbd5SgZ54
:cl:
- fix: Fixed loadouts becoming uneditable after spending all your points
> Fix Loadouts Breaking when You Spend All Your Points

- Content.Shared/OfferItem/SharedOfferItemSystem.cs
Fixes #522
---
:cl:
- fix: Food and handcuffs can now be given
> Fix Item Transfer System

- Content.Client/Audio/AmbientSoundSystem.cs
- Content.Client/Audio/ContentAudioSystem.LobbyMusic.cs
- Content.IntegrationTests/Tests/Buckle/BuckleTest.cs
- Content.IntegrationTests/Tests/Disposal/DisposalUnitTest.cs
- Content.IntegrationTests/Tests/GameObjects/Components/ActionBlocking/HandCuffTest.cs
- Content.Server/Anomaly/Effects/BluespaceAnomalySystem.cs
- Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
- Content.Shared/Disposal/SharedDisposalUnitSystem.cs
- Content.Shared/Light/Components/SharedExpendableLightComponent.cs
- Content.Shared/Storage/EntitySystems/DumpableSystem.cs
Ready to Merge Now
(I had to go to 217.2.1 because the prior versions of 217.0.0 weren't viable)
Includes the following Cherry-Picks:
https://github.com/space-wizards/space-station-14/pull/26387
https://github.com/space-wizards/space-station-14/pull/25963
> Update Submodule to 217.2.1

- Content.Server/Nutrition/EntitySystems/DrinkSystem.cs
- Content.Server/Nutrition/EntitySystems/FoodSystem.cs
- Content.Shared/CCVar/CCVars.cs
<p>
https://github.com/user-attachments/assets/1276c50a-b50b-45a9-a69f-17bca32c736c
</p>
</details>
---
:cl:
- tweak: You no longer eat food like a starving wolf or something
> CVar Food/Drink AutoEating

- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/inconveniences.yml
Changes the Social Anxiety Traits Name, Description, and ID's
---
:mefinks:
- tweak: Changed the name of the Social Anxiety Trait.
> Social Anxiety Trait Renamed

- Content.Client/LateJoin/LateJoinGui.cs
Last update broke late joins on Release build. This hotfixes latejoins.
> Hotfix Late Joins

- Resources/Prototypes/Catalog/Cargo/cargo_cargo.yml
> Remove Cargo Pallet From Request Console

- Resources/Changelog/Changelog.yml
> Use Correct Changelog Name

- Resources/Locale/en-US/station-events/events/anomaly-spawn.ftl
Title.
</details>
No cl no fun
> Fix Stinky Anomaly Announcement

- Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
This test fail has annoyed me for the last time.
> Fix NoMaterialArbitrage Test Fail

- Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
@DEATHB4DEFEAT 
No changelog because this isn't player facing.
> 1984 Dresser Arbitrage 2, Electric Boogaloo

- Content.Shared/Humanoid/SkinColor.cs
I'll let google image search make my case.
Done. By popular request, I'm bringing back RGB Moths.
:cl:
- fix: Moths can now once again be colorful.
> 1984 Shit Colored Moths

- Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Cherry-picks https://github.com/Fansana/floofstation1/pull/88 from Floofstation - changes skeleton description to match with Delta-v. Credit to ShatteredSwords.
:cl: ShatteredSwords
- tweak: Skeleton ghost role description has been adjusted to be less evil.
> Tweak Skeleton Description

- Content.Server/Abilities/Psionics/PsionicAbilitiesSystem.cs
- Content.Server/Psionics/PsionicsSystem.cs
Just some regular cleanup of PsionicSystem and PsionicAbilitiesSystem. No refactoring today, just cleanup. Tomorrow I will serialize this shit, assuming this gets merged. 
No media because there's nothing to show. No changelog because this isn't playerfacing.
> Psionic System Cleanup

- Content.Server/Psionics/Glimmer/GlimmerCommands.cs
- Content.Server/Psionics/Glimmer/GlimmerReactiveSystem.cs
- Content.Server/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
- Content.Server/Psionics/Glimmer/Structures/GlimmerSourceComponent.cs
- Content.Server/Psionics/Glimmer/Structures/GlimmerStructuresSystem.cs
More tedium to get out of the way, I can't do much more than this since by now in the day my adderall has worn off. This just does basic code cleanup of the glimmer system.
No media because there's nothing to show. No changelog because this isn't player facing.
> Minor Glimmer System Cleanup

- Content.Shared/Medical/SuitSensor/SharedSuitSensor.cs
Crew Monitor right now only shows Good! or Bad! (dead). Should show more states, this fixes it.
:cl: Xavier
- fix: Crew monitor not working properly, now displays correctly.
> Ports 78 From Floofstation - Fix Crew Monitor

- flake.lock
The bi-monthly nix version bump. Only impacts the nix users, which are me and @DEATHB4DEFEAT
> Nix Version Bump

- Content.Shared/Psionics/Abilities/PsionicRegeneration/PsionicRegenerationPowerComponent.cs
I LOVE OLD SHITCODE THAT DOESN'T VALIDATE ANYTHING. 
Not going to validate it in this PR because I'm just hot fixing this shit, and I'm busy as hell with serializing Psionics.
I'll go do a significantly more longer-term fix 2 PRs from now. 
:cl:
- fix: Fix missing Psionic Regeneration sound effect
> Hotfix Psionic Regeneration

- Content.Client/Voting/VoteManager.cs
- Content.IntegrationTests/Tests/GameObjects/Components/Mobs/AlertsComponentTests.cs
Attempt number 5000 to get the Heisentests to STOP.
> Fix Heisentests

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Commands.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
This is a cherry-pick of https://github.com/space-wizards/space-station-14/pull/27113
Which fixes a bug that has been reported here where the FixGridAtmos command does not work.
:cl:
- fix: Fixed the FixGridAtmos command.
> Cherry-Pick PR #27113

- LEGAL.md
- README.md
Was vague and poorly written, might still be a bit vague, but that's why it's being reviewed.
> Improve README/Legal Files

- Content.Server/Mood/MoodSystem.cs
MoodSystem has a Race Condition against DeleteAllThenGhost.
> Disable Mood In Debug

- Tools/actions_changelogs_since_last_run.py
- Tools/changelogs/changelog.js
:cl:
- add: New changelogs should now show links to their PRs
- tweak: Changelog authors should now be a header instead of bold text
- fix: Changelogs shouldn't send random amounts of old changelogs
> Add PR URL to Changelogs and Make Author a Header

- Resources/Prototypes/CharacterItemGroups/headGroup.yml
- Resources/Prototypes/Loadouts/head.yml
Cheaper Hats
:cl:
- tweak: All non-job specific headgear has been significantly reduced in Loadout point costs, most of them to 0.
> Hat Loadout Group

- Resources/Prototypes/CharacterItemGroups/outerwearGroup.yml
- Resources/Prototypes/Loadouts/outerClothing.yml
And now Outerwear. :)
:cl:
- tweak: All non-job outerwear has had their Loadout point costs significantly reduced.
> Outerclothes Loadout Group

- Resources/Prototypes/CharacterItemGroups/gloveGroup.yml
- Resources/Prototypes/Loadouts/hands.yml
Gloves Next. Woo.
:cl:
- tweak: All gloves have had their Loadout point costs reduced, many to 0.
> Gloves Loadout Group

- Resources/Locale/en-US/devices/device-network.ftl
- Resources/Locale/en-US/reagents/meta/consumable/drink/alcohol.ftl
- Resources/Locale/en-US/revenant/revenant.ftl
- Resources/Locale/en-US/weapons/melee/melee.ftl
Fixed some comment syntax that annoyed me.
> Fixed some Comment Syntax

- Content.Server/StationEvents/OscillatingStationEventScheduler.cs
SOMEHOW THIS GOT PAST THE LINTER. THE FUCK?
> Hotfix Linter

- Content.Shared/Contests/ContestsSystem.cs
I CAN'T BELIEVE I MISSED THIS.
> Filespace ContestsSystem.cs

- Resources/Prototypes/Entities/Mobs/Player/ipc.yml
Grrrr, I may have forgotten to remove it as a part of #733.
> Remove InteractionPopup From IPCs

- Resources/Prototypes/Entities/Mobs/Species/harpy.yml
- Resources/Prototypes/Guidebook/species.yml
- Resources/ServerInfo/Guidebook/Mobs/Harpy.xml
This PR adds a long overdue Guidebook for Harpies. However, I am physically incapable of half-assing it, so it contains ALL information about Harpies. Where they come from, notes on biology, what traits they have, what their average height is, what Language do they speak, etc. 
Also while I was at it, I put the singing animation in the character creation screen. So now it's basically impossible for anyone to miss out on the silly fact that they can do this.
:cl:
- add: Added a full Guidebook entry for Harpies. Unlike previous species guidebooks, this document contains extensive lore and background information for Harpies, in addition to notes on their game mechanics.
> Harpy Guidebook

- Resources/Prototypes/Entities/Objects/Devices/Electronics/door_access.yml
- Resources/Prototypes/Nyanotrasen/Entities/Structures/Doors/Airlocks/access.yml
Fixes mail doors. I missed this door when working on the previous PR
:cl:
- fix: Fixes door access for mail doors
> Fix Mail Doors

- Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml
Who the fuck gave them 80% temp resistance?
TODO: actually test this
:cl:
- fix: Winter boots are no longer able to protect you from insane temperatures.
> Nerf the Fuck Out of Winter Boots

- Resources/Locale/en-US/loadouts/itemgroups.ftl
- Resources/Locale/en-US/loadouts/jobs/security.ftl
- Resources/Prototypes/CharacterItemGroups/securityGroups.yml
- Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
- Resources/Prototypes/Loadouts/Jobs/security.yml
- Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
This PR *significantly* expands upon Loadouts available to the entire Security Department. First to note, is that all security roles no longer automatically spawn with a weapon, instead every security role has a single selection choice from the new Security Duty Weapon group, with many of the options being free or very little points. But it also now features significantly more options available. Players can freely choose whether they want their duty weapon loaded with Lethal vs. Nonlethal, with a modest restriction that Lethals require some Security playtime for Shitter Protection. The basic choices are either a Disabler, a Mk58, or an Inspector revolver, but players can spend loadout points to "Trade up" for a fancier gun. 
Security equipment now also includes selections of magazines for …
> Security Loadouts Expansion 2

- Content.Server.Database/Migrations/Postgres/20241001054803_CustomSpecieName.cs
- Content.Server.Database/Migrations/Sqlite/20241001054735_CustomSpecieName.cs
- Content.Shared/Preferences/HumanoidCharacterProfile.cs
This is an emercency fix regarding Custom Name, apprently this is fucked... wow...
Regarding DB issues please @DEATHB4DEFEAT review or check if you can assist or anyone.
Thank you.
---
:cl:
- fix: Custom Specie Name!
> Custom Name Fixes

- Resources/Prototypes/Entities/Objects/Misc/spider_web.yml
This add the missing tags for webs for Oneirophage to hide in webs (works tested on floof)
Overall Oneirophage need more changes, languages, psionic, ect but so far this is needed.
---
:cl:
- fix: Oneirophage is once more psionic invisible in webs.
> Add ArachneWeb to Spiderweb.

- Resources/Prototypes/Entities/Mobs/Species/arachne.yml
title
---
im lazy, imagine arachne but they arent big errors.
---
:cl:
- fix: Arachne no longer turn into errors when they take damage
> Fix Arachne Turning Into Errors when They Take Damage

- Resources/Textures/Clothing/Head/Hardsuits/atmospherics.rsi/meta.json
- Resources/Textures/Clothing/Head/Hardsuits/spatiohelm.rsi/meta.json
- Resources/Textures/Clothing/OuterClothing/Hardsuits/cburn.rsi/meta.json
- Resources/Textures/Clothing/OuterClothing/Hardsuits/syndieelite.rsi/meta.json
- Resources/Textures/Clothing/OuterClothing/Suits/eva_emergency.rsi/meta.json
- Resources/Textures/Clothing/OuterClothing/Suits/fire.rsi/meta.json
- Resources/Textures/Clothing/OuterClothing/Suits/rad.rsi/meta.json
There were some missing meta.json entries.
> Fix RSI Validator

- Resources/Prototypes/Recipes/Construction/utilities.yml
make it so you cant build disposal pipes in impassable objects (like walls)
This Fixes #1072 
By cherry-picking https://github.com/space-wizards/space-station-14/pull/28447
> Cherry-Pick Wizden PR #28447

- Content.Server/Psionics/PsionicsCommands.cs
Someone came up with the fix for this 3 days ago, and then never PR'ed it here. So I guess I'm PR'ing it now while I'm still on a bugfixing binge.
:cl:
- fix: addpsionicpower command now works.
> Fix Add Psionic Power Command

- Content.Server/Chat/Systems/ChatSystem.cs
- Resources/Maps/glacier.yml
For #1070 
This PR adds a dedicated Arrivals docking area, notably dropping people off at the "Village" rather than the Evac site. I felt it was more appropriate to drop people off at the village than near any industrial area, as it helps add to some of the map's charm that the first thing people see is a wintery wonderland village area. 
<p>
</p>
</details>
:cl:
- add: Glacier now has a dedicated Arrivals dock that leads into the Village.
> Glacier Dedicated Arrivals Dock

- Resources/Locale/en-US/interaction/verbs/noop.ftl
> Fix a Single Petting Interaction Locale

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Title
---
<p>
https://gyazo.com/6814d0306c06b66d845ec2991b79bd82.mp4
</p>
</details>
---
:cl:
- fix: Flavor text can be updated again.
> Fix Flavor Text Not Updating

- Resources/Locale/en-US/alerts/alerts.ftl
It was missing from the #944 for some reasons.
:cl:
- fix: Added missing deflect alert locale.
> [Fix] Added Missing Deflect Alert Locale

- Content.Server/Medical/PenLightSystem.cs
Updated the penlight to work with the new UI system.
---
---
:cl:
- fix: Fixed penlights
> Penlight Repair

- .github/workflows/update-credits.yml
- Tools/contribs_shared.ps1
- Tools/dump_github_contributors.ps1
https://github.com/space-wizards/space-station-14/pull/31739
> Properly Credit Contributors Who Were Truncated by GitHub API

- Resources/Locale/en-US/language/languages.ftl
Fix Issue  #1124 - The previous description was a butchering of the English language.
Third attempt. At least you are better at English than I am at GitHub. I won't screw it up this time.
> Update Marish Language Description

- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
I don't need to explain this further. The image speaks for itself.
:cl:
- tweak: Cargo Technicians and Salvage Techs can now process cargo orders. You don't need to smash the fucking LO Locker with a pickaxe anymore.
> Fix This Stupid Behavior

- Content.Shared/Interaction/SharedInteractionSystem.cs
Cherry-picks https://github.com/space-wizards/space-station-14/pull/28375/ to fix an issue with BUIs closing themselves.
> Cherry-Pick Wizden PR 28375

- Content.Server/Communications/CommunicationsConsoleSystem.cs
Fixes the call shuttle button.
> Fix Call Shuttle

- Resources/Prototypes/Body/Prototypes/ipc.yml
- Resources/Prototypes/Body/Prototypes/shadowkin.yml
- Resources/Prototypes/DeltaV/Body/Prototypes/harpy.yml
- Resources/Prototypes/DeltaV/Body/Prototypes/vulpkanin.yml
[From Floof, original PR by cynical24
(missing nyanotrassen stuff, felinids and arachne)
https://github.com/Fansana/floofstation1/pull/292
> Swapped Hands HUD Fix

- Resources/Prototypes/DeltaV/NPC/roboisseur.yml
Fixes Butlertron's hitbox. Thanks to https://github.com/WWhiteDreamProject/wwdpublic/pull/105
:cl:
- fix: Butlertron is no longer as wide as a barn.
> Fix Butlertron's Hitbox

- Content.Server/StationEvents/Events/PirateRadioSpawnRule.cs
Syndicate Listening Post causes servers to shit themselves if it spawns on any map configured as a Planet, by causing the server to attempt to spawn 7 BILLION entities. That number is neither a joke nor an exaggeration. EntityUid is a signed 32bit integer, meaning only 2 billion entities can ever exist at a time. This would be a goddamn performance nightmare even if I made an engine PR changing EntityUid to a 64bit integer. 
:cl:
- tweak: Syndicate Listening Posts can no longer spawn on a planet surface. This isn't for balance reasons, I would love for planetside listening posts. This is actually to address a server crashing bug whereby listening posts on planets cause 7 billion entities to spawn.
> Prevent Listening Posts From Spawning On Planets

- Resources/Prototypes/Catalog/Fills/Crates/materials.yml
One word change; silver was named incorrectly.
> Fix Silver Crate Name

- Content.Server/Traits/TraitSystem.Functions.cs
Caused a debug assert due to the component not being real.
> Fix Trait Component Removal

- Content.Client/Buckle/BuckleSystem.cs
- Content.Server/Disposal/Tube/DisposalTubeSystem.cs
- Content.Server/Disposal/Unit/EntitySystems/DisposableSystem.cs
- Content.Server/Disposal/Unit/EntitySystems/DisposalUnitSystem.cs
- Content.Server/MagicMirror/MagicMirrorSystem.cs
- Content.Server/StationEvents/Events/PirateRadioSpawnRule.cs
- Content.Shared/Buckle/Components/BuckleComponent.cs
- Content.Shared/Buckle/Components/StrapComponent.cs
- Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs
- Content.Shared/Buckle/SharedBuckleSystem.Interaction.cs
- Content.Shared/Buckle/SharedBuckleSystem.Strap.cs
- Content.Shared/Interaction/SharedInteractionSystem.cs
- Content.Shared/MagicMirror/MagicMirrorComponent.cs
- Content.Shared/MagicMirror/SharedMagicMirrorSystem.cs
- Content.Shared/Standing/StandingStateSystem.cs
- Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
- Resources/Prototypes/Entities/Structures/Furniture/rollerbeds.yml
- Resources/Prototypes/Entities/Structures/Wallmounts/mirror.yml
Mass bug fixing, for bugs related to #1220.
Feel free to link or send bugs.
Fix list:
- #1242 
- #1243 
- #1244
- https://github.com/space-wizards/space-station-14/pull/28084
- https://github.com/space-wizards/space-station-14/pull/28282
- Actually fixed PirateRadioSpawnRule heisentest (with a bandaid) (I cancel if it's 0)
- https://github.com/Simple-Station/Einstein-Engines/issues/1263
---
:cl:
- fix: Fixed chair visuals drawing depth wrongly if you sat in a north-facing chair.
- fix: Fixed buckling doing several buckles each time you did one.
- fix: Fixed the magic mirror.
- fix: Fixed beds re-positioning you every few seconds.
- fix: Fixed E not opening containers that are in another container.
- fix: Fixed disposal systems not flushing or ejecting properly.
> Mass Bug Fixing

- Content.Server/Disposal/Unit/EntitySystems/DisposableSystem.cs
Updates to engine version v237.2.0.
Fixes disposals systems breaking and not using the proper direction.
> Engine Update v237.2.0

- SpaceStation14.sln
Mirrors https://github.com/space-wizards/space-station-14/pull/31573
> [Fix] Added Robust.Xaml to the Project Solution

- Resources/Prototypes/Entities/Mobs/Customization/Markings/arachnid.yml
- Resources/Prototypes/Entities/Mobs/Species/arachne.yml
- Resources/Prototypes/Species/arachne.yml
Adds the ability for Arachne to be male.
Also in this I added chest/arm Arachnid markings for Arachne to use. I enabled footstep sounds for Arachne since it doesn't seem that they were intended to have silent footsteps.
:cl: Skubman
- add: Arachne can now be Male instead of only being Female. They can now also wear Facial Hair.
- add: Arachne can use Arachnid chest and arm markings.
- fix: Arachne will now have footstep sounds instead of being quiet when moving.
> ♂️ Add Male Arachne

- Resources/Prototypes/Loadouts/Jobs/Service/bartender.yml
Bartender Mosin was replacing their duffel bag at roundstart.
> Fix Bartender Mosin

- Resources/Prototypes/Traits/physical.yml
These were supposed to be negative traits(They give you points), but I accidentally made them positive traits(They cost points).
> Fix Redshirt & Brittle Bone Traits

- Resources/Prototypes/Entities/Mobs/NPCs/glimmer_creatures.yml
- Resources/Prototypes/Nyanotrasen/Damage/modifier_sets.yml
THESE GUYS CAN AND DID SOLO ENTIRE STATIONS, WHAT THE HELL?
:cl:
- tweak: NERFED WISPS, A LOT.
> NERF WISPS

- Resources/Prototypes/Datasets/tips.yml
This one took me a few hours to get working. Truly one of the most important PRs to ever grace this codebase :)
Solves #1286 
---
<p>
</p>
</details>
---
:cl:
- fix: Remove a filthy, dirty, lie that has ruined the dreams of many spessmans.
> Fix EE's Most Pressing Issue

- Content.Shared/Clothing/Loadouts/Systems/SharedLoadoutSystem.cs
- Content.Shared/Customization/Systems/CharacterRequirementsSystem.cs
- Content.Shared/Inventory/InventorySystem.Equip.cs
Title
---
:cl:
- fix: Loadouts should now properly be applied when spawning in cryopods.
> [Fix] Fixed Loadouts Spawning in Backpacks when Spawning via Cryopods

- Content.Shared/Clothing/MagbootsSystem.cs
- Content.Shared/Gravity/SharedGravitySystem.cs
lmao.
:cl:
- fix: Fixed magboots being toggled crashing the server.
> Fix Toggling Magboots Crashing the Server

- Resources/Locale/en-US/chat/managers/chat-language.ftl
- Resources/Locale/en-US/deltav/markings/vulpkanin.ftl
- Resources/Locale/en-US/language/languages.ftl
- Resources/Locale/en-US/markings/reptilian.ftl
- Resources/Locale/en-US/markings/shadowkin.ftl
- Resources/Locale/en-US/markings/vox.ftl
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Customization/Markings/moth.yml
Title :3
---
:cl:
- fix: Fixed a ton of languages missing chat names.
- fix: Fixed a ton of markings missing names.
> Add Missing Language and Marking Localization Strings

- Resources/Prototypes/Entities/Structures/Furniture/chairs.yml
This is a pretty easy one line fix.
> Hotfix Material Arbitrage Test

- Content.Server/Language/Commands/AdminLanguageCommand.cs
- Content.Server/Language/Commands/AdminTranslatorCommand.cs
- Content.Server/Station/Commands/JobsCommand.cs
- Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs
I'm not fully confident in this fix, I can't test it right now.
closes #1409 1409
> Fix Toolshed Crash

- Content.Server/Body/Systems/InternalsSystem.cs
Title. Refers to [this](https://github.com/Simple-Station/Einstein-Engines/actions/runs/12688697909/job/35365794632?pr=1466)
---
no cl no fun
> [Fix] Fixed Shadowking Throwing Errors when Spawning as a Random Humanoid Spawner

- Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs
Fixes https://github.com/Simple-Station/Einstein-Engines/issues/1498
Funny trig errors go brrr.
:cl:
- fix: Fixed an issue where ranged NPCs were incapable of aiming.
> Remove NPC Stormtrooper Mode

- Content.Server/Materials/MaterialSiloSystem.cs
I forgot about it.
---
:cl: Aviu00
- fix: Fix silo being out of range.
> Fix Silo Distation

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
:cl:
- fix: Fixed Nanotrasen Representative lacking in the starter clothes department
- fix: Fixed Nanotrasen Representative lacking in the headset department
> Fix Nanotrasen Rep Nakedness and Lack of Headset

- Resources/Prototypes/CharacterItemGroups/Jobs/Engineering/atmosphericTechnician.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Engineering/engineeringUncategorized.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Epistemics/golemancer.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Logistics/logisticsOfficer.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Medical/chemist.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Medical/uncategorized.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Security/headOfSecurity.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Security/uncategorized.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Security/warden.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Service/bartender.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Service/botanist.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Service/janitor.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Service/musician.yml
- Resources/Prototypes/Loadouts/Jobs/Engineering/atmosphericTechnician.yml
- Resources/Prototypes/Loadouts/Jobs/Engineering/uncategorized.yml
- Resources/Prototypes/Loadouts/Jobs/Epistemics/golemancer.yml
- Resources/Prototypes/Loadouts/Jobs/Logistics/logisticsOfficer.yml
- Resources/Prototypes/Loadouts/Jobs/Medical/chemist.yml
- Resources/Prototypes/Loadouts/Jobs/Medical/uncategorized.yml
- Resources/Prototypes/Loadouts/Jobs/Security/headOfSecurity.yml
- Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml
- Resources/Prototypes/Loadouts/Jobs/Security/warden.yml
- Resources/Prototypes/Loadouts/Jobs/Service/bartender.yml
- Resources/Prototypes/Loadouts/Jobs/Service/botanist.yml
- Resources/Prototypes/Loadouts/Jobs/Service/clown.yml
- Resources/Prototypes/Loadouts/Jobs/Service/janitor.yml
- Resources/Prototypes/Loadouts/Jobs/Service/musician.yml
i may be stupid....
Closes https://github.com/Simple-Station/Einstein-Engines/issues/1473
---
:cl:
- add: A bunch of winter coats that are already in the game were added as a loadouts.
> [Add] More Winter Coats in Loadout

- Resources/Maps/meta.yml
- Resources/Prototypes/Maps/meta.yml
Howdy y'all, I just added Holopads to Meta and made some minor fixes. I added a reporter to the game and increased the job of cargo technician. I also added MacBoots industrial gloves and Atmos lockers. 
</p>
</details>
---
:cl: Mike32oz
- add: Meta Station, Holopad every Department.
- add: Meta Station, Job Reporter/room near arrival.
- add: Meta Station, added MacBoots/ industrial gloves in Atmos lockers.
- tweak: Meta Station, Tweaked increased job for Cargo.
- tweak: Meta Station, More AI laws-circuit boards have been added to upload.
> Meta Station with Holopads

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
This should be 12... 
---
:cl:
- tweak: Tweaked .35 magazine size to 12 rounds
> Increases .35 Mag Size From 10 to 12

- Resources/Prototypes/DeltaV/Entities/Markers/Spawners/ghost_roles.yml
- Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/familiars.yml
- Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/pets.yml
- Resources/Prototypes/DeltaV/Roles/Jobs/Command/administrative_assistant.yml
- Resources/Prototypes/DeltaV/Roles/Jobs/Medical/medical_borg.yml
- Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
- Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
- Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
> Remove All Usages of DepartmentTimeRequirement

- Resources/Prototypes/Entities/Mobs/Player/silicon_base.yml
My bad
---
:cl:
- fix: Fixed IPCs being unable to cryo.
> IPCs Can Cryo Again

- Resources/Locale/en-US/traits/traits.ftl
:cl:
- tweak: Made the Redshirt trait's description say what it does
> Update Redshirt Trait Description

- Resources/Prototypes/Entities/Effects/puddle.yml
for our janitors
:cl:
- tweak: Tweaked puddles and footsteps to be able to see them in context menu.
> Show Puddles and Footsteps in Context Menu

- Content.Server/Administration/Commands/SetOutfitCommand.cs
yes this is a system
i dont know why it's not better named
> Use System

- Content.Server/Humanoid/Systems/RandomHumanoidSystem.cs
it will no longer choose vox or lamia.
> Only Use Roundstart Species for RandomHumanoid

- Content.Shared/Content.Shared.csproj
- Directory.Packages.props
The documentation for it can be found here: https://numerics.mathdotnet.com/api/MathNet.Numerics/index.htm
This adds an entire massive library of academic/scientific/engineering math functions. 
I basically need this going forwards to start comprehensively fixing this game's terrible math.
Not player facing, but it deserves to be here:
:cl:
- add: (For Developers): Added the MathNet.Numerics library. It contains a great number of scientific and engineering math related functions. For more information, its documentation can be found here, https://numerics.mathdotnet.com/api/MathNet.Numerics/index.htm
> Add MathNet.Numerics To The Project

- Content.Client/Content.Client.csproj
- Content.Server/Content.Server.csproj
Whoops. To be fair it's my first time adding something like this to a project. :)
> MathNet.Numerics Apparently Needed To Be In Server And Client Too

- Resources/Prototypes/Entities/Mobs/Species/harpy.yml
> HideSpawnMenu Harpy Dummy

- Content.Client/Chemistry/UI/ChemMasterWindow.xaml.cs
:cl:
- fix: ChemMaster no longer loses your last added progress because of a silly goose move.
> Hotfix ChemMaster

- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
They're *just a bit* too loud. A 5db reduction should be enough. My salvage techs were complaining of migraines.
:cl:
- tweak: Made hardsuits 5db quieter.
> Make Hardsuits Not Destroy Ears

- Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Give 'em plungers.
---
<p>
</p>
</details>
---
:cl: Timfa
- add: Add plunger to a Borg Cleaning Mobule
> Add a Plunger to the Cleaning Module

- Content.Client/Overlays/Switchable/BaseSwitchableOverlay.cs
- Content.Client/Overlays/Switchable/NightVisionSystem.cs
- Content.Client/Overlays/Switchable/ThermalVisionOverlay.cs
- Content.Client/Overlays/Switchable/ThermalVisionSystem.cs
- Content.Shared/Overlays/Switchable/SwitchableOverlayComponent.cs
- Content.Shared/Overlays/Switchable/SwitchableOverlaySystem.cs
Last changes to CyberEyes broke nightvision, so this reverts those changes. 
:cl:
- fix: Fixed night vision not working correctly.
> Fix CyberEyes

- Resources/Changelog/Changelog.yml
Broke the CL when I edited it for them
> Shhhh I Fucked Up

- Content.Client/Chemistry/UI/ChemMasterWindow.xaml.cs
- Content.Client/Storage/StorageBoundUserInterface.cs
:cl:
- fix: Fixes the ChemMaster playing the button press sound on open.
> Quick ChemMaster Fix

- Content.Client/Arcade/BlockGameMenu.cs
- Content.Client/Arcade/UI/BlockGameBoundUserInterface.cs
- Content.Client/Arcade/UI/SpaceVillainArcadeBoundUserInterface.cs
- Content.Server/Arcade/BlockGame/BlockGame.Ui.cs
:cl:
- fix: Fixed the most pressing issue: arcade games not working.
> Fix Arcade Machines (#30376)

- Content.Client/DeltaV/VendingMachines/UI/ShopVendorWindow.xaml.cs
:cl:
- fix: Salvage vendors will no longer accept any inputs to buy an item.
> Fix Shop Vendor Buying on Non-Click (#2906)

- Resources/Locale/en-US/deltav/station-laws/laws.ftl
- Resources/Locale/en-US/station-laws/laws.ftl
- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/silicon-laws.yml
Adds 10 new Law Boards for AI
AI Please State Laws.
---
:cl: Ichai
- add: Added 10 new Law Boards to the AI: Plasma Flood, Mother Drone, Druid, Cowboy, Chaplain, Clown, Janitor, Engineer, Research and Medical.
> Adds New Law Boards for AI

- Content.Client/Options/UI/Tabs/GraphicsTab.xaml
- Content.Client/Options/UI/Tabs/GraphicsTab.xaml.cs
- Content.Client/Overlays/SaturationScaleSystem.cs
- Content.Shared/CCVar/CCVars.Mood.cs
- Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
Separate from the shaders toggle because some want one and the other.
---
:cl:
- add: Added a toggle for the mood visual effects, for the ones with sensitive eyes.
> Add Mood Visual Effects Toggle

- Content.Client/_Shitmed/Autodoc/PickSurgeryWindow.xaml.cs
it was using the wrong id for metadata so casting didnt work
---
it is infact fixed
---
:trollface:
> Fix Autodoc Surgery UI

- Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
ENABLES WAROPS
Turns war ops back on since delta-v turned them off apparently.
<p>
</p>
</details>
---
:cl:
-tweak: reenabled war ops
> WAR OPS ARE BACK!!!

- Content.Server/EntityEffects/Effects/PlantMetabolism/PlantAdjustPotency.cs
- Content.Server/EntityEffects/Effects/PlantMetabolism/PlantDestroySeeds.cs
- Content.Server/EntityEffects/Effects/PlantMetabolism/PlantRestoreSeeds.cs
- Resources/Locale/en-US/botany/seeds.ftl
- Resources/Locale/en-US/guidebook/chemistry/effects.ftl
- Resources/Locale/en-US/guidebook/chemistry/plant-attributes.ftl
- Resources/Locale/en-US/reagents/meta/botany.ftl
- Resources/Prototypes/Reagents/botany.yml
- Resources/Prototypes/Recipes/Reactions/botany.yml
Ports https://github.com/space-wizards/space-station-14/pull/27110
---
:cl: Erisfiregamer1
- add: New chemical, Sedin. It restores seeds on plants 20% of the time with other adverse effects included.
> Sedin (#27110)

- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
> Fix Silly Test Fail

- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Adds the Justice coms channel to AI.
---
:cl:
- tweak: Station AI now has access to the Justice channel
> Adds Justice Channel To AI

- Resources/Locale/en-US/traits/misc.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/physical.yml
Plateled Factories but for IPCs, at the cost of 10 trait points, heals 0,8.
Bionic legs roundstart, at the cost of 6 points, since they are not as useful as the arms.
Plateled Factories but for IPCs, at the cost of 10 trait points, heals 0,8.
Bionic legs roundstart, at the cost of 6 points, since they are not as useful as the arms.
Platelet Factories for IPC feel good since it made, in my opinion, and in the opinion of many others, no sense that IPCs had nothing for regen, as for bionic legs, consider it my personal mald PR for not having bionic legs from the start.
---
---
<p>
</p>
</details>
---
:cl: Diggy
- add: A trait for IPCs, which is essentially a platelet factories, at the same trait cost, etc, as the normal platelet factories, and …
> Two New Traits.

- Content.IntegrationTests/PoolManagerTestEventHandler.cs
- Content.IntegrationTests/Tests/StoreTests.cs
- Content.Server/StoreDiscount/Systems/StoreDiscountSystem.cs
- Resources/Prototypes/Catalog/discount_categories.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Entities/Objects/Tools/gps.yml
- Resources/Prototypes/Entities/Objects/Tools/t-ray.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/Maps/arena.yml
- Resources/Prototypes/Maps/asterisk.yml
- Resources/Prototypes/Maps/edge.yml
- Resources/Prototypes/Maps/europa.yml
- Resources/Prototypes/Maps/hammurabi.yml
- Resources/Prototypes/Maps/hive.yml
- Resources/Prototypes/Maps/lambda.yml
- Resources/Prototypes/Maps/submarine.yml
- Resources/Prototypes/Maps/tortuga.yml
Fuck the stupid "Tests kill themselves after a hardcoded time limit has passed".
> Fix Every Debug Test Fail

- Resources/Prototypes/Entities/Effects/puddle.yml
Add some components to the footstep entity to make it be more like the puddle entity
> Make Footstep Entity Better

- Content.Server/GameTicking/GameTicker.RoundFlow.cs
- Content.Shared/CCVar/CCVars.Game.cs
Cherrypicks https://github.com/space-wizards/space-station-14/pull/29151 by Durk's request
> Cherrypick Wizden Pr 29151

- Content.Client/Light/AfterLightTargetOverlay.cs
- Content.Client/Light/LightBlurOverlay.cs
- Content.Client/Light/RoofOverlay.cs
- Content.Client/Light/TileEmissionOverlay.cs
high lighting quality is no longer fucked
:cl:
- fix: Ported fix for high lighting quality
> Apply RoofOverlay Per-Grid Not Per-Map + Fix Lighting Quality (#35207)

- Content.Client/NukeOps/WarDeclaratorWindow.xaml.cs
Basically just https://github.com/space-wizards/space-station-14/pull/30221
> Fix War Declarator

- Resources/Prototypes/CharacterItemGroups/Generic/gloveGroup.yml
- Resources/Prototypes/Loadouts/Generic/hands.yml
Adds the Cloth Wraps to the hands loadout
---
---
:cl:
- add: Added cloth wraps to hands loadouts
> Add Clothwraps to Hands Loadouts

- Resources/Prototypes/Traits/physical.yml
Fixed the nano bot trait having a bit too much healing and actually got the bionic leg trait to work.
Could be defined as incompetence and also a "this is the first time I do this" kind of error, regardless, platelet factories for IPC now only heals 0,6 instead of 0,9 and Bionic Legs ACTUALLY do work this time around..
---
---
<p>
</p>
</details>
---
:cl: Diggy
- tweak: Tweaked the nano bot trait value from 0,9 to 0,6.
- fix: Bionic legs DO work now, yay.
> Minor Fixes to My Two Traits PR.

- Resources/Prototypes/Entities/Structures/Decoration/bonfire.yml
- Resources/Prototypes/Entities/Structures/Decoration/fireplace.yml
- Resources/Prototypes/Recipes/Construction/Graphs/furniture/fires.yml
Porting - Allow Construction of Fireplaces and Bonfires
Ported from - https://github.com/Goob-Station/Goob-Station/pull/1646
Yeah it's a port of a port. Yes there was sofas, benches and banners, I've very lazily stolen just the fires. Sofa might be nice but that's lot more code pinching.
---
---
:cl:
- add: Recipes to build Fireplaces and Bonfires
> Fireplace Construction

- Content.Shared/NPC/Systems/NpcFactionSystem.cs
Fixed bug that made ClothingAddFactionComponent not add the faction of the clothing to the mob when the clothing is equipped.
The bug is described in greater detail in [this issue](https://github.com/Simple-Station/Einstein-Engines/issues/1228).
---
<p>
https://github.com/user-attachments/assets/41fe9411-0eac-478d-956c-b094f211f565
</p>
</details>
---
:cl:
- fix: Fixed bug that made ClothingAddFactionComponent not work.
> Faction Clothing Bug Fix

- Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
Just a random event that had a tiny chance to spawn an Abstract entity.
> Fix A Minor Test Fail

- Content.Client/FootPrint/FootPrintsVisualizerSystem.cs
- Content.Server/FootPrint/FootPrintsSystem.cs
- Content.Shared/Footprint/FootPrintComponent.cs
- Content.Shared/Footprint/FootPrintsComponent.cs
Port of https://github.com/WWhiteDreamProject/wwdpublic/pull/298
> Footstep Netcode Fixes

- Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml
Fix the bug described by [this issue.](https://github.com/Simple-Station/Einstein-Engines/issues/1820)
---
<p>
</p>
</details>
---
:cl:
- fix: Health analyzer's doll is now in the normal size.
> Health Analyzer UI Fix

- Resources/Prototypes/Traits/physical.yml
Spinarette Trait now adds SpiderCraft Tag
:cl:
- add: SpiderCraft Tag to Spinarette
> Spinarette Fix

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Resources/Prototypes/Entities/Structures/base_structure.yml
More fun, chopped out some math that wasn't needed anymore.
> More Space Wind Tweaks

- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Adds a bunch of random ass changes to Smile the slime; its description says its been through thousands of experiments so I thought I'd make it a very wacky creature. Smile can no longer do damage, but rather injects a TINY amount of omnizine on hit, allowing it to heal people (slowly), Smile is now functionally immortal, cannot be slowed, is unaffected by gravity, can go under doors, and bleeds Nothing (the reagent)
Smile is basically a spectator now, besides the fact that it can heal (and I guess take a bullet or two(hundred) for a member of the crew, if you want to be cinematic)
----
:cl:
- tweak: Smile no longer does damage, but rather injects a tiny amount of omnizine on hit
- tweak: Smile is no longer effected by most slowness sources
- tweak: Smile has ascended to godhood
- tweak: …
> The Accursed Abomination Grows Ever Stronger

- Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
Make armblades cut food, which previously wasn't possible. That's goofy as hell.
---
<p>
https://github.com/user-attachments/assets/3e850773-4e00-404c-86fb-bcddd3f0f219
</p>
</details>
---
:cl:
- tweak: Changelings can cut food.
> Armblades Can Now Cut Food

- Resources/Prototypes/_Nuclear14/Tiles/floors.yml
Oh uhhh, THERE'S A FALLOUT WASTELAND UNDER MY STATION.
And now there isn't. Nothing to see here.
> Fix MS13 Flooring

- Resources/Prototypes/_Lavaland/Reagents/medicine.yml
Makes miner's salve brute and burn healing amounts equal: 
- total burn heal increased from 5 to 6.5, 
- total brute heal increased from 2.5 to 6.5
makes it weaker in normal pressure, but stronger in low pressure
reference: https://github.com/Goob-Station/Goob-Station/pull/1951
(maybe too strong ?)
Increase OD limit (close to 2 survival medipens) and decrease OD damage to a slower rate
context: https://github.com/Simple-Station/Einstein-Engines/pull/1954#pullrequestreview-2691153209
---
Tested locally:
---
<p>
</p>
</details>
---
:cl:
- tweak: make miner's salve overdose less punishing
- tweak: change miner's salve healing rates to better suit low pressure environment
> Update Miner's Salve

- Resources/Maps/meta.yml
Just annoying map errors to clear.
> Clear Annoying Map Errors

- Resources/Maps/core.yml
Not sure who merged this. But pleaaase do actually check Build Test Debug to make sure there isn't a valid test fail.
> Remove Invalid Map Proto

- Content.Shared/DrawDepth/DrawDepth.cs
- Resources/Prototypes/Entities/Effects/puddle.yml
- Resources/Prototypes/Entities/Objects/Misc/kudzu.yml
- Resources/Prototypes/Entities/Structures/Machines/artifact_analyzer.yml
- Resources/Prototypes/Entities/Structures/Machines/holopad.yml
- Resources/Prototypes/Entities/Structures/Wallmounts/switch.yml
- Resources/Prototypes/Entities/Structures/cargo_telepad.yml
- Resources/Prototypes/Entities/Structures/conveyor.yml
https://github.com/space-wizards/space-station-14/pull/32369
<p>
</p>
</details>
---
:cl:
- tweak: Puddles now have a separate draw depth so they display properly
> Add Puddle Drawdepth 

- Content.Shared/_Goobstation/Changeling/ChangelingInfectionComponent.cs
Reduced the timer on Changeling infections to 10 minutes. However, symptoms are now about 4 times worse. You asked for this.
---
---
<p>
</p>
</details>
---
:cl:
- add: Nerfed the time Changeling Infections take to complete (20 minutes -> 10)
> Changeling Infection Buffs

- Content.MapRenderer/Content.MapRenderer.csproj
Just makes the Map Renderer ignore the recent ImageSharp vulnerability (I verified that it was completely unrelated to our use-case).
No CL, this isn't playerfacing.
> Fix MapRenderer

- Resources/Prototypes/CharacterItemGroups/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/CharacterItemGroups/Jobs/Command/captain.yml
- Resources/Prototypes/Loadouts/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/Loadouts/Jobs/Command/captain.yml
Adds the terminus as a loadout item for BSO or Captain (if you are an oni)
:cl:
- add: BSO/Captain Onis can now pick the terminus as their weapon
> Terminus Loadout

- Resources/Prototypes/ai_factions.yml
Fix the syndicate turrets not shooting lings since it's a new faction.
---
---
:cl:
- tweak: Turrets will now shoot lings except for NT turrets.
> Turrets Fix Not Shooting Lings

- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
- Resources/Prototypes/_EE/Damage/modifier_sets.yml
I fucked up while buffing smile and missed a few things, this adds everything I intended to add in my previous smile PR. This gives them complete damage resistance so they cant be gibbed, stamina resist, and some more potentia.
<p>
</p>
</details>
---
:cl:
- add: You will smile.
> The Wicked Abomination Is Unstoppable

- Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
- Resources/Prototypes/Traits/physical.yml
Title
---
- fix: IPCs can now heal Ion damage using cables or nano repair bots.
> Add Ways to Heal Ion Damage.

- Resources/Locale/en-US/_EE/contractors/lifepath.ftl
- Resources/Prototypes/_EE/Contractors/lifepath.yml
Some of the Lifepaths were wildly inappropriate for a character that can be employed on the station.
> Some Of These Really Dont Fit

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml
- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Resources/Locale/en-US/preferences/ui/humanoid-profile-editor.ftl
Adds a description to your chosen lifepath, employer or nationality.
---
<p>
</p>
</details>
---
:cl:
- add: Moved Nationality, Employer, and Lifepath to a new Background tab. They now also show descriptions for the chosen selections.
> Show the Description

- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/silicon-laws.yml
Adds an asimov variant for AI so they don't have a law stating they have to listen to themselves
<p>
</p>
</details>
---
:cl:
- tweak: Station AI gets a variant of Asimov that doesn't state they have to obey themselves
> Unique Asimov Variant for AI

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.Processing.cs
- Resources/Changelog/Changelog.yml
WOW. ENTITY QUERIES SURE DO SUCK FOR PERFORMANCE. I CAN'T BELIEVE THESE ARE THE NORM.
before: 
after:
> Yeet Entity Querries

- Resources/Prototypes/game_presets.yml
- Resources/Prototypes/secret_weights.yml
When I added the changelings game mode, I forgot to also add changelings as a secret weight, so this fixes that, and also adds it to all at once alongside bloodcult.
---
:cl:
- tweak: Give changelings a secret weight, so hopefully they actually pop up now
- tweak: Added changelings and bloodcult to all at once
> Changeling Gamemode Fixes (Again)

- Content.Client/CartridgeLoader/Cartridges/MailMetricUiFragment.xaml.cs
- Content.Client/Holopad/HolopadWindow.xaml.cs
- Content.Client/Info/RulesPopup.xaml
- Content.Client/Lobby/UI/ObserveWarningWindow.xaml
- Content.Client/Nuke/NukeMenu.xaml
- Content.Client/NukeOps/WarDeclaratorWindow.xaml
- Content.Client/Options/UI/Tabs/AudioTab.xaml
- Content.Client/Options/UI/Tabs/NetworkTab.xaml
- Content.Client/PDA/Ringer/RingtoneMenu.xaml.cs
- Content.Client/Power/Generator/GeneratorWindow.xaml.cs
- Content.Client/_Shitmed/Autodoc/AutodocProgramWindow.xaml
- Content.Client/_Shitmed/Autodoc/AutodocProgramWindow.xaml.cs
- Content.Client/_Shitmed/Autodoc/AutodocWindow.xaml.cs
I changed something so long ago but didn't make sure others were changed to follow.
---
<p>
</p>
</details>
---
:cl:
- fix: Fixed many buttons being yellow instead of red
> Fix Buttons Being Yellow Instead of Red

- Content.Server/Body/Systems/RespiratorSystem.cs
Fixes an issue where the BreathingImmunityComponent is not checked in RespiratorSystem, this component is used for carp lungs, but since it was never checked it meant that carp lungs did nothing.
---
---
:cl:
- fix: Made RespiratorSystem check for BreathingImmunityComponent
> Fix Carp Lungs

- Resources/Prototypes/DeltaV/Entities/Clothing/Eyes/glasses.yml
Literally what it says.
This SIMPLE fix makes it so corpsman glasses use the medhud as well.
---
---
---
:cl: Diggy
- fix: Corpsman glasses now have the medhud they should have always had.
> Corpsman Glasses Fix.

- Content.Client/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml
- Content.Server/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
This tweaks glimmer to be properly time differentiated, such that the linear decay CVar directly corresponds 1:1 with 1 glimmer decayed linearly per second.
> Tweak Glimmer Decay Math

- Resources/Prototypes/Entities/Mobs/NPCs/Rslimes.yml
- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
- Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
- Resources/Prototypes/Entities/Mobs/NPCs/hellspawn.yml
- Resources/Prototypes/Entities/Mobs/NPCs/lavaland.yml
- Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
- Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Died 2025 Born 2025 welcome back rat king 2 rp
Lings can now eat a bunch of animals, now they shouldn't be 100% KOS, they can co-exist with the crew or do enough rat king-ish shit that they are deemed KOS despite being able to eat animals.
---
---
:cl: Diggy
- add: Changelings can now "Co-Exist" with the crew by eating animals / unwanted pests like xenos.
> Lings Can Now Eat Animals

- Content.Shared/_EE/Contractors/Prototypes/EmployerPrototype.cs
- Resources/Locale/en-US/_EE/contractors/employer.ftl
- Resources/Prototypes/_EE/Contractors/employer.yml
Adds the Orion Express employer
---
:cl:
- add: Added Orion Express as an employer
> Add Orion Express

- Resources/Locale/en-US/traits/misc.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/Traits/physical.yml
So Bram didn't test his changes, meaning weakling and bodybuilder didn't do anything except break taildrag. I'm not fixing those traits because he also added traits that functionally do the same thing but better. 
I'm removing weakling and the old bodybuilder, and keeping featherweight / bulky (which has now been renamed to bodybuilder by request of the person who paid for the original PR)
:cl:
- remove: Removed old bodybuilder and weakling traits since they didn't work, and gave bulky the name bodybuilder instead
> Pull Speed Trait Changes

- Resources/Prototypes/CharacterItemGroups/Generic/languageGroups.yml
- Resources/Prototypes/Traits/languages.yml
- Resources/Prototypes/Traits/neutral.yml
- Resources/Prototypes/_EE/Traits/languages.yml
This PR comments out the CharacterItemGroup for basic languages so you can take ALL OF THEM (side effects may include using all your trait slots) and the lines responsible for breaking both languages and accents (the ones that specify how many slots it takes up in the item group and how many trait slots it uses)
This is so we can have them functioning until that code gets fixed
---
:cl:
- fix: Languages and accents now work. JOHN LANGUAGE IS FINALLY REAL!
> (Bandaid Fix for Languages/Accents) I'M LANGUAGING OUT MAN!!!

- Resources/Maps/gax.yml
minor fixes on Gax:
* fixed xenoarch doors locking incorrectly
* Named several airlocks, making them easier to locate
* fixed AI turret not connected
* added a mining shuttle console to LO Office
---
:cl: Emilly
- fix: Gax: minor fixes
> [NVS Gax] Minor Fixes

- Content.IntegrationTests/Tests/EntityTest.cs
- Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs
If wizden are okay with doing this then screw it I'll do it to DeleteAllThenGhost too.
https://github.com/space-wizards/space-station-14/pull/34021
No CL this isn't playerfacing but great for my sanity.
> Make Tests Shut Up About Audio Entities

- Resources/Maps/pebble.yml
AAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> Fix Pebble Invalid Again

- Resources/Maps/anchor.yml
> Update Anchor Again

- Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
Fixes an issue where sec magboots tried to use a container that didn't exist
---
---
---
:cl:
- fix: Fixed an issue where Combat Magboots would cause a test fail.
> Fix Sec Magboots Since They Throw Errors

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
- Content.Server/Atmos/EntitySystems/AtmosphereSystem.MAS.cs
- Content.Shared/Damage/Components/DamageOtherOnHitComponent.cs
- Content.Shared/Damage/Systems/SharedDamageOtherOnHitSystem.cs
- Content.Shared/Throwing/ThrownItemSystem.cs
I have finally completed the math here, and now have a direct Navier-Stokes solver for any arbitrary given tile. The only thing this isn't accounting for yet is fluid viscosity and "Other Accelerations"
THE PROOF OF MY DIVINE ASCENSION INTO THE REALM OF DIFFERENTIAL EQUATIONS.
https://github.com/user-attachments/assets/6bb17838-3970-4ac4-a922-515732df4130
When I return from my Physics final exam, I will obliterate Monstermos completely.
:cl:
- add: MAS Version 1 is here.
> Navier-Stokes Space Wind

- Resources/Prototypes/_EE/Entities/NanoTrasen/Modsuits/praetorian.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Changed the light on the modsuit to be the right colour, gave BSO the over ear CC headset instead of the normal CC headset.
---
---
<p>
</p>
</details>
---
:cl:
- tweak: BSO now has the over-ear headset
- tweak: BSO's modsuit now has the right colour for its light
> Fixes some Parts of BSO's Gear

- Content.Server/Pinpointer/NavMapSystem.cs
https://github.com/Simple-Station/Einstein-Engines/pull/2337
> Beacons No Longer Glitch Off on Grid Split (#28518)

- Content.Server/_DV/Abilities/Chitinid/ChitinidSystem.cs
- Resources/Prototypes/DeltaV/Species/chitinid.yml
Re-enable these if and only if you are fixing their shitcode.
:cl:
- remove: Chitinids have been disabled due to being a server performance nightmare.
> Disable Chitinids

- Resources/Locale/en-US/_EE/markings/harpy.ftl
Made an error while setting up the harpy wing localization initially, which fucked up the text when the downward wings were selected for coloring. This just fixes that bit of localization so it works.
---
<p>
</p>
</details>
> Fix Downward Harpy Wing Localization

- Resources/Prototypes/Entities/Objects/Devices/pda.yml
https://github.com/Simple-Station/Einstein-Engines/pull/2361
> Fix Mystic PDA

- Content.Server/Traits/TraitSystem.Functions.cs
- Content.Shared/Overlays/Switchable/SwitchableOverlayComponent.cs
- Content.Shared/Overlays/Switchable/ThermalVisionComponent.cs
It turns out that traits that add or modify a shared component also need to make sure that said component is Dirtied to the client. Also I finally figured out what was going on with Thermal Vision. 
<p>
Thermal vision is finally fixed:
https://github.com/user-attachments/assets/64aeea2f-39bf-40ec-8530-518194fbb0fc
</p>
</details>
:cl:
- fix: Fixed Thermal Vision lasting only a single tick instead of the full 2 seconds its intended to last.
- fix: Fixed traits not correctly updating the client on changes made to the character.
> Fixes For Trait Netcode

- Resources/Maps/northway.yml
Minor fixes to Northway pertaining to visibility, etc.
---
<p>
</p>
</details>
---
:cl: ODJ
- tweak: Slight changes to Northway
> Northway Fixes

- Resources/Prototypes/Maps/lambda.yml
Magistrate, administrative assistant, and prison guard has been removed. Lambda now has one AI over three. Bar, kitchen, and medical has been worked on.
---
<details><summary><h1>Extra Media</h1></summary>
<p>
</p>
</details>
---
:cl: ODJ
- tweak: Cleanup and slight rework of Lambda
> Lambda Fixes

- Resources/Maps/anchor.yml
- Resources/Maps/pebble.yml
Now you can't open airlocks and space the station while mapping.
> Fix Tiny Issue With Pebble And Anchor

- Content.Shared/Roles/SharedRoleSystem.cs
We were missing a subscription.
> Fix MindRole Test

- Content.Server/PowerCell/PowerCellSystem.Draw.cs
Current implementation of `PowerCellSystem.Update()`:
```csharp
public override void Update(float frameTime)
{
base.Update(frameTime);
var query = EntityQueryEnumerator<PowerCellDrawComponent, PowerCellSlotComponent>();
while (query.MoveNext(out var uid, out var comp, out var slot))
{
if (!comp.Enabled)
continue;
if (Timing.CurTime < comp.NextUpdateTime)
continue;
comp.NextUpdateTime += comp.Delay;
if (!TryGetBatteryFromSlot(uid, out var batteryEnt, out var battery, slot))
continue;
// TCJ: "Multiplying by frameTime to make this tick-invariant. Otherwise it'll draw 30x to 60x faster than you expect."
if (_battery.TryUseCharge(batteryEnt.Value, comp.DrawRate * frameTime, battery))
continue;
var ev = new PowerCellSlotEmptyEvent();
RaiseLocalEvent(uid, ref ev);
}
}
```
Multiplying …
> Fix PowerCellDrawComponent Consuming Less Power than It Should

- Content.Server/Abilities/Psionics/Abilities/MindSwapPowerSystem.cs
Just tweaks mindswap so that it doesn't produce error messages.
No CL this isn't player facing
> Small Mindswap Fix

- Resources/Audio/DeltaV/Voice/Harpy/attributions.yml
Corrects a YAML mapping.
<p>
</p>
</details>
> Fixed YAML Mapping

- Content.Server/Atmos/Consoles/AtmosAlertsComputerSystem.cs
This was yet another system that had non-functional logic for preventing it from running on every frame. I'm kind of shocked how often this "Literally does nothing" boilerplate was. 
:cl:
- tweak: Made some server performance improvements to Atmos Alert Computers.
> Atmos Alert Computer Performance Tweaks

- Content.Server/StationEvents/Events/SolarFlareRule.cs
This system had a non-functional check for preventing it from running on every frame. This PR fixes that.
:cl:
- tweak:Improved the server performance of Solar Flare events.
> Solar Flare Performance Tweaks

- Resources/Prototypes/Entities/Objects/Fun/toys.yml
Removed "Why does it look familiar?" in the description for the Arachne plush toy.
Changed the description of the Arachne plush. Removing "Why does it look familiar?"
Description.
---
:cl:
- tweak: Tweaked Arachne plush description
> Changed Arachn Plush Description

- Resources/Prototypes/Recipes/Construction/Graphs/furniture/fires.yml
> Bonfire Fix

- Content.Server/Administration/ServerApi.cs
- Content.Server/_Funkystation/Administration/ServerApi.Funkystation.cs
i totally didn't write this, tay did, mhm
backend game portion for from-discord whitelisting  https://github.com/funky-station/funky-station/pull/679
Add a player to the whitelist via the admin HTTP API.
Meant to be used with a bot like https://github.com/sleepyyapril/FunkyWhitelist
> Port (Totally Tay's and Not Mine) Funky's Whitelist HTTP API Action

- Content.Server/Atmos/EntitySystems/AtmosphereSystem.MAS.cs
There was a math error in the "wall smoothing" step of space wind hiding in plain sight which was causing the "Wall Bugs", this PR fixes that. Behold in all its video proofy glory.
https://github.com/user-attachments/assets/91e87324-b3a9-4d08-bca7-365b64c4888c
:cl:
- fix: Finally completed Space Wind V5's airflow math. It no longer produces extremely inconsistent airflow values in and around airlocks and walls.
> Fix SpaceWindv5 Wall Smoothing

- Content.Shared/CCVar/CCVars.Game.cs
> Disable Contraband Examine

- Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
- Content.Server/_Lavaland/Shuttles/Systems/DockingShuttleSystem.cs
- Resources/Prototypes/Entities/Mobs/Player/observer.yml
Fixed bugs that appeared after wizmerge
---
:cl:
- fix: Shuttle docking emergency announcement has been fixed
- fix: The miners shuttle can now arrive at the station
- fix: Ghost toggle light now works
> [Fix] Wizmerge

- Resources/Locale/en-US/deltav/species/species.ftl
- Resources/Locale/en-US/traits/traits.ftl
- Resources/Prototypes/DeltaV/Species/vulpkanin.yml
- Resources/Prototypes/Species/arachne.yml
- Resources/Prototypes/Species/arachnid.yml
- Resources/Prototypes/Species/shadowkin.yml
- Resources/Prototypes/Species/slime.yml
This PR disables a bunch of bloat species for the defaults. As requested by @OldDanceJacket
> Disable Some Bloat

- Resources/Maps/pebble.yml
This has a variety of small fixes for Pebble, to make it an actual playable map. Primarily around power and lights.
These fixes were done for awhile. Whoops.
---
<p>
</p>
</details>
---
:cl: ODJ
- fix: Fixed Pebble.
> Pebble v3.1

- Resources/Prototypes/Announcers/intern.yml
- Resources/Prototypes/Announcers/medbot.yml
- Resources/Prototypes/Announcers/neil.yml
- Resources/Prototypes/Announcers/voxfem.yml
Howdy y'all, just a quick fix on the announcements for the call for the shuttle for Intern, Medbot, Neil, and Voxfem.
only Yml changes
:cl:
- fix: Fixed shuttle announcements not playing audio
> Announcers Fixed
